#!/usr/bin/env bash

rm ~/upload/* || true

export WINEDEBUG=-all wine program.exe

set -e

mkdir ~/upload || true

rm -r ~/upp.tmp || true
mkdir ~/upp.tmp || true

# bash ~/Scripts/www

cd ~/upp.src
git rev-list --count HEAD >~/upp-revision
cd ~

echo ------------------------- Win32

bash ~/Scripts/win

echo ------------------------- POSIX

bash ~/Scripts/posix

# bash ~/Scripts/deb64

chmod a=rw ~/upload/*

#bash ~/upp.src/lpbuild2/lpbuild.sh ~/upp.src/lpbuild2/nightly.cfg
