#!/usr/bin/env bash

set -e

#rm ~/upload/* || true

#remove Win32 specific files
rm ~/upp.tmp/upp/*.exe || true
rm ~/upp.tmp/upp/README || true
rm ~/upp.tmp/upp/*.map || true
rm ~/upp.tmp/upp/*.dll || true
rm ~/upp.tmp/upp/*.upp || true
rm ~/upp.tmp/upp/*.chk || true
rm -R ~/upp.tmp/upp/bin || true

cp -p ~/Scripts/GCCMK.bm ~/.upp/theide

~/bin/umk ~/upp.src/uppsrc ide GCCMK -asrXk ~/upp.tmp/upp/uppsrc

mv ~/upp.tmp/upp/uppsrc/Makefile ~/upp.tmp/upp/uppsrc/Makefile.in

~/bin/umk ~/upp.src/uppsrc umk GCCMK -asrXk ~/upp.tmp/upp/uppsrc

mv ~/upp.tmp/upp/uppsrc/Makefile ~/upp.tmp/upp/uppsrc/uMakefile.in

cp -p ~/Scripts/Makefile ~/upp.tmp/upp
cp -p ~/Scripts/domake ~/upp.tmp/upp
cp -p ~/Scripts/doinstall ~/upp.tmp/upp
cp -p ~/Scripts/douninstall ~/upp.tmp/upp
cp -p ~/Scripts/do-xdg-desktop-menu ~/upp.tmp/upp
cp -p ~/Scripts/function_library ~/upp.tmp/upp
cp -p ~/Scripts/readme.md ~/upp.tmp/upp
cp -p ~/Scripts/upp.spec ~/upp.tmp/upp
cp -p ~/Scripts/debian ~/upp.tmp/upp/buildrequires.debian
cp -p ~/Scripts/fedora ~/upp.tmp/upp/buildrequires.fedora

svn_snapshot_version=$(svnversion ~/upp.src)
current_date=$(LC_TIME=En date '+%a %b %d %Y')

sed -i -e 's|%version|'"$svn_snapshot_version"'|g' -e 's|%date|'"$current_date"'|g' ~/upp.tmp/upp/upp.spec

cd ~/upp.tmp
mv upp upp-x11-src-$svn_snapshot_version
tar -cvvzf ~/upload/upp-x11-src-$svn_snapshot_version.tar.gz upp-x11-src-$svn_snapshot_version
#mv upp-x11-src-$svn_snapshot_version upp
#~/bin/upload
