#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// ScatterCtrl.cpp

T_("%s data file")
caES("")
esES("Fichero de datos %s")
euES("")
frFR("")

T_("Scatter plot data")
caES("")
esES("Datos del gr\303\241fico")
euES("")
frFR("")

T_("Loading plot data from file")
caES("")
esES("Leyendo gr\303\241fico del fichero")
euES("")
frFR("")

T_("Plot has not been loaded")
caES("")
esES("Gr\303\241fico no ha sido leido")
euES("")
frFR("")

T_("File format \"%s\" not found")
caES("Format \"%s\" no trobat")
esES("Formato \"%s\" no encontrado")
euES("Formatua \"%s\" ez da aurkitu")
frFR("Format de fichier \"%s\" est introuvable")

T_("Saving plot data to file")
caES("")
esES("Salvando gr\303\241fico a fichero")
euES("")
frFR("")

T_("Plot has not been saved")
caES("El gr\303\240fic no s'ha desat")
esES("El gr\303\241fico no ha sido guardado")
euES("Lurzatia ez da gorde")
frFR("Plot n'a pas \303\251t\303\251 enregistr\303\251")

T_("\316\224")
caES("")
esES("\342\210\206")
euES("")
frFR("")

T_("Fit to data")
caES("Ajust a les dades")
esES("Ajustar a los datos")
euES("Datuak egokitzen")
frFR("Ajust\303\251 aux donn\303\251es")

T_("Zoom to fit visible all data")
caES("")
esES("Zoom para ver todos los datos")
euES("")
frFR("")

T_("Zoom +")
caES("")
esES("")
euES("")
frFR("")

T_("Zoom in (closer)")
caES("")
esES("Zoom para acercar")
euES("")
frFR("")

T_("Zoom -")
caES("")
esES("")
euES("")
frFR("")

T_("Zoom out (away)")
caES("")
esES("Zoom para alejar")
euES("")
frFR("")

T_("Attach X axis")
caES("")
esES("Fijar eje X")
euES("")
frFR("")

T_("Fix X axis so no zoom or scroll is possible")
caES("")
esES("Fijar eje X evitando scroll y zoom")
euES("")
frFR("")

T_("Scroll Left")
caES("Moure a l'esquerra")
esES("Mover a la izquierda")
euES("Korritu Ezker")
frFR("Faites d\303\251filer \303\240 gauche")

T_("Scrolls plot to the left")
caES("")
esES("Mueve el gr\303\241fico a la izquierda")
euES("")
frFR("")

T_("Scroll Right")
caES("More a la dreta")
esES("Mover a la derecha")
euES("Korritu eskubidea")
frFR("Faites d\303\251filer \303\240 droite")

T_("Scrolls plot to the right")
caES("")
esES("Mueve el gr\303\241fico a la derecha")
euES("")
frFR("")

T_("Attach Y axis")
caES("")
esES("Fijar eje Y")
euES("")
frFR("")

T_("Fix Y axis so no zoom or scroll is possible")
caES("")
esES("Fijar eje Y evitando scroll y zoom")
euES("")
frFR("")

T_("Scroll Up")
caES("Moure amunt")
esES("Mover arriba")
euES("Korritu gora")
frFR("D\303\251filement vers le haut")

T_("Scrolls plot up")
caES("")
esES("Mueve el gr\303\241fico hacia arriba")
euES("")
frFR("")

T_("Scroll Down")
caES("Moure baix")
esES("Mover abajo")
euES("Korritu behera")
frFR("D\303\251filement vers le bas")

T_("Scrolls plot down")
caES("")
esES("Mueve el gr\303\241fico hacia abajo")
euES("")
frFR("")

T_("Properties")
caES("Propietats")
esES("Propiedades")
euES("Propietateak")
frFR("Propri\303\251t\303\251s")

T_("Plot properties dialog")
caES("")
esES("Di\303\241logo de propiedades del gr\303\241fico")
euES("")
frFR("")

T_("Data")
caES("Dades")
esES("Datos")
euES("Egokitzen")
frFR("Donn\303\251es")

T_("Raw data table")
caES("")
esES("Tabla de datos base")
euES("")
frFR("")

T_("Process")
caES("")
esES("Procesado")
euES("")
frFR("")

T_("Data processing dialog")
caES("")
esES("Di\303\241logo para procesado de datos")
euES("")
frFR("")

T_("Copy image")
caES("")
esES("Copiar imagen")
euES("")
frFR("")

T_("Copy image to clipboard")
caES("")
esES("Copiar imagen al portapapeles")
euES("")
frFR("")

T_("Save image")
caES("")
esES("Guardar imagen")
euES("")
frFR("")

T_("Save image to file")
caES("")
esES("Guardar imagen en un fichero")
euES("")
frFR("")

T_("Load plot")
caES("")
esES("Leer gr\303\241fico")
euES("")
frFR("")

T_("Load plot from file")
caES("")
esES("Leer gr\303\241fico de fichero")
euES("")
frFR("")

T_("Save plot")
caES("")
esES("Salvar gr\303\241fico")
euES("")
frFR("")

T_("Save plot to file")
caES("")
esES("Salvar gr\303\241fico a fichero")
euES("")
frFR("")

T_("%s bitmap file")
caES("")
esES("Fichero de mapa de bits %s")
euES("")
frFR("")

T_("%s vector file")
caES("")
esES("Fichero vectorial %s")
euES("")
frFR("")

T_("Scatter plot")
caES("")
esES("Gr\303\241fico")
euES("")
frFR("")

T_("Saving plot image to file")
caES("")
esES("Salvando imagen del gr\303\241fico a fichero")
euES("")
frFR("")

T_("x")
caES("")
esES("")
euES("")
frFR("")

T_("y1")
caES("")
esES("")
euES("")
frFR("")

T_("y2")
caES("")
esES("")
euES("")
frFR("")


// Properties.cpp

T_("X min has to be lower than X max")
caES("")
esES("X min tiene que ser menor que X max")
euES("")
frFR("")

T_("Y min has to be lower than Y max")
caES("")
esES("Y min tiene que ser menor que Y max")
euES("")
frFR("")

T_("Y min2 has to be lower than Y max2")
caES("")
esES("Y min2 tiene que ser menor que Y max2")
euES("")
frFR("")

T_("Name")
caES("Nom")
esES("Nombre")
euES("Izena")
frFR("Nom")

T_("No mark")
caES("Sense marca")
esES("Sin marca")
euES("Marka gabe")
frFR("Sans marque")

T_("Dash \"%s\"")
caES("")
esES("Guiones \"%s\"")
euES("")
frFR("")

T_("You are going to delete '%s' series.&Do you agree?")
caES("")
esES("Vas a borrar la serie '%s'.&\302\277Est\303\241s de acuerdo?")
euES("")
frFR("")


// Properties.h

T_("Font")
caES("")
esES("Fuente")
euES("")
frFR("")


// Processing.cpp

T_("Scatter properties")
caES("Propietats de gr\303\240fic")
esES("Propiedades de gr\303\241fico")
euES("Grafikoa propietateak")
frFR("Propri\303\251t\303\251s des graphes")

T_("Measures")
caES("Mesures")
esES("Medidas")
euES("Neurriak")
frFR("Mesures")

T_("Texts")
caES("Textos")
esES("Textos")
euES("Testuak")
frFR("Textes")

T_("Legend")
caES("Llegenda")
esES("Leyenda")
euES("Kondaira")
frFR("L\303\251gende")

T_("Series")
caES("S\303\250ries")
esES("Series")
euES("Series")
frFR("S\303\250ries")

T_("Id")
caES("")
esES("")
euES("")
frFR("")

T_("Data fit")
caES("")
esES("Ajuste de datos")
euES("")
frFR("")

T_("Frequency")
caES("")
esES("Frecuencia")
euES("")
frFR("")

T_("Operations")
caES("")
esES("Operaciones")
euES("")
frFR("")

T_("Best fit")
caES("")
esES("Mejor ajuste")
euES("")
frFR("")

T_("To show real equation coefficients with different precisions or just in "
     "text")
caES("")
esES("")
euES("")
frFR("")

T_("Min. R2 to plot the equation")
caES("")
esES("M\303\255n. R2 para mostrar ecuaci\303\263n")
euES("")
frFR("")

T_("User suppled equation. Initial guess values separated with ';'")
caES("")
esES("Ecuaci\303\263n de usuario. Valores iniciales estimados separados con ';'")
euES("")
frFR("")

T_("Type")
caES("")
esES("Tipo")
euES("")
frFR("")

T_("Equation")
caES("")
esES("Ecuaci\303\263n")
euES("")
frFR("")

T_("R2")
caES("")
esES("")
euES("")
frFR("")

T_("It tries to fit the series with the supported equations")
caES("")
esES("Intenta ajustar la serie con las ecuaciones incluidas")
euES("")
frFR("")

T_("Select all")
caES("Seleccionar tot")
esES("Seleccionar todo")
euES("Hautatu guztiak")
frFR("S\303\251lectionner tout")

T_("Select all rows")
caES("Seleccionar totes les files")
esES("Seleccionar todas las filas")
euES("Hautatu errenkada guztiak")
frFR("S\303\251lectionnez toutes les lignes")

T_("Copy")
caES("Copiar")
esES("Copiar")
euES("Kopiatu")
frFR("Copier")

T_("Copy selected rows")
caES("")
esES("Copiar files selecc.")
euES("")
frFR("")

T_("'x >' has to be lower than 'x <'")
caES("")
esES("'x >' tiene que ser menor que 'x <'")
euES("")
frFR("")

T_("Max")
caES("")
esES("M\303\241x")
euES("")
frFR("")

T_("Min")
caES("")
esES("M\303\255n")
euES("")
frFR("")

T_("MovAvg")
caES("")
esES("MedMov")
euES("")
frFR("")

T_("SecAvg")
caES("")
esES("MedSeg")
euES("")
frFR("")

T_("Impossible to calculate FFT from a not sampled series")
caES("")
esES("Imposible calcular FFT de una serie no muestreada")
euES("")
frFR("")

T_("Insufficient data to calculate FFT")
caES("")
esES("Datos insufucientes para calcular FFT")
euES("")
frFR("")

T_("Sampling time changes from %f to %f")
caES("")
esES("El tiempo de muestreo varia entre %f y %f")
euES("")
frFR("")

T_("Processed")
caES("")
esES("Procesado")
euES("")
frFR("")

T_("Average")
caES("")
esES("Promedio")
euES("")
frFR("")

T_("Linear")
caES("")
esES("Lineal")
euES("")
frFR("")

T_("Cuadratic")
caES("")
esES("Cuadr\303\241tico")
euES("")
frFR("")

T_("Cubic")
caES("")
esES("C\303\272bico")
euES("")
frFR("")

T_("Sinusoidal")
caES("")
esES("")
euES("")
frFR("")

T_("Sinusoidal tend")
caES("")
esES("Tend. sinusoidal")
euES("")
frFR("")

T_("Spline")
caES("")
esES("")
euES("")
frFR("")

T_("Incorrect sampling time")
caES("")
esES("Tiempo de muestreo incorrecto")
euES("")
frFR("")

T_("Error obtaining FFT")
caES("")
esES("Error obteniendo FFT")
euES("")
frFR("")

T_("FFT")
caES("")
esES("")
euES("")
frFR("")

T_("FFT-phase [rad]")
caES("")
esES("FFT-fase [rad]")
euES("")
frFR("")

T_("Power Spectral Density")
caES("")
esES("Espectro de densidad energ\303\251tica")
euES("")
frFR("")

T_("Frequency [Hz]")
caES("")
esES("Frecuencia [Hz]")
euES("")
frFR("")

T_("Period [sec]")
caES("")
esES("Periodo [seg]")
euES("")
frFR("")


// Data.cpp

T_("Scatter data")
caES("Dades del gr\303\240fic")
esES("Datos del gr\303\241fico")
euES("Datuak taula")
frFR("Tableau de donn\303\251es")

T_("All")
caES("")
esES("Todo")
euES("")
frFR("")

T_("%s file")
caES("Fitxer %s")
esES("Fichero %s")
euES("Fitxategia %s")
frFR("Fichier %s")

T_("Comma separated values (.csv)")
caES("")
esES("Valores separados por coma (.csv)")
euES("")
frFR("")

T_("Saving plot data")
caES("")
esES("Salvando los datos del gr\303\241fico")
euES("")
frFR("")

T_("Plot data has not been saved")
caES("")
esES("Los datos del gr\303\241fico no han sido salvados")
euES("")
frFR("")

T_("No row selected")
caES("")
esES("Ninguna fila seleccionada")
euES("")
frFR("")

T_("Selected %d rows")
caES("")
esES("Seleccionadas %d filas")
euES("")
frFR("")

T_("Copy selected rows to clipboard")
caES("")
esES("Copiar filas seleccionadas al portapapeles")
euES("")
frFR("")

T_("Save to file")
caES("Guardar a fitxer")
esES("Guardar en fichero")
euES("Gorde fitxategira")
frFR("Enregistrer dans un fichier")

T_("Save to .csv file")
caES("")
esES("Salvar a fichero .csv")
euES("")
frFR("")


// ScatterCtrl.lay

T_("OK")
caES("")
esES("Continuar")
euES("")
frFR("")

T_("Close this dialog")
caES("Tancar aquesta finestra")
esES("Cerrar este di\303\241logo")
euES("Itxi elkarrizketa hau")
frFR("Fermez cette bo\303\256te de dialogue")

T_("X max")
caES("")
esES("")
euES("")
frFR("")

T_("Y max 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y min 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y max")
caES("")
esES("")
euES("")
frFR("")

T_("Y min")
caES("")
esES("")
euES("")
frFR("")

T_("X min")
caES("")
esES("")
euES("")
frFR("")

T_("Reticle")
caES("")
esES("Ret\303\255cula")
euES("")
frFR("")

T_("Attach")
caES("")
esES("Fijar")
euES("")
frFR("")

T_("Label Y2:")
caES("Etiqueta Y2:")
esES("Etiqueta Y2:")
euES("Etiketa Y2:")
frFR("\303\211tiquette Y2:")

T_("Title:")
caES("T\303\255tol:")
esES("T\303\255tulo:")
euES("Izenburua:")
frFR("Titre:")

T_("Label X:")
caES("Etiqueta X:")
esES("Etiqueta X:")
euES("Etiketa X:")
frFR("\303\211tiquette X:")

T_("Top margin:")
caES("")
esES("Margen superior:")
euES("")
frFR("")

T_("Label Y:")
caES("Etiqueta Y:")
esES("Etiqueta Y:")
euES("Etiketa Y:")
frFR("\303\211tiquette Y:")

T_("Left margin:")
caES("")
esES("Margen izquierdo:")
euES("")
frFR("")

T_("Right margin:")
caES("")
esES("Margen derecho:")
euES("")
frFR("")

T_("Bottom margin:")
caES("")
esES("Margen inferior:")
euES("")
frFR("")

T_("Show Legend")
caES("Mostra llegenda")
esES("Mostrar leyenda")
euES("Erakutsi legenda")
frFR("Afficher la l\303\251gende")

T_("Top\nTable")
caES("Dalt\nTaula")
esES("Arriba\nTabla")
euES("Sortu\nTaula")
frFR("Haut\nTable")

T_("Position")
caES("Posici\303\263")
esES("Posici\303\263n")
euES("Kokaleku")
frFR("Position")

T_("Left-Top")
caES("Esq-Dalt")
esES("Izq-Arriba")
euES("Ezker-Sortu")
frFR("Gauche-Haut")

T_("Right-Top")
caES("Dret-Dalt")
esES("Der-Arriba")
euES("Esku-Sortu")
frFR("Droit-Haut")

T_("Left-Bottom")
caES("Esq-Fons")
esES("Izq-Abajo")
euES("Ezker-Behean")
frFR("Gauche-Bas")

T_("Right-Bottom")
caES("Dret-Fons")
esES("Der-Abajo")
euES("Esku-Behean")
frFR("Droit-Bas")

T_("Vertical:")
caES("Vertical:")
esES("Vertical:")
euES("Bertikal:")
frFR("Vertical:")

T_("Column number:")
caES("Nombre de columna:")
esES("N\303\272mero de columnas:")
euES("Zutabe kopurua:")
frFR("Num\303\251ro de colonne:")

T_("Row spacing:")
caES("Dist\303\240ncia entre l\303\255nies:")
esES("Distancia entre lineas:")
euES("Errenkada tartea:")
frFR("\303\211cartement des rangs:")

T_("Border color:")
caES("Color de la vora:")
esES("Color del borde:")
euES("Ertzean kolorea:")
frFR("Couleur de la bordure")

T_("Horiz.:")
caES("Horiz.:")
esES("Horiz.:")
euES("Horitz.:")
frFR("Horiz.:")

T_("Fill color:")
caES("Color de farciment:")
esES("Color de relleno:")
euES("Kolore betegarri:")
frFR("Couleur de remplissage:")

T_("Distance to corner")
caES("Dist\303\240ncia a la cantonada:")
esES("Distancia a la esquina:")
euES("Txoko distantzia:")
frFR("Distance \303\240 coin:")

T_("Anchor corner")
caES("Cantonada d'ancoratge")
esES("Esquina de anclaje")
euES("Txoko aingura")
frFR("Ancrage de coin")

T_("Table")
caES("Taula")
esES("Tabla")
euES("Taula")
frFR("Table")

T_("Remove")
caES("")
esES("Borrar")
euES("")
frFR("")

T_("Down")
caES("")
esES("Abajo")
euES("")
frFR("")

T_("Up")
caES("")
esES("Arriba")
euES("")
frFR("")

T_("Primary")
caES("Prim\303\240ria")
esES("Primaria")
euES("Lehen")
frFR("Primaire")

T_("Visible")
caES("Visible")
esES("Visible")
euES("Ikusgai")
frFR("Visible")

T_("Units")
caES("Unitats")
esES("Unidades")
euES("Unitateak")
frFR("Unit\303\251s")

T_("Mark")
caES("Marca")
esES("Marca")
euES("Marka")
frFR("Marque")

T_("Type:")
caES("")
esES("Tipo:")
euES("")
frFR("")

T_("Color:")
caES("Color:")
esES("Color:")
euES("Kolorea")
frFR("Couleur")

T_("Fill:")
caES("Omplir:")
esES("Relleno:")
euES("Bete:")
frFR("Remplir:")

T_("X axis:")
caES("Eix X:")
esES("Eje X:")
euES("X ardatzean:")
frFR("Axe X:")

T_("Y axis:")
caES("Eix Y:")
esES("Eje Y:")
euES("Y ardatzean:")
frFR("Axe Y:")

T_("Line:")
caES("L\303\255nia:")
esES("L\303\255nea:")
euES("Line:")
frFR("Ligne:")

T_("Dash:")
caES("Gui\303\263:")
esES("Gui\303\263n:")
euES("Marraz:")
frFR("Tiret:")

T_("Thickness:")
caES("Espessor:")
esES("Espesor")
euES("Lodiera:")
frFR("\303\211paisseur:")

T_("Name:")
caES("Nom:")
esES("Nombre:")
euES("Izena:")
frFR("Nom:")

T_("Width:")
caES("Ample:")
esES("Anchura:")
euES("Zabalera:")
frFR("Largeur:")

T_("Style:")
caES("Estil:")
esES("Estilo:")
euES("Tankera:")
frFR("Style:")

T_("Close")
caES("Tancar")
esES("Cerrar")
euES("Itxi")
frFR("Fermer")

T_("Sin. tend.")
caES("")
esES("Tend. sin.")
euES("")
frFR("")

T_("Show Eq.")
caES("")
esES("Most. eq.")
euES("")
frFR("")

T_("Max curve")
caES("")
esES("Curva m\303\241x.")
euES("")
frFR("")

T_("Min curve")
caES("")
esES("Curva m\303\255n.")
euES("")
frFR("")

T_("Moving Average")
caES("")
esES("Media m\303\263vil")
euES("")
frFR("")

T_("Sector Average")
caES("")
esES("Promed. sector")
euES("")
frFR("")

T_("Autosens")
caES("")
esES("")
euES("")
frFR("")

T_("Max imp.:")
caES("")
esES("")
euES("")
frFR("")

T_("R2 coeff.")
caES("")
esES("R2 coef.")
euES("")
frFR("")

T_("Num decimals:")
caES("")
esES("N\303\272m decimales:")
euES("")
frFR("")

T_("Max:")
caES("")
esES("M\303\241x:")
euES("")
frFR("")

T_("StdDev:")
caES("")
esES("DevEst:")
euES("")
frFR("")

T_("Average:")
caES("")
esES("Promedio:")
euES("")
frFR("")

T_("Sensitivity")
caES("")
esES("Sensibilidad")
euES("")
frFR("")

T_("Statistical data")
caES("")
esES("Datos estadisticos")
euES("")
frFR("")

T_("RMS:")
caES("")
esES("Med. cuad.:")
euES("")
frFR("")

T_("Min:")
caES("")
esES("M\303\255n:")
euES("")
frFR("")

T_("x <")
caES("")
esES("")
euES("")
frFR("")

T_("Conditions")
caES("")
esES("Condiciones")
euES("")
frFR("")

T_("x >")
caES("")
esES("")
euES("")
frFR("")

T_("sec")
caES("")
esES("seg")
euES("")
frFR("")

T_("Sampling time:")
caES("")
esES("Tiempo de muestreo:")
euES("")
frFR("")

T_("Time\nFrequency")
caES("")
esES("Tiempo\nFrecuencia")
euES("")
frFR("")

T_("Subdivision")
caES("")
esES("Subdivisi\303\263n")
euES("")
frFR("")

T_("Spectral moments")
caES("")
esES("Momentos espectrales")
euES("")
frFR("")

T_("FFT\nPhase\nPSD")
caES("")
esES("FFT\nFase\nPSD")
euES("")
frFR("")

T_("Overlapping:")
caES("")
esES("Solapamiento:")
euES("")
frFR("")

T_("Number:")
caES("")
esES("N\303\272m:")
euES("")
frFR("")

T_("Window")
caES("")
esES("Ventana")
euES("")
frFR("")

T_("m0:")
caES("")
esES("")
euES("")
frFR("")

T_("m1:")
caES("")
esES("")
euES("")
frFR("")

T_("m2:")
caES("")
esES("")
euES("")
frFR("")

T_("m-1:")
caES("")
esES("")
euES("")
frFR("")

T_("X Axis")
caES("")
esES("Eje X")
euES("")
frFR("")

T_("Normal\nFull\nText")
caES("")
esES("Normal\nCompleto\nTexto")
euES("")
frFR("")

T_("Fit")
caES("")
esES("")
euES("")
frFR("")

T_("Min R2:")
caES("")
esES("M\303\255n R2:")
euES("")
frFR("")

T_("Coefficients")
caES("")
esES("Coeficientes")
euES("")
frFR("")

T_("User equation:")
caES("")
esES("Ecuacion usuario:")
euES("")
frFR("")

T_("Bold")
caES("")
esES("Negrita")
euES("")
frFR("")

T_("Italic")
caES("")
esES("Cursiva")
euES("")
frFR("")

T_("NonAntiAliased")
caES("")
esES("NoAntialiased")
euES("")
frFR("")


// PieCtrl.cpp

T_("Pie plot")
caES("")
esES("Gr\303\241fico de tarta")
euES("")
frFR("")

T_("Saving plot to PNG or JPEG file")
caES("Guardant gr\303\240fic en fitxer PNG o JPEG")
esES("Guardando gr\303\241fico en fichero PNG o JPEG")
euES("Aurrezteko grafikoa PNG edo JPEG fitxategia")
frFR("Enregistrement plot visant \303\240 fichier PNG ou JPEG")


// Obsolete

T_("Size:")
caES("")
esES("Tam:")
euES("")
frFR("")

T_("Font:")
caES("")
esES("Tipo:")
euES("")
frFR("")

T_("Text:")
caES("")
esES("Texto:")
euES("")
frFR("")

T_("Data processing")
caES("")
esES("Procesado de datos")
euES("")
frFR("")

T_("%s processing")
caES("")
esES("Procesado de %s")
euES("")
frFR("")
