#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// ScatterCtrl.cpp

T_("Fit to data")
caES("Ajust a les dades")
esES("Ajustar a los datos")
euES("Datuak egokitzen")
frFR("Ajust\303\251 aux donn\303\251es")

T_("Zoom +")
caES("")
esES("")
euES("")
frFR("")

T_("Zoom -")
caES("")
esES("")
euES("")
frFR("")

T_("Attach X axis")
caES("")
esES("Fijar eje X")
euES("")
frFR("")

T_("Scroll Left")
caES("Moure a l'esquerra")
esES("Mover a la izquierda")
euES("Korritu Ezker")
frFR("Faites d\303\251filer \303\240 gauche")

T_("Scroll Right")
caES("More a la dreta")
esES("Mover a la derecha")
euES("Korritu eskubidea")
frFR("Faites d\303\251filer \303\240 droite")

T_("Attach Y axis")
caES("")
esES("Fijar eje Y")
euES("")
frFR("")

T_("Scroll Up")
caES("Moure amunt")
esES("Mover arriba")
euES("Korritu gora")
frFR("D\303\251filement vers le haut")

T_("Scroll Down")
caES("Moure baix")
esES("Mover abajo")
euES("Korritu behera")
frFR("D\303\251filement vers le bas")

T_("Properties")
caES("Propietats")
esES("Propiedades")
euES("Propietateak")
frFR("Propri\303\251t\303\251s")

T_("Data")
caES("Dades")
esES("Datos")
euES("Egokitzen")
frFR("Donn\303\251es")

T_("Copy")
caES("Copiar")
esES("Copiar")
euES("Kopiatu")
frFR("Copier")

T_("Save to file")
caES("Guardar a fitxer")
esES("Guardar en fichero")
euES("Gorde fitxategira")
frFR("Enregistrer dans un fichier")

T_("%s file")
caES("Fitxer %s")
esES("Fichero %s")
euES("Fitxategia %s")
frFR("Fichier %s")

T_("Saving plot to PNG or JPEG file")
caES("Guardant gr\303\240fic en fitxer PNG o JPEG")
esES("Guardando gr\303\241fico en fichero PNG o JPEG")
euES("Aurrezteko grafikoa PNG edo JPEG fitxategia")
frFR("Enregistrement plot visant \303\240 fichier PNG ou JPEG")

T_("Plot has not been saved")
caES("El gr\303\240fic no s'ha desat")
esES("El gr\303\241fico no ha sido guardado")
euES("Lurzatia ez da gorde")
frFR("Plot n'a pas \303\251t\303\251 enregistr\303\251")

T_("File format \"%s\" not found")
caES("Format \"%s\" no trobat")
esES("Formato \"%s\" no encontrado")
euES("Formatua \"%s\" ez da aurkitu")
frFR("Format de fichier \"%s\" est introuvable")


// Properties.cpp

T_("Name")
caES("Nom")
esES("Nombre")
euES("Izena")
frFR("Nom")

T_("No mark")
caES("Sense marca")
esES("Sin marca")
euES("Marka gabe")
frFR("Sans marque")

T_("Scatter data")
caES("Dades del gr\303\240fic")
esES("Datos del gr\303\241fico")
euES("Datuak taula")
frFR("Tableau de donn\303\251es")

T_("Select all")
caES("Seleccionar tot")
esES("Seleccionar todo")
euES("Hautatu guztiak")
frFR("S\303\251lectionner tout")

T_("Select all rows")
caES("Seleccionar totes les files")
esES("Seleccionar todas las filas")
euES("Hautatu errenkada guztiak")
frFR("S\303\251lectionnez toutes les lignes")

T_("Copy selected rows")
caES("Copiar les files seleccionades")
esES("Copiar las filas seleccionadas")
euES("Kopiatu hautatutako errenkadak")
frFR("Copie les lignes s\303\251lectionn\303\251es")

T_("Scatter properties")
caES("Propietats de gr\303\240fic")
esES("Propiedades de gr\303\241fico")
euES("Grafikoa propietateak")
frFR("Propri\303\251t\303\251s des graphes")

T_("Measures")
caES("Mesures")
esES("Medidas")
euES("Neurriak")
frFR("Mesures")

T_("Texts")
caES("Textos")
esES("Textos")
euES("Testuak")
frFR("Textes")

T_("Legend")
caES("Llegenda")
esES("Leyenda")
euES("Kondaira")
frFR("L\303\251gende")

T_("Series")
caES("S\303\250ries")
esES("Series")
euES("Series")
frFR("S\303\250ries")


// ScatterCtrl.lay

T_("Close")
caES("Tancar")
esES("Cerrar")
euES("Itxi")
frFR("Fermer")

T_("Close this dialog")
caES("Tancar aquesta finestra")
esES("Cerrar este di\303\241logo")
euES("Itxi elkarrizketa hau")
frFR("Fermez cette bo\303\256te de dialogue")

T_("X max")
caES("")
esES("")
euES("")
frFR("")

T_("Y max 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y min 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y max")
caES("")
esES("")
euES("")
frFR("")

T_("Y min")
caES("")
esES("")
euES("")
frFR("")

T_("X min")
caES("")
esES("")
euES("")
frFR("")

T_("Update")
caES("")
esES("")
euES("")
frFR("")

T_("Label Y2:")
caES("Etiqueta Y2:")
esES("Etiqueta Y2:")
euES("Etiketa Y2:")
frFR("\303\211tiquette Y2:")

T_("Title:")
caES("T\303\255tol:")
esES("T\303\255tulo:")
euES("Izenburua:")
frFR("Titre:")

T_("Label X:")
caES("Etiqueta X:")
esES("Etiqueta X:")
euES("Etiketa X:")
frFR("\303\211tiquette X:")

T_("Top margin:")
caES("")
esES("")
euES("")
frFR("")

T_("Label Y:")
caES("Etiqueta Y:")
esES("Etiqueta Y:")
euES("Etiketa Y:")
frFR("\303\211tiquette Y:")

T_("Left margin:")
caES("")
esES("Margen izquierdo:")
euES("")
frFR("")

T_("Right margin:")
caES("")
esES("Margen derecho:")
euES("")
frFR("")

T_("Bottom margin:")
caES("")
esES("Margen inferior:")
euES("")
frFR("")

T_("Position")
caES("Posici\303\263")
esES("Posici\303\263n")
euES("Kokaleku")
frFR("Position")

T_("Vertical:")
caES("Vertical:")
esES("Vertical:")
euES("Bertikal:")
frFR("Vertical:")

T_("Column number:")
caES("Nombre de columna:")
esES("N\303\272mero de columnas:")
euES("Zutabe kopurua:")
frFR("Num\303\251ro de colonne:")

T_("Row spacing:")
caES("Dist\303\240ncia entre l\303\255nies:")
esES("Distancia entre lineas:")
euES("Errenkada tartea:")
frFR("\303\211cartement des rangs:")

T_("Border color:")
caES("Color de la vora:")
esES("Color del borde:")
euES("Ertzean kolorea:")
frFR("Couleur de la bordure")

T_("Horiz.:")
caES("Horiz.:")
esES("Horiz.:")
euES("Horitz.:")
frFR("Horiz.:")

T_("Show Legend")
caES("Mostra llegenda")
esES("Mostrar leyenda")
euES("Erakutsi legenda")
frFR("Afficher la l\303\251gende")

T_("Fill color:")
caES("Color de farciment:")
esES("Color de relleno:")
euES("Kolore betegarri:")
frFR("Couleur de remplissage:")

T_("Distance to corner")
caES("Dist\303\240ncia a la cantonada:")
esES("Distancia a la esquina:")
euES("Txoko distantzia:")
frFR("Distance \303\240 coin:")

T_("Anchor corner")
caES("Cantonada d'ancoratge")
esES("Esquina de anclaje")
euES("Txoko aingura")
frFR("Ancrage de coin")

T_("Top\nTable")
caES("Dalt\nTaula")
esES("Arriba\nTabla")
euES("Sortu\nTaula")
frFR("Haut\nTable")

T_("Right-Bottom")
caES("Dret-Fons")
esES("Der-Abajo")
euES("Esku-Behean")
frFR("Droit-Bas")

T_("Left-Top")
caES("Esq-Dalt")
esES("Izq-Arriba")
euES("Ezker-Sortu")
frFR("Gauche-Haut")

T_("Right-Top")
caES("Dret-Dalt")
esES("Der-Arriba")
euES("Esku-Sortu")
frFR("Droit-Haut")

T_("Table")
caES("Taula")
esES("Tabla")
euES("Taula")
frFR("Table")

T_("Left-Bottom")
caES("Esq-Fons")
esES("Izq-Abajo")
euES("Ezker-Behean")
frFR("Gauche-Bas")

T_("Visible")
caES("Visible")
esES("Visible")
euES("Ikusgai")
frFR("Visible")

T_("Units")
caES("Unitats")
esES("Unidades")
euES("Unitateak")
frFR("Unit\303\251s")

T_("Mark")
caES("Marca")
esES("Marca")
euES("Marka")
frFR("Marque")

T_("Style:")
caES("Estil:")
esES("Estilo:")
euES("Tankera:")
frFR("Style:")

T_("Color:")
caES("Color:")
esES("Color:")
euES("Kolorea")
frFR("Couleur")

T_("Fill:")
caES("Omplir:")
esES("Relleno:")
euES("Bete:")
frFR("Remplir:")

T_("X axis:")
caES("Eix X:")
esES("Eje X:")
euES("X ardatzean:")
frFR("Axe X:")

T_("Y axis:")
caES("Eix Y:")
esES("Eje Y:")
euES("Y ardatzean:")
frFR("Axe Y:")

T_("Line:")
caES("L\303\255nia:")
esES("L\303\255nea:")
euES("Line:")
frFR("Ligne:")

T_("Dash:")
caES("Gui\303\263:")
esES("Gui\303\263n:")
euES("Marraz:")
frFR("Tiret:")

T_("Thickness:")
caES("Espessor:")
esES("Espesor")
euES("Lodiera:")
frFR("\303\211paisseur:")

T_("Name:")
caES("Nom:")
esES("Nombre:")
euES("Izena:")
frFR("Nom:")

T_("Width:")
caES("Ample:")
esES("Anchura:")
euES("Zabalera:")
frFR("Largeur:")

T_("Primary")
caES("Prim\303\240ria")
esES("Primaria")
euES("Lehen")
frFR("Primaire")

