// main.cpp
T_("Monday")
plPL("Poniedziałek")
T_("Tuesday")
plPL("Wtorek")
T_("Wednesday")
plPL("Środa")
T_("Thursday")
plPL("Czwartek")
T_("Friday")
plPL("Piątek")
T_("Saturday")
plPL("Sobota")
T_("Sunday")
plPL("Niedziela")

T_("Mo")
plPL("Pn")
T_("Tu")
plPL("Wt")
T_("We")
plPL("Śr")
T_("Th")
plPL("Cz")
T_("Fr")
plPL("Pt")
T_("Sa")
plPL("So")
T_("Su")
plPL("Nd")

T_("January")
plPL("Styczeń")
T_("February")
plPL("Luty")
T_("March")
plPL("Marzec")
T_("April")
plPL("Kwiecień")
T_("May")
plPL("Maj")
T_("June")
plPL("Czerwiec")
T_("July")
plPL("Lipiec")
T_("August")
plPL("Sierpień")
T_("September")
plPL("Wrzesień")
T_("October")
plPL("Październik")
T_("November")
plPL("Listopad")
T_("December")
plPL("Grudzień")

T_("Week")
plPL("Tydzień")
T_("Wk")
plPL("Ty.")

T_("Today")
plPL("Dziś")

T_("Next month")
plPL("Następny miesiąc")
T_("Previous month")
plPL("Poprzedni miesiąc")

T_("Next year")
plPL("Następny rok")
T_("Previous year")
plPL("Poprzedni rok")
