T_("Exit")
plPL("Zakończ")
T_("Options")
plPL("Ustawienia")
T_("About")
plPL("O programie")

T_("Home budget")
plPL("Budżet domowy")
T_("Expenses")
plPL("Wydatki")
T_("Categories")
plPL("Kategorie")
T_("Summary")
plPL("Podsumowanie")
T_("Category")
plPL("Kategoria")
T_("Product")
plPL("Produkt")
T_("Value")
plPL("Ile")
T_("When")
plPL("Kiedy")
T_("Describe")
plPL("Opis")
T_("Month")
plPL("Miesiąc")
T_("Default value")
plPL("Wartość domyślna")
T_("Plus / Minus")
plPL("Plus / Minus")
T_("Default for a new month")
plPL("Domyślnie w nowym miesiącu")
T_("Minus")
plPL("Minus")
T_("Plus")
plPL("Plus")
T_("No")
plPL("Nie")
T_("Yes")
plPL("Tak")

T_("Name")
plPL("Nazwa")

T_("Language")
plPL("Język")

T_("Income:")
plPL("Dochód:")
T_("Spent:")
//T_("Laid out:")
plPL("Wydano:")
T_("Rest:")
plPL("Zostało:")
T_("Amount from prev. month:")
plPL("Kwota z poprz. miesiąca:")
T_("Final rest:")
plPL("Realnie zostało:")
T_("Most expensive")
plPL("Najwięcej wydano na")
T_("Product")
plPL("Produkt")
T_("Category")
plPL("Kategoria")
T_("Amount")
plPL("Ile")

T_("New item")
plPL("Nowa pozycja")
T_("New category")
plPL("Nowa kategoria")

T_("No help available yet")
plPL("Pomoc nie jest obecnie dostępna")

T_("You can't remove this group. It is not empty.")
plPL("Nie można usunąc tej grupy. Nie jest pusta.")

T_("Item '%s' can't be removed. It is used in calculations.")
plPL("Nie można usunąć pozycji '%s'. Jest wykorzystywana w rozliczeniach.")

T_("Clear all data from database")
plPL("Usuń wszystkie dane z bazy danych")

T_("Database was cleared")
plPL("Baza danych została wyczyszczona")

T_("Can't create or open database file")
plPL("Nie można utworzyć lub otworzyć bazy danych")
T_("Database file is corrupted")
plPL("Plik bazy danych jest uszkodzony")
