TABLE_(BOOK)
	INT_    (ID) PRIMARY_KEY AUTO_INCREMENT
	STRING_ (AUTHOR, 2000)
	STRING_ (TITLE, 2000)
END_TABLE

TABLE_(BORROW_RECORD)
	INT     (ID) PRIMARY_KEY AUTO_INCREMENT
	INT_    (BOOK_ID) REFERENCES(BOOK)
	STRING_ (PERSON, 2000) INDEX
	INT_    (BORROWED) INDEX
	INT_    (RETURNED) INDEX
END_TABLE
