TABLE_(SUPPLIER)
	INT_    (ID) PRIMARY_KEY AUTO_INCREMENT
	STRING_ (NAME, 80) NOT_NULL SQLDEFAULT("")
	STRING_ (ADDRESS1, 128)
	STRING_ (ADDRESS2, 128)
	STRING_ (CITY, 128)
	STRING_ (STATE, 80)
	STRING_ (POSTAL_CODE, 24)
	STRING_ (PRIMARY_PHONE, 35)
	STRING_ (SECONDARY_PHONE, 35)
	STRING_ (EMAIL, 128)
	STRING_ (WEB_ADDRESS, 500)
	BLOB_   (DESCRIPTION)
END_TABLE
