#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// Util.cpp

T_("Aborted by user.")
csCZ("Operace byla přerušena uživatelem.")
deDE("Vom Benutzer abgebrochen")
esES("Abortado por el usuario.")
fiFI("Käyttäjän peruuttama.")
frFR("Annulé par l'utilisateur.")
huHU("Megszakította a felhasználó")
itIT("Annullato dall'utente")
nlNL("Afgebroken door de gebruiker.")
plPL("Anulowany przez użytkownika")
roRO("Anulat de către utilizator.")
ruRU("Прервано пользователем")
skSK("Operácia bola prerušená používateľom.")
srSP("Prekinuto od strane korisnika.")
trTR("Kullanıcı tarafından iptal edildi.")
zhCN("用户放弃")
zhTW("使用者取消")


// TimeDate.cpp

T_("date\vSunday")
csCZ("Neděle")
deDE("Sonntag")
esES("Domingo")
fiFI("Sunnuntai")
frFR("Dimanche")
huHU("Vasárnap")
itIT("Domenica")
nlNL("Zondag")
plPL("Niedziela")
roRO("Duminică")
ruRU("Суббота")
skSK("Nedeľa")
srSP("Nedelja")
trTR("Pazar")
zhCN("星期日")
zhTW("星期日")

T_("date\vMonday")
csCZ("Pondělí")
deDE("Montag")
esES("Lunes")
fiFI("Maanantai")
frFR("Lundi")
huHU("Hétfő")
itIT("Lunedì")
nlNL("Maandag")
plPL("Poniedziałek")
roRO("Luni")
ruRU("Понедельник")
skSK("Pondelok")
srSP("Ponedeljak")
trTR("Pazartesi")
zhCN("星期一")
zhTW("星期一")

T_("date\vTuesday")
csCZ("Úterý")
deDE("Dienstag")
esES("Martes")
fiFI("Tiistai")
frFR("Mardi")
huHU("Kedd")
itIT("Martedì")
nlNL("Dinsdag")
plPL("Wtorek")
roRO("Marţi")
ruRU("Вторник")
skSK("Utorok")
srSP("Utorak")
trTR("Salı")
zhCN("星期二")
zhTW("星期二")

T_("date\vWednesday")
csCZ("Středa")
deDE("Mittwoch")
esES("Miercoles")
fiFI("Keskiviikko")
frFR("Mercredi")
huHU("Szerda")
itIT("Mercoledì")
nlNL("Woensdag")
plPL("Środa")
roRO("Miercuri")
ruRU("Среда")
skSK("Streda")
srSP("Sreda")
trTR("Çarşamba")
zhCN("星期三")
zhTW("星期三")

T_("date\vThursday")
csCZ("Čtvrtek")
deDE("Donnerstag")
esES("Jueves")
fiFI("Torstai")
frFR("Jeudi")
huHU("Csütörtök")
itIT("Giovedì")
nlNL("Donderdag")
plPL("Czwartek")
roRO("Joi")
ruRU("Четверг")
skSK("Štvrtok")
srSP("Četvrtak")
trTR("Perşembe")
zhCN("星期四")
zhTW("星期四")

T_("date\vFriday")
csCZ("Pátek")
deDE("Freitag")
esES("Viernes")
fiFI("Perjantai")
frFR("Vendredi")
huHU("Péntek")
itIT("Venerdì")
nlNL("Vrijdag")
plPL("Piątek")
roRO("Vineri")
ruRU("Пятница")
skSK("Piatok")
srSP("Petak")
trTR("Cuma")
zhCN("星期五")
zhTW("星期五")

T_("date\vSaturday")
csCZ("Sobota")
deDE("Samstag")
esES("S�bado")
fiFI("Lauantai")
frFR("Samedi")
huHU("Szombat")
itIT("Sabato")
nlNL("Zaterdag")
plPL("Sobota")
roRO("Sâmbătă")
ruRU("Воскресенье")
skSK("Sobota")
srSP("Subota")
trTR("Cumartesi")
zhCN("星期六")
zhTW("星期六")

T_("date\vSu")
csCZ("Ne")
deDE("Sa")
esES("Do")
fiFI("Su")
frFR("Sam")
huHU("Vas")
itIT("Do")
nlNL("Zo")
plPL("So")
roRO("Du")
ruRU("Вс")
skSK("Ne")
srSP("Ne")
trTR("Pz")
zhCN("Fri")
zhTW("Su")

T_("date\vMo")
csCZ("Po")
deDE("Mo")
esES("Lu")
fiFI("Ma")
frFR("Lun")
huHU("Hé")
itIT("Lu")
nlNL("Ma")
plPL("Po")
roRO("Lu")
ruRU("Пн")
skSK("Po")
srSP("Po")
trTR("Pts")
zhCN("Mon")
zhTW("Mon")

T_("date\vTu")
csCZ("Út")
deDE("Di")
esES("Ma")
fiFI("Ti")
frFR("Mar")
huHU("Ke")
itIT("Ma")
nlNL("Di")
plPL("Wt")
roRO("Ma")
ruRU("Вт")
skSK("Ut")
srSP("Ut")
trTR("Sl")
zhCN("Tue")
zhTW("Tue")

T_("date\vWe")
csCZ("St")
deDE("Mi")
esES("Mi")
fiFI("Ke")
frFR("Mer")
huHU("Sze")
itIT("Me")
nlNL("Wo")
plPL("Śr")
roRO("Mi")
ruRU("Ср")
skSK("St")
srSP("Sr")
trTR("Çrş")
zhCN("Wed")
zhTW("Wed")

T_("date\vTh")
csCZ("Čt")
deDE("Do")
esES("Ju")
fiFI("To")
frFR("Jeu")
huHU("Csüt")
itIT("Gi")
nlNL("Do")
plPL("Cz")
roRO("Jo")
ruRU("Чт")
skSK("Št")
srSP("Če")
trTR("Prş")
zhCN("Thu")
zhTW("Thu")

T_("date\vFr")
csCZ("Pa")
deDE("Fr")
esES("Vi")
fiFI("Pe")
frFR("Ven")
huHU("Pé")
itIT("Ve")
nlNL("Vr")
plPL("Pt")
roRO("Vi")
ruRU("Пт")
skSK("Pi")
srSP("Pe")
trTR("Cu")
zhCN("星期五")
zhTW("Fri")

T_("date\vSa")
csCZ("So")
deDE("So")
esES("S�")
fiFI("La")
frFR("Dim")
huHU("Szo")
itIT("Sa")
nlNL("Za")
plPL("Nd")
roRO("Sâ")
ruRU("Сб")
skSK("So")
srSP("Su")
trTR("Cts")
zhCN("Sun")
zhTW("Sun")

T_("date\vJanuary")
csCZ("Leden")
deDE("Januar")
esES("Enero")
fiFI("Tammikuu")
frFR("Janvier")
huHU("Január")
itIT("Gennaio")
nlNL("Januari")
plPL("Styczeń")
roRO("Ianuarie")
ruRU("Январь")
skSK("Január")
srSP("Januar")
trTR("Ocak")
zhCN("一月")
zhTW("一月")

T_("date\vFebruary")
csCZ("Únor")
deDE("Februar")
esES("Febrero")
fiFI("Helmikuu")
frFR("Février")
huHU("Február")
itIT("Febbraio")
nlNL("Februari")
plPL("Luty")
roRO("Februarie")
ruRU("Февраль")
skSK("Február")
srSP("Februar")
trTR("Şubat")
zhCN("二月")
zhTW("二月")

T_("date\vMarch")
csCZ("Březen")
deDE("März")
esES("Marzo")
fiFI("Maaliskuu")
frFR("Mars")
huHU("Március")
itIT("Marzo")
nlNL("Maart")
plPL("Marzec")
roRO("Martie")
ruRU("Март")
skSK("Marec")
srSP("Mart")
trTR("Mart")
zhCN("三月")
zhTW("三月")

T_("date\vApril")
csCZ("Duben")
deDE("April")
esES("Abril")
fiFI("Huhtikuu")
frFR("Avril")
huHU("Április")
itIT("Aprile")
nlNL("April")
plPL("Kwiecień")
roRO("Aprilie")
ruRU("Апрель")
skSK("Apríl")
srSP("April")
trTR("Nisan")
zhCN("四月")
zhTW("四月")

T_("date\vMay")
csCZ("Květen")
deDE("Mai")
esES("Mayo")
fiFI("Toukokuu")
frFR("Mai")
huHU("Május")
itIT("Maggio")
nlNL("Mei")
plPL("Maj")
roRO("Mai")
ruRU("Май")
skSK("Máj")
srSP("Maj")
trTR("Mayıs")
zhCN("五月")
zhTW("五月")

T_("date\vJune")
csCZ("Červen")
deDE("Juni")
esES("Junio")
fiFI("Kesäkuu")
frFR("Juin")
huHU("Június")
itIT("Giugno")
nlNL("Juni")
plPL("Czerwiec")
roRO("Iunie")
ruRU("Июнь")
skSK("Jún")
srSP("Jun")
trTR("Haziran")
zhCN("六月")
zhTW("六月")

T_("date\vJuly")
csCZ("Červenec")
deDE("Juli")
esES("Julio")
fiFI("Heinäkuu")
frFR("Juillet")
huHU("Július")
itIT("Luglio")
nlNL("Juli")
plPL("Lipiec")
roRO("Iulie")
ruRU("Июль")
skSK("Júl")
srSP("Jul")
trTR("Temmuz")
zhCN("七月")
zhTW("七月")

T_("date\vAugust")
csCZ("Srpen")
deDE("August")
esES("Agosto")
fiFI("Elokuu")
frFR("Août")
huHU("Augusztus")
itIT("Agosto")
nlNL("Augustus")
plPL("Sierpień")
roRO("August")
ruRU("Август")
skSK("August")
srSP("Avgust")
trTR("Ağustos")
zhCN("八月")
zhTW("八月")

T_("date\vSeptember")
csCZ("Září")
deDE("September")
esES("Septiembre")
fiFI("Syyskuu")
frFR("Septembre")
huHU("Szeptember")
itIT("Settembre")
nlNL("September")
plPL("Wrzesień")
roRO("Septembrie")
ruRU("Сентябрь")
skSK("September")
srSP("Septembar")
trTR("Eylül")
zhCN("九月")
zhTW("九月")

T_("date\vOctober")
csCZ("Říjen")
deDE("Oktober")
esES("Octubre")
fiFI("Lokakuu")
frFR("Octobre")
huHU("Október")
itIT("Ottobre")
nlNL("Oktober")
plPL("Październik")
roRO("Octombrie")
ruRU("Октябрь")
skSK("Október")
srSP("Oktobar")
trTR("Ekim")
zhCN("十月")
zhTW("十月")

T_("date\vNovember")
csCZ("Listopad")
deDE("November")
esES("Noviembre")
fiFI("Marraskuu")
frFR("Novembre")
huHU("November")
itIT("Novembre")
nlNL("November")
plPL("Listopad")
roRO("Noiembrie")
ruRU("Ноябрь")
skSK("November")
srSP("Novembar")
trTR("Kasım")
zhCN("十一月")
zhTW("十一月")

T_("date\vDecember")
csCZ("Prosinec")
deDE("Dezember")
esES("Diciembre")
fiFI("Joulukuu")
frFR("Décembre")
huHU("December")
itIT("Dicembre")
nlNL("December")
plPL("Grudzień")
roRO("Decembrie")
ruRU("Декабрь")
skSK("December")
srSP("Decembar")
trTR("Aralık")
zhCN("十二月")
zhTW("十二月")

T_("sdate\vJan")
csCZ("Led")
deDE("Jan")
esES("Ene")
fiFI("Tam")
frFR("Jan")
huHU("Jan")
itIT("Gen")
nlNL("Jan")
plPL("Sty")
roRO("Ian")
ruRU("Янв")
skSK("Jan")
srSP("Jan")
trTR("Ock")
zhCN("Jan")
zhTW("Jan")

T_("sdate\vFeb")
csCZ("Úno")
deDE("Feb")
esES("Feb")
fiFI("Hel")
frFR("Fév")
huHU("Feb")
itIT("Feb")
nlNL("Feb")
plPL("Lut")
roRO("Feb")
ruRU("Фев")
skSK("Feb")
srSP("Feb")
trTR("Şub")
zhCN("Feb")
zhTW("Feb")

T_("sdate\vMar")
csCZ("Bře")
deDE("Mär")
esES("Mar")
fiFI("Maa")
frFR("Mar")
huHU("Márc")
itIT("Mar")
nlNL("Mrt")
plPL("Mar")
roRO("Mar")
ruRU("Мрт")
skSK("Mar")
srSP("Mar")
trTR("Mar")
zhCN("Mar")
zhTW("Mar")

T_("sdate\vApr")
csCZ("Dub")
deDE("Apr")
esES("Abr")
fiFI("Huh")
frFR("Avr")
huHU("Ápr")
itIT("Apr")
nlNL("Apr")
plPL("Kwi")
roRO("Apr")
ruRU("Апр")
skSK("Apr")
srSP("Apr")
trTR("Nis")
zhCN("Apr")
zhTW("Apr")

T_("sdate\vMay")
csCZ("Kvě")
deDE("Mai")
esES("May")
fiFI("Tou")
frFR("Mai")
huHU("Máj")
itIT("Mag")
nlNL("Mei")
plPL("Maj")
roRO("Mai")
ruRU("Май")
skSK("Máj")
srSP("Maj")
trTR("May")
zhCN("May")
zhTW("May")

T_("sdate\vJun")
csCZ("Čer")
deDE("Jun")
esES("Jun")
fiFI("Kes")
frFR("Jun")
huHU("Jún")
itIT("Giu")
nlNL("Jun")
plPL("Cze")
roRO("Iun")
ruRU("Инь")
skSK("Jún")
srSP("Jun")
trTR("Haz")
zhCN("Jun")
zhTW("Jun")

T_("sdate\vJul")
csCZ("Čec")
deDE("Jul")
esES("Jul")
fiFI("Hei")
frFR("Jui")
huHU("Júl")
itIT("Lug")
nlNL("Jul")
plPL("Lip")
roRO("Iul")
ruRU("Иль")
skSK("Júl")
srSP("Jul")
trTR("Tem")
zhCN("Jul")
zhTW("Jul")

T_("sdate\vAug")
csCZ("Srp")
deDE("Aug")
esES("Ago")
fiFI("Elo")
frFR("Aou")
huHU("Aug")
itIT("Ago")
nlNL("Aug")
plPL("Sie")
roRO("Aug")
ruRU("Авг")
skSK("Aug")
srSP("Avg")
trTR("Ağu")
zhCN("Aug")
zhTW("Aug")

T_("sdate\vSep")
csCZ("Zář")
deDE("Sep")
esES("Sep")
fiFI("Syy")
frFR("Sep")
huHU("Szept")
itIT("Set")
nlNL("Sep")
plPL("Wrz")
roRO("Sep")
ruRU("Сен")
skSK("Sep")
srSP("Sep")
trTR("Eyl")
zhCN("Sep")
zhTW("Sep")

T_("sdate\vOct")
csCZ("Říj")
deDE("Okt")
esES("Oct")
fiFI("Lok")
frFR("Oct")
huHU("Okt")
itIT("Ott")
nlNL("Okt")
plPL("Paź")
roRO("Oct")
ruRU("Окт")
skSK("Okt")
srSP("Okt")
trTR("Ekm")
zhCN("Oct")
zhTW("Oct")

T_("sdate\vNov")
csCZ("Lis")
deDE("Nov")
esES("Nov")
fiFI("Mar")
frFR("Nov")
huHU("Nov")
itIT("Nov")
nlNL("Nov")
plPL("Lis")
roRO("Nov")
ruRU("Ноя")
skSK("Nov")
srSP("Nov")
trTR("Kas")
zhCN("Nov")
zhTW("Nov")

T_("sdate\vDec")
csCZ("Pro")
deDE("Dez")
esES("Dic")
fiFI("Jou")
frFR("Déc")
huHU("Dec")
itIT("Dic")
nlNL("Dec")
plPL("Gru")
roRO("Dec")
ruRU("Дек")
skSK("Dec")
srSP("Dec")
trTR("Arl")
zhCN("Dec")
zhTW("Dec")


// Convert.cpp

T_("Invalid number !")
csCZ("Chybný zápis čísla !")
deDE("Ungültige Zahl!")
esES("N�mero invalido !")
fiFI("Virheellinen numero!")
frFR("Nombre invalide !")
huHU("Érvénytelen szám")
itIT("Numero non valido !")
nlNL("Ongeldig nummer !")
plPL("Niepoprawny numer !")
roRO("Număr invalid !")
ruRU("Неправильное число!")
skSK("Nesprávny zápis čísla !")
srSP("Pogrešan broj!")
trTR("Geçersiz sayı !")
zhCN("无效数字!")
zhTW("無效數字!")

T_("Invalid date !")
csCZ("Chybný zápis data !")
deDE("Ungültiges Datum!")
esES("Fecha invalida !")
fiFI("Virheellinen päivämäärä!")
frFR("Date invalide !")
huHU("Érvénytelen dátum")
itIT("Data non valida !")
nlNL("Ongeldige datum !")
plPL("Niepoprawna data !")
roRO("Dată invalidă !")
ruRU("Неправильная дата!")
skSK("Nesprávny zápis dátumu !")
srSP("Pogrešan datum!")
trTR("Geçersiz tarih !")
zhCN("无效日期")
zhTW("無效日期")

T_("Invalid time !")
csCZ("Chybný čas")
deDE("Ungültige Zeitangabe!")
esES("Hora invalida !")
fiFI("Virheellinen aika!")
frFR("")
huHU("Érvénytelen időpont")
itIT("")
nlNL("Ongeldige tijd !")
plPL("")
roRO("Oră invalidă !")
ruRU("Неправильное время !")
skSK("Nesprávny zápis času !")
srSP("")
trTR("Geçersiz Zaman !")
zhCN("无效时间")
zhTW("無效時間")

T_("Null value not allowed.")
csCZ("Hodnota nesmí být prázdná.")
deDE("Null nicht erlaubt.")
esES("No se permite valor nulo.")
fiFI("Arvon puuttuminen ei ole sallittua.")
frFR("Valeur nulle non autorisée.")
huHU("Nullérték nem megengedett")
itIT("Lo zero non è ammesso")
nlNL("Null waarde niet toegestaan.")
plPL("Pusta wartość jest niedozwolona.")
roRO("Valoare nulă nu este permisă.")
ruRU("Нулевое значение не разрешено.")
skSK("Hodnota nesmie byť prázdna.")
srSP("Bez vrednosti nisu dopuštene.")
trTR("Bu alan boş bırakılamaz.")
zhCN("不允许空值.")
zhTW("不允許空值.")

T_("Number must be between %d and %d.")
csCZ("Číslo musí být v rozsahu %d až %d.")
deDE("Zahl muss zwischen %d und %d liegen.")
esES("El n�mero debe estar entre %d y %d.")
fiFI("Arvon täytyy olla välillä %d.. %d.")
frFR("Le nombre doit être compris entre %d et %d.")
huHU("A számnak %d és %d közé kell esnie")
itIT("Il numero deve essere compreso tra %d e %d.")
nlNL("Nummer moet tussen de %d en %d zijn.")
plPL("Numer musi być z przedziału %d i %d.")
roRO("Numărul trebuie să fie între %d și %d.")
ruRU("Число должно быть в пределах между %d и "
     "%d")
skSK("Číslo musí byť v rozsahu %d až %d.")
srSP("Broj mora biti između %d i %d.")
trTR("Girilen sayı %d ile %d aralığında olmaldır.")
zhCN("数字必须在%d和%d之间.")
zhTW("數字必須在%d和%d之間.")

T_("Number must be between %g and %g.")
csCZ("Číslo musí být v rozsahu %g až %g.")
deDE("Zahl muss zwischen %g und %g liegen.")
esES("El n�mero debe estar entre %g y %g.")
fiFI("Arvon täytyy olla välillä %g.. %g.")
frFR("Le nombre doit être compris entre %g et %g.")
huHU("A számnak %g és %g közé kell esnie")
itIT("Il numero deve essere compreso tra %g e %g.")
nlNL("Nummer moet tussen de %g en %g zijn.")
plPL("Numer musi być z przedziału %g i %g.")
roRO("Numărul trebuie să fie între %g și %g.")
ruRU("Число должно быть в пределах между %g и "
     "%g")
skSK("Číslo musí byť v rozsahu %g až %g.")
srSP("Broj mora biti između %g i %g.")
trTR("Girilen sayı %g ile %g aralığında olmaldır.")
zhCN("数字必须在%g和%g之间.")
zhTW("數字必須在%g和%g之間.")

T_("Date must be between ")
csCZ("Datum musí být v rozsahu ")
deDE("Datum muss liegen zwischen ")
esES("La fecha debe estar entre ")
fiFI("Päivämäärän täytyy olla välillä ")
frFR("La date doit comprise entre")
huHU("A dátum érvényes határai ")
itIT("La data deve essere compre tra ")
nlNL("Datum moet vanaf ")
plPL("Data musi być z zakresu ")
roRO("Data trebuie să fie în intervalul ")
ruRU("Дата должна быть в пределах ")
skSK("Dátum musí byť v rozsahu ")
srSP("Datum mora biti između ")
trTR("Girilen tarih")
zhCN("日期必须介入")
zhTW("日期必須介於")

T_("range\v and ")
csCZ(" až ")
deDE(" und ")
esES("rango\v y ")
fiFI(" ja ")
frFR(" et ")
huHU(" és ")
itIT(" e ")
nlNL(" en ")
plPL(" i ")
roRO(" și ")
ruRU(" и ")
skSK(" až ")
srSP(" i ")
trTR(" and ")
zhCN(" 和 ")
zhTW(" 和 ")

T_("Time must be between ")
csCZ("Čas musí být od")
deDE("Zeitangabe muss liegen zwischen ")
esES("La fecha debe estar entre ")
fiFI("Ajan täytyy olla välillä ")
frFR("")
huHU("Az időpont a köv. kettő között legyen: ")
itIT("")
nlNL("Tijd moet vanaf ")
plPL("Czas musi być z zakresu ")
roRO("Ora trebuie să fie în intervalul ")
ruRU("Время должно быть в интервале")
skSK("Čas musí byť v rozsahu ")
srSP("")
trTR("Time must be between ")
zhCN("时间必须介于")
zhTW("時間必須介於 ")

T_("Please enter no more than %d characters.")
csCZ("Text nesmí být delší než %d znaků.")
deDE("Bitte geben Sie nicht mehr als %d Zeichen ein.")
esES("Ingrese no m�s de %d caracteres.")
fiFI("Syötä enintään %d merkkiä.")
frFR("Veuillez ne pas saisir plus de %d caractères.")
huHU("Ne adjon be többet %d karakternél.")
itIT("Non scrivere più di %d caratteri.")
nlNL("Gaarne niet meer dan %d karakters invullen.")
plPL("Proszę wprowadzić nie więcej niż %d znaków.")
roRO("Introduceți până la %d caractere")
ruRU("Пожайлуста, введите не более чем %d символов.")
skSK("Text nesmie byť dlhší ako %d znakov.")
srSP("Molim vas unesite najviše %d slova.")
trTR("Lütfen en fazla %d karakter girin.")
zhCN("输入请不要超过%d字符")
zhTW("輸入請不要超過%d字元")


// t.cpp

T_("date-format\a%2:02d/%3:02d/%1:4d")
csCZ("%3:02d.%2:02d.%1:04d")
deDE("%3:02d.%2:02d.%1:4d")
esES("%3:02d/%2:02d/%1:4d")
fiFI("%3:02d.%2:02d.%1:04d")
frFR("%3:02d/%2:02d/%1:04d")
huHU("%1:04d.%2:02d.%3:02d.")
itIT("%3:02d/%2:02d/%1:04d")
nlNL("%2:02d/%3:02d/%1:4d")
plPL("%3:02d.%2:02d.%1:04d")
roRO("format-dată\a%2:02d/%3:02d/%1:4d")
ruRU("%3:02d.%2:02d.%1:04d")
skSK("%3:02d.%2:02d.%1:04d")
srSP("%3:02d.%2:02d.%1:04d")
trTR("%3:02d.%2:02d.%1:04d")
zhCN("%2:02d/%3:02d/%1:4d")
zhTW("%2:02d/%3:02d/%1:4d")

T_("date-scan\amdy")
csCZ("dmy")
deDE("dmy")
esES("dmy")
fiFI("dmy")
frFR("dmy")
huHU("ymd")
itIT("dmy")
nlNL("mdy")
plPL("dmy")
roRO("dmy")
ruRU("dmy")
skSK("dmy")
srSP("dmy")
trTR("dmy")
zhCN("mdy")
zhTW("mdy")

T_("date-filter\aA/\a .-")
csCZ(".\a /,")
deDE("A/\a .-")
esES("A/ .-")
fiFI(".\a ,-/")
frFR("/\a .,")
huHU("A.\a .-")
itIT("/\a .,")
nlNL("A/\r .-")
plPL("\a .,-/")
roRO(".\r -/")
ruRU(".\a /,")
skSK(".\r /,")
srSP(".\a /,")
trTR(".\a /,")
zhCN("A/\a .-")
zhTW("A/\r .-")


// Lang.cpp

T_("Invalid language specification.")
csCZ("Chybná specifikace jazyka.")
deDE("Ungültige Sprachenbezeichnung")
esES("Especificaci�n de lenguaje no v�lida")
fiFI("Virheellinen kielimääritys.")
frFR("Langue spécifiée invalide.")
huHU("Érvénytelen nyelvbeállítás")
itIT("Lingua specificata non valida.")
nlNL("Ongeldige taal specificate.")
plPL("Niepoprawna specyfikacja języka.")
roRO("Specificare de limbă invalidă")
ruRU("Неправильная спецификация языка.")
skSK("Nesprávna špecifikácia jazyka.")
srSP("Nevalidna specifikacija jezika.")
trTR("Geçersiz dil.")
zhCN("无效语言指示")
zhTW("無效語言指示")


// Obsolete

T_("invalid day number.")
csCZ("neplatné číslo dne.")
deDE("Ungültige Tageszahl")
esES("n�mero de d�a incorrecto.")
fiFI("virheellinen päivä.")
frFR("jour invalide.")
huHU("érvénytelen nap.")
itIT("giorno non valido.")
nlNL("ongeldige dag nummer.")
plPL("niepoprawny numer dnia.")
roRO("număr de zi invalid.")
ruRU("неправильное число дня месяца.")
skSK("neplatné číslo dňa.")
srSP("nevalidan dan.")
trTR("geçersiz gün.")
zhCN("无效天数")
zhTW("無效天數")

T_("invalid month number.")
csCZ("neplatné číslo měsíce.")
deDE("Ungültige Monatszahl")
esES("n�mero de mes incorrecto.")
fiFI("virheellinen kuukausi.")
frFR("mois invalide.")
huHU("érvénytelen hónap.")
itIT("mese non valido.")
nlNL("ongeldige maand nummer.")
plPL("niepoprawny numer miesiąca.")
roRO("număr de lună invalid")
ruRU("неправильное число месяца.")
skSK("neplatné číslo mesiaca.")
srSP("nevalidan mesec.")
trTR("geçersiz ay.")
zhCN("无效月数")
zhTW("無效月數")

T_("invalid year number.")
csCZ("neplatné číslo roku.")
deDE("Ungültige Jahreszahl")
esES("n�mero de a�o incorrecto.")
fiFI("virheellinen vuosi.")
frFR("année invalide.")
huHU("érvénytelen év.")
itIT("anno non valido.")
nlNL("ongeldige jaar nummer.")
plPL("niepoprawny numer roku.")
roRO("an invalid")
ruRU("неправильное число года.")
skSK("neplatné číslo roku.")
srSP("nevalidana godina.")
trTR("geçersiz yıl.")
zhCN("无效年数")
zhTW("無效年數")

T_("invalid hour number.")
csCZ("chybné číslo hodiny.")
deDE("Ungültige Stundenzahl")
esES("n�mero de hora incorrecto.")
fiFI("virheellinen tunti.")
frFR("heure invalide.")
huHU("érvénytelen óra.")
itIT("ora non valida.")
nlNL("ongeldige uur nummer.")
plPL("niepoprawna wartość godziny.")
roRO("oră invalidă")
ruRU("неправильное число часа.")
skSK("nesprávne číslo hodiny.")
srSP("nevalidan sat.")
trTR("geçersiz saat.")
zhCN("无效小时")
zhTW("無效小時")

T_("invalid minute number.")
csCZ("chybné číslo minuty.")
deDE("Ungültige Minutenzahl")
esES("n�mero de minuto incorrecto.")
fiFI("virheellinen minuutti.")
frFR("minute invalide.")
huHU("érvénytelen perc.")
itIT("minuti non valido.")
nlNL("ongeldige minuut nummer.")
plPL("niepoprawna wartość minuty.")
roRO("minut invalid")
ruRU("неправильное число минуты.")
skSK("nesprávne číslo minúty.")
srSP("nevalidna minuta.")
trTR("geçersiz dakika.")
zhCN("无效分")
zhTW("無效分")

T_("invalid second number.")
csCZ("chybné číslo sekundy.")
deDE("Ungültige Sekundenzahl")
esES("n�mero de segundo incorrecto.")
fiFI("virheellinen sekunti.")
frFR("seconde invalide.")
huHU("érvénytelen másodperc.")
itIT("secondi non valido.")
nlNL("ongeldige seconde nummer.")
plPL("niepoprawna druga wartość.")
roRO("secundă invalidă")
ruRU("неправильное число секунды.")
skSK("nesprávne číslo sekundy.")
srSP("nevalidna sekunda.")
trTR("geçersiz saniye.")
zhCN("无效秒")
zhTW("無效秒")

T_("invalid character '%c' following date/time.")
csCZ("neplatný znak '%c' za koncem data.")
deDE("Ungültiges Zeichen '%c' folgt Datum/Zeit.")
esES("car�cter '%c' incorrecto despu�s de d�a/hora.")
fiFI("virheellinen merkki '%c' seuraa päivämäärää/kellonaikaa.")
frFR("caractère invalide '%c' suivant la date.")
huHU("érvénytelen karakter '%c' a dátum/idő mellett.")
itIT("carattere non valido '%c' dopo la data.")
nlNL("ongeldige karakter '%c' na de datum/tijd.")
plPL("niepoprawny znak '%c' na końcu daty/czasu.")
roRO("data/ora este urmată de caracterul invalid '%c'")
ruRU("неправильный символ '%c' идущий за датой/временем.")
skSK("neplatný znak '%c' za koncom dátumu.")
srSP("nevalidni karakter '%c' posle datuma/vremena.")
trTR("girilen tarih/zaman bilgisi içindeki '%c' geçersiz bir karakterdir.")
zhCN("日期/时间后跟字符 '%c' 无效")
zhTW("日期/時間後跟字元 '%c' 無效")

T_("invalid day number %d - February in year %d has only %d days.")
csCZ("neplatné číslo dne %d - únor v roce %d má pouze %d dní.")
deDE("Ungültige Tagesnummer %d - Februar im Jahr %d hat nur %d Tage.")
esES("n�mero de d�a %d incorrecto - En el a�o %d Febrero solo tiene %d d�as.")
fiFI("virheellinen päivä %d - Helmikuussa %d on vain %d päivää.")
frFR("jour %d invalide pour Février qui n'a que %d jours.")
huHU("érvénytelen nap %d - a február a(z) %d évben csak %d napos.")
itIT("Febbraio ha solo %d giorni.")
nlNL("ongeldige dag nummer %d - Februarie in jaar %d heeft alleen maar % dagen.")
plPL("niepoprawny numer dnia %d - Luty w roku %d ma tylko %d dni.")
roRO("ziua %d invalidă - februarie are doar %d zile în anul %d")
ruRU("неправильное число месяца %d - В феврале "
     "%d года только %d дней.")
skSK("neplatné číslo dňa %d - február v roku %d má len %d dní.")
srSP("nevalidan dan %d - Februar u godini %d ima %d dana.")
trTR("%d geçersiz bir gün sayısıdır - %d yılında Şubat ayı %d gün "
     "çeker.")
zhCN("无效天数 %d -  %d年二月只有%d天.")
zhTW("無效天數 %d -  %d年二月只有%d天.")

T_("invalid day number %d - %month has only %d days.")
csCZ("neplatné číslo dne %d - %month má pouze %d dní.")
deDE("Ungültige Tagesnummer %d - %month hat nur %d Tage.")
esES("n�mero de d�a %d incorrecto - %month tiene solo %d d�as.;\r\n\r\n")
fiFI("virheellinen päivä %d - %monthssa on vain %d päivää.")
frFR("jour %d invalide pour %month qui n'a que %d jours.")
huHU("érvénytelen nap %d - %month csak % napos.")
itIT("Giorno non valido %d - %month ha solo %d giorni.")
nlNL("ongeldige dag nummer %d - %month heeft alleen maar %d dagen.")
plPL("niepoprawny numer dnia - %month ma tylko %d dni.")
roRO("ziua %d invalidă - %month are numai %d zile")
ruRU("неправильное число месяца %d - В %month только "
     "%d дней.")
skSK("neplatné číslo dňa %d - %month má len %d dní.")
srSP("nevalidan dan %d - %month ima %d dana.")
trTR("%d geçersiz bir gün sayısıdır - %month ayı %d gün çeker.")
zhCN("无效天数 %d - %month月只有 %d 天.")
zhTW("無效天數 %d - %month月只有 %d 天.")

T_("exceeded valid range (lower bound: %`).")
csCZ("překročení povoleného rozsahu (dolní mez: %`).")
deDE("Gültigkeitsbereich unterschritten (untere Grenze: %`).")
esES("rango v�lido excedido (l�mite inferior: %`).")
fiFI("sallitun alueen ulkopuolella (alaraja: %`).")
frFR("validité de l'intervalle dépassée (limite inférieure : %d`).")
huHU("érvényes tartomány alatt (alsó határ: %`).")
itIT("range valido superato (limite inferiore: %`).")
nlNL("geldig gebied overschreden (beneden grens: %`).")
plPL("przekroczono dopuszczalny zakres (dolna granica: %`).")
roRO("interval depășit (margine inferioară: %`).")
ruRU("превышен допустимый предел (нижний предел: "
     "%`).")
skSK("prekročenie povoleného rozsahu (dolná hranica: %`).")
srSP("prekoračena validna granica (donja granica: %`).")
trTR("Geçerli aralık aşıldı (alt sınır: %`).")
zhCN("超出有效范围(下限:%`).")
zhTW("超出有效範圍(下限:%`).")

T_("exceeded valid range (upper bound: %`).")
csCZ("překročení povoleného rozsahu (horní mez: %`).")
deDE("Gültigkeitsbereich überschritten (obere Grenze: %`).")
esES("rango v�lido excedido (l�mite superior: %`).")
fiFI("sallitun alueen ulkopuolella (yläraja: %`).")
frFR("validité de l'intervalle dépassée (limite supérieure : %d`).")
huHU("érvényes tartomány fölött (felső határ: %`)")
itIT("range valido superato (limite superiore: %`).")
nlNL("geldig gebied overschreden (boven grens: %`).")
plPL("przekroczono dopuszczalny zakres (górna granica: %`).")
roRO("interval depășit (margine superioară: %`).")
ruRU("превышен допустимый предел (верхний предел: "
     "%`).")
skSK("prekročenie povoleného rozsahu (horná hranica: %`).")
srSP("prekoračena validna granica (gornja granica: %`).")
trTR("Geçerli aralık aşıldı (üst sınır: %`).")
zhCN("超出有效范围(上限:%`).")
zhTW("超出有效範圍(上限:%`).")

T_("Invalid date/time: digit expected, found character")
csCZ("Chybné datum/čas: očekávána číslice, nalezen znak")
deDE("Ungültige(s) Datum/Zeit: Ziffer erwartet, Zeichen vorgefunden")
esES("Fecha/d�a incorrecto: se espera d�gito, encontrado car�cter")
fiFI("Virheellinen pvm/aika: Käytä numeroita kirjaimien sijaan.")
frFR("Date/heure invalide : chiffre attendu, caractère détecté")
huHU("érvénytelen dátum/idő: számjegy helyett más karakter áll")
itIT("Data/ora non valida")
nlNL("Ongeldige datum/tijd: getal verwacht, karakter gevonden")
plPL("Niepoprawna data/czas: oczekiwano cyfry, znaleziono znak")
roRO("Dată/oră invalidă: se așteaptă cifră, caracter găsit")
ruRU("Неправильные дата/время: ожидается цифра, "
     "а найден символ")
skSK("Nesprávny dátum/čas: očakávaná číslica, nájdený znak")
srSP("Nevalidan datum/vreme: očekuje se cifra, pronađen karakter")
trTR("Geçersiz tarih/zaman: sayı olması gereken yerde harf var")
zhCN("无效日期/时间:只能是数字,不能为字符")
zhTW("無效日期/時間:只能是數位,不能為字元")

T_("Invalid date/time:")
csCZ("Chybné datum/čas:")
deDE("Ungültige(s) Datum/Zeit:")
esES("Fecha/d�a incorrecto:")
fiFI("Virheellinen pvm/aika:")
frFR("Date/heure invalide :")
huHU("érvénytelen dátum/idő")
itIT("Data/ora non valida:")
nlNL("Ongeldige datum/tijd:")
plPL("Niepoprawna data/czas:")
roRO("Dată/oră invalidă:")
ruRU("Неправильные дата/время:")
skSK("Nesprávny dátum/čas:")
srSP("Nevalidan datum/vreme:")
trTR("Geçersiz tarih/zaman:")
zhCN("无效日期/时间:")
zhTW("無效日期/時間:")
