#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// main.cpp

T_("Error saving configuration file!")
deDE("Fehler beim Speichern der Konfiguration!")
esES("")
frFR("")
itIT("Errore durante il salvataggio del file di configurazione")
ptPT("")
ruRU("Ошибка, при сохранении файла!")


// Vega.lay

T_("Edit Player")
deDE("Spieler eingeben")
esES("")
frFR("")
itIT("Edita giocatore")
ptPT("")
ruRU("Редактировать Игрока")

T_("Player Name")
deDE("Spieler")
esES("")
frFR("")
itIT("Nome Giocatore")
ptPT("")
ruRU("Имя Игрока")

T_("Fed")
deDE("Verb.")
esES("")
frFR("")
itIT("Fed")
ptPT("")
ruRU("Фед")

T_("Birthday")
deDE("Geboren")
esES("")
frFR("")
itIT("Nato/a il")
ptPT("")
ruRU("Дата рожд")

T_("Gender")
deDE("M/W")
esES("")
frFR("")
itIT("Sesso")
ptPT("")
ruRU("Пол")

T_("Title")
deDE("Titel")
esES("")
frFR("")
itIT("Titolo")
ptPT("")
ruRU("Титул")

T_("ID FIDE")
deDE("ID FIDE")
esES("")
frFR("")
itIT("ID FIDE")
ptPT("")
ruRU("код ФИДЕ")

T_("RAT FIDE")
deDE("Wertg FIDE")
esES("")
frFR("")
itIT("Elo FIDE")
ptPT("")
ruRU("Рейт. ФИДЕ")

T_("ID Nat")
deDE("ID Nat")
esES("")
frFR("")
itIT("ID Naz.")
ptPT("")
ruRU("код Нац")

T_("Rat Nat")
deDE("Wertg Nat")
esES("")
frFR("")
itIT("Elo Naz.")
ptPT("")
ruRU("Рат Нац")

T_("K")
deDE("K")
esES("K")
frFR("K")
itIT("K")
ptPT("K")
ruRU("K")

T_("Add Player")
deDE("Spieler hinzu")
esES("")
frFR("")
itIT("Aggiungi Gioc.")
ptPT("")
ruRU("Добавить Игрока")

T_("Modify Player")
deDE("Spieler ändern")
esES("")
frFR("")
itIT("Modifica dati")
ptPT("")
ruRU("Изменить Игрока")

T_("Clear Mask")
deDE("Maske löschen")
esES("")
frFR("")
itIT("Svuota campi")
ptPT("")
ruRU("Свободное поле")

T_("Print Archive")
deDE("Drucke Archiv")
esES("")
frFR("")
itIT("Stampa")
ptPT("")
ruRU("Печать")

T_("Close Registration")
deDE("Registration beenden")
esES("")
frFR("")
itIT("Chiudi registrazione")
ptPT("")
ruRU("Закрыть Регистрацию")

T_("Remove Player")
deDE("Spieler entfernen")
esES("")
frFR("")
itIT("Rimuovi gioc.")
ptPT("")
ruRU("Удалить Игрока")

T_("Round")
deDE("Runde")
esES("")
frFR("")
itIT("Turno")
ptPT("")
ruRU("Тур")

T_("Output")
deDE("Ausgabe")
esES("")
frFR("")
itIT("Output")
ptPT("")
ruRU("Результат")

T_("Verbose output")
deDE("Ausführlich")
esES("")
frFR("")
itIT("Spiegazione")
ptPT("")
ruRU("Пояснение рез-та")

T_("Accept WWW/BBB")
deDE("WWW/BBB zulassen")
esES("")
frFR("")
itIT("Accetta BBB/NNN")
ptPT("")
ruRU("Допустить БББ/ЧЧЧ")

T_("Danubian Variant (Dubov)")
deDE("Danubische Variante (Dubov)")
esES("")
frFR("")
itIT("Variante Danubio (Dubov)")
ptPT("")
ruRU("Вариант Danubian (Дубов)")

T_("Automatic")
deDE("Automatisch")
esES("")
frFR("")
itIT("Automatico")
ptPT("")
ruRU("Автоматически")

T_("Manual")
deDE("Manuell")
esES("")
frFR("")
itIT("Manuale")
ptPT("")
ruRU("Вручную")

T_("Verbose")
deDE("Ausführlich")
esES("")
frFR("")
itIT("Spiega")
ptPT("")
ruRU("Объяснение")

T_("Print Pairing")
deDE("Paarungen drucken")
esES("")
frFR("")
itIT("Stampa abb.")
ptPT("")
ruRU("Распечатать пары")

T_("Do Pairing")
deDE("Paarungen ermitteln")
esES("")
frFR("")
itIT("Genera abbinamento")
ptPT("")
ruRU("Сформировать пары")

T_("Option")
deDE("Option")
esES("")
frFR("")
itIT("Opzioni")
ptPT("")
ruRU("Вариант")

T_("Result")
deDE("Ergebnis")
esES("")
frFR("")
itIT("Risultato")
ptPT("")
ruRU("Результат")

T_("adjourned [7]")
deDE("verschoben [7]")
esES("")
frFR("")
itIT("Aggiornata [7]")
ptPT("")
ruRU("отложить [7]")

T_("non standard")
deDE("nicht regulär")
esES("")
frFR("")
itIT("Non standard")
ptPT("")
ruRU("Редко")

T_("Current Round")
deDE("Aktuelle Runde")
esES("")
frFR("")
itIT("Turno corrente")
ptPT("")
ruRU("Текущий Раунд")

T_("Modify Pairing")
deDE("Paarungen verändern")
esES("")
frFR("")
itIT("Modifica coppie")
ptPT("")
ruRU("Изменить пару")

T_("Load Results")
deDE("Ergebnisse laden")
esES("")
frFR("")
itIT("Importa risultati")
ptPT("")
ruRU("Вписать результаты")

T_("Update CrossT")
deDE("Kreuztabelle aktualisieren")
esES("")
frFR("")
itIT("Aggiorna dati")
ptPT("")
ruRU("Обновить даты")

T_("Improve Colors")
deDE("Farben verbessern")
esES("")
frFR("")
itIT("Scambia colori")
ptPT("")
ruRU("Улучшить Цвета ")

T_("Show File")
deDE("Zeige Datei")
esES("")
frFR("")
itIT("Mostra File")
ptPT("")
ruRU("Показать Файл")

T_("Pairing")
deDE("Paarungen")
esES("")
frFR("")
itIT("Abbinamento")
ptPT("")
ruRU("Пары")

T_("Cross Table")
deDE("Kreuztabelle")
esES("")
frFR("")
itIT("Tabellone")
ptPT("")
ruRU("Таблица")

T_("Rank Category")
deDE("Gruppenränge")
esES("")
frFR("")
itIT("Class. per Cat.")
ptPT("")
ruRU("Группа Разряда")

T_("Rating variation")
deDE("Wertungsdifferenz")
esES("")
frFR("")
itIT("Variazione Elo")
ptPT("")
ruRU("Изменения Оценки")

T_("Score Group")
deDE("Punktgruppen")
esES("")
frFR("")
itIT("Punteggio gruppi")
ptPT("")
ruRU("Группа Счета")

T_("Ranking List")
deDE("")
esES("")
frFR("")
itIT("Classifica")
ptPT("")
ruRU("")

T_("Board Card")
deDE("Brettkarten")
esES("")
frFR("")
itIT("Cartellino tavolo")
ptPT("")
ruRU("Этикетка на стол")

T_("Player Card")
deDE("Spielerdetails")
esES("")
frFR("")
itIT("Cartellino giocatore")
ptPT("")
ruRU("Карта Игрока")

T_("Score Game")
deDE("Punkteverteilung")
esES("")
frFR("")
itIT("Punti partita")
ptPT("")
ruRU("Счет Игры")

T_("Tournament Directory")
deDE("Turnier-Verzeichnis")
esES("")
frFR("")
itIT("Cartella del Torneo")
ptPT("")
ruRU("Справочник Турнира")

T_("Tournament File Name")
deDE("Turnier-Dateiname")
esES("")
frFR("")
itIT("Sigla torneo")
ptPT("")
ruRU("Название Файла Турнира")

T_("Rounds")
deDE("Runden")
esES("")
frFR("")
itIT("Turni")
ptPT("")
ruRU("Раунды")

T_("Play System")
deDE("Spielsystem")
esES("")
frFR("")
itIT("Sistema di gioco")
ptPT("")
ruRU("Система Игры")

T_("Arbiter")
deDE("Schiedsrichter")
esES("")
frFR("")
itIT("Arbitro")
ptPT("")
ruRU("Арбитр")

T_("End Date")
deDE("Enddatum")
esES("")
frFR("")
itIT("Data fine")
ptPT("")
ruRU("Дата окончания")

T_("Begin Date")
deDE("Startdatum")
esES("")
frFR("")
itIT("Data inizio")
ptPT("")
ruRU("Дата начала")

T_("Use FIDE rating")
deDE("Nach FIDE Wertg")
esES("")
frFR("")
itIT("Usa Elo FIDE")
ptPT("")
ruRU("Использовать рейтинг ФИДЕ")

T_("Federation")
deDE("Verband")
esES("")
frFR("")
itIT("Federazione")
ptPT("")
ruRU("Федерация")

T_("Place")
deDE("Platz")
esES("")
frFR("")
itIT("Luogo")
ptPT("")
ruRU("Место")

T_("Tournament Name")
deDE("Turniername")
esES("")
frFR("")
itIT("Nome Torneo")
ptPT("")
ruRU("Название Турнира")

T_("Acc. rounds")
deDE("Beschl. Runden")
esES("")
frFR("")
itIT("Turni accel.")
ptPT("")
ruRU("")

T_("Available Tie Breaks")
deDE("Verfügbare TieBreaks")
esES("")
frFR("")
itIT("Spareggi")
ptPT("")
ruRU("Доступные Перерывы Связи ")

T_("...")
deDE("...")
esES("...")
frFR("...")
itIT("...")
ptPT("...")
ruRU("...")

T_("Done")
deDE("Fertig")
esES("")
frFR("")
itIT("Conferma")
ptPT("")
ruRU("Сделанно")

T_("Close")
deDE("Schließen")
esES("")
frFR("Fermer")
itIT("Chiudi")
ptPT("")
ruRU("Закрыть")

T_("Set Record Filter")
deDE("Setze Eintrag-Filter")
esES("")
frFR("")
itIT("Seleziona filtro")
ptPT("")
ruRU("Поставить запис.фильтр")

T_("Field name")
deDE("Feldname")
esES("")
frFR("")
itIT("Nome campo")
ptPT("")
ruRU("Название поля")

T_("Start Column")
deDE("Startspalte")
esES("")
frFR("")
itIT("Inizio colonna")
ptPT("")
ruRU("Начало Колонки")

T_("Max Length")
deDE("Maximale Länge")
esES("")
frFR("")
itIT("Lunghezza max")
ptPT("")
ruRU("Max длинна")

T_("Load Filter")
deDE("Lade Filter")
esES("")
frFR("")
itIT("Carica filtro")
ptPT("")
ruRU("Загрузить Фильтр")

T_("Save Filter")
deDE("Speichere Filter")
esES("")
frFR("")
itIT("Salva filtro")
ptPT("")
ruRU("Сохран.Фильтр")

T_("Cancel")
deDE("Abbrechen")
esES("")
frFR("Annuler")
itIT("Annulla")
ptPT("")
ruRU("Отмена")

T_("Search")
deDE("")
esES("")
frFR("")
itIT("Cerca")
ptPT("")
ruRU("")

T_("search player")
deDE("Suche Spieler")
esES("")
frFR("")
itIT("Cerca giocatore")
ptPT("")
ruRU("Поиск игрока")

T_("Set Filter")
deDE("Setze Filter")
esES("")
frFR("")
itIT("Seleziona filtro")
ptPT("")
ruRU("Выбор Фильтра")

T_("Selected Players")
deDE("Ausgewählte Spieler")
esES("")
frFR("")
itIT("Giocatori selezionati")
ptPT("")
ruRU("Отобранные игроки")

T_("Register All")
deDE("Alle registrieren")
esES("")
frFR("")
itIT("Registra tutti")
ptPT("")
ruRU("Регистрация Всех")

T_("Exit")
deDE("Ende")
esES("")
frFR("")
itIT("Esci")
ptPT("")
ruRU("Выход")

T_("Non standard result")
deDE("Anderes Ergebnis")
esES("")
frFR("")
itIT("Risultato non standard")
ptPT("")
ruRU("Не стандартный результат")

T_("Set Result")
deDE("Setze Ergebnis")
esES("")
frFR("")
itIT("Inserisci risultato")
ptPT("")
ruRU("Вписать результат")

T_("ID Player")
deDE("ID Spieler")
esES("")
frFR("")
itIT("ID giocatore")
ptPT("")
ruRU("ИД игрока")

T_("Place of birth")
deDE("Geburtsort")
esES("")
frFR("")
itIT("Luogo di nascita")
ptPT("")
ruRU("Место рождения")

T_("Rate of play")
deDE("Turnierleistung")
esES("")
frFR("")
itIT("Tempo di gioco")
ptPT("")
ruRU("Игровое время")

T_("Type Norm")
deDE("Norm vom Typ")
esES("")
frFR("")
itIT("Tipo Norma")
ptPT("")
ruRU("Тип Нормы")

T_("FIDE Norm Certificate")
deDE("FIDE Normzertifikat")
esES("")
frFR("")
itIT("Certificato norme FIDE")
ptPT("")
ruRU("Сертификат нормы ФИДЕ")

T_("Rating Report to FIDE")
deDE("Wertungsbericht an FIDE")
esES("")
frFR("")
itIT("Verbale Elo per la FIDE")
ptPT("")
ruRU("Рейтинг-Отчёт для ФИДЕ")

T_("Date of end")
deDE("Enddatum")
esES("")
frFR("")
itIT("Data fine")
ptPT("")
ruRU("Дата окончания")

T_("Date of start")
deDE("Startdatum")
esES("")
frFR("")
itIT("Data inizio")
ptPT("")
ruRU("Дата начала")

T_("City")
deDE("Stadt")
esES("")
frFR("")
itIT("Città")
ptPT("")
ruRU("Город")

T_("Allotted time per move/game")
deDE("Zeit pro Zug/Spiel")
esES("")
frFR("")
itIT("Cadenza per mosse/partita")
ptPT("")
ruRU("Вр.выделенное на ход/игру")

T_("Type of tournament")
deDE("Turnierart")
esES("")
frFR("")
itIT("Tipo di Torneo")
ptPT("")
ruRU("Тип турнира")

T_("Rated Players")
deDE("Gewertete Spieler")
esES("")
frFR("")
itIT("Giocatori FIDE")
ptPT("")
ruRU("Игроки ФИДЕ")

T_("Total Players")
deDE("Spieler gesamt")
esES("")
frFR("")
itIT("Totale Giocat.")
ptPT("")
ruRU("Кол-во игроков")

T_("Tournament name")
deDE("Turniername")
esES("")
frFR("")
itIT("Nome Torneo")
ptPT("")
ruRU("Название турнира")

T_("Deputy Chief Arbiter(s)")
deDE("Hilfsschiedrichter")
esES("")
frFR("")
itIT("Vice arbitro")
ptPT("")
ruRU("Помощник арб.")

T_("Chief Arbiter")
deDE("Hauptschiedsrichter")
esES("")
frFR("")
itIT("Arbitro capo")
ptPT("")
ruRU("Гл.арбитр")

T_("USCF tournament section rating report")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("ID Assistant TD")
deDE("ID Assistenzturnierleiter")
esES("")
frFR("")
itIT("ID vice arbitro")
ptPT("")
ruRU("")

T_("ID Chief TD")
deDE("ID Turnierleiter")
esES("")
frFR("")
itIT("ID arbitro capo")
ptPT("")
ruRU("ИД Гл.арбитра")

T_("Rating System")
deDE("Wertungssystem")
esES("")
frFR("")
itIT("Sistema di rating")
ptPT("")
ruRU("Сист.Рейтинга")

T_("K factor")
deDE("K Faktor")
esES("")
frFR("")
itIT("coeff. K")
ptPT("")
ruRU("Коэфф.K")

T_("Status")
deDE("Status")
esES("")
frFR("")
itIT("Status")
ptPT("")
ruRU("Статус")

T_("Operator")
deDE("Bediener")
esES("")
frFR("")
itIT("Operatore")
ptPT("")
ruRU("Оператор")

T_("Number of Players")
deDE("Anzahl der Spieler")
esES("")
frFR("")
itIT("Numero Giocatori")
ptPT("")
ruRU("Кол-во Игроков")

T_("Tournament Type")
deDE("Turnierart")
esES("")
frFR("")
itIT("Tipo di Torneo")
ptPT("")
ruRU("Тип турнира")

T_("Section name")
deDE("Abschnitt")
esES("")
frFR("")
itIT("Sezione")
ptPT("")
ruRU("Назв. секции")

T_("Do USCF Report")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Open section list")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Remove Section")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Add Section ...")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Save section list")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Section list")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("USCF Tournament Rating Report")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Numebr of sections")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Event name")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Scholastic event")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Whom to send the cross table")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("State abbreviation")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Tournament city")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("End date")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Affiliate ID")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Event ID")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Begin date")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Country for event")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Zip code")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Group Rating Interval")
deDE("Gruppenwertung von/bis")
esES("")
frFR("")
itIT("Fasce elo")
ptPT("")
ruRU("Группа рейт.интервала")

T_("maximum")
deDE("Maximum")
esES("")
frFR("")
itIT("Massimo")
ptPT("")
ruRU("Максимум")

T_("minimum")
deDE("Minimum")
esES("")
frFR("")
itIT("Minimo")
ptPT("")
ruRU("Минимум")

T_("Group 1: >")
deDE("Gruppe 1: >")
esES("")
frFR("")
itIT("Gruppo 1: >")
ptPT("")
ruRU("Группа 1: >")

T_("\\& <=")
deDE("\\& <=")
esES("")
frFR("")
itIT("\\& <=")
ptPT("")
ruRU("\\& <=")

T_("Group 2: >")
deDE("Gruppe 2: >")
esES("")
frFR("")
itIT("Gruppo 2: >")
ptPT("")
ruRU("Группа 2: >")

T_("Group 3: >")
deDE("Gruppe 3: >")
esES("")
frFR("")
itIT("Gruppo 3: >")
ptPT("")
ruRU("Группа 3: >")

T_("Group 4: >")
deDE("Gruppe 4: >")
esES("")
frFR("")
itIT("Gruppo 4: >")
ptPT("")
ruRU("Группа 4: >")

T_("Group 5: >")
deDE("Gruppe 5: >")
esES("")
frFR("")
itIT("Gruppo 5: >")
ptPT("")
ruRU("Группа 5: >")

T_("Group Date Interval")
deDE("Gruppenintervall")
esES("")
frFR("")
itIT("Fasce per date")
ptPT("")
ruRU("Группа числ.интервала")

T_("Fields to print")
deDE("Zu druckende Felder")
esES("")
frFR("")
itIT("Campi da stampare")
ptPT("")
ruRU("Области печати")

T_("remove Available")
deDE("Verfügbare löschen")
esES("")
frFR("")
itIT("senza i presenti")
ptPT("")
ruRU("Удалить имеющихся")

T_("ID")
deDE("ID")
esES("")
frFR("")
itIT("ID")
ptPT("")
ruRU("нод")

T_("Name")
deDE("Name")
esES("")
frFR("Nom")
itIT("Nome")
ptPT("")
ruRU("Имя")

T_("Rtg FIDE")
deDE("Wtg FIDE")
esES("")
frFR("")
itIT("Elo FIDE")
ptPT("")
ruRU("Рейт. ФИДЕ")

T_("Rtg Nat")
deDE("Wtg Nat")
esES("")
frFR("")
itIT("Elo Naz.")
ptPT("")
ruRU("Рейт.Нац.")

T_("K coefficient")
deDE("K Koeffizient")
esES("")
frFR("")
itIT("Coefficiente K")
ptPT("")
ruRU("Коэфф.K")

T_("Print")
deDE("Drucken")
esES("")
frFR("Imprimer")
itIT("Stampa")
ptPT("")
ruRU("Печать")

T_("Save players.html")
deDE("Speichere players.html")
esES("")
frFR("")
itIT("Salva players.html")
ptPT("")
ruRU("Сохр. игр-в в html")

T_("player")
deDE("Spieler")
esES("")
frFR("")
itIT("giocatore")
ptPT("")
ruRU("Игрок")

T_("Colors")
deDE("Farben")
esES("")
frFR("")
itIT("Colori")
ptPT("")
ruRU("Цвета")

T_("Opponent")
deDE("Gegner")
esES("")
frFR("")
itIT("Avversario")
ptPT("")
ruRU("Противник")

T_("Ok")
deDE("Ok")
esES("")
frFR("")
itIT("Ok")
ptPT("")
ruRU("Ok")

T_("Available Players")
deDE("Verfügbare Spieler")
esES("")
frFR("")
itIT("Gioc. disponibile")
ptPT("")
ruRU("Свободный игрок")

T_("White ID")
deDE("ID Weiß")
esES("")
frFR("")
itIT("ID Bianco")
ptPT("")
ruRU("Белый")

T_("Black ID")
deDE("ID Schwarz")
esES("")
frFR("")
itIT("ID Nero")
ptPT("")
ruRU("Черный")

T_("Add Pair")
deDE("Paarung hinzu")
esES("")
frFR("")
itIT("Agg. coppia")
ptPT("")
ruRU("Добавить Пару")

T_("Remove Pair")
deDE("Paarung löschen")
esES("")
frFR("")
itIT("Rimuovi")
ptPT("")
ruRU("Удалить Пару")

T_("Verify Pair")
deDE("Paarung prüfen")
esES("")
frFR("")
itIT("Verifica")
ptPT("")
ruRU("Проверить Пару")

T_("Pairs added:")
deDE("Hinzugefügte Paare:")
esES("")
frFR("")
itIT("Coppie tot.:")
ptPT("")
ruRU("Добавилен.Пары:")

T_("Remained players:")
deDE("Übrige Spieler:")
esES("")
frFR("")
itIT("Giocatori rimasti")
ptPT("")
ruRU("Оставшиеся Игроки")

T_("Load Pairing")
deDE("Lade Paarungen")
esES("")
frFR("")
itIT("Carica abbin.")
ptPT("")
ruRU("Закрузить пары")

T_("Save Pairing")
deDE("Speichere Paarungen")
esES("")
frFR("")
itIT("Salva abb.")
ptPT("")
ruRU("Сохр.пары")

T_("-")
deDE("-")
esES("")
frFR("")
itIT("-")
ptPT("")
ruRU("-")

T_("    Board  ")
deDE("    Brett  ")
esES("")
frFR("")
itIT("    Board  ")
ptPT("")
ruRU(" Стол ")

T_("   Score       Rating           ID       color      |    color        "
     "  ID             Rating       Score")
deDE("  Punkte       Wertung          ID       Farbe      |    Farbe        "
     "  ID             Wertung     Punkte")
esES("")
frFR("")
itIT("   Score       Rating           ID       color      |    color        "
     "  ID             Rating       Score")
ptPT("")
ruRU("   Счет        Рейтинг          ИД       цвет      | "
     "   цвет           ИД             Рейтинг       Счет")

T_("Exchange Players")
deDE("Spieler tauschen")
esES("")
frFR("")
itIT("Scambia Colori")
ptPT("")
ruRU("Поменяться Цветами")

T_("OK")
deDE("OK")
esES("")
frFR("Ok")
itIT("Ok")
ptPT("")
ruRU("OK")


// VegaMenus.cpp

T_("File")
deDE("")
esES("")
frFR("")
itIT("File")
ptPT("")
ruRU("Файл")

T_("Extras")
deDE("")
esES("")
frFR("")
itIT("Extra")
ptPT("")
ruRU("")

T_("Report")
deDE("Bericht")
esES("")
frFR("Rapport")
itIT("Report")
ptPT("")
ruRU("Отчёт")

T_("Help")
deDE("Hilfe")
esES("")
frFR("Aide")
itIT("Aiuto")
ptPT("")
ruRU("Помощь")

T_("New Tournament")
deDE("Neues Turnier")
esES("")
frFR("")
itIT("Nuovo Torneo")
ptPT("")
ruRU("Новый Турнир")

T_("Open Tournament")
deDE("Öffne Turnier")
esES("")
frFR("")
itIT("Apri Torneo")
ptPT("")
ruRU("Открыть Турнир")

T_("Save Tournament")
deDE("Speichere Turnier")
esES("")
frFR("")
itIT("Salva Torneo")
ptPT("")
ruRU("Сохр. Турнир")

T_("Export")
deDE("Exportieren")
esES("")
frFR("")
itIT("Esporta")
ptPT("")
ruRU("Экспорт")

T_("Connect Database")
deDE("")
esES("")
frFR("")
itIT("Collega Database")
ptPT("")
ruRU("")

T_("Dangerous Stuff!")
deDE("Nur für Experten!")
esES("")
frFR("")
itIT("Operazioni pericolose!")
ptPT("")
ruRU("Опасные Действия!")

T_("archive FIDE")
deDE("")
esES("")
frFR("")
itIT("archivio FIDE")
ptPT("")
ruRU("")

T_("archive FSI Italy")
deDE("")
esES("")
frFR("")
itIT("archivio FSI")
ptPT("")
ruRU("")

T_("archive USCF Regular")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("archive USCF Quick")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("archive VEG")
deDE("")
esES("")
frFR("")
itIT("archivio VEG")
ptPT("")
ruRU("")

T_("national archive with Fixed Length")
deDE("")
esES("")
frFR("")
itIT("dati nazionali con lunghezza fissa")
ptPT("")
ruRU("")

T_("All Players")
deDE("Alle Spieler")
esES("")
frFR("")
itIT("Tutti i giocatori")
ptPT("")
ruRU("Все игроки")

T_("Tournament")
deDE("Turnier")
esES("")
frFR("")
itIT("Torneo")
ptPT("")
ruRU("Турнир")

T_("Selected Player")
deDE("Gewählter Spieler")
esES("")
frFR("")
itIT("Giocatore selezionato")
ptPT("")
ruRU("Отобранный Игрок")

T_("Modify Tournament")
deDE("Turnier ändern")
esES("")
frFR("")
itIT("Modifica torneo")
ptPT("")
ruRU("Изменить Турнир")

T_("Load Round")
deDE("Runde laden")
esES("")
frFR("")
itIT("Carica turno")
ptPT("")
ruRU("Загрузить раунд")

T_("Reset Tournament")
deDE("Turnier zurücksetzen")
esES("")
frFR("")
itIT("Ricomincia Torneo")
ptPT("")
ruRU("Сбросить Турнир")

T_("Delete Round")
deDE("Runde löschen")
esES("")
frFR("")
itIT("Cancella turno")
ptPT("")
ruRU("Удалить раунд")

T_("Reopen Registration")
deDE("Registration erneut öffnen")
esES("")
frFR("")
itIT("Riapri iscrizioni")
ptPT("")
ruRU("Повторно откр. Регистрацию")

T_("[s0;=*@6 All tournament data will be lost &(but you can keep the players).&][s0;=*@6 "
     "Do you want to continue?]")
deDE("[s0;=*@6 Alle Turnierdaten gehen verloren &(die Spieler können übernommen "
     "werden).&][s0;=*@6 Möchten Sie wirklich neu anfangen?]")
esES("")
frFR("")
itIT("[s0;=*@6 Tutti i dati saranno persi &(ma potrai conservare i giocatori).&][s0;=*@6 "
     "Vuoi continuare?]")
ptPT("")
ruRU("[s0;=*@6 Все данные турнира будут потеряны "
     " и(но Вы можете сохранить игроков).&][s0;=*@6 "
     "Вы хотите продолжить?]")

T_("Do you want to keep& the players currently registered?")
deDE("Möchten Sie die Liste der aktuell& registrierten Spieler beibehalten?")
esES("")
frFR("")
itIT("Vuoi mantenere&i giocatori al momento presenti")
ptPT("")
ruRU(" Вы хотите сохр. зарегистрировавшихся "
     "игроков?")

T_("Created new tournament")
deDE("Neues Turnier angelegt")
esES("")
frFR("")
itIT("Creato torneo nuovo")
ptPT("")
ruRU("Создать новый турнир")

T_("There are no players to export")
deDE("Es sind keine Spieler zum Export vorhanden")
esES("")
frFR("")
itIT("Non ci sono giocatori da esportare")
ptPT("")
ruRU("Нет игроков, чтобы экспортировать")

T_("File vega")
deDE("Vega Datei")
esES("")
frFR("")
itIT("File vega")
ptPT("")
ruRU("Файл vega")

T_("Set destination .VEG file")
deDE("Wähle .VEG Datei")
esES("")
frFR("")
itIT("Scegli il file .VEG di destinazione")
ptPT("")
ruRU("Выбрать файл .VEG место назнач.")

T_("The player has been copied")
deDE("Der Spieler wurde kopiert")
esES("")
frFR("")
itIT("Il giocatore è stato aggiunto")
ptPT("")
ruRU("Игрок был скопирован")

T_("Saved tournament data")
deDE("Turnierdaten gespeichert")
esES("")
frFR("")
itIT("Dati torneo salvati")
ptPT("")
ruRU("Сохр. данные турнира")

T_("[s0;=*@6 All your data will be lost.&][s0;=*@6 Do you want to continue?]")
deDE("[s0;=*@6 Alle Daten werden gelöscht.&][s0;=*@6 Möchten Sie dies wirklich?]")
esES("")
frFR("")
itIT("[s0;=*@6 Tutti i dati saranno persi.&][s0;=*@6 Vuoi continuare?]")
ptPT("")
ruRU("[s0;=*@6 Все ваши данные будут потеряны.&][s0;=*@6 "
     "Вы хотите продолжить?]")

T_("Opened tournament ")
deDE("Turnier geöffnet ")
esES("")
frFR("")
itIT("Torneo aperto ")
ptPT("")
ruRU("Турнир Открыт")

T_("archive FIDE (txt)")
deDE("FIDE Archiv (txt)")
esES("")
frFR("")
itIT("archivio FIDE (txt)")
ptPT("")
ruRU("Архив для ФИДЕ в (txt)")

T_("archive VEG (csv & veg)")
deDE("VEGA Archiv (csv & veg)")
esES("")
frFR("")
itIT("archivio VEG (csv & veg)")
ptPT("")
ruRU("Архив VEG (csv & veg)")

T_("national archive with Fixed Length (txt & csv)")
deDE("Nationales Archiv mit fester Länge (txt & csv)")
esES("")
frFR("")
itIT("archivio nazionale a campi fissi (txt & csv)")
ptPT("")
ruRU("нац. архив с неподвижной длиной (txt & csv)")

T_("archive FSI Italy (csv)")
deDE("FSI Archiv, Italien (csv)")
esES("")
frFR("")
itIT("Archivio FSI - Italia (csv)")
ptPT("")
ruRU("архив FSI - Италия (csv)")

T_("archive USCF Regular (txt)")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("archive USCF Quick (txt)")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Imported ")
deDE("Importiert wurden ")
esES("")
frFR("")
itIT("Importati ")
ptPT("")
ruRU("Передано ")

T_(" players")
deDE(" Spieler")
esES("")
frFR("")
itIT(" giocatori")
ptPT("")
ruRU(" Игроки")

T_("Nothing to load")
deDE("Keine Daten gefunden")
esES("")
frFR("")
itIT("Nessun file da caricare")
ptPT("")
ruRU("Нет файлов, для загрузки")

T_("File round")
deDE("Runde in Datei speichern")
esES("")
frFR("")
itIT("File del turno")
ptPT("")
ruRU("Файл раунда")

T_("Read round file: ")
deDE("Lese Runden-Datei: ")
esES("")
frFR("")
itIT("Leggi file RND:")
ptPT("")
ruRU("Чтение Файла раунда:")

T_("Nothing to reset")
deDE("Keine Daten zum Zurücksetzen vorhanden")
esES("")
frFR("")
itIT("Niente da annullare")
ptPT("")
ruRU("Аннулировать нечего")

T_("[s0;=* Do you want to [@6 RESET] the Tournament at round 0?&][s0;=* The "
     "current data will be lost]")
deDE("")
esES("")
frFR("")
itIT("[s0;=* Vuoi [@6 RICOMINCIARE] il torneo dal primo turno?&][s0;=* I dati "
     "già inseriti saranno persi]")
ptPT("")
ruRU("")

T_("[s0;=* LAST WARNING!&][s0;=* Do you want to [@6 RESET] the Tournament "
     "at round 0?&][s0;=* The current data will be lost]")
deDE("")
esES("")
frFR("")
itIT("[s0;=* ULTIMO AVVERTIMENTO!&][s0;=* Vuoi [@6 RICOMINCIARE] il torneo dal "
     "primo turno?&][s0;=* I dati già inseriti saranno persi]")
ptPT("")
ruRU("")

T_("Reset tournament")
deDE("Turnier zurücksetzen")
esES("")
frFR("")
itIT("Ricomincia torneo")
ptPT("")
ruRU("Возобновить турнир")

T_("Nothing to delete")
deDE("Keine Daten zum Löschen gefunden")
esES("")
frFR("")
itIT("Niente da cancellare")
ptPT("")
ruRU("Ничего нет для удаления")

T_("Do you want to delete the current round?")
deDE("Möchten Sie die aktuelle Runde löschen?")
esES("")
frFR("")
itIT("Vuoi cancellare il turno corrente?")
ptPT("")
ruRU("Хотите удалить текущий раунд?")

T_("Deleted Round ")
deDE("Gelöschte Runde: ")
esES("")
frFR("")
itIT("Turno cancellato")
ptPT("")
ruRU("Раунд удален ")

T_("The tournament is not closed!")
deDE("Das Turnier ist nicht beendet!")
esES("")
frFR("")
itIT("Il torneo non è chiuso!")
ptPT("")
ruRU("Турнир не закрыт!")

T_("[s0;=* Do you want to [@6 REOPEN] the Registration?&][s0;=* All your data "
     "will be lost]")
deDE("")
esES("")
frFR("")
itIT("[s0;=* Vuoi davvero [@6 RIAPRIRE] le iscrizioni?&][s0;=* Tutti i turni "
     "inseriti saranno perduti]")
ptPT("")
ruRU("")

T_("[s0;=* LAST WARNING!&][s0;=* Do you want to [@6 REOPEN] the Registration?&][s0;=* "
     "All your data will be lost]")
deDE("")
esES("")
frFR("")
itIT("[s0;=* ULTIMO AVVERTIMENTO!&][s0;=* Vuoi davvero [@6 RIAPRIRE] le iscrizioni?&][s0;=* "
     "Tutti i turni inseriti saranno perduti]")
ptPT("")
ruRU("")

T_("Reopened registration")
deDE("Registration erneut geöffnet")
esES("")
frFR("")
itIT("Iscrizioni riaperte")
ptPT("")
ruRU("Возобновить регистрацию")

T_("Closing Vega")
deDE("Vega wird beendet")
esES("")
frFR("")
itIT("Chiusura del programma")
ptPT("")
ruRU("Закрыть программу")

T_("Save-Exit")
deDE("Speichern-Ende")
esES("")
frFR("")
itIT("Salva-Esci")
ptPT("")
ruRU("Сохр./выход")

T_("Sort Cross Table")
deDE("Kreuztabelle nach Punkten")
esES("")
frFR("")
itIT("Classifica + tabellone")
ptPT("")
ruRU("Классифика+таблица")

T_("Rank Rating Group")
deDE("Gruppen nach Wertung")
esES("")
frFR("")
itIT("Classifica per fasce Elo")
ptPT("")
ruRU("Классифик.групп рейтинга")

T_("Rank Date Group")
deDE("Gruppen nach Alter/Geb.Datum")
esES("")
frFR("")
itIT("Classifica per fasce di date")
ptPT("")
ruRU("Классифик. групп по датам")

T_("Round Robin Calendar")
deDE("Rundenturnier-Kalender")
esES("")
frFR("")
itIT("Calendario girone italiano")
ptPT("")
ruRU("Календарь круг.турнира")

T_("Missing Point Score system")
deDE("Fehlpunkte-System")
esES("")
frFR("")
itIT("Sistema dei punti mancanti")
ptPT("")
ruRU("Система нехват. баллов")

T_("Backup *.veg file")
deDE("Backup der VEG-Datei")
esES("")
frFR("")
itIT("Backup file *.veg")
ptPT("")
ruRU("копия файла*.veg")

T_("Find Duplicate Player")
deDE("Finde doppelte Spieler")
esES("")
frFR("")
itIT("Trova giocatori duplicati")
ptPT("")
ruRU("Найти запасного Игрока")

T_("Select Language")
deDE("Sprache wählen")
esES("")
frFR("")
itIT("Seleziona lingua")
ptPT("")
ruRU("Выбрать язык")

T_("Fide")
deDE("FIDE")
esES("")
frFR("")
itIT("FIDE")
ptPT("")
ruRU("ФИДЕ")

T_("English")
deDE("Englisch")
esES("")
frFR("")
itIT("Inglese")
ptPT("")
ruRU("Английский")

T_("Italian")
deDE("Italienisch")
esES("")
frFR("")
itIT("Italiano")
ptPT("")
ruRU("Итальянский")

T_("German")
deDE("Deutsch")
esES("")
frFR("")
itIT("Tedesco")
ptPT("")
ruRU("Немецкий")

T_("French")
deDE("Französisch")
esES("")
frFR("")
itIT("Francese")
ptPT("")
ruRU("Французский")

T_("Spanish")
deDE("Spanisch")
esES("")
frFR("")
itIT("Spagnolo")
ptPT("")
ruRU("Испанский")

T_("Russian")
deDE("Russisch")
esES("")
frFR("")
itIT("Russo")
ptPT("")
ruRU("Русский")

T_("Portuguese")
deDE("Portugiesisch")
esES("")
frFR("")
itIT("Portoghese")
ptPT("")
ruRU("Португальский")

T_("Enter the registration fee")
deDE("")
esES("")
frFR("")
itIT("Inserisci la quota di iscrizione")
ptPT("")
ruRU("вступительный взнос")

T_("Please close and restart the program&to make active the change")
deDE("Bitte beenden Sie das Programm und starten Sie&es neu, um die Änderungen "
     "zu aktivieren")
esES("")
frFR("")
itIT("Chiudi e riavvia il programma&per attivare la nuova lingua")
ptPT("")
ruRU("Закройте и откройте программу&для активации "
     "измененний")

T_("History card")
deDE("Verlauf")
esES("")
frFR("")
itIT("Cartellino giocatore")
ptPT("")
ruRU("Карта игрока")

T_("Find Norm")
deDE("Finde Norm")
esES("")
frFR("")
itIT("Trova Norma")
ptPT("")
ruRU("Найти норму")

T_("FIDE norm certificate")
deDE("FIDE Normzertifikat")
esES("")
frFR("")
itIT("Certificato norme FIDE")
ptPT("")
ruRU("Сертифицир. нормы ФИДЕ")

T_("Statistics")
deDE("Statistik")
esES("")
frFR("")
itIT("Statistiche")
ptPT("")
ruRU("Статистика")

T_("Option available after the closure&of the registration")
deDE("Diese Option ist erst nach Beenden der&Registration verfügbar")
esES("")
frFR("")
itIT("Opzione disponibile solo dopo&la chiusura delle registrazioni")
ptPT("")
ruRU("Выриант будет доступен после&закрытия "
     "регистрации")

T_("DONE")
deDE("FERTIG")
esES("")
frFR("")
itIT("Fatto")
ptPT("")
ruRU("Сделанно")

T_("Process current section")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Tournament Report (all sections) ")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Option available with a running tournament")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Option available only for Round Robin system!")
deDE("Diese Option ist nur für Rundenturniere verfügbar!")
esES("")
frFR("")
itIT("Opzione disponibile solo per il girone italiano")
ptPT("")
ruRU("Вариант доступен только для круг.турнира")

T_("Option not available for Round Robin")
deDE("Nicht möglich bei Rundenturnieren")
esES("")
frFR("")
itIT("Opzione non disponibile per il Girone Italiano")
ptPT("")
ruRU("Вариант недоступен для круг.турнира")

T_("Found the following duplicates: &")
deDE("Folgende Spieler sind doppelt: &")
esES("")
frFR("")
itIT("Trovati i seguenti duplicati: &")
ptPT("")
ruRU("Найти следующих запасных")

T_("There are no duplicate")
deDE("Keine doppelten Spieler gefunden")
esES("")
frFR("")
itIT("Non ci sono duplicati")
ptPT("")
ruRU("Запасных нет ")

T_("Content")
deDE("Inhalt")
esES("")
frFR("")
itIT("Contenuto")
ptPT("")
ruRU("Содержание")

T_("Registered to ...")
deDE("Registriert auf ...")
esES("")
frFR("")
itIT("Registrato a nome di ...")
ptPT("")
ruRU("Зарегистрированный на имя... ")

T_("About")
deDE("Über")
esES("")
frFR("")
itIT("Info su Vega")
ptPT("")
ruRU("Инфо о Vega")

T_("  Players Archive  ")
deDE("  Spieler  ")
esES("")
frFR("")
itIT("  Giocatori  ")
ptPT("")
ruRU("Архив игроков")

T_("  Round Manager ")
deDE("  Runden ")
esES("")
frFR("")
itIT("  Gestione Turno  ")
ptPT("")
ruRU(" Управление туром ")

T_("  Output  ")
deDE("  Ausgabe  ")
esES("")
frFR("")
itIT("  Output  ")
ptPT("")
ruRU(" Результат ")

T_("waiting new pairing")
deDE("Warte auf neue Paarungen")
esES("")
frFR("")
itIT("Attendo nuovo abbinamento")
ptPT("")
ruRU("ожидание новой пары")

T_("waiting result of current round")
deDE("Warte auf Ergebnisse dieser Runde")
esES("")
frFR("")
itIT("Attendo i risultati del turno corrente")
ptPT("")
ruRU("ожидание результат текущего раунда")

T_("Add at least 6 players for a swiss system")
deDE("Sie brauchen mindestens 6 Spieler für das Schweizer System")
esES("")
frFR("")
itIT("Aggiungi almeno 6 giocatori per il sistema svizzero")
ptPT("")
ruRU("Добавить, хотя бы 6 игроков, для швейцарской "
     "сист.")

T_("Too many rounds")
deDE("Zu viele Runden")
esES("")
frFR("")
itIT("Troppi turni")
ptPT("")
ruRU("Слишком много туров")

T_("wrong number of players")
deDE("Falsche Anzahl von Spielern")
esES("")
frFR("")
itIT("Numero giocatori errato")
ptPT("")
ruRU("Кол-во игроков ошибочное")

T_("you could not get a clear winner... increase Rounds")
deDE("Es gibt keinen eindeutigen Gewinner...Rundenzahl erhöhen")
esES("")
frFR("")
itIT("non puoi designare un vincitore certo... aumenta i turni")
ptPT("")
ruRU("Невозможно выбрать победителя... добавьте "
     "раунды")

T_("Do you want to close the registration?")
deDE("Möchten Sie die Registrierung abschließen?")
esES("")
frFR("")
itIT("Vuoi chiudere le registrazioni?")
ptPT("")
ruRU("Хотите закрыть регистрацию?")

T_("Sort of the players")
deDE("Sortierung der Spieler")
esES("")
frFR("")
itIT("Ordinamento giocatori")
ptPT("")
ruRU("Порядок игроков")

T_("Assign the ID by:")
deDE("ID zuweisen nach:")
esES("")
frFR("")
itIT("Assegna l'ID per:")
ptPT("")
ruRU("Передать ID для:")

T_("RtgTtlName")
deDE("WtgTtlName")
esES("")
frFR("")
itIT("RtgTtlName")
ptPT("")
ruRU("РейтТитИмя")

T_("Random")
deDE("Zufällig")
esES("")
frFR("")
itIT("Casuale")
ptPT("")
ruRU("Случайно")

T_("no sort")
deDE("unsortiert")
esES("")
frFR("")
itIT("Non ordinare")
ptPT("")
ruRU("Не упорядочивать")

T_("Please insert the result of the current round")
deDE("Bitte geben Sie das Ergebnis dieser Runde ein")
esES("")
frFR("")
itIT("Inserisci il risultato del turno corrente")
ptPT("")
ruRU("Добавьте рез.текущего раунда")

T_("You cannot generate a new pairing. First close the Registration")
deDE("Sie können noch keine Paarungen erzeugen. Beenden Sie erst die Registration")
esES("")
frFR("")
itIT("Non puoi generare gli abbinamenti. Prima chiudi le iscrizioni")
ptPT("")
ruRU("Невозможно создавать новые пары, незакрыв "
     "регистрацию.")

T_("The Tournament is finished")
deDE("Das Turnier ist beendet")
esES("")
frFR("")
itIT("Il torneo è finito!")
ptPT("")
ruRU("Турнир закрыт!")

T_("Option not available.&First close the Registration")
deDE("Diese Option ist noch nicht verfügbar.&Beenden Sie bitte erst die Registration")
esES("")
frFR("")
itIT("Opzione non disponibile.&Prima chiudi le registrazioni")
ptPT("")
ruRU("Вариант недоступен. Закройте регистрацию")

T_("Option available only for the current round")
deDE("Nicht möglich für die aktuelle Runde")
esES("")
frFR("")
itIT("Opzione disponibile solo per il turno corrente")
ptPT("")
ruRU("Вариант доступен, только для текущего "
     "раунда")

T_("Open or Create a tournament!")
deDE("Öffnen oder erzeugen Sie ein Turnier!")
esES("")
frFR("")
itIT("Apri o crea un Torneo!")
ptPT("")
ruRU("Открыть и создать Турнир!")

T_("Registration of players")
deDE("Registrierung der Spieler")
esES("")
frFR("")
itIT("Iscrizione giocatori")
ptPT("")
ruRU("Зарегистрировать игроков")

T_("Waiting insert results!")
deDE("Erwarte die Eingabe von Ergebnissen!")
esES("")
frFR("")
itIT("Attendo l'inserimento dei risultati")
ptPT("")
ruRU("Подождите вносить результаты!")

T_("Tournament finished!")
deDE("Turnier abgeschlossen!")
esES("")
frFR("")
itIT("Il torneo è finito!")
ptPT("")
ruRU("Турнир закрыт!")

T_("Waiting new pairing")
deDE("Erwarte die neuen Paarungen")
esES("")
frFR("")
itIT("Attendo il nuovo abbinamento")
ptPT("")
ruRU("Подождите новые соединения")

T_("LAST ROUND!")
deDE("LETZTE RUNDE!")
esES("")
frFR("")
itIT("ULTIMO TURNO!")
ptPT("")
ruRU("ПОСЛЕДНИЙ РАУНД!")

T_("swiss Dubov")
deDE("Swiss Dubov")
esES("")
frFR("")
itIT("Svizzero Dubov")
ptPT("")
ruRU("Швейц. Дубов")

T_("single RR")
deDE("RT einfach")
esES("")
frFR("")
itIT("RR singolo")
ptPT("")
ruRU("Ед.RR")

T_("double RR")
deDE("RT doppelt")
esES("")
frFR("")
itIT("RR doppio")
ptPT("")
ruRU("Двойной RR")

T_("swiss vega")
deDE("Swiss Vega")
esES("")
frFR("")
itIT("Svizzero Vega")
ptPT("")
ruRU("Швейц.Vega")

T_("swiss USCF")
deDE("Swiss USCF")
esES("")
frFR("")
itIT("Svizzero USCF")
ptPT("")
ruRU("Швейц.USCF")

T_("swiss Lim")
deDE("Swiss Lim")
esES("")
frFR("")
itIT("Svizzero Lim")
ptPT("")
ruRU("Швейц.Lim")

T_(" got a BYE!")
deDE(" erhielt ein BYE!")
esES("")
frFR("")
itIT(" ha ricevuto un BYE!")
ptPT("")
ruRU(" Достался BYE!")

T_(" is available")
deDE(" ist verfügbar")
esES("")
frFR("")
itIT(" è disponibile")
ptPT("")
ruRU(" доступен")

T_(" is NOT available!")
deDE(" ist NICHT verfügbar!")
esES("")
frFR("")
itIT(" non è disponibile")
ptPT("")
ruRU(" недоступен!")

T_("removed player")
deDE("")
esES("")
frFR("")
itIT("cancellato giocatore")
ptPT("")
ruRU("")

T_("Time")
deDE("Zeit")
esES("")
frFR("")
itIT("Data")
ptPT("")
ruRU("Дата")

T_("System")
deDE("System")
esES("")
frFR("")
itIT("Sistema")
ptPT("")
ruRU("Система")

T_(" Total, Avail, Bye")
deDE("")
esES("")
frFR("")
itIT("Totale, Disp., Bye")
ptPT("")
ruRU("Total, Avail, Bye")

T_("Action")
deDE("Aktion")
esES("")
frFR("Action")
itIT("Azione")
ptPT("")
ruRU("Действие")

T_("Hello!")
deDE("Hallo!")
esES("")
frFR("")
itIT("Ciao!")
ptPT("")
ruRU("Приветствую!")


// VegaTab1.cpp

T_("G")
deDE("")
esES("")
frFR("")
itIT("S")
ptPT("")
ruRU("")

T_("Do you want to remove the player&")
deDE("")
esES("")
frFR("")
itIT("Vuoi cancellare il giocatore&")
ptPT("")
ruRU("")

T_("The Name field cannot be empty!")
deDE("Bitte geben Sie einen Namen ein!")
esES("")
frFR("")
itIT("Il campo Nome non può essere vuoto")
ptPT("")
ruRU("Поле ИМЯ, неможет быть пустым!")

T_("You can't add a player in a Round Robin&after the closure of registration")
deDE("Sie können keine Spieler zu einem Rundenturnier&hinzufügen nachdem die "
     "Registration beendet wurde")
esES("")
frFR("")
itIT("Non puoi aggiungere un giocatore in un girone italiano&dopo la chiusura "
     "delle iscrizioni")
ptPT("")
ruRU("Невозможно добавить игрока в круг.игру, "
     "после закрытия регистрации ")

T_("Too much players! Stop with the registration")
deDE("Zu viele Spieler! Bitte beenden Sie die Registration")
esES("")
frFR("")
itIT("Troppi giocatori! Chiudere le iscrizioni")
ptPT("")
ruRU("Слишком много игроков! Закрыть регистрацию")

T_("Do you want to add a Late-Comer to the tournament?&You will not be able "
     "to delete him again")
deDE("Möchten Sie einen Späteinsteiger zum Turnier hinzufügen?&Sie können "
     "diesen Spieler nicht wieder löschen")
esES("")
frFR("")
itIT("Vuoi aggiungere un ritardatario al torneo?&Non si potrà poi cancellarlo")
ptPT("")
ruRU("Добавить опаздывающего на турнир?Потом "
     "будет невозможно удалить его")

T_("Category and gender does not coincide&Please check")
deDE("Kategorie und Geschlecht passen nicht zusammen&Bitte prüfen")
esES("")
frFR("")
itIT("Categoria e sesso non coincidono&Ricontrolla")
ptPT("")
ruRU("Категория и пол не совпадают, пожалуйста "
     "проверте")

T_("It will contain all the registered players")
deDE("")
esES("")
frFR("")
itIT("Conterrà tutti i giocatori registrati")
ptPT("")
ruRU("Здесь будут содержаться все зарегистрирован. "
     "игроки")

T_("Set the round to display all other data")
deDE("Setzen Sie die aktuelle Runde um Daten auszugeben")
esES("")
frFR("")
itIT("Indica il turno per vedere gli altri dati")
ptPT("")
ruRU("Набрать раунд для показа других данных")

T_("Game against player 0=BYE&is considered forfeited")
deDE("Das Spiel gegen Spieler 0=BYE& wird nicht gewertet")
esES("")
frFR("")
itIT("La partita con il 0=BYE&è coinsiderata a forfeit")
ptPT("")
ruRU("Игра 0=BYE-рассматривается как проигрыш")

T_("'Null' set the game as 'unplayed'")
deDE("'Null' markiert die Begegnung als 'nicht gespielt'")
esES("")
frFR("")
itIT("Usa 'Null' per considerarla 'non giocata'")
ptPT("")
ruRU("Исрользование 'Null'-несыгранная")

T_("Round out of range")
deDE("Runde liegt nicht im gültigen Bereich")
esES("")
frFR("")
itIT("numero Turno scorretto")
ptPT("")
ruRU("неправильный номер раунда ")

T_("Set a valid opponent for the selected player")
deDE("Geben Sie einen gültigen Gegner für den gewählten Spieler an")
esES("")
frFR("")
itIT("Indica un avversario valido")
ptPT("")
ruRU("Показать законного оппонента")


// VegaTab3.cpp

T_("New Pairing")
deDE("Neue Paarungen")
esES("")
frFR("")
itIT("Nuovo abbinamento")
ptPT("")
ruRU("Новая пара")

T_("Insert/Modify Result")
deDE("Ergebnis einfügen/ändern")
esES("")
frFR("")
itIT("Inserisci/modifica risultato")
ptPT("")
ruRU("Вписать/изменить результат")

T_("Bo.")
deDE("Br.")
esES("")
frFR("")
itIT("Tav.")
ptPT("")
ruRU("Стол")

T_("White Player")
deDE("Spieler Weiß")
esES("")
frFR("")
itIT("Bianco")
ptPT("")
ruRU("Белые")

T_("Black Player")
deDE("Spieler Schwarz")
esES("")
frFR("")
itIT("Nero")
ptPT("")
ruRU("Черные")

T_("IDW-IDB")
deDE("IDW-IDS")
esES("")
frFR("")
itIT("IDW-IDB")
ptPT("")
ruRU("  НБ-НЧ")

T_("Double click to exchange the colors")
deDE("Doppelclick tauscht die Farben")
esES("")
frFR("")
itIT("Doppio per scambiare i colori")
ptPT("")
ruRU("Двойной щелчок для изменения цвета")

T_("Save the explanation pairing file")
deDE("Speichern der Paarungsermittlung")
esES("")
frFR("")
itIT("Salva il file con le spiegazioni")
ptPT("")
ruRU("Сохр. файл с объяснениями")

T_("Permit the same color\nthree time in a row")
deDE("Erlaube dreimal hintereinander\ndie gleiche Farbe")
esES("")
frFR("")
itIT("Permetti lo stesso colore\nper tre volte di seguito")
ptPT("")
ruRU("Разрешить игру одним и тем же цветом\n 3 "
     "раза подряд")

T_("Enable the Danubian variant\nfor the dubov system")
deDE("Danubische Variante für\ndas Dubov-System aktivieren")
esES("")
frFR("")
itIT("Abilita la variante Danubio\nper il sistema Dubov")
ptPT("")
ruRU("Позволение Danubian варианта\nдля системы "
     "Дубова")

T_("Round not valid")
deDE("Runde ist nicht gültig")
esES("")
frFR("")
itIT("Turno non valido")
ptPT("")
ruRU("Раунд не действительный")

T_("You cannot visualize other rounds.&First insert the results of the current "
     "round")
deDE("Sie können noch keine Rundendaten ausgeben.&Beenden Sie erst die Eingabe "
     "der aktuellen Runde")
esES("")
frFR("")
itIT("Inserisci i risultati del turno corrente")
ptPT("")
ruRU("Невозможно посмотреть другие раунды.Вначале "
     "должны быть внесены рез. текущего раунда")

T_("Are you sure do you want&to change an old result?")
deDE("Möchten Sie wirklich ein&altes Ergebnis ändern?")
esES("")
frFR("")
itIT("Sei sicuro di voler&cambiare il vecchio risultato?")
ptPT("")
ruRU("Уверенны, что хотите изменить старый рез.?")

T_("Load result file")
deDE("Lade Ergebnis-Datei")
esES("")
frFR("")
itIT("File risultati")
ptPT("")
ruRU("Загрузить файл с рез.")

T_("The selected file doens't correspond to the current round!&Please choose "
     "the correct one")
deDE("Die gewählte Datei passt nicht zur aktuellen Runde!&Bitte korrigieren "
     "Sie Ihre Wahl")
esES("")
frFR("")
itIT("Il file scelto non corrisponde a quello corrente&scegli quello giusto")
ptPT("")
ruRU("Выбранный файл не соответствует текущему "
     "раунду&выберите правельный")

T_("[s0;= There are still pairs without result. &] [s0;= Please insert all "
     "results or you will be not able to continue]")
deDE("[s0;= Zu einigen Paarungen gibt es noch kein Ergebnis. &] [s0;= Bitte "
     "tragen Sie die Daten nach sonst geht es nicht weiter]")
esES("")
frFR("")
itIT("[s0;= Ci sono ancora coppie senza risultato. &] [s0;= Inseriscili tutti "
     "o non potrai continuare")
ptPT("")
ruRU("[s0;= Есть еще пары без результата. &] [s0;= Пожалуйста, "
     "внесите все результаты для продолжения")

T_("[s0;= All results have been inserted")
deDE("[s0;= Alle Ergebnisse wurden eingegeben")
esES("")
frFR("")
itIT("[s0;= Tutti i risultati sono stati inseriti")
ptPT("")
ruRU("[s0;= Все результаты внесены")

T_("Option not available.&First generate the new pairing")
deDE("Option nicht verfügbar.&Erzeugen Sie erst eine neue Paarung")
esES("")
frFR("")
itIT("Opzione non disponibile. Prima genera l'abbinamento")
ptPT("")
ruRU("Вариант недоступен.&Вначале создайте новую "
     "пару")

T_("Do you want to exchange the colors&of the selected players?")
deDE("Möchten Sie für die ausgewählten&Spieler die Farben tauschen?")
esES("")
frFR("")
itIT("Vuoi scambiare i colori&della coppia selezionata?")
ptPT("")
ruRU("Хотите поменять цвета выбранных игроков?")

T_("The exchange is not permitted!&Do you want to continue in any case?")
deDE("Dieser Tausch ist nicht regulär!&Möchten Sie trotzdem damit fortfahren?")
esES("")
frFR("")
itIT("Lo scambio è illegale!&Vuoi continuare lo stesso?")
ptPT("")
ruRU("Изменение незаконно!Тем неменее хотете "
     "продолжить?")


// VegaTab4.cpp

T_("text files")
deDE("Text Dateien")
esES("")
frFR("")
itIT("File di testo")
ptPT("")
ruRU("Текстовой файл")

T_("New")
deDE("Neu")
esES("")
frFR("Nouveau")
itIT("Nuovo")
ptPT("")
ruRU("Новый")

T_("Create new document")
deDE("Erzeuge neues Dokument")
esES("")
frFR("")
itIT("Crea nuovo documento")
ptPT("")
ruRU("Создать новый документ")

T_("New Qtf")
deDE("Neues Qtf")
esES("")
frFR("")
itIT("Nuovo Qtf")
ptPT("")
ruRU("Новый Qtf")

T_("Open new QTF window")
deDE("Öffne neues Qtf-Fenster")
esES("")
frFR("")
itIT("Apri nuova finestra Qtf")
ptPT("")
ruRU("Открыть новое окно Qtf")

T_("Open existing document")
deDE("Öffne Dokument")
esES("")
frFR("")
itIT("Apri documento esistente")
ptPT("")
ruRU("Открыть существующий док.")

T_("SaveAs")
deDE("Speichern als")
esES("")
frFR("")
itIT("Salva con nome")
ptPT("")
ruRU("Сохр. как")

T_("Save current document with a new name")
deDE("Speichere aktuelles Dokument unter neuem Namen")
esES("")
frFR("")
itIT("Salva il documento corrente con un nuovo nome")
ptPT("")
ruRU("Сохр. данный док. под новым именем")

T_("Print..")
deDE("Drucken..")
esES("")
frFR("")
itIT("Stampa...")
ptPT("")
ruRU("Печать...")

T_("Print document")
deDE("Drucke Dokument")
esES("")
frFR("")
itIT("Stampa documento")
ptPT("")
ruRU("Распечатать док.")

T_("Print selected text")
deDE("Drucke selektierten Text")
esES("")
frFR("")
itIT("Stampa il testo selezionato")
ptPT("")
ruRU("Распечатать выделенный текст")

T_("The current data will be lost.&Do you want to continue?")
deDE("Die aktuellen Daten gehen dadurch verloren.&Möchten Sie trotzdem fortfahren?")
esES("")
frFR("")
itIT("I dati verranno persi.&Vuoi continuare?")
ptPT("")
ruRU("Данные будут потеряны.&Продолжить?")

T_("Error saving the file: ")
deDE("Fehler beim Speichern von: ")
esES("")
frFR("")
itIT("Errore nel salvataggio del file")
ptPT("")
ruRU("Ошибка при сохранении файла")


// Tournament.cpp

T_(" # Do not edit this file!")
deDE(" # Diese Datei nicht editieren!")
esES("")
frFR("")
itIT(" # Non modificare questo file!")
ptPT("")
ruRU("# Не изменяйте этот файл!")

T_("error in the data format")
deDE("Fehler im Datenformat")
esES("")
frFR("")
itIT("Errore nel formato dei dati")
ptPT("")
ruRU("Ошибка в формате данных")

T_("Standing at round ")
deDE("")
esES("")
frFR("")
itIT("Classifica al turno ")
ptPT("")
ruRU("")

T_(" sorted by category")
deDE("")
esES("")
frFR("")
itIT(" ordinati per categoria")
ptPT("")
ruRU("")

T_("Ranking for category: ")
deDE("")
esES("")
frFR("")
itIT("Classifica per categoria")
ptPT("")
ruRU("")

T_("Rating variation at round ")
deDE("")
esES("")
frFR("")
itIT("Variazione Elo al turno ")
ptPT("")
ruRU("")

T_("National Player Cards")
deDE("")
esES("")
frFR("")
itIT("Cartellini Nazionali")
ptPT("")
ruRU("")

T_(",  Round: ")
deDE("")
esES("")
frFR("")
itIT(",  Turno: ")
ptPT("")
ruRU("")

T_(": Results of round ")
deDE("")
esES("")
frFR("")
itIT(": Risultati del turno ")
ptPT("")
ruRU("")

T_(": Pairing of round ")
deDE("")
esES("")
frFR("")
itIT(": Abbinamento del turno ")
ptPT("")
ruRU("")

T_("\n The following player(s) got a BYE:\n")
deDE("\n Folgende Spieler erhielten ein Freilos:\n")
esES("")
frFR("")
itIT("\n I seguenti giocatori hanno preso un BYE:")
ptPT("")
ruRU("\n Данные игроки получили BYE:\n")

T_("\n The following player(s) withdrew:\n")
deDE("\n Die folgenden Spieler sind ausgeschieden:\n")
esES("")
frFR("")
itIT("\n I seguenti giocatori si sono ritirati:")
ptPT("")
ruRU("\n Данные игроки ушли:")

T_("Tournament Summary")
deDE("Turnier in Kürze")
esES("")
frFR("")
itIT("Riassunto torneo")
ptPT("")
ruRU("Резюме турнира")

T_("Standing")
deDE("Rangliste")
esES("")
frFR("")
itIT("Classifica")
ptPT("")
ruRU("Ранжирование")

T_("Rating Report")
deDE("Wertungsbericht")
esES("")
frFR("")
itIT("Report Elo")
ptPT("")
ruRU("Рейтинг-отчет")

T_("Score Groups")
deDE("Punktegruppen")
esES("")
frFR("")
itIT("Gruppi di punteggio")
ptPT("")
ruRU("Группы баллов")

T_("Participants")
deDE("Teilnehmer")
esES("")
frFR("")
itIT("Partecipanti")
ptPT("")
ruRU("Участники")

T_("Pairings/Results: ")
deDE("")
esES("")
frFR("")
itIT("Abbinamenti/Risultati: ")
ptPT("")
ruRU("")

T_("UCSF archive converted")
deDE("USCF Archiv, konvertiert")
esES("")
frFR("")
itIT("archivio USCF convertito")
ptPT("")
ruRU("Архив UCSF конвертирован")


// ConnectDB.cpp

T_("Import Player from Database")
deDE("Importiere Spieler aus Datenbank")
esES("")
frFR("")
itIT("Importa giocatore dal database")
ptPT("")
ruRU("Перенести игрока из БД")

T_("import from FIDE db: ")
deDE("Importiere aus FIDE DB: ")
esES("")
frFR("")
itIT("Importa dal DB FIDE: ")
ptPT("")
ruRU("Перенести из БД ФИДЕ: ")

T_("import from VEG db: ")
deDE("Importiere aus VEG DB: ")
esES("")
frFR("")
itIT("Importa da DB Vega: ")
ptPT("")
ruRU("Перенести из БД Vega:")

T_("import from Fixed Length db: ")
deDE("Importiere aus Feste-Länge DB: ")
esES("")
frFR("")
itIT("importa da un DB a campi fissi: ")
ptPT("")
ruRU("Перенести из БД Fixed Length: ")

T_("import from FSI db: ")
deDE("Importiere aus FSI DB: ")
esES("")
frFR("")
itIT("Importa da DB FSI: ")
ptPT("")
ruRU("Перенести из БД FSI: ")

T_("import from USCF db (regular): ")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("import from FSI db (quick): ")
deDE("")
esES("")
frFR("")
itIT("")
ptPT("")
ruRU("")

T_("Insert at least 5 characters\nspace included")
deDE("Mindestens 5 Zeichen eingeben\ninclusive Leerzeichen")
esES("")
frFR("")
itIT("Inserisci almeno 5 caratteri\nspazi inclusi")
ptPT("")
ruRU("Внести хотя бы 5 хар-к\nвключяя место")

T_("Because the registration are closed & you cannot import players & but "
     "only browse the DB")
deDE("")
esES("")
frFR("")
itIT("Poiché le registrazioni sono chiuse & puoi solo esplorare il database "
     "& ma senza importare giocatori")
ptPT("")
ruRU("")

T_("not found")
deDE("Nicht gefunden")
esES("")
frFR("")
itIT("Non trovato")
ptPT("")
ruRU("Не найдено")

T_("Option not available for Round Robin tournament")
deDE("Nicht möglich bei Rundenturnieren")
esES("")
frFR("")
itIT("Opzione non disponibile per il Girone Italiano")
ptPT("")
ruRU("Вариант не доступен для круг.турнира")

T_("You cannot add player from the DB.&Insert it from Edit Mask")
deDE("Sie können den Spieler nicht aus der Datenbank hinzufügen.&Bitte benutzen "
     "Sie die allgemeine Eingabemaske")
esES("")
frFR("")
itIT("Non puoi aggiungere giocatori dal DB.&Inseriscili dalla maschera Edit")
ptPT("")
ruRU("Невозможно добавить игрока из БД.&Внести "
     "его через Поле Редактирования")

T_("exceeded maximum number of players.&Please remove at least ")
deDE("Maximale Anzahl der Spieler ist überschritten.&Bitte löschen Sie mindestens ")
esES("")
frFR("")
itIT("Raggiunto il numero massimo di giocatori. Togli almeno ")
ptPT("")
ruRU("Кол-во игроков максимальное. Удалите хотя "
     "бы")

T_("record")
deDE("Eintrag")
esES("")
frFR("")
itIT("record")
ptPT("")
ruRU("Рекорд")

T_("& in the wrong format!&check the DB")
deDE("& im falschen Format!&Prüfen Sie die Datenbank")
esES("")
frFR("")
itIT("& è in un formato errato!&Controlla il DB")
ptPT("")
ruRU("& ошибочный формат!&Надо проверить БД")

T_("exceeded maximum number of players")
deDE("Maximale Anzahl der Spieler überschritten")
esES("")
frFR("")
itIT("Superato il massimo numero di giocatori")
ptPT("")
ruRU("Кол-во игроков максимальное.")


// FilterDB.cpp

T_("File Filter")
deDE("Datei-Filter")
esES("")
frFR("")
itIT("Filtro del file")
ptPT("")
ruRU("Фильтр Файла")

T_("The default FIDE filter was not found. & Please set it to retrieve the "
     "players")
deDE("")
esES("")
frFR("")
itIT("Il filtro FIDE non è stato trovato.&Inseriscilo per caricare i giocatori")
ptPT("")
ruRU("")


// Rankgroup.cpp

T_("Rated Player Group at round ")
deDE("")
esES("")
frFR("")
itIT("Classifica per gruppi al turno ")
ptPT("")
ruRU("")


// ImproveColors.cpp

T_("Please select two players")
deDE("Bitte wählen Sie zwei Spieler")
esES("")
frFR("")
itIT("Seleziona due giocatori")
ptPT("")
ruRU("Выбирете двух игроков")

T_("The selected players are compatible")
deDE("Die gewählten Spieler sind kompatibel")
esES("")
frFR("")
itIT("I giocatori selezionati sono compatibili")
ptPT("")
ruRU("Выбранные игроки совместимы")

T_("The selected players are NON compatible")
deDE("Die gewählten Spieler sind NICHT kompatibel")
esES("")
frFR("")
itIT("I giocatori selezionati NON sono compatibili")
ptPT("")
ruRU("Выбранные игроки несовместимы")

T_("FORBID!")
deDE("NICHT ERLAUBT!")
esES("")
frFR("")
itIT("Proibito!")
ptPT("")
ruRU("Запрещено!")

T_("Choose two players to exchange")
deDE("Wählen Sie zwei Spieler zum Tausch")
esES("")
frFR("")
itIT("Scegli due giocatori da scambiare")
ptPT("")
ruRU("Выберите двух игроков для обмена")

T_("This exchange is ILLEGAL")
deDE("Dieser Tausch ist nicht erlaubt")
esES("")
frFR("")
itIT("Questo scambio è illegale")
ptPT("")
ruRU("Этот обмен незаконен")


// Newtournament.cpp

T_("Export Tournament")
deDE("Turnier exportieren")
esES("")
frFR("")
itIT("Esporta torneo")
ptPT("")
ruRU("Экспорт. Турнир")

T_("Federation FIDE code")
deDE("FIDE Code")
esES("")
frFR("")
itIT("Codice FIDE")
ptPT("")
ruRU("Код ФИДЕ")

T_("ddmmyyyy for FIDE\nyyyymmdd for USCF")
deDE("ttmmjjjj für FIDE\njjjjmmtt für USCF")
esES("")
frFR("")
itIT("ggmmaaaa per FIDE e FSI\naaaammgg per USCF")
ptPT("")
ruRU("д/м/г для ФИДЕ и FSI\nг/м/д для USCF")

T_("Check it if pairing (swiss system)\nand rating calculation are made with\n"
     "the FIDE rating")
deDE("")
esES("")
frFR("")
itIT("Marca se il torneo è valido\nper le variazioni Elo FIDE")
ptPT("")
ruRU("")

T_("Max 20 rounds for Swiss System\nCalculated by Vega for round robin")
deDE("Maximal 20 Runden für Swiss\nFür Rundenturnier automatisch")
esES("")
frFR("")
itIT("Max 20 turni per il sistema svizzero.\nCalcolato da Vega per il girone "
     "italiano")
ptPT("")
ruRU("Max 20 раундов в Швейц. Системе\nПросчитано "
     "Vega  для круг.турнира")

T_("Selected Tie Breaks")
deDE("Gewählte Tie-Breaks")
esES("")
frFR("")
itIT("Spareggi selezionati")
ptPT("")
ruRU("Выбрать перерывы связи")

T_("Export players in this")
deDE("Exportiere Spieler in")
esES("")
frFR("")
itIT("Esporta giocat. in questo")
ptPT("")
ruRU("Перенести игрока в ")

T_("FIDE")
deDE("FIDE")
esES("")
frFR("")
itIT("FIDE")
ptPT("")
ruRU("ФИДЕ")

T_("National")
deDE("National")
esES("")
frFR("")
itIT("Nazionale")
ptPT("")
ruRU("Нац-сть")

T_("FIDE & Nat")
deDE("FIDE & Nat")
esES("")
frFR("")
itIT("FIDE & Naz")
ptPT("")
ruRU("ФИДЕ & Нац")

T_("rating interval: Min")
deDE("Wertungsintervall: Min")
esES("")
frFR("")
itIT("intervallo Elo: Min")
ptPT("")
ruRU("Рейтинг-интервал: Min")

T_("- Max ")
deDE("- Max ")
esES("")
frFR("")
itIT("- Max ")
ptPT("")
ruRU("- Max ")

T_("Set a name for the tournament")
deDE("Geben Sie einen Namen für das Turnier an")
esES("")
frFR("")
itIT("Inserisci un nome per il torneo")
ptPT("")
ruRU("Указать Название турнира")

T_("Set the place/city of the tournament")
deDE("Geben Sie den Ort/die Stadt des Turniers an")
esES("")
frFR("")
itIT("Inserisci la città del torneo")
ptPT("")
ruRU("Указать место/город проведения турнира")

T_("Set the Federation FIDE code")
deDE("Geben Sie den FIDE Code an")
esES("")
frFR("")
itIT("Inserisci il codice FIDE della federazione")
ptPT("")
ruRU("Указать код Федерации ФИДЕ")

T_("Set the begin date")
deDE("Setzen Sie das Startdatum")
esES("")
frFR("")
itIT("Data di inizio torneo")
ptPT("")
ruRU("Указать дату начало")

T_("Set the end date")
deDE("Setzen Sie das Enddatum")
esES("")
frFR("")
itIT("Data di fine torneo")
ptPT("")
ruRU("Указать дату окончания")

T_("Set the name of the arbiter")
deDE("Geben Sie den Namen des Schiedsrichters an")
esES("")
frFR("")
itIT("Nome dell'arbitro del torneo")
ptPT("")
ruRU("Указать имя арбитра")

T_("You cannot change Play system")
deDE("Sie können das Spielsystem nicht ändern")
esES("")
frFR("")
itIT("Non puoi cambiare il sistema di gioco")
ptPT("")
ruRU("Невозможно изменить систему игры")

T_("Set the tournament directory")
deDE("Setzen Sie das Turnier-Verzeichnis")
esES("")
frFR("")
itIT("Seleziona la cartella del torneo")
ptPT("")
ruRU("Указать справочник турнира")

T_("Set the Tournament File Name")
deDE("Setzen Sie den Namen der Turnierdatei")
esES("")
frFR("")
itIT("Inserisci la sigla del torneo")
ptPT("")
ruRU("Указать название файла турнира")

T_("Change not permitted")
deDE("Ein Ändern ist nicht erlaubt")
esES("")
frFR("")
itIT("Modifica non permessa")
ptPT("")
ruRU("Запрещено Изменение")

T_("Set the rating interval")
deDE("Eingabe des Wertungsintervalls")
esES("")
frFR("")
itIT("Scegli l'intervallo Elo")
ptPT("")
ruRU("Указать интервал рейтинга")

T_("A file with the same name already exist!&Choose another name")
deDE("Eine Datei mit gleichem Namen existiert bereits!&Wählen Sie einen neuen "
     "Namen")
esES("")
frFR("")
itIT("Un file con lo stesso nome esiste!&Scegli un altro nome")
ptPT("")
ruRU("Файл с таким названием уже существует!Выберите "
     "другое")

T_("You have not selected a directory")
deDE("Sie haben kein Verzeichnis ausgewählt")
esES("")
frFR("")
itIT("Non hai selezionato una cartella")
ptPT("")
ruRU("Справочник не выбран")


// RoundRobin.cpp

T_(" Cross Table")
deDE("")
esES("")
frFR("")
itIT(" Tabellone")
ptPT("")
ruRU("")

T_(" Cross Table at round ")
deDE("")
esES("")
frFR("")
itIT(" Tabellone al turno ")
ptPT("")
ruRU("")

T_(" : Round ")
deDE("")
esES("")
frFR("")
itIT(" : Turno ")
ptPT("")
ruRU("")


// ForlanoScoreSystem.cpp

T_("The tournament is not yet started!")
deDE("Das Turnier wurde noch nicht gestartet!")
esES("")
frFR("")
itIT("Il torneo non è iniziato!")
ptPT("")
ruRU("Турнир еще не начат!")

T_("I'm sorry, but I can't process more than 200 players")
deDE("Ich kann leider nicht mehr als 200 Spieler verwalten")
esES("")
frFR("")
itIT("Opzione non disponibile per più di 200 giocatori")
ptPT("")
ruRU("К сожалению система недоступна для более "
     "200 игроков")

T_("Done Missing Point Score System")
deDE("OK, Fehlpunkte-System in mpscorelog.txt gespeichert")
esES("")
frFR("")
itIT("OK sistema dei punti mancanti")
ptPT("")
ruRU("созданна Система нехватки баллов")


// RoundSwiss.cpp

T_("Error while writing .rnd file")
deDE("")
esES("")
frFR("")
itIT("Errore durante la scrittura del file .rnd")
ptPT("")
ruRU("Ошибка при написании.rnd файла")

T_("Do you want to assign the WHITE&to the higher rated players?")
deDE("Soll ich den Spielern mit höherer&Wertung die Farbe Weiß zuordnen?")
esES("")
frFR("")
itIT("Vuoi assegnare il Bianco&al giocatore con l'elo più alto?")
ptPT("")
ruRU("Хотете дать белый цвет игроку у кот. рейтинг "
     "больше?")


// flist.cpp

T_("Out of memory! & I have to close the program :-(")
deDE("Kein Speicher mehr frei! & Das Programm wird beendet :-(")
esES("")
frFR("")
itIT("Memoria finita & Devo terminare il programma :-(")
ptPT("")
ruRU("Закончилась память & Программа должна "
     "быть закрыта :-(")


// swissDubov9.cpp

T_("I cannot do the pairing!&Trying to set all upfloater ON and restart")
deDE("Keine Paarung möglich!&Ich setze alle Upfloater und starte erneut")
esES("")
frFR("")
itIT("Non posso generare l'abbinamento!&Provo a modificare gli upfloater e riparto")
ptPT("")
ruRU("Невозможно создать пары!&Система попытается "
     "изменить upfloater и перезагрузиться")

T_("I cannot do the pairing!&Trying to merge all the groups and restart")
deDE("Keine Paarung möglich!&Ich mische alle Gruppen und starte erneut")
esES("")
frFR("")
itIT("Non posso generare l'abbinamento!&Creo un solo gruppo e riparto")
ptPT("")
ruRU("Невозможно создать пары!&Система попытается "
     "создать группы и перезагрузиться")

T_("The pairing is impossible.&Try a manual pairing")
deDE("Keine automatische Paarung gefunden.&Bitte geben Sie die Paarungen manuell "
     "ein")
esES("")
frFR("")
itIT("L'abbinamento è impossibile!&Prova con uno manuale")
ptPT("")
ruRU("Группирование невозможно!&Попробуй вручную.")


// swissLim6.cpp

T_("Error while writing verbose file")
deDE("Fehler beim Schreiben der Datei verbose.txt")
esES("")
frFR("")
itIT("Errore durante la scrittura del file verbose.txt")
ptPT("")
ruRU("Ошибка во время записи файла с объяснениями")


// ManualPairing.cpp

T_("use CTRL+'up' and CTRL+'down'\nto move the pair up or down")
deDE("CTRL+'hoch' und CTRL+'runter'\nverschieben die Paarung nach oben/unten")
esES("")
frFR("")
itIT("usa CTRL+'su' e CTRL+'giù'\nper modificare l'ordine di scacchiera")
ptPT("")
ruRU("CTRL+'вверх' и CTRL+'вниз'\nдля изменения порядк. "
     "номера стола")

T_("Please fill each ID field")
deDE("Bitte füllen Sie alle ID Felder aus")
esES("")
frFR("")
itIT("Riempi entrambi i capi ID")
ptPT("")
ruRU("Заполните все номера игрока")

T_("Only 1 player of the pair can be the BYE")
deDE("Es ist nur ein Freilos pro Paarung erlaubt")
esES("")
frFR("")
itIT("Solo uno dei due può essere il BYE")
ptPT("")
ruRU("Только один игрок пары может получить "
     "BYE")

T_("The White ID is out of range")
deDE("Die ID von Weiß ist außerhalb des gültigen Bereichs")
esES("")
frFR("")
itIT("L'ID del Bianco è scorretto")
ptPT("")
ruRU("Ошибка в номере играющего белыми")

T_("The Black ID is out of range")
deDE("Die ID von Schwarz ist außerhalb des gültigen Bereichs")
esES("")
frFR("")
itIT("L'ID del Nero è scorretto")
ptPT("")
ruRU("Ошибка в номере играющего черными")

T_("The White player is NOT available")
deDE("Der Spieler für Weiß ist nicht verfügbar")
esES("")
frFR("")
itIT("Il giocatore Bianco non è disponibile")
ptPT("")
ruRU("Играющий белыми недоступен")

T_("The Black player is NOT available")
deDE("Der Spieler für Schwarz ist nicht verfügbar")
esES("")
frFR("")
itIT("Il giocatore Nero non è disponibile")
ptPT("")
ruRU("Играющий черными недоступен")

T_("The selected players are NOT compatible")
deDE("Die ausgewählten Spieler sind nicht kompatibel")
esES("")
frFR("")
itIT("I giocatori inseriti NON sono compatibili")
ptPT("")
ruRU("Выбранные игроки несовместимы ")

T_("The White player has already been paired")
deDE("Der Spieler für Weiß wurde bereits einer Paarung zugewiesen")
esES("")
frFR("")
itIT("Il giocatore bianco è stato già abbinato")
ptPT("")
ruRU("Игрок Играющий белыми уже имеет пару")

T_("The Black player has already been paired")
deDE("Der Spieler für Schwarz wurde bereits einer Paarung zugewiesen")
esES("")
frFR("")
itIT("Il giocatore nero è stato già abbinato")
ptPT("")
ruRU("Игрок Играющий черными уже имеет пару")

T_("File manual pairing (*.man)")
deDE("Speichere manuelle Paarung (*.man)")
esES("")
frFR("")
itIT("File abbinamento manuale (*.man)")
ptPT("")
ruRU("Файл с парами,созданный вручную (*.man)")

T_("Save pairing file (*.man)")
deDE("Speichere Paarungs-Datei (*.man)")
esES("")
frFR("")
itIT("Salva file abbinamento (*.man)")
ptPT("")
ruRU("Сохр.файл с парами (*.man)")

T_("No pair to save")
deDE("Keine Paarung zum Speichern")
esES("")
frFR("")
itIT("Non ci sono coppie da salvare")
ptPT("")
ruRU("Отсутствуют сочитания для сохранения")

T_("You must pair all the available players")
deDE("Sie müssen alle verfügbaren Spieler einer Paarung zuweisen")
esES("")
frFR("")
itIT("Devi inserire tutti i giocatori disponibili")
ptPT("")
ruRU("Должны быть внесены все доступные игроки")


// Fidereport.cpp

T_(" FIDE rating variation at round ")
deDE("")
esES("")
frFR("")
itIT(" Variazioni Elo FIDE al turno ")
ptPT("")
ruRU("")

T_("Enter the tournament ID")
deDE("Geben Sie die Turnier ID ein")
esES("")
frFR("")
itIT("Inserisci l'ID del torneo")
ptPT("")
ruRU("Внести номер турнира")
