TABLE_ (BASE1)
	INT_       (NUMBER1)
	STRING_	   (TEXT1, 200)
	INT_ARRAY_ (A, 5)
	BOOL_      (FLAG)
	BOOL_      (FLAG2)
END_TABLE

TABLE_ (BASE2)
	INT_    (NUMBER2)
	STRING_	(TEXT2, 200)
END_TABLE

TABLE_II_ (TEST, BASE1, BASE2)
	INT_    (NUMBER)
	STRING_	(TEXT, 200)
END_TABLE
