#ifndef _SDLFb_Keys_h_
#define _SDLFb_Keys_h_
K_BACK       = SDLK_BACKSPACE + K_DELTA,
K_BACKSPACE  = SDLK_BACKSPACE + K_DELTA,

K_TAB        = SDLK_TAB,

K_SPACE      = SDLK_SPACE,

K_RETURN     = SDLK_RETURN,
K_ENTER      = K_RETURN,

K_SHIFT_KEY  = SDLK_LSHIFT + K_DELTA,
K_CTRL_KEY   = SDLK_LCTRL + K_DELTA,
K_ALT_KEY    = SDLK_LALT + K_DELTA,
K_CAPSLOCK   = SDLK_CAPSLOCK + K_DELTA,
K_ESCAPE     = SDLK_ESCAPE + K_DELTA,
K_PRIOR      = SDLK_PAGEUP + K_DELTA,
K_PAGEUP     = SDLK_PAGEUP + K_DELTA,
K_NEXT       = SDLK_PAGEDOWN + K_DELTA,
K_PAGEDOWN   = SDLK_PAGEDOWN + K_DELTA,
K_END        = SDLK_END + K_DELTA,
K_HOME       = SDLK_HOME + K_DELTA,
K_LEFT       = SDLK_LEFT + K_DELTA,
K_UP         = SDLK_UP + K_DELTA,
K_RIGHT      = SDLK_RIGHT + K_DELTA,
K_DOWN       = SDLK_DOWN + K_DELTA,
K_INSERT     = SDLK_INSERT + K_DELTA,
K_DELETE     = SDLK_DELETE + K_DELTA,

K_NUMPAD0    = SDLK_KP0 + K_DELTA,
K_NUMPAD1    = SDLK_KP1 + K_DELTA,
K_NUMPAD2    = SDLK_KP2 + K_DELTA,
K_NUMPAD3    = SDLK_KP3 + K_DELTA,
K_NUMPAD4    = SDLK_KP4 + K_DELTA,
K_NUMPAD5    = SDLK_KP5 + K_DELTA,
K_NUMPAD6    = SDLK_KP6 + K_DELTA,
K_NUMPAD7    = SDLK_KP7 + K_DELTA,
K_NUMPAD8    = SDLK_KP8 + K_DELTA,
K_NUMPAD9    = SDLK_KP9 + K_DELTA,
K_MULTIPLY   = SDLK_KP_MULTIPLY + K_DELTA,
K_ADD        = SDLK_KP_PLUS + K_DELTA,
K_SEPARATOR  = SDLK_KP_PERIOD + K_DELTA,
K_SUBTRACT   = SDLK_KP_MINUS + K_DELTA,
K_DECIMAL    = SDLK_KP_PERIOD + K_DELTA,
K_DIVIDE     = SDLK_KP_DIVIDE + K_DELTA,
K_SCROLL     = SDLK_SCROLLOCK + K_DELTA,

K_F1         = SDLK_F1 + K_DELTA,
K_F2         = SDLK_F2 + K_DELTA,
K_F3         = SDLK_F3 + K_DELTA,
K_F4         = SDLK_F4 + K_DELTA,
K_F5         = SDLK_F5 + K_DELTA,
K_F6         = SDLK_F6 + K_DELTA,
K_F7         = SDLK_F7 + K_DELTA,
K_F8         = SDLK_F8 + K_DELTA,
K_F9         = SDLK_F9 + K_DELTA,
K_F10        = SDLK_F10 + K_DELTA,
K_F11        = SDLK_F11 + K_DELTA,
K_F12        = SDLK_F12 + K_DELTA,

K_A          = 'A' + K_DELTA,
K_B          = 'B' + K_DELTA,
K_C          = 'C' + K_DELTA,
K_D          = 'D' + K_DELTA,
K_E          = 'E' + K_DELTA,
K_F          = 'F' + K_DELTA,
K_G          = 'G' + K_DELTA,
K_H          = 'H' + K_DELTA,
K_I          = 'I' + K_DELTA,
K_J          = 'J' + K_DELTA,
K_K          = 'K' + K_DELTA,
K_L          = 'L' + K_DELTA,
K_M          = 'M' + K_DELTA,
K_N          = 'N' + K_DELTA,
K_O          = 'O' + K_DELTA,
K_P          = 'P' + K_DELTA,
K_Q          = 'Q' + K_DELTA,
K_R          = 'R' + K_DELTA,
K_S          = 'S' + K_DELTA,
K_T          = 'T' + K_DELTA,
K_U          = 'U' + K_DELTA,
K_V          = 'V' + K_DELTA,
K_W          = 'W' + K_DELTA,
K_X          = 'X' + K_DELTA,
K_Y          = 'Y' + K_DELTA,
K_Z          = 'Z' + K_DELTA,
K_0          = '0' + K_DELTA,
K_1          = '1' + K_DELTA,
K_2          = '2' + K_DELTA,
K_3          = '3' + K_DELTA,
K_4          = '4' + K_DELTA,
K_5          = '5' + K_DELTA,
K_6          = '6' + K_DELTA,
K_7          = '7' + K_DELTA,
K_8          = '8' + K_DELTA,
K_9          = '9' + K_DELTA,

K_CTRL_LBRACKET  = K_CTRL|219|K_DELTA,
K_CTRL_RBRACKET  = K_CTRL|221|K_DELTA,
K_CTRL_MINUS     = K_CTRL|0xbd|K_DELTA,
K_CTRL_GRAVE     = K_CTRL|0xc0|K_DELTA,
K_CTRL_SLASH     = K_CTRL|0xbf|K_DELTA,
K_CTRL_BACKSLASH = K_CTRL|0xdc|K_DELTA,
K_CTRL_COMMA     = K_CTRL|0xbc|K_DELTA,
K_CTRL_PERIOD    = K_CTRL|0xbe|K_DELTA,
K_CTRL_SEMICOLON = K_CTRL|0xbe|K_DELTA,
K_CTRL_EQUAL     = K_CTRL|0xbb|K_DELTA,
K_CTRL_APOSTROPHE= K_CTRL|0xde|K_DELTA,

K_BREAK      = SDLK_BREAK + K_DELTA,

#endif
