#ifndef _SDLFb_Keys_h_
#define _SDLFb_Keys_h_
K_BACK       = SDLK_BACKSPACE + K_DELTA,
K_BACKSPACE  = SDLK_BACKSPACE + K_DELTA,

//handled extra in fbKEYtoK
K_TAB        = 9, //SDLK_TAB,

K_SPACE      = 32, //SDLK_SPACE,

K_RETURN     = 13, //SDLK_RETURN,
K_ENTER      = K_RETURN,

K_SHIFT_KEY  = SDLK_LSHIFT + K_DELTA,
K_CTRL_KEY   = SDLK_LCTRL + K_DELTA,
K_ALT_KEY    = SDLK_LALT + K_DELTA,
K_CAPSLOCK   = SDLK_CAPSLOCK + K_DELTA,
K_ESCAPE     = SDLK_ESCAPE + K_DELTA,
K_PRIOR      = SDLK_PAGEUP + K_DELTA,
K_PAGEUP     = SDLK_PAGEUP + K_DELTA,
K_NEXT       = SDLK_PAGEDOWN + K_DELTA,
K_PAGEDOWN   = SDLK_PAGEDOWN + K_DELTA,
K_END        = SDLK_END + K_DELTA,
K_HOME       = SDLK_HOME + K_DELTA,
K_LEFT       = SDLK_LEFT + K_DELTA,
K_UP         = SDLK_UP + K_DELTA,
K_RIGHT      = SDLK_RIGHT + K_DELTA,
K_DOWN       = SDLK_DOWN + K_DELTA,
K_INSERT     = SDLK_INSERT + K_DELTA,
K_DELETE     = SDLK_DELETE + K_DELTA,

K_NUMPAD0    = SDLK_KP0 + K_DELTA,
K_NUMPAD1    = SDLK_KP1 + K_DELTA,
K_NUMPAD2    = SDLK_KP2 + K_DELTA,
K_NUMPAD3    = SDLK_KP3 + K_DELTA,
K_NUMPAD4    = SDLK_KP4 + K_DELTA,
K_NUMPAD5    = SDLK_KP5 + K_DELTA,
K_NUMPAD6    = SDLK_KP6 + K_DELTA,
K_NUMPAD7    = SDLK_KP7 + K_DELTA,
K_NUMPAD8    = SDLK_KP8 + K_DELTA,
K_NUMPAD9    = SDLK_KP9 + K_DELTA,
K_MULTIPLY   = SDLK_KP_MULTIPLY + K_DELTA,
K_ADD        = SDLK_KP_PLUS + K_DELTA,
K_SEPARATOR  = SDLK_KP_PERIOD + K_DELTA,
K_SUBTRACT   = SDLK_KP_MINUS + K_DELTA,
K_DECIMAL    = SDLK_KP_PERIOD + K_DELTA,
K_DIVIDE     = SDLK_KP_DIVIDE + K_DELTA,
K_SCROLL     = SDLK_SCROLLOCK + K_DELTA,

K_F1         = SDLK_F1 + K_DELTA,
K_F2         = SDLK_F2 + K_DELTA,
K_F3         = SDLK_F3 + K_DELTA,
K_F4         = SDLK_F4 + K_DELTA,
K_F5         = SDLK_F5 + K_DELTA,
K_F6         = SDLK_F6 + K_DELTA,
K_F7         = SDLK_F7 + K_DELTA,
K_F8         = SDLK_F8 + K_DELTA,
K_F9         = SDLK_F9 + K_DELTA,
K_F10        = SDLK_F10 + K_DELTA,
K_F11        = SDLK_F11 + K_DELTA,
K_F12        = SDLK_F12 + K_DELTA,

K_A          = SDLK_a + K_DELTA,
K_B          = SDLK_b + K_DELTA,
K_C          = SDLK_c + K_DELTA,
K_D          = SDLK_d + K_DELTA,
K_E          = SDLK_e + K_DELTA,
K_F          = SDLK_f + K_DELTA,
K_G          = SDLK_g + K_DELTA,
K_H          = SDLK_h + K_DELTA,
K_I          = SDLK_i + K_DELTA,
K_J          = SDLK_j + K_DELTA,
K_K          = SDLK_k + K_DELTA,
K_L          = SDLK_l + K_DELTA,
K_M          = SDLK_m + K_DELTA,
K_N          = SDLK_n + K_DELTA,
K_O          = SDLK_o + K_DELTA,
K_P          = SDLK_p + K_DELTA,
K_Q          = SDLK_q + K_DELTA,
K_R          = SDLK_r + K_DELTA,
K_S          = SDLK_s + K_DELTA,
K_T          = SDLK_t + K_DELTA,
K_U          = SDLK_u + K_DELTA,
K_V          = SDLK_v + K_DELTA,
K_W          = SDLK_w + K_DELTA,
K_X          = SDLK_x + K_DELTA,
K_Y          = SDLK_y + K_DELTA,
K_Z          = SDLK_z + K_DELTA,
K_0          = SDLK_0 + K_DELTA,
K_1          = SDLK_1 + K_DELTA,
K_2          = SDLK_2 + K_DELTA,
K_3          = SDLK_3 + K_DELTA,
K_4          = SDLK_4 + K_DELTA,
K_5          = SDLK_5 + K_DELTA,
K_6          = SDLK_6 + K_DELTA,
K_7          = SDLK_7 + K_DELTA,
K_8          = SDLK_8 + K_DELTA,
K_9          = SDLK_9 + K_DELTA,

K_CTRL_LBRACKET  = K_CTRL|219|K_DELTA,
K_CTRL_RBRACKET  = K_CTRL|221|K_DELTA,
K_CTRL_MINUS     = K_CTRL|0xbd|K_DELTA,
K_CTRL_GRAVE     = K_CTRL|0xc0|K_DELTA,
K_CTRL_SLASH     = K_CTRL|0xbf|K_DELTA,
K_CTRL_BACKSLASH = K_CTRL|0xdc|K_DELTA,
K_CTRL_COMMA     = K_CTRL|0xbc|K_DELTA,
K_CTRL_PERIOD    = K_CTRL|0xbe|K_DELTA,
K_CTRL_SEMICOLON = K_CTRL|0xbe|K_DELTA,
K_CTRL_EQUAL     = K_CTRL|0xbb|K_DELTA,
K_CTRL_APOSTROPHE= K_CTRL|0xde|K_DELTA,

K_BREAK      = SDLK_BREAK + K_DELTA,

#endif
