#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// Editor.cpp

T_("Units")
csCZ("Jednotky")
deDE("Einheiten")
esES("Unidades")
fiFI("Yksiköt")
frFR("Unités")
huHU("Egységek")
itIT("Unit�")
nlNL("Eenheden")
plPL("Jednostki")
roRO("Unități")
ruRU("Единицы")
skSK("Jednotky")
srSP("Jedinice")
trTR("Birimler")
zhCN("单位")
zhTW("單位")

T_("%d%% of width")
csCZ("%d%% šířky")
deDE("%d%% der Breite")
esES("%d%% de ancho")
fiFI("%d%% leveydestä")
frFR("%d%% de la largeur")
huHU("%d%% szélesség")
itIT("%d%% di larghezza")
nlNL("%d%% van breedte")
plPL("%d%% szerokości")
roRO("%d%% din lățime")
ruRU("%d%% длинны")
skSK("%d%% šírky")
srSP("%d%% širine")
trTR("%d%%")
zhCN("宽的%d%%")
zhTW("寬的%d%%")

T_("None")
csCZ("Není")
deDE("Ohne")
esES("Ninguno")
fiFI("Ei mitään")
frFR("Aucun")
huHU("Semmi")
itIT("Nulla")
nlNL("Geen")
plPL("Brak")
roRO("Nimic")
ruRU("Нет")
skSK("Nie je")
srSP("NIšta")
trTR("Hiçbiri")
zhCN("无")
zhTW("無")

T_("Hyperlink")
csCZ("Propojení")
deDE("Hyperlink")
esES("Hyperlink")
fiFI("Hyperlinkki")
frFR("Hyperlien")
huHU("Hiperhivatkozás")
itIT("Collegamento")
nlNL("Hyperlink")
plPL("Odnośnik")
roRO("Hiperlegătură")
ruRU("Ссылка")
skSK("Prepojenie")
srSP("Hiperveza")
trTR("Hiperlink")
zhCN("超级链接")
zhTW("超連結")

T_("Paragraph label")
csCZ("Návěští odstavce")
deDE("Absatzmarke")
esES("Etiqueta de p�rrafo")
fiFI("Kappaleen otsake")
frFR("Marque de paragraphe")
huHU("Bekezdéscímke")
itIT("Etichetta paragrafo")
nlNL("Paragraaf etiket")
plPL("Etykieta paragrafu")
roRO("Etichetă paragraf")
ruRU("Метка параграфа")
skSK("Návestia odstavca")
srSP("Labela paragrafa")
trTR("Paragraf etiketi")
zhCN("段标")
zhTW("段落標籤")

T_("Label")
csCZ("Návěští")
deDE("Absatz")
esES("Etiqueta")
fiFI("Merkintä")
frFR("Marque")
huHU("Címke")
itIT("Etichetta")
nlNL("Etiket")
plPL("Etykieta")
roRO("Etichetă")
ruRU("Метка")
skSK("Návestie")
srSP("Labela")
trTR("Etiket")
zhCN("标签")
zhTW("標籤")

T_("Store as style")
csCZ("Uložit jako styl")
deDE("Als Stil speichern")
esES("Guardar como estilo")
fiFI("Tallenna tyylinä")
frFR("Enregistrer comme style")
huHU("Tárolás stílusként")
itIT("Salva come stile")
nlNL("Bewaar als stijl")
plPL("Zapisz jako styl")
roRO("Salvează ca stil")
ruRU("Сохранить как стиль")
skSK("Uložiť ako štýl")
srSP("Sačuvaj kao stil")
trTR("Stil olarak sakla")
zhCN("存为类型")
zhTW("存為樣式")

T_("Style manager")
csCZ("Styly")
deDE("Stilmanager")
esES("Gestor de estilo")
fiFI("Tyylimanageri")
frFR("Gestionnaire de styles")
huHU("Stíluskezelő")
itIT("Manager stili")
nlNL("Stijl manager ")
plPL("Menadżer styli")
roRO("Manager de stiluri")
ruRU("Менеджер стилей")
skSK("Štýly")
srSP("Menadžer stilova")
trTR("Stil yöneticisi")
zhCN("类型管理器")
zhTW("樣式管理器")

T_("Style")
csCZ("Styl")
deDE("Stil")
esES("Estilo")
fiFI("Tyyli")
frFR("Style")
huHU("Stílus")
itIT("Stile")
nlNL("Stijl")
plPL("Styl")
roRO("Stil")
ruRU("Стиль")
skSK("Štýl")
srSP("Stil")
trTR("Stil")
zhCN("类型")
zhTW("樣式")

T_("Font face")
csCZ("Písmo")
deDE("Schriftart")
esES("Tipo de fuente")
fiFI("Kirjasinlaji")
frFR("Police")
huHU("Font jelleg")
itIT("Tipo carattere")
nlNL("Lettertype gezicht")
plPL("Czcionka")
roRO("Nume font")
ruRU("Шрифт")
skSK("Písmo")
srSP("Izgled fonta")
trTR("Yazı tipi")
zhCN("Font face")
zhTW("字型")

T_("Language")
csCZ("Jazyk")
deDE("Sprache")
esES("Idioma")
fiFI("Kieli")
frFR("Langue")
huHU("Nyelv")
itIT("Lingua")
nlNL("Taal")
plPL("Język")
roRO("Limbă")
ruRU("Язык")
skSK("Jazyk")
srSP("Jezik")
trTR("Dil")
zhCN("语言")
zhTW("語言")

T_("Font height")
csCZ("Výška písma")
deDE("Schriftgrad")
esES("Altura de fuente")
fiFI("Kirjasinkorkeus")
frFR("Taille de police")
huHU("Font magasság")
itIT("Altezza carattere")
nlNL("Lettertype hoogte")
plPL("Wysokość czcionki")
roRO("Înalțime font")
ruRU("Высота шрифта")
skSK("Výška písma")
srSP("Visina fonta")
trTR("Yazı tipi boyutu")
zhCN("字体高度")
zhTW("字型大小")

T_("Go to label")
csCZ("Přejít na návěští")
deDE("Gehe zu Marke")
esES("Ir a etiqueta")
fiFI("Siirry merkintään")
frFR("Aller à la marque")
huHU("Ugrás a címkéhez")
itIT("Vai ad etichetta")
nlNL("Ga naar etiket")
plPL("Idź do etykiety")
roRO("Salt la eticheta")
ruRU("Перейти к метке")
skSK("Prejsť na návestie")
srSP("Idi na labelu")
trTR("Etikete git")
zhCN("转到标签")
zhTW("轉到標籤")

T_("Go to index entry")
csCZ("Přejít na rejstříkový odkaz")
deDE("Gehe zu Indexeintrag")
esES("Ir a �ndice de etiqueta")
fiFI("Siirry hakusanaan")
frFR("Aller à la marque d'index")
huHU("Ugrás a belépés mutatóhoz")
itIT("")
nlNL("Ga naar index ingang")
plPL("Przejdź do indeksu")
roRO("Salt la index entitate")
ruRU("Перейти к точке входа")
skSK("Prejsť na registrový odkaz")
srSP("Idi na indeks ulaza")
trTR("Dizin girdisine git")
zhCN("转到索引项")
zhTW("轉到索引項")

T_("Text color")
csCZ("Barva textu")
deDE("Textfarbe")
esES("Color de texto")
fiFI("Tekstin väri")
frFR("Couleur du texte")
huHU("Szövegszín")
itIT("Colore testo")
nlNL("Tekst kleur")
plPL("Kolor tekstu")
roRO("Culoare text")
ruRU("Цвет текста")
skSK("Farba textu")
srSP("Boja teksta")
trTR("Yazı rengi")
zhCN("文本颜色")
zhTW("文字顏色")

T_("Background color")
csCZ("Barva pozadí")
deDE("Hintergrundfarbe")
esES("Color de fondo")
fiFI("Taustaväri")
frFR("Couleur d'arrière plan")
huHU("Háttérszín")
itIT("Colore sfondo")
nlNL("Achtergrond kleur")
plPL("Kolor tła")
roRO("Culoare fundal")
ruRU("Цвет фона")
skSK("Farba pozadia")
srSP("Pozadinska boja")
trTR("Arkaplan rengi")
zhCN("背景颜色")
zhTW("背景顏色")

T_("Find / Replace")
csCZ("Vyhledat / Nahradit")
deDE("Suchen / Ersetzen")
esES("Buscar / Reemplazar")
fiFI("Etsi / Korvaa")
frFR("Rechercher / Remplacer")
huHU("Keresés / Csere")
itIT("Trova / Sostituisci")
nlNL("Zoek / Vervang")
plPL("Znajdź / Zamień")
roRO("Găsește / Înlocuiește")
ruRU("Найти / Заменить")
skSK("Vyhľadať / Nahradiť")
srSP("Pronađi / Zameni")
trTR("Bul / Değiştir")
zhCN("查找/替换")
zhTW("尋找/取代")


// Mouse.cpp

T_("Object position..")
csCZ("Pozice objektu..")
deDE("Objektposition ...")
esES("Posici�n de objeto..")
fiFI("Kohteen sijainti..")
frFR("Position de l'objet")
huHU("Objektum pozíció..")
itIT("Posizione oggetto..")
nlNL("Object positie..")
plPL("Pozycja obiektu..")
roRO("Poziție obiect..")
ruRU("Позиция объекта...")
skSK("Pozícia objektu..")
srSP("Pozicija objekta..")
trTR("Nesne konumu...")
zhCN("对象位置..")
zhTW("物件位置..")

T_("3 pt up")
csCZ("3 body nahoru")
deDE("3 pt hoch")
esES("3 pt arriba")
fiFI("3 pt ylös")
frFR("3 points vers le haut")
huHU("3 pont fel")
itIT("3 pt su")
nlNL("3 pt omhoog")
plPL("3 pt w górę")
roRO("3 pt sus")
ruRU("на 3 pt больше")
skSK("3 body hore")
srSP("3 pt na gore")
trTR("3 punto yukarı")
zhCN("3 pt up")
zhTW("3 pt up")

T_("2 pt up")
csCZ("2 body nahoru")
deDE("2 pt hoch")
esES("2 pt arriba")
fiFI("2 pt ylös")
frFR("2 points vers le haut")
huHU("2 pont fel")
itIT("2 pt su")
nlNL("2 pt omhoog")
plPL("2 pt w dół")
roRO("2 pt sus")
ruRU("на 2 pt больше")
skSK("2 body hore")
srSP("2 pt na gore")
trTR("2 punto yukarı")
zhCN("2 pt up")
zhTW("2 pt up")

T_("1 pt up")
csCZ("1 bod nahoru")
deDE("1 pt hoch")
esES("1 pt arriba")
fiFI("1 pt ylös")
frFR("1 point vers le haut")
huHU("1 pont fel")
itIT("1 pt su")
nlNL("1 pt omhoog")
plPL("1 pt w górę")
roRO("1 pt sus")
ruRU("на 1 pt больше")
skSK("3 body hore")
srSP("1 pt na gore")
trTR("1 punto yukarı")
zhCN("1 pt up")
zhTW("1 pt up")

T_("Baseline")
csCZ("Základní pozice")
deDE("Schriftlinie")
esES("L�nea de base")
fiFI("Perusviiva")
frFR("Ligne de base")
huHU("Alapvonal")
itIT("Normale")
nlNL("Basislijn")
plPL("Linia bazowa")
roRO("Aliniat la bază")
ruRU("Базовая линия")
skSK("Základná pozícia")
srSP("Osnovna linija")
trTR("Taban çizgisi")
zhCN("基线")
zhTW("基線")

T_("1 pt down")
csCZ("1 bod dolů")
deDE("1 pt runter")
esES("1 pt abajo")
fiFI("1 pt alas")
frFR("1 point vers le bas")
huHU("1 pont le")
itIT("1 pt gi�")
nlNL("1 pt omlaag")
plPL("1 pt w dół")
roRO("1 pt jos")
ruRU("на 1 pt меньше")
skSK("1 bod dole")
srSP("1 pt na dole")
trTR("1 punto aşağı")
zhCN("1 pt down")
zhTW("1 pt down")

T_("2 pt down")
csCZ("2 body dolů")
deDE("2 pt runter")
esES("2 pt abajo")
fiFI("2 pt alas")
frFR("2 points vers le bas")
huHU("2 pont le")
itIT("2 pt gi�")
nlNL("2 pt omlaag")
plPL("2 pt w dół")
roRO("2 pt jos")
ruRU("на 2 pt меньше")
skSK("2 body dole")
srSP("2 pt na dole")
trTR("2 punto aşağı")
zhCN("2 pt down")
zhTW("2 pt down")

T_("3 pt down")
csCZ("3 body dolů")
deDE("3 pt runter")
esES("3 pt abajo")
fiFI("3 pt alas")
frFR("3 points vers le bas")
huHU("3 pont le")
itIT("3 pt gi�")
nlNL("3 pt omlaag")
plPL("3 pt w dół")
roRO("3 pt jos")
ruRU("на 3 pt меньше")
skSK("3 body dole")
srSP("3 pt na dole")
trTR("3 punto aşağı")
zhCN("3 pt down")
zhTW("3 pt down")

T_("Add to user dictionary")
csCZ("Přidat do uživatelského slovníku")
deDE("Zum Benutzerwörterbuch hinzufügen")
esES("A�adir a diccionario de usuario")
fiFI("Lisää käyttäjän sanastoon")
frFR("Ajouter au dictionnaire utilisateur")
huHU("Hozzáadás a felhasználó mappájához")
itIT("Aggiungi al dizionario")
nlNL("Toevoegen aan gebruikers woordenboek")
plPL("Dodaj do słownika użytkownika")
roRO("Adaugă la dicționarul utilizatorului")
ruRU("Добавить в словарь пользователя")
skSK("Pridať do uživateľského slovníka")
srSP("Dodaj u korisnički rečnik")
trTR("Kullanıcı sözlüğüne ekle")
zhCN("添加到用户词典")
zhTW("增加到使用者字典")


// Formating.cpp

T_("Index Entry")
csCZ("Rejstříkový Odkaz")
deDE("Indexeintrag")
esES("�ndice de etiqueta")
fiFI("Hakusana")
frFR("Marque d'index")
huHU("Belépés mutató")
itIT("")
nlNL("Index Ingang")
plPL("Index")
roRO("Index entitate")
ruRU("Точка входа")
skSK("Registrový Odkaz")
srSP("Indeks ulaza")
trTR("Dizin girdisi")
zhCN("索引项")
zhTW("索引項")

T_("Index entry")
csCZ("Resjtříkový odkaz")
deDE("Indexeintrag")
esES("Entrada de �ndice")
fiFI("Hakusana")
frFR("Marque l'index")
huHU("Belépés mutató")
itIT("")
nlNL("Index ingang")
plPL("Indeks")
roRO("Index entitate")
ruRU("Точка входа")
skSK("Registrový odkaz")
srSP("Indeks ulaza")
trTR("Dizin girdisi")
zhCN("索引项")
zhTW("索引項")

T_("Left")
csCZ("Vlevo")
deDE("Links")
esES("Izquierda")
fiFI("Vasen")
frFR("Gauche")
huHU("Bal")
itIT("Sinistra")
nlNL("Links")
plPL("Do lewej")
roRO("Stânga")
ruRU("Влево")
skSK("Vľavo")
srSP("Levo")
trTR("Sol")
zhCN("左")
zhTW("左")

T_("Right")
csCZ("Vpravo")
deDE("Rechts")
esES("Derecha")
fiFI("Oikea")
frFR("Droite")
huHU("Jobb")
itIT("Destra")
nlNL("Rechts")
plPL("Do prawej")
roRO("Dreapta")
ruRU("Вправо")
skSK("Vpravo")
srSP("Desno")
trTR("Sağ")
zhCN("右")
zhTW("右")

T_("Center")
csCZ("Na střed")
deDE("Mitte")
esES("Centro")
fiFI("Keskikohta")
frFR("Centrer")
huHU("Közép")
itIT("Centro")
nlNL("Centraal")
plPL("Wyśrodkowany")
roRO("Centru")
ruRU("По центру")
skSK("Na stred")
srSP("Na sredini")
trTR("Orta")
zhCN("中")
zhTW("中")

T_("No fill")
csCZ("Bez výplně")
deDE("Kein Füllzeichen")
esES("No rellenar")
fiFI("Ei täyttöä")
frFR("Ne pas remplir")
huHU("Nincs kitöltés")
itIT("Nessuno riempimento")
nlNL("Geen vulling")
plPL("Bez wypełnienia")
roRO("Fără umplutură")
ruRU("Без заливки")
skSK("Bez výplne")
srSP("Bez ispune")
trTR("Doldurma")
zhCN("无填充")
zhTW("無填滿")

T_("Fill with ....")
csCZ("Vyplnit ....")
deDE("Füllen mit ....")
esES("Rellenar con ....")
fiFI("Täytä käyttäen ....")
frFR("Remplir avec ....")
huHU("Kitöltés ....")
itIT("Riempi con ....")
nlNL("Vul met ....")
plPL("Wypełnij ....")
roRO("Umple cu ....")
ruRU("Залить ....")
skSK("Vyplniť ....")
srSP("Ispuni sa ....")
trTR(".... ile doldur")
zhCN("填充为 ....")
zhTW("填滿為 ....")

T_("Fill with ----")
csCZ("Vyplnit ----")
deDE("Füllen mit ----")
esES("Rellenar con ----")
fiFI("Täytä käyttäen ----")
frFR("Remplir avec ----")
huHU("Kitöltés ----")
itIT("Riempi con ----")
nlNL("Vul met ----")
plPL("Wypełnij ----")
roRO("Umple cu ----")
ruRU("Залить ----")
skSK("Vyplniť ----")
srSP("Ispuni sa ----")
trTR("---- ile doldur")
zhCN("填充为 ----")
zhTW("填滿為 ----")

T_("Fill with __")
csCZ("Vyplnit __")
deDE("Füllen mit ____")
esES("Rellenar con __")
fiFI("Täytä käyttäen __")
frFR("Remplir avec __")
huHU("Kitöltés __")
itIT("Riempi con __")
nlNL("Vul met __")
plPL("Wypełnij __")
roRO("Umple cu __")
ruRU("Залить __")
skSK("Vyplniť __")
srSP("Ispuni sa __")
trTR("__ ile doldur")
zhCN("填充为 __")
zhTW("填滿為 __")

T_("Remove")
csCZ("Odstranit")
deDE("Entfernen")
esES("Eliminar")
fiFI("Poista")
frFR("Eliminer")
huHU("Eltávolítás")
itIT("Elimina")
nlNL("Verwijderen")
plPL("Usuń")
roRO("Înlătură")
ruRU("Удалить")
skSK("Odstrániť")
srSP("Uklonu")
trTR("Kaldır")
zhCN("删除")
zhTW("移除")

T_("Object position")
csCZ("Pozice objektu")
deDE("Objektposition")
esES("Posici�n de objeto")
fiFI("Kohteen sijainti")
frFR("Position de l'objet")
huHU("Objektum pozíció")
itIT("Posizione oggetto")
nlNL("Object positie")
plPL("Pozycja obiektu")
roRO("Poziție obiect")
ruRU("Позиция объекта")
skSK("Pozícia objektu")
srSP("Pozicija objekta")
trTR("Nesne konumu")
zhCN("对象位置")
zhTW("物件位置")


// FormatDlg.cpp

T_("Centered")
csCZ("Uprostřed")
deDE("Zentriert")
esES("Centrado")
fiFI("Keskitetty")
frFR("Centré")
huHU("Középre zárt")
itIT("Centrato")
nlNL("Gëcentreerd")
plPL("Wyśrodkowany")
roRO("Centrat")
ruRU("Центрованный")
skSK("Uprostred")
srSP("Centrirano")
trTR("Ortalanmış")
zhCN("居中")
zhTW("置中")

T_("....")
csCZ("....")
deDE("....")
esES("....")
fiFI("....")
frFR("....")
huHU("....")
itIT("....")
nlNL("....")
plPL("....")
roRO("....")
ruRU("")
skSK("....")
srSP("....")
trTR("....")
zhCN("....")
zhTW("....")

T_("----")
csCZ("----")
deDE("----")
esES("----")
fiFI("----")
frFR("----")
huHU("----")
itIT("----")
nlNL("----")
plPL("----")
roRO("----")
ruRU("")
skSK("----")
srSP("----")
trTR("----")
zhCN("----")
zhTW("----")

T_("__")
csCZ("__")
deDE("____")
esES("__")
fiFI("__")
frFR("__")
huHU("__")
itIT("__")
nlNL("__")
plPL("__")
roRO("__")
ruRU("")
skSK("__")
srSP("__")
trTR("__")
zhCN("__")
zhTW("__")

T_("Tab position")
csCZ("Pozice tabelace")
deDE("Tabulatorposition")
esES("Posici�n de tabulador")
fiFI("Tabulaattori positio")
frFR("Position de tabulation")
huHU("Tabulátor pozíció")
itIT("Posizione tabulatore")
nlNL("Tabblad positie")
plPL("Pozycja")
roRO("Poziție tab")
ruRU("Позиция табуляции")
skSK("Pozícia tabelátora")
srSP("Pozicija tabulatora")
trTR("Sekme konumu")
zhCN("Tab位置")
zhTW("Tab位置")

T_("Type")
csCZ("Typ")
deDE("Typ")
esES("Tipo")
fiFI("Tyyppi")
frFR("Type")
huHU("Típus")
itIT("Tipo")
nlNL("Type")
plPL("Wyrównanie")
roRO("Tip")
ruRU("Тип")
skSK("Typ")
srSP("Tip")
trTR("Tip")
zhCN("类型")
zhTW("類型")

T_("Fill")
csCZ("Výplň")
deDE("Füllen")
esES("Rellenar")
fiFI("Täytä")
frFR("Remplir")
huHU("Kitöltés")
itIT("Riempi")
nlNL("Vul")
plPL("Wypełnienie")
roRO("Umplutură")
ruRU("Заливка")
skSK("Výplň")
srSP("Ispuni")
trTR("Doldur")
zhCN("填充")
zhTW("填滿")

T_("Create new style..")
csCZ("Vytvořit nový styl..")
deDE("Neuen Stil erstellen ...")
esES("Crear nuevo estilo..")
fiFI("Luo uusi tyyli...")
frFR("Créer un nouveau style..")
huHU("Új stílus létrehozása")
itIT("Crea nuovo stile..")
nlNL("Creëer nieuwe stijl..")
plPL("Utwórz nowy styl..")
roRO("Crează stil nou..")
ruRU("Создать новый стиль..")
skSK("Vytvoriť nový štýl..")
srSP("Napravi novi stil..")
trTR("Yeni stil oluştur...")
zhCN("创建新类型")
zhTW("建立新樣式..")

T_("Remove style")
csCZ("Odstranit styl")
deDE("Stil entfernen")
esES("Eliminar estilo")
fiFI("Poista tyyli")
frFR("Supprimer le style")
huHU("Stílus eltávolítása")
itIT("Rimuovi stile")
nlNL("Verwijder stijl")
plPL("Usuń styl")
roRO("Șterge stil")
ruRU("Удалить стиль")
skSK("Odstrániť štýl")
srSP("Ukloni stil")
trTR("Stili sil")
zhCN("删除类型")
zhTW("移除樣式")

T_("Rename..")
csCZ("Přejmenovat..")
deDE("Umbenennen ...")
esES("Renombrar..")
fiFI("Nimeä uudelleen...")
frFR("Renommer..")
huHU("Átnevezés")
itIT("Rinomina..")
nlNL("Hernoem..")
plPL("Zmień nazwę..")
roRO("Redenumește..")
ruRU("Переименовать..")
skSK("Premenovať..")
srSP("Preimenuj..")
trTR("Yeniden adlandır...")
zhCN("重命名")
zhTW("重新命名..")

T_("Styles")
csCZ("Styly")
deDE("Stile")
esES("Estilos")
fiFI("Tyylit")
frFR("Styles")
huHU("Stílusok")
itIT("Stili")
nlNL("Stijlen")
plPL("Style")
roRO("Stiluri")
ruRU("Стили")
skSK("Štýly")
srSP("Stilovi")
trTR("Stiller")
zhCN("类型")
zhTW("樣式")


// ParaFormat.cpp

T_("Paragraph format")
csCZ("Formát odstavce")
deDE("Absatzformat")
esES("Formato de p�rrafo")
fiFI("Kappaleformaatti")
frFR("Format de paragraphe")
huHU("Bekezdésformátum")
itIT("Formato paragrafo")
nlNL("Paragraaf formaat")
plPL("Format paragrafu")
roRO("Format paragraf")
ruRU("Формат параграфа")
skSK("Formát odstavca")
srSP("Fromat paragrafa")
trTR("Paragraf düzeni")
zhCN("段格式")
zhTW("段落格式")

T_("Set style")
csCZ("Nastavit styl")
deDE("Stil einstellen")
esES("Establecer estilo")
fiFI("Aseta tyyli")
frFR("Utiliser le style")
huHU("Stílus beállítása")
itIT("Imposta stile")
nlNL("Stel stijl in")
plPL("Ustaw styl")
roRO("Setează stil")
ruRU("Установить стиль")
skSK("Nastaviť štýl")
srSP("Postavi stil")
trTR("Stili seç")
zhCN("设置类型")
zhTW("設定樣式")

T_("New style no. %d")
csCZ("Nový styl č. %d")
deDE("Neuer Stil Nr. %d")
esES("Nuevo estilo n�m. %d")
fiFI("Uusi tyyli nro %d")
frFR("Nouveau style n° %d")
huHU("Új stílus szám %d")
itIT("Nuovo stile no. %d")
nlNL("Nieuwe stijl №%d")
plPL("Nowy styl numer %d")
roRO("Stil nou nr. %d")
ruRU("Новый стиль номер %d")
skSK("Nový štýl č. %d")
srSP("Novi stil br. %d")
trTR("Yeni stil no. %d")
zhCN("新类型号%d")
zhTW("新樣式 no. %d")


// Table.cpp

T_("Insert table")
csCZ("Vložit tabulku")
deDE("Tabelle einfügen")
esES("Insertar tabla")
fiFI("Lisää taulukko")
frFR("Insérer un tableau")
huHU("Táblázat beszúrása")
itIT("Inserisci tbella")
nlNL("Voeg tabel in")
plPL("Wstaw tabelę")
roRO("Inserează tabel")
ruRU("Вставить таблицу")
skSK("Vložiť tabuľku")
srSP("Ubaci tabelu")
trTR("Araya tablo ekle")
zhCN("插入表格")
zhTW("插入表格")

T_("Table properties")
csCZ("Vlastnosti tabulky")
deDE("Tabelleneigenschaften")
esES("Propiedades de tabla")
fiFI("Taulukon ominaisuudet")
frFR("Propriétés du tableau")
huHU("Táblázat tulajdonságok")
itIT("Propriet� tabella")
nlNL("Tabel eigenschappen")
plPL("Właściwości tabeli")
roRO("Proprietăți tabel")
ruRU("Свойства таблицы")
skSK("Vlastnosti tabuľky")
srSP("Svojstva tabele")
trTR("Tablo özellikleri")
zhCN("表格属性")
zhTW("表格屬性")

T_("Invalid header row count %d, cell at rw %d, co %d has vspan = %d.")
csCZ("")
deDE("")
esES("Suma de filas en cabecera invalida, celda en la fila %d, col %d tiene "
     "vspan = %d")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("Ongeldige header rij som %d, cel op rij %d, kolom %d heeft vspan = %d.")
plPL("")
roRO("")
ruRU("")
skSK("Neplatn� po�et st�pcov z�hlavia %d, bunka na r. %d, s. %d m� vspan = %d.")
srSP("")
trTR("")
zhCN("无效标题行数 %d，单元格在行 %d，列 %d 竖跨 = %d")
zhTW("無效的列數 %d, cell at rw %d, co %d has vspan = %d.")

T_("Split cell")
csCZ("Rozdělit buňku")
deDE("Zelle teilen")
esES("Dividir celda")
fiFI("Jaa solu")
frFR("Diviser la cellule")
huHU("Mező felosztása")
itIT("Dividi cella")
nlNL("Cel splitsen")
plPL("Podziel komórkę")
roRO("Subdivide celulă")
ruRU("Разбить ячейки")
skSK("Rozdeliť bunku")
srSP("Podeli ćeliju")
trTR("Hücreyi böl")
zhCN("拆分单元格")
zhTW("分割單格")

T_("Cell properties")
csCZ("Vlastnosti buňky")
deDE("Zelleigenschaften")
esES("Propiedades de celda")
fiFI("Solun ominaisuudet")
frFR("Propriétés de la cellule")
huHU("Mező tulajdonságok")
itIT("Propriet� cella")
nlNL("Cel eigenschappen")
plPL("Właściwości komórki")
roRO("Proprietăți celulă")
ruRU("Свойства ячейки")
skSK("Vlastnosti bunky")
srSP("Svojstva ćelije")
trTR("Hücre özellikleri")
zhCN("单元格属性")
zhTW("單格屬性")


// Find.cpp

T_("Replace")
csCZ("Nahradit")
deDE("Ersetzen")
esES("Reemplazar")
fiFI("Korvaa")
frFR("Remplacer")
huHU("Csere")
itIT("Sostituisci")
nlNL("Vervang")
plPL("Zamień")
roRO("Înlocuiește")
ruRU("Заменить")
skSK("Nahradiť")
srSP("Zameni")
trTR("Değiştir")
zhCN("替换")
zhTW("取代")

T_("Replace in selection")
csCZ("Nahradit ve výběru")
deDE("In der Auswahl ersetzen")
esES("Reemplazar en selecci�n")
fiFI("Korvaa valinnan sisällä")
frFR("Remplacer dans la sélection")
huHU("Csere a kijelölésben")
itIT("Sostituisci nella selezione")
nlNL("Vervang in selectie")
plPL("Zamień w selekcji")
roRO("Înlocuiește în selecție")
ruRU("Заменить в выделении")
skSK("Nahradiť vo výbere")
srSP("Zameni u izboru")
trTR("Seçili olan içinde değiştir")
zhCN("替换选择")
zhTW("取代已選取範圍")

T_("Find")
csCZ("Vyhledat")
deDE("Suchen")
esES("Encontrar")
fiFI("Etsi")
frFR("Rechercher")
huHU("Keresés")
itIT("Trova")
nlNL("Zoeken")
plPL("Znajdź")
roRO("Găsește")
ruRU("Найти")
skSK("Vyhľadať")
srSP("Pronađi")
trTR("Bul")
zhCN("查找")
zhTW("尋找")


// Tool.cpp

T_("Bold")
csCZ("Tučně")
deDE("Fett")
esES("Negrita")
fiFI("Lihavointi")
frFR("Gras")
huHU("Félkövér")
itIT("Grassetto")
nlNL("Vet")
plPL("Pogrubienie")
roRO("Aldine")
ruRU("Полужирный")
skSK("Tučné")
srSP("Masno")
trTR("Kalın")
zhCN("粗体")
zhTW("粗體")

T_("Italic")
csCZ("Kurzíva")
deDE("Kursiv")
esES("Cursiva")
fiFI("Kursivointi")
frFR("Italique")
huHU("Dőlt")
itIT("Corsivo")
nlNL("Cursief")
plPL("Kursywa")
roRO("Înclinat")
ruRU("Наклонный")
skSK("Kurzíva")
srSP("Kurziv")
trTR("İtalik")
zhCN("斜体")
zhTW("斜體")

T_("Underline")
csCZ("Podtržené")
deDE("Unterstrichen")
esES("Subrayar")
fiFI("Alleviivaus")
frFR("Souligné")
huHU("Aláhúzott")
itIT("Sottolineato")
nlNL("Onderstreept")
plPL("Podkreślenie")
roRO("Subliniat")
ruRU("Подчёркнутый")
skSK("Podčiarknuté")
srSP("Podcrtano")
trTR("Altı çizili")
zhCN("下划线")
zhTW("底線")

T_("Strikeout")
csCZ("Přeškrtnuté")
deDE("Durchgestrichen")
esES("Tachar")
fiFI("Yliviivaus")
frFR("Barré")
huHU("Áthúzott")
itIT("Sbarrato")
nlNL("Doorgestreept")
plPL("Przekreślenie")
roRO("Tăiat")
ruRU("Зачёркнутый")
skSK("Preškrtnuté")
srSP("Precrtano")
trTR("Üstü çizili")
zhCN("Strikeout")
zhTW("Strikeout")

T_("Capitals")
csCZ("Kapitálky")
deDE("Kapitälchen")
esES("May�sculas")
fiFI("Isot kirjaimet")
frFR("Majuscules")
huHU("Nagybetűk")
itIT("Maiuscoletto")
nlNL("Hoofdletters")
plPL("Kapitaliki")
roRO("Majuscule")
ruRU("Прописными")
skSK("Kapitálky")
srSP("Velika slova")
trTR("Büyük harfler")
zhCN("大写")
zhTW("大寫")

T_("Superscript")
csCZ("Horní index")
deDE("Hochgestellt")
esES("Super�ndice")
fiFI("Yläindeksi")
frFR("Exposant")
huHU("Felső index")
itIT("Apice")
nlNL("Superscript")
plPL("Indeks górny")
roRO("Superscript")
ruRU("Надстрочный")
skSK("Horný index")
srSP("Gornji indeks")
trTR("Üstyazı")
zhCN("上标")
zhTW("上標")

T_("Subscript")
csCZ("Dolní index")
deDE("Tiefgestellt")
esES("Sub�ndice")
fiFI("Alaindeksi")
frFR("Indice")
huHU("Alsó index")
itIT("Pedice")
nlNL("Subscript")
plPL("Indeks dolny")
roRO("Subscript")
ruRU("Подстрочный")
skSK("Dolný index")
srSP("Donji indeks")
trTR("Altyazı")
zhCN("下标")
zhTW("下標")

T_("Show spelling errors")
csCZ("Ukazovat pravopisné chyby")
deDE("Rechtschreibfehler anzeigen")
esES("Mostrar errores de ortograf�a")
fiFI("Näytä tavutusvirheet")
frFR("Montrer les erreurs de correction")
huHU("Helyesírásellenőrzés")
itIT("Visualizza errori")
nlNL("Toon spel fouten")
plPL("Pokaż błędy pisowni")
roRO("Arată erorile de ortografie")
ruRU("Показать ошибки орфографии")
skSK("Ukazovať pravopisné chyby")
srSP("Prikaži jezičke greške")
trTR("İmla hatalarını göster")
zhCN("显示拼写错误")
zhTW("顯示拼字錯誤")

T_("Justify")
csCZ("Zarovnat do bloku")
deDE("Blocksatz")
esES("Justificar")
fiFI("Rivintasaus")
frFR("Justifier")
huHU("Margószabályozás")
itIT("Giustificato")
nlNL("Rechtvaardig")
plPL("Wyjustuj")
roRO("Aliniat la margini")
ruRU("По ширине")
skSK("Zarovnať do bloku")
srSP("Poravnaj")
trTR("Yasla")
zhCN("调整")
zhTW("調整")

T_("Round bullet")
csCZ("Kulatá zarážka")
deDE("Rundes Aufzählungszeichen")
esES("Vi�eta s�lida circular")
fiFI("Pyöreä ranskalainen viiva")
frFR("Puce ronde")
huHU("Korong")
itIT("Punto elenco circolare")
nlNL("Ronde kogel")
plPL("Okrągłe wypunktowanie")
roRO("Marcaj rotund")
ruRU("Круглые списочные маркеры")
skSK("Okrúhla zarážka")
srSP("Okruglo označavanje")
trTR("Yuvarlak işaret imi")
zhCN("Round bullet")
zhTW("Round bullet")

T_("White round bullet")
csCZ("Bíla kruhová odrážka")
deDE("Weißes rundes Aufzählungszeichen")
esES("Vi�eta circular")
fiFI("Valkoinen pyöreä ranskalainen viiva")
frFR("Puce ronde blanche")
huHU("Fehér korong")
itIT("Punto elenco circolare bianco")
nlNL("Witte ronde kogel")
plPL("Białe, okrągłe wypunktowanie")
roRO("Marcaj rotund alb")
ruRU("Белые круглые списочные маркеры")
skSK("Biela okrúhla zarážka")
srSP("Belo okruglo označavanje")
trTR("Beyaz yuvarlak işaret imi")
zhCN("White round bullet")
zhTW("White round bullet")

T_("Box bullet")
csCZ("Čtvercová odrážka")
deDE("Quadratisches Aufzählungszeichen")
esES("Vi�eta s�lida cuadrada")
fiFI("Neliö ranskalainen viiva")
frFR("Puce boîte")
huHU("Négyzet")
itIT("Punto elenco quadrato")
nlNL("Kist kogel")
plPL("Kwadratowe wypunktowanie")
roRO("Marcaj pătrat")
ruRU("Квадратные списочные маркеры")
skSK("Štvorcová zarážka")
srSP("Kvadratno označvanje")
trTR("Kutu işaret imi")
zhCN("Box bullet")
zhTW("Box bullet")

T_("White box bullet")
csCZ("Bílá čtvercová odrážka")
deDE("Weißes quadratisches Aufzählungszeichen")
esES("Vi�eta cuadrada")
fiFI("Valkoinen neliö ranskalainen viiva")
frFR("Puce boîte blanche")
huHU("Fehér négyzet")
itIT("Punto elenco quadrato bianco")
nlNL("Witte kist kogel")
plPL("Białe kwadratowe wypunktowanie")
roRO("Marcaj pătrat alb")
ruRU("Белые квадратные списочные маркеры")
skSK("Biela štvorcová zarážka")
srSP("Belo kvadratno označvanje")
trTR("Beyaz kutu işaret imi")
zhCN("White box bullet")
zhTW("White box bullet")

T_("Text bullet")
csCZ("Textová odrážka")
deDE("Textaufzählungszeichen")
esES("Vi�eta de texto")
fiFI("Teksti ranskalainen viiva")
frFR("Puce texte")
huHU("Szöveg korong")
itIT("Punto elenco carattere")
nlNL("Tekst kogel")
plPL("Tekstowe wypunktowanie")
roRO("Marcaj cu text")
ruRU("Текстовые списочные маркеры")
skSK("Textová zarážka")
srSP("Tekst označavanje")
trTR("Metin işaret imi")
zhCN("Text bullet")
zhTW("Text bullet")

T_("Paragraph format..")
csCZ("Formát odstavce")
deDE("Absatzformat ...")
esES("Formato de p�rrafo..")
fiFI("Kappaleformaatti...")
frFR("Format de paragraphe..")
huHU("Bekezdés formátum..")
itIT("Formato paragrafo..")
nlNL("Paragraaf formaat..")
plPL("Format paragrafu..")
roRO("Format paragraf..")
ruRU("Формат параграфа")
skSK("Formát odstavca")
srSP("Format paragrafa..")
trTR("Paragraf formatı...")
zhCN("段格式")
zhTW("段落格式..")

T_("To single paragraph")
csCZ("Do jednoho odstavce")
deDE("Absätze zusammenfassen")
esES("A p�rrafo �nico")
fiFI("Yksittäiseen kappaleeseen")
frFR("Fusionner en un paragraphe")
huHU("Egyszerű bekezdéshez")
itIT("Paragrafo singolo")
nlNL("Naar een enkele paragraaf")
plPL("Do pojedynczego paragrafu")
roRO("La un singur paragraf")
ruRU("В один параграф")
skSK("Do jedného odstavca")
srSP("Ka jednom paragrafu")
trTR("Tek paragraf haline getir")
zhCN("转为单段")
zhTW("轉為單一段落")

T_("Undo")
csCZ("Zpět")
deDE("Rückgängig")
esES("Deshacer")
fiFI("Kumoa")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
nlNL("Ondoen")
plPL("Cofnij")
roRO("Anulează ultima operație")
ruRU("Отменить")
skSK("Späť")
srSP("Undo")
trTR("Geri Al")
zhCN("撤销")
zhTW("復原")

T_("Redo")
csCZ("Znovu")
deDE("Wiederherstellen")
esES("Rehacer")
fiFI("Toista")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
nlNL("Herdoen")
plPL("Powtórz")
roRO("Refă ultima operație")
ruRU("Повторить")
skSK("Znovu")
srSP("Redo")
trTR("Yinele")
zhCN("重做")
zhTW("重做")

T_("Cut")
csCZ("Vyjmout")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
nlNL("Knippen")
plPL("Wytnij")
roRO("Decupează")
ruRU("Вырезать")
skSK("Vystrihnúť")
srSP("Iseci")
trTR("Kes")
zhCN("剪切")
zhTW("剪下")

T_("Copy")
csCZ("Kopírovat")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
nlNL("Kopieëren")
plPL("Kopiuj")
roRO("Copiază")
ruRU("Копировать")
skSK("Kopírovať")
srSP("Kopiraj")
trTR("Kopyala")
zhCN("复制")
zhTW("複製")

T_("Paste")
csCZ("Vložit")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
nlNL("Plakken")
plPL("Wklej")
roRO("Lipește")
ruRU("Вставить")
skSK("Prilepiť")
srSP("Zalepi")
trTR("Yapıştır")
zhCN("粘贴")
zhTW("貼上")

T_("Print")
csCZ("Tisk")
deDE("Drucken")
esES("Imprimir")
fiFI("Tulosta")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
nlNL("Afdrukken")
plPL("Drukuj")
roRO("Listează")
ruRU("Печать")
skSK("Tlač")
srSP("Štampa")
trTR("Yazdır")
zhCN("打印")
zhTW("列印")

T_("Find/Replace")
csCZ("Vyhledat/Nahradit")
deDE("Suchen/Ersetzen")
esES("Buscar/Reemplazar")
fiFI("Etsi/Korvaa")
frFR("Chercher/Remplacer")
huHU("Keresés/Csere")
itIT("Trova/Sostituisci")
nlNL("Zoek/Vervang")
plPL("Znajdź/Zamień")
roRO("Găsire/Înlocuire")
ruRU("Найти/Заменить")
skSK("Vyhľadať/Nahradiť")
srSP("Pronađi/Zameni")
trTR("Bul/Değiştir")
zhCN("查找/替换")
zhTW("尋找/取代 ")

T_("Insert table..")
csCZ("Vložit tabulku..")
deDE("Tabelle einfügen ...")
esES("Insertar tabla..")
fiFI("Lisää taulukko...")
frFR("Insérer un tableau..")
huHU("Táblázat beszútása")
itIT("Inserisci tabella..")
nlNL("Tabel invoegen..")
plPL("Wstaw tabelę..")
roRO("Inserează tabel..")
ruRU("Вставить таблицу")
skSK("Vložiť tabuľku..")
srSP("Ubaci tabelu..")
trTR("Araya tablo ekle...")
zhCN("插入表格..")
zhTW("插入表格..")

T_("Table properties..")
csCZ("Vlastnosti tabulky..")
deDE("Tabelleneigenschaften ...")
esES("Propiedades de tabla..")
fiFI("Taulukon ominaisuudet...")
frFR("Propriétés du tableau..")
huHU("Táblázat tulajdonságai")
itIT("Propriet� tabella..")
nlNL("Tabel eigenschappen..")
plPL("Właściwości tabeli..")
roRO("Proprietăți tabel..")
ruRU("Свойства таблицы")
skSK("Vlastnosti tabuľky..")
srSP("Svojstva tabele..")
trTR("Tablo özellikleri...")
zhCN("表格属性..")
zhTW("表格屬性..")

T_("Insert row")
csCZ("Vložit řádek")
deDE("Zeile einfügen")
esES("Insertar fila")
fiFI("Lisää rivi")
frFR("Insérer une ligne")
huHU("Sor beszúrása")
itIT("Inserisci riga")
nlNL("Rij invoegen")
plPL("Wstaw wiersz")
roRO("Inserează linie")
ruRU("Вставить ряд")
skSK("Vložiť riadok")
srSP("Ubaci red")
trTR("Araya satır ekle")
zhCN("插入行")
zhTW("插入列")

T_("Remove row")
csCZ("Odstranit řádek")
deDE("Zeile entfernen")
esES("Eliminar fila")
fiFI("Poista rivi")
frFR("Supprimer la ligne")
huHU("Sor törlése")
itIT("Rimuovi riga")
nlNL("Rij verwijderen")
plPL("Usuń wiersz")
roRO("Șterge linie")
ruRU("Удалить ряд")
skSK("Odstrániť riadok")
srSP("Ukloni red")
trTR("Satır sil")
zhCN("删除行")
zhTW("移除列")

T_("Insert column")
csCZ("Vložit sloupec")
deDE("Spalte einfügen")
esES("Insertar columna")
fiFI("Lisää sarake")
frFR("Insérer une colonne")
huHU("Oszlop beszúrása")
itIT("Inserisci colonna")
nlNL("Kolom invoegen")
plPL("Wstaw kolumnę")
roRO("Inserează coloană")
ruRU("Вставить колонку")
skSK("Vložiť stĺpec")
srSP("Ubaci kolonu")
trTR("Araya sütun ekle")
zhCN("插入列")
zhTW("插入行")

T_("Remove column")
csCZ("Odstranit sloupec")
deDE("Spalte entfernen")
esES("Eliminar columna")
fiFI("Poista sarake")
frFR("Supprimer la colonne")
huHU("Oszlop törlése")
itIT("Rimuovi colonna")
nlNL("Kolom verwijderen")
plPL("Usuń kolumnę")
roRO("Șterge coloană")
ruRU("Удалить колонку")
skSK("Odstrániť stĺpec")
srSP("Ukloni kolonu")
trTR("Sütun sil")
zhCN("删除列")
zhTW("移除行")

T_("Join cells")
csCZ("Spojit buňky")
deDE("Zellen verbinden")
esES("Unir celdas")
fiFI("Yhdistä solut")
frFR("Fusionner les cellules")
huHU("Mezők egyesítése")
itIT("Unisci celle")
nlNL("Cellen samenvoegen")
plPL("Scal komórki")
roRO("Unește celule")
ruRU("Объединить ячейки")
skSK("Spojiť bunky")
srSP("Spoji ćelije")
trTR("Hücreleri birleştir")
zhCN("合并单元格")
zhTW("合併單格")

T_("Split cell..")
csCZ("Rozdělit buňku")
deDE("Zelle teilen ...")
esES("Dividir celda..")
fiFI("Halkaise solu...")
frFR("Diviser la cellule..")
huHU("Mező felosztása..")
itIT("Dividi cella..")
nlNL("Cellen splitsen..")
plPL("Podziel komórkę..")
roRO("Subdivide celule..")
ruRU("Разбить ячейки...")
skSK("Rozdeliť bunky")
srSP("Podeli ćeliju..")
trTR("Hücreyi böl...")
zhCN("拆分单元格")
zhTW("分割單格..")

T_("Cell properties..")
csCZ("Vlastnosti buňky..")
deDE("Zelleigenschaften ...")
esES("Propiedades de celda..")
fiFI("Solun ominaisuudet")
frFR("Propriétés de la cellule")
huHU("Mező tulajdonságok..")
itIT("Propriet� celle..")
nlNL("Cel eigenschappen..")
plPL("Właściwości komórki")
roRO("Proprietăți celulă..")
ruRU("Свойства ячейки...")
skSK("Vlastnosti bunky")
srSP("Svojstva ćelije..")
trTR("Hücre özellikleri...")
zhCN("单元格属性")
zhTW("單格屬性")

T_("Insert image from file..")
csCZ("")
deDE("")
esES("Insertar imagen desde fichero..")
fiFI("")
frFR("Insérer image à partir du fichier..")
huHU("")
itIT("")
nlNL("Afbeelding invoegen vanuit een bestand..")
plPL("")
roRO("Inserează imagine din fișier..")
ruRU("Вставить изображение из файла")
skSK("Vložiť obrázok zo súboru..")
srSP("")
trTR("")
zhCN("插入来自文件的图片")
zhTW("插入圖片..")

T_("Style keys..")
csCZ("")
deDE("")
esES("Teclas de estilo")
fiFI("")
frFR("Raccourcis styles ..")
huHU("")
itIT("")
nlNL("Stijl toetsen..")
plPL("")
roRO("Taste stil..")
ruRU("Стили..")
skSK("Štýly")
srSP("")
trTR("")
zhCN("样式键标...")
zhTW("樣式鍵..")


// RichEdit.lay

T_("Alignment")
csCZ("&Zarovnat:")
deDE("Ausrichtung")
esES("Alineamiento")
fiFI("Kohdistus")
frFR("Alignement")
huHU("Igazítás")
itIT("Allineamento")
nlNL("Aanpassing")
plPL("Wyrównanie")
roRO("Aliniament")
ruRU("Выравнивание")
skSK("&Zarovnať")
srSP("Poravnanje:")
trTR("Hizalama:")
zhCN("对齐")
zhTW("對齊")

T_("Left\nCenter\nRight\nJustify")
csCZ("Vlevo\nStřed\nVpravo\nDo bloku")
deDE("Links\nMitte\nRechts\nBlocksatz")
esES("Izquierda\nCentro\nDerecha\nJustificar")
fiFI("Vasen\nKeskitys\nOikea\nTasaus")
frFR("Gauche\nCentrer\nDroite\nJustifier")
huHU("Bal\nKözép\nJobb\nMargó")
itIT("Sinistra\nCentro\nDestra\nGiustificato")
nlNL("Links\nCentraal\nRechts\nRechtvaardig")
plPL("Do lewej\nWyśrodkowane\nDo prawej\nWyjustowane")
roRO("Stânga\nCentru\nDreapta\nAliniat la margini")
ruRU("Влево\nПо центру\nВправо\nПо ширине")
skSK("Vľavo\nStred\nVpravo\nDo bloku")
srSP("Levo\nPo sredini\nDesno\nporavnato")
trTR("Sola yasla\nOrtala\nSağa yasla\nİki yana yasla")
zhCN("左对齐\n居中\n右对齐\n两端对齐")
zhTW("靠左對齊\n置中\n靠右對齊\n左右對齊")

T_("Spacing")
csCZ("Mezery")
deDE("Zeichenabstand")
esES("Espaciado")
fiFI("Väli")
frFR("Espacement")
huHU("Térköz")
itIT("")
nlNL("Spatieëring")
plPL("Odstęp")
roRO("Spațiere")
ruRU("Межсимвольное расстояние")
skSK("Medzery")
srSP("")
trTR("Aralık")
zhCN("间隔")
zhTW("間距")

T_("Before")
csCZ("Před")
deDE("Vorher")
esES("Antes")
fiFI("Ennen")
frFR("Avant")
huHU("Előtte")
itIT("Prima")
nlNL("Hiervoor")
plPL("Przed")
roRO("Înainte")
ruRU("Перед")
skSK("Pred")
srSP("Pre")
trTR("Önce")
zhCN("前")
zhTW("前")

T_("After")
csCZ("Po")
deDE("Danach")
esES("Despu�s")
fiFI("Jälkeen")
frFR("Après")
huHU("Utána")
itIT("Dopo")
nlNL("Hierna")
plPL("Po")
roRO("După")
ruRU("После")
skSK("Po")
srSP("Posle")
trTR("Sonra")
zhCN("后")
zhTW("後")

T_("Line spacing")
csCZ("Řádkování")
deDE("Zeilenabstand")
esES("Espaciado de l�nea")
fiFI("Rivinväli")
frFR("Interligne")
huHU("Sorköz")
itIT("")
nlNL("Lijn spatieëring")
plPL("Interlinia")
roRO("Spațierea liniilor")
ruRU("Расстояние между строками")
skSK("Riadkovanie")
srSP("")
trTR("Satır aralığı")
zhCN("行间隔")
zhTW("行間距")

T_("Text flow")
csCZ("Tok textu")
deDE("Textfluss")
esES("Flujo de texto")
fiFI("Tekstin virtaus")
frFR("Flux du texte")
huHU("Szöveg körbefolyatás")
itIT("Flusso testo")
nlNL("Tekst stroming")
plPL("Przepływ tekstu")
roRO("Fluxul textului")
ruRU("Расположение текста")
skSK("Tok textu")
srSP("Tok teksta")
trTR("Metin akışı")
zhCN("文本流")
zhTW("文字串流")

T_("Break page before")
csCZ("&Zalomit stránku před")
deDE("Seitenumbruch vorher")
esES("Dividir p�gina antes")
fiFI("Katkaise sivu ennen")
frFR("Saut de page avant")
huHU("Oldaltörés előtte")
itIT("Precedi interruzione pagina")
nlNL("Pagina hiervoor breken")
plPL("Załam stronę przed")
roRO("Marcaj pagină nouă înainte")
ruRU("Оборвать страницу после")
skSK("&Zalomiť stránku pred")
srSP("Prelomi stranu pre")
trTR("Önce sayfa sonu")
zhCN("断开页前于")
zhTW("斷開頁前於")

T_("Keep together")
csCZ("&Svázat řádky")
deDE("Zusammenhalten")
esES("Mantener unido")
fiFI("Pidä yhdessä")
frFR("Garder assemblé")
huHU("Együtt tartás")
itIT("Mantieni assieme")
nlNL("Koppelen")
plPL("Trzymaj razem")
roRO("Păstrează alăturat")
ruRU("Держать вместе")
skSK("&Zviazať riadky")
srSP("Drži zajedno")
trTR("Satırları birlikte tut")
zhCN("保持在一起")
zhTW("保持在一起")

T_("Keep with next")
csCZ("Svázat s &následujícím")
deDE("Zusammen mit nächstem")
esES("Mantener con siguiente")
fiFI("Pidä seuraavan kanssa")
frFR("Assembler au suivant")
huHU("Marad a következővel")
itIT("Mantieni col successivo")
nlNL("Koppel met volgende")
plPL("Trzymaj z następną")
roRO("Păstrează lângă următorul")
ruRU("Придерживаться следующего")
skSK("Sviazať s &nasledujúcim")
srSP("Drži sa sledećim")
trTR("Sonraki ile birlikte")
zhCN("与下一个保持")
zhTW("與下一個保持")

T_("Allow orphans")
csCZ("Povolit osa&mocené řádky")
deDE("Schusterjungen zulassen")
esES("Permitir hu�rfanas")
fiFI("Salli orvot")
frFR("Autoriser les orphelines")
huHU("Árvák megengedése")
itIT("Consenti isolati")
nlNL("Wezen toelaten")
plPL("Dopuszczaj sieroty")
roRO("Permite izolări")
ruRU("Разрешить висячие строки")
skSK("Povoliť osa&motené riadky")
srSP("Dozvoli siročiće")
trTR("Artık satırlara izin ver")
zhCN("Allow orphans")
zhTW("Allow orphans")

T_("Ruler")
csCZ("Pravítko")
deDE("")
esES("Regla")
fiFI("")
frFR("Règle")
huHU("")
itIT("")
nlNL("Liniaal")
plPL("")
roRO("Liniar")
ruRU("Линейка")
skSK("Pravítko")
srSP("")
trTR("")
zhCN("标尺")
zhTW("量尺")

T_("Ruler height")
csCZ("")
deDE("")
esES("Altura de regla")
fiFI("")
frFR("Hauteur règle")
huHU("")
itIT("")
nlNL("Liniaal hoogte")
plPL("")
roRO("Înalțime linear")
ruRU("Высота линейки")
skSK("Výška pravítka")
srSP("")
trTR("")
zhCN("标尺高度")
zhTW("量尺高度")

T_("Ink")
csCZ("Text")
deDE("Textfarbe")
esES("Tinta")
fiFI("Muste")
frFR("Encre")
huHU("Tinta")
itIT("Testo")
nlNL("Inkt")
plPL("Kolor tekstu")
roRO("Cerneală")
ruRU("Чернила")
skSK("Text")
srSP("Tinta")
trTR("Yazı rengi")
zhCN("墨水")
zhTW("墨水")

T_("Indentation")
csCZ("Zarovnání")
deDE("Einrückung")
esES("Sangr�a")
fiFI("Sisennys")
frFR("Indentation")
huHU("Behúzás")
itIT("")
nlNL("Inspringing")
plPL("Wcięcie")
roRO("Indentare")
ruRU("Выравнивание")
skSK("Zarovnanie")
srSP("")
trTR("Girinti")
zhCN("缺口")
zhTW("Indentation")

T_("Left margin")
csCZ("Levý okraj")
deDE("Linker Rand")
esES("Margen izquierdo")
fiFI("Vasen marginaali")
frFR("Marge de gauche")
huHU("Bal szegély")
itIT("Margine sinistro")
nlNL("Marge links")
plPL("Lewy margines")
roRO("Margine din stânga")
ruRU("Поле слева")
skSK("Ľavý okraj")
srSP("Leva margina")
trTR("Sol boşluk")
zhCN("左边空白")
zhTW("左邊空白")

T_("ParaLayout_rm_1_SetLabel\aRight margin")
csCZ("Pravý okraj")
deDE("Rechter Rand")
esES("ParaLayout_rm_1_SetLabel\aMargen derecho")
fiFI("Oikea marginaali")
frFR("")
huHU("Jobb szegély")
itIT("Margine destro")
nlNL("Marge rechts")
plPL("Prawy margines")
roRO("Margine dreapta")
ruRU("")
skSK("Pravý okraj")
srSP("")
trTR("Sağ boşluk")
zhCN("Right margin")
zhTW("右邊空白")

T_("First line")
csCZ("První řádka")
deDE("Erste Zeile")
esES("Primera l�nea")
fiFI("Ensimmäinen rivi")
frFR("Première ligne")
huHU("Első sor")
itIT("")
nlNL("Eerste regel")
plPL("Pierwsza linia")
roRO("Prima linie")
ruRU("Красная строка")
skSK("Prvý riadok")
srSP("")
trTR("İlk satır")
zhCN("首行")
zhTW("首行")

T_("Bullet")
csCZ("Odrážka")
deDE("Aufzählungszeichen")
esES("Vi�eta")
fiFI("Ranskalainen viiva")
frFR("Puce")
huHU("korong")
itIT("Elenco puntato")
nlNL("Kogel")
plPL("Wypunktowanie")
roRO("Marcaj")
ruRU("Списочный маркер")
skSK("Zarážka")
srSP("Označavanje")
trTR("Madde imi")
zhCN("Bullet")
zhTW("Bullet")

T_("Tabs")
csCZ("Tabelace")
deDE("Tabulatoren")
esES("Tabuladores")
fiFI("Tabulaattorit")
frFR("Tabulations")
huHU("Tabulátorok")
itIT("Tabulatori")
nlNL("Tabbladen")
plPL("Tabulatory")
roRO("Taburi")
ruRU("Табуляторы")
skSK("Tabelátor")
srSP("Tabulatori")
trTR("Sekmeler")
zhCN("Tabs")
zhTW("Tabs")

T_("Default tab size")
csCZ("Výchozí tabelace")
deDE("Voreingestellte Tabulatorweite")
esES("Tama�o por defecto de tabulador")
fiFI("Tabulaattorin oletuskoko")
frFR("Tabulation par défaut")
huHU("Alapértelmezett tabulátorméret")
itIT("Dimensione tabulatore predefinita")
nlNL("Standaard tabblad grootte")
plPL("Domyślny rozmiar tabulacji")
roRO("Dimensiune tab implicită")
ruRU("Размер табуляции по умолчанию")
skSK("Predvolená tabelácia")
srSP("Podrazumevana veličina tabulatora")
trTR("Varsayılan sekme boyutu")
zhCN("缺省tab大小")
zhTW("預設 tab 大小")

T_("Numbering")
csCZ("Číslování")
deDE("Nummerierung")
esES("Numeraci�n")
fiFI("Numerointi")
frFR("Numérotation")
huHU("Számozás")
itIT("Numerazione")
nlNL("Nummering")
plPL("Numerowanie")
roRO("Numere")
ruRU("Нумерование")
skSK("Číslovanie")
srSP("Nabrajanje")
trTR("Sayfa numaralandırma")
zhCN("编号")
zhTW("編號")

T_("Before number")
csCZ("Před číslem")
deDE("Vor der Nummer")
esES("Antes de n�mero")
fiFI("Ennen numeroa")
frFR("Nombre avant")
huHU("Szám előtte")
itIT("Numero prima")
nlNL("Nummer hiervoor")
plPL("Przed numerem")
roRO("Numar precedent")
ruRU("Перед числом")
skSK("Pred číslom")
srSP("Pre broja")
trTR("Başlangıç")
zhCN("号码前")
zhTW("號碼前")

T_("After number")
csCZ("Po čísle")
deDE("Nach der Nummer")
esES("Despu�s de n�mero")
fiFI("Numeron jälkeen")
frFR("Nombre après")
huHU("Szám utána")
itIT("Numero successivo")
nlNL("Nummer hierna")
plPL("Po numerze")
roRO("Număr următor")
ruRU("После числа")
skSK("Po čísle")
srSP("Posle broja")
trTR("Son")
zhCN("号码后")
zhTW("號碼後")

T_("Reset")
csCZ("Nulovat")
deDE("Zurücksetzen")
esES("Iniciar")
fiFI("Resetoi")
frFR("Réinitialiser")
huHU("Kiinduló állapot")
itIT("Azzera")
nlNL("Herstel")
plPL("Przywróć")
roRO("Resetează")
ruRU("Сбросить")
skSK("Nulovať")
srSP("Vrati")
trTR("Sıfırla")
zhCN("重置")
zhTW("重置")

T_("dot\npoint\ninch\nmm\ncm")
csCZ("dot\nbod\npalec\nmm\ncm")
deDE("Pixel\nPunkt\nZoll\nmm\ncm")
esES("dot\npoint\ninch\nmm\ncm")
fiFI("dot\npoint\ntuuma\nmm\ncm")
frFR("pica\npoint\npouce\nmm\ncm")
huHU("képpont\npont\nhüvelyk\nmm\ncm")
itIT("dot\npunti\npollici\nmm\ncm")
nlNL("stip\npunt\ninch\nmm\ncm")
plPL("punkty\npiksele\ncale\nmm\ncm")
roRO("dot\npunct\ninch\nmm\ncm")
ruRU("точки\nпоинты\nдюймы\nмм\nсм")
skSK("dot\nbod\npalec\nmm\ncm")
srSP("tačka\npoint\ninč\nmm\ncm")
trTR("piksel\nnokta\ninç\nmm\ncm")
zhCN("dot\npoint\ninch\nmm\ncm")
zhTW("dot\npoint\ninch\nmm\ncm")

T_("Reveal codes")
csCZ("Pomocné znaky")
deDE("Steuerzeichen anzeigen")
esES("Mostrar c�digos")
fiFI("Paljasta koodit")
frFR("Texte masqué")
huHU("Kódok megjelenítése")
itIT("Visualizza codici")
nlNL("Onthul codes")
plPL("Niewidoczne znaki")
roRO("Arată coduri")
ruRU("Показать коды")
skSK("Pomocné znaky")
srSP("Pokaži kod")
trTR("Kodları göster")
zhCN("显示码")
zhTW("顯示代碼")

T_("Zoom")
csCZ("Zmenšit")
deDE("Zoom")
esES("Acercar")
fiFI("Zoom")
frFR("Zoom")
huHU("Nagyítás")
itIT("Zoom")
nlNL("Zoom")
plPL("Powiększenie")
roRO("Mărire")
ruRU("Увеличить")
skSK("Zmenšiť")
srSP("Uveličaj")
trTR("Yakınlaştır")
zhCN("扩大")
zhTW("縮放大小")

T_("Style keys")
csCZ("")
deDE("")
esES("Teclas de estilo")
fiFI("")
frFR("Raccourcis styles")
huHU("")
itIT("")
nlNL("Stijl toetsen")
plPL("")
roRO("Taste stil")
ruRU("Стили")
skSK("Štýly")
srSP("")
trTR("")
zhCN("样式键标")
zhTW("樣式鍵")

T_("OK")
csCZ("OK")
deDE("OK")
esES("Continuar")
fiFI("OK")
frFR("Ok")
huHU("Rendben")
itIT("Ok")
nlNL("OK")
plPL("OK")
roRO("OK")
ruRU("OK")
skSK("OK")
srSP("OK")
trTR("Tamam")
zhCN("确定")
zhTW("確定")

T_("Cancel")
csCZ("Storno")
deDE("Abruch")
esES("Cancelar")
fiFI("Peruuta")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
nlNL("Afbreken")
plPL("Anuluj")
roRO("Anulează")
ruRU("Отмена")
skSK("Storno")
srSP("Otkaži")
trTR("İptal")
zhCN("取消")
zhTW("取消")

T_("New")
csCZ("Nový")
deDE("Neu")
esES("Nuevo")
fiFI("Uusi")
frFR("Nouveau")
huHU("Új")
itIT("Nuovo")
nlNL("Nieuw")
plPL("Nowy")
roRO("Nou")
ruRU("Новый")
skSK("Nový")
srSP("Novi")
trTR("Yeni")
zhCN("新建")
zhTW("新建")

T_("Wi&dth:")
csCZ("&Šířka")
deDE("&Breite")
esES("A&ncho")
fiFI("&Leveys:")
frFR("La&rgeur :")
huHU("&Szélesség:")
itIT("La&rghezza:")
nlNL("Bree&dte:")
plPL("Szero&kość:")
roRO("&Lățime:")
ruRU("&Ширина:")
skSK("&Šírka")
srSP("&Širina")
trTR("Genişl&ik")
zhCN("宽度(&d):")
zhTW("寬度(&d)：")

T_("H&eight:")
csCZ("&Výška")
deDE("&Höhe")
esES("A&lto")
fiFI("&Korkeus:")
frFR("H&auteur :")
huHU("&Magasság:")
itIT("A&ltezza")
nlNL("Hoogt&e:")
plPL("Wysok&ość:")
roRO("Î&nălțime:")
ruRU("&Высота:")
skSK("&Výška")
srSP("&Visina")
trTR("&Yükseklik:")
zhCN("高度(&e)")
zhTW("高度(&e)")

T_("&Width (%):")
csCZ("Šíř&ka (%):")
deDE("B&reite (%)")
esES("&Ancho (%):")
fiFI("&Leveys (%):")
frFR("&Largeur (%) :")
huHU("S&zélesség (%):")
itIT("&Larghezza (%):")
nlNL("&Breedte (%):")
plPL("&Szerokość (%):")
roRO("&Lățime (%):")
ruRU("&Ширина (%):")
skSK("Šír&ka (%):")
srSP("&Širina (%):")
trTR("&Genişlik (%):")
zhCN("宽度&W(%):")
zhTW("寬度&W(%)：")

T_("Height (%):")
csCZ("Výška (%):")
deDE("H&öhe (%)")
esES("Alto (%):")
fiFI("Korkeus (%):")
frFR("Hauteur (%) :")
huHU("Magasság (%):")
itIT("Altezza (%):")
nlNL("Hoogte (%):")
plPL("Wysokość (%):")
roRO("Î&nălțime (%):")
ruRU("Высота (%):")
skSK("Výška (%):")
srSP("&Visina (%):")
trTR("Yükseklik (%):")
zhCN("高度(%):")
zhTW("高度(%)：")

T_("&Descent:")
csCZ("&Zanoření")
deDE("&Unterlänge")
esES("&Descendente:")
fiFI("&Aleneva:")
frFR("&Descente :")
huHU("&Csökkenés:")
itIT("&Diminuisci:")
nlNL("Af&daling:")
plPL("&Pochyłość")
roRO("&Descendent:")
ruRU("&Наклон:")
skSK("&Zanorenie")
srSP("&Nagib:")
trTR("&Harf Kuyruğu:")
zhCN("降序(&D):")
zhTW("降冪(&D)：")

T_("Keep aspect ratio")
csCZ("Zachovat poměr")
deDE("Seitenverhältnis beibehalten")
esES("Mantener proporci�n")
fiFI("Säilytä kuvasuhde")
frFR("Garder les proportions")
huHU("Méretarány megtartása")
itIT("Mantieni proporzioni")
nlNL("Behoudt beeldverhouding")
plPL("Zachowuj stosunek szerokości do wysokości")
roRO("Păstrează proporții")
ruRU("Сохранять пропорции")
skSK("Zachovať pomer")
srSP("Zadrži razmeru")
trTR("En/Boy oranını koru")
zhCN("保持样式比例")
zhTW("保持長寬比例")

T_("Font")
csCZ("Písmo")
deDE("Schriftart")
esES("Fuente")
fiFI("Kirjasin")
frFR("Police")
huHU("Font")
itIT("Carattere")
nlNL("Lettertype")
plPL("Czcionka")
roRO("Font")
ruRU("Шрифт")
skSK("Písmo")
srSP("Font")
trTR("Yazı tipi")
zhCN("字体")
zhTW("字型")

T_("Height")
csCZ("Výška")
deDE("Schriftgrad")
esES("Alto")
fiFI("Korkeus")
frFR("Hauteur")
huHU("Magasság")
itIT("Altezza")
nlNL("Hoogte")
plPL("Wysokość")
roRO("Înălțime")
ruRU("Высота")
skSK("Výška")
srSP("Visina")
trTR("Yükseklik")
zhCN("高度")
zhTW("高度")

T_("Paper")
csCZ("Papír")
deDE("Hintergrundfarbe")
esES("Papel")
fiFI("Paperi")
frFR("Papier")
huHU("Papír")
itIT("Sfondo")
nlNL("Papier")
plPL("Kolor tła")
roRO("Hârtie")
ruRU("Бумага")
skSK("Papier")
srSP("Papir")
trTR("Kağıt")
zhCN("页")
zhTW("頁")

T_("Style of next paragraph")
csCZ("Styl následujícího odstavce")
deDE("Stil des folgenden Absatzes")
esES("Estilo de p�rrafo siguiente")
fiFI("Seuraavan kappaleen tyyli")
frFR("Style du paragraphe suivant")
huHU("Következő bekezdés stílusa")
itIT("Stile paragrafo successivo")
nlNL("Stijl van de volgende paragraaf")
plPL("Styl następnego paragrafu")
roRO("Stilul următorului paragraf")
ruRU("Стиль следующего параграфа")
skSK("Štýl nasledujúceho odstavca")
srSP("Stil sledećeg paragrafa")
trTR("Sonraki paragrafın stili")
zhCN("下段格式")
zhTW("下一段落的樣式")

T_("Character")
csCZ("Znaky")
deDE("Zeichen")
esES("Car�cter")
fiFI("Merkki")
frFR("Caractère")
huHU("Karakter")
itIT("Carattere")
nlNL("Karakter")
plPL("Znak")
roRO("Caracter")
ruRU("Символ")
skSK("Znaky")
srSP("Karakter")
trTR("Karakter")
zhCN("字符")
zhTW("字元")

T_("&Find:")
csCZ("&Vyhledat")
deDE("&Suchen:")
esES("&Buscar:")
fiFI("&Etsi:")
frFR("&Rechercher :")
huHU("&Keresés:")
itIT("&Trova:")
nlNL("&Zoeken:")
plPL("&Znajdź:")
roRO("&Găsește:")
ruRU("&Найти:")
skSK("&Vyhľadať")
srSP("&Pronađi:")
trTR("&Bul:")
zhCN("查找(&F):")
zhTW("尋找(&F)：")

T_("&Replace:")
csCZ("&Nahradit")
deDE("&Ersetzen:")
esES("&Reemplazar:")
fiFI("&Korvaa:")
frFR("&Remplacer :")
huHU("&Csere:")
itIT("&Sostituisci:")
nlNL("&Vervangen:")
plPL("&Zamień:")
roRO("Â&nlocuiește:")
ruRU("&Заменить:")
skSK("&Nahradiť")
srSP("&Zameni:")
trTR("&Değiştir:")
zhCN("替换(&R):")
zhTW("取代(&R)：")

T_("&Whole word")
csCZ("&Celé slovo")
deDE("Ganzes &Wort")
esES("&Palabra completa")
fiFI("&Kokonainen sana")
frFR("&Mot entier")
huHU("&Egész szó")
itIT("")
nlNL("&Hele woord")
plPL("&Całe słowo")
roRO("&Cuvânt întreg")
ruRU("&Слово целиком")
skSK("&Celé slovo")
srSP("&Cela reč")
trTR("&Sözün tümü")
zhCN("全字(&W)")
zhTW("全字(&W)")

T_("&Ignore case")
csCZ("&Ignorovat velikost písma")
deDE("&Groß-/Kleinschreibung ignorieren")
esES("&Ignorar may�sculas/min�sculas")
fiFI("&Isot ja pienet")
frFR("&Ignorer la casse")
huHU("&Nagybetűk figyelmen kívül")
itIT("Ignora maiuscole/minuscole")
nlNL("&Hoofdletters negeren")
plPL("Ignoruj wielkość liter")
roRO("&Ignoră majusucule")
ruRU("&Игнорировать регистр")
skSK("&Ignorovať veľkosť písma")
srSP("&Ignoriši mala/velika slova")
trTR("Büyük/Küçük harf &ayırma")
zhCN("忽略大小写(&I)")
zhTW("忽略大小寫(&I)")

T_("&Replace")
csCZ("N&ahradit")
deDE("&Ersetzen")
esES("&Reemplazar")
fiFI("&Korvaa")
frFR("&Remplacer")
huHU("&Csere")
itIT("&Sostituisci")
nlNL("&Vervangen")
plPL("&Zamień")
roRO("În&locuiește")
ruRU("&Заменить")
skSK("N&ahradiť")
srSP("&Zameni")
trTR("&Değiştir")
zhCN("替换(&R)")
zhTW("取代(&R)")

T_("Header")
csCZ("Záhlaví")
deDE("Überschrift")
esES("Encabezado")
fiFI("Otsikko")
frFR("En-tête")
huHU("Fejléc")
itIT("Intestazione")
nlNL("Kop")
plPL("Nagłówek")
roRO("Antet")
ruRU("Заголовок")
skSK("Záhlavie")
srSP("Zaglavlje")
trTR("Üstbilgi")
zhCN("头")
zhTW("標頭")

T_("Number of columns")
csCZ("Počet sloupců")
deDE("Anzahl der Spalten")
esES("N�mero de columnas")
fiFI("Sarakkeitten lukumäärä")
frFR("Nombre de colonnes")
huHU("Oszlopok száma")
itIT("Numero di colonne")
nlNL("Aantal kolommen")
plPL("Liczba kolumn")
roRO("Număr coloane")
ruRU("Число столбцов")
skSK("Počet stĺpcov")
srSP("BRoj kolona")
trTR("Sütun sayısı")
zhCN("列数")
zhTW("行數")

T_("Right margin")
csCZ("Pravý okraj")
deDE("Rechter Rand")
esES("Margen derecho")
fiFI("Oikea marginaali")
frFR("Marge de droite")
huHU("Jobb szegély")
itIT("Margine destro")
nlNL("Marge rechts")
plPL("Prawy margines")
roRO("Margine din dreapta")
ruRU("Поле справа")
skSK("Pravý okraj")
srSP("Desna margina")
trTR("Sağdan boşluk")
zhCN("右空白")
zhTW("右邊空白")

T_("Frame")
csCZ("Rámeček")
deDE("Rahmen")
esES("Marco")
fiFI("Kehys")
frFR("Cadre")
huHU("Keret")
itIT("Riquadro")
nlNL("Scherm")
plPL("Obramowanie")
roRO("Cadru")
ruRU("Рамка")
skSK("Rámček")
srSP("Okvir")
trTR("Çerçeve")
zhCN("边框")
zhTW("邊框")

T_("color")
csCZ("barva")
deDE("Farbe")
esES("color")
fiFI("väri")
frFR("couleur")
huHU("szín")
itIT("Colore")
nlNL("kleur")
plPL("kolor")
roRO("culoare")
ruRU("цвет")
skSK("farba")
srSP("boja")
trTR("renk")
zhCN("颜色")
zhTW("顏色")

T_("Grid")
csCZ("Mřížka")
deDE("Gitternetz")
esES("Trama")
fiFI("Gridi")
frFR("grille")
huHU("Illesztőrács")
itIT("Griglia")
nlNL("Raster")
plPL("Siatka")
roRO("Grilă")
ruRU("Сетка")
skSK("Mriežka")
srSP("Mreža")
trTR("Kılavuz")
zhCN("格")
zhTW("網格")

T_("Keep rows together")
csCZ("")
deDE("")
esES("Mantener las filas juntas")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("Koppel rijen aan elkaar")
plPL("")
roRO("Ține liniile împreună")
ruRU("")
skSK("Zachovať zoskupenie riadkov")
srSP("")
trTR("")
zhCN("绑定多行")
zhTW("保持列在一起")

T_("Equalize")
csCZ("Vyrovnat")
deDE("Angleichen")
esES("Ecualizar")
fiFI("Normalisoi")
frFR("Egaliser")
huHU("Kiegyenlítés")
itIT("Equalizza")
nlNL("Vereffenen")
plPL("Wyrównaj")
roRO("Egalizează")
ruRU("")
skSK("Vyrovnať")
srSP("Izjednači")
trTR("Eşitle")
zhCN("相等")
zhTW("相等")

T_("Remove table")
csCZ("Odstranit tabulku")
deDE("Tabelle entfernen")
esES("Eliminar tabla")
fiFI("Poista taulukko")
frFR("Supprimer le tableau")
huHU("Táblázat törlése")
itIT("Rimuovi tabella")
nlNL("Verwijder tabel")
plPL("Usuń tabelę")
roRO("Șterge tabel")
ruRU("Удалить таблицу")
skSK("Odstrániť tabuľku")
srSP("Ukloni tabelu")
trTR("Tabloyu kaldır")
zhCN("删除表格")
zhTW("移除表格")

T_("Horizontal")
csCZ("Vodorovně")
deDE("Horizontal")
esES("Horizontal")
fiFI("Vaakasuuntainen")
frFR("Horizontal")
huHU("Vízszintes")
itIT("Orizzontale")
nlNL("Horizontaal")
plPL("Poziomy")
roRO("Orizonatal")
ruRU("Горизонтально")
skSK("Vodorovne")
srSP("Horizontalno")
trTR("Yatay")
zhCN("水平")
zhTW("水平")

T_("Vertical")
csCZ("Svisle")
deDE("Vertikal")
esES("Vertical")
fiFI("Pystysuuntainen")
frFR("Vertical")
huHU("Függőleges")
itIT("Verticale")
nlNL("Verticaal")
plPL("Pionowy")
roRO("Vertical")
ruRU("Вертикально")
skSK("Zvisle")
srSP("Vertikalno")
trTR("Dikey")
zhCN("垂直")
zhTW("垂直")

T_("Borders")
csCZ("Ohraničení")
deDE("Rahmen")
esES("Bordes")
fiFI("Rajat")
frFR("Bordures")
huHU("Határvonalak")
itIT("Bordi")
nlNL("Randen")
plPL("Ramki")
roRO("Contur")
ruRU("Рамки")
skSK("Ohraničenia")
srSP("Granice")
trTR("Kenarlıklar")
zhCN("边框")
zhTW("邊界")

T_("Top")
csCZ("Nahoře")
deDE("Oben")
esES("Superior")
fiFI("Ylä")
frFR("Haut")
huHU("Felső szél")
itIT("Alto")
nlNL("Boven")
plPL("Góra")
roRO("Partea de sus")
ruRU("Верх")
skSK("Hore")
srSP("Vrh")
trTR("Üst")
zhCN("上部")
zhTW("上部")

T_("Bottom")
csCZ("Dole")
deDE("Unten")
esES("Inferior")
fiFI("Ala")
frFR("Base")
huHU("Alsó szél")
itIT("Basso")
nlNL("Beneden")
plPL("Dół")
roRO("Partea de jos")
ruRU("Низ")
skSK("Dole")
srSP("Dno")
trTR("Alt")
zhCN("底部")
zhTW("底部")

T_("Margins")
csCZ("Okraje")
deDE("Ränder")
esES("M�rgenes")
fiFI("Marginaalit")
frFR("Marges")
huHU("Margók")
itIT("Margini")
nlNL("Marges")
plPL("Marginesy")
roRO("Margini")
ruRU("Поля")
skSK("Okraje")
srSP("Margine")
trTR("Kenar boşlukları")
zhCN("空白")
zhTW("空白")

T_("Align")
csCZ("Zarovnání")
deDE("Ausrichten")
esES("Alinear")
fiFI("Tasaa")
frFR("Aligner")
huHU("Igazítás")
itIT("Allinea")
nlNL("Uitlijnen")
plPL("Wyrównanie")
roRO("Aliniament")
ruRU("Выровнять")
skSK("Zarovnanie")
srSP("Poravnanje")
trTR("Yasla")
zhCN("对齐")
zhTW("對齊")

T_("Top\nCenter\nBottom")
csCZ("Horní okraj\nStřed\nDolní okraj")
deDE("Oben\nMitte\nUnten")
esES("Superior\nCentro\nInferior")
fiFI("Ylös\nKeskelle\nAlas")
frFR("Haut\nCentrer\nBas")
huHU("Felülre\nKözépre\nAlulra")
itIT("Ato\nCentro\nBasso")
nlNL("Boven\nMidden\nBeneden")
plPL("Góra\nŚrodek\nDół")
roRO("Sus\nCentru\nJos")
ruRU("Верх\nЦентр\nНиз")
skSK("Horný okraj\nStred\nDolný okraj")
srSP("Vrh\nSredina\nDno")
trTR("Üst\nOrta\nAlt")
zhCN("上\n中\n下")
zhTW("上\n中\n下")

T_("Border")
csCZ("Ohraničení")
deDE("Rahmen")
esES("Borde")
fiFI("Raja")
frFR("Bordure")
huHU("Határvonal")
itIT("Bordo")
nlNL("Rand")
plPL("Ramka")
roRO("Contur")
ruRU("Рамка")
skSK("Ohraničenie")
srSP("Granica")
trTR("Kenarlık")
zhCN("边框")
zhTW("邊界")

T_("Background")
csCZ("Pozadí")
deDE("Hintergrund")
esES("Fondo")
fiFI("Tausta")
frFR("Arrière-plan")
huHU("Háttér")
itIT("Sfondo")
nlNL("Achtergrond")
plPL("TŁo")
roRO("Fundal")
ruRU("Цвет фона")
skSK("Pozadie")
srSP("Pozadina")
trTR("Arkaplan")
zhCN("背景")
zhTW("背景")

T_("Minimal height")
csCZ("Minimální výška")
deDE("Mindesthöhe")
esES("Altura m�nima")
fiFI("Vähimmäiskorkeus")
frFR("")
huHU("Minimális magasság")
itIT("")
nlNL("Minimale hoogte")
plPL("Minimalna wysokość")
roRO("Înălțime minimă")
ruRU("Минимальная высота")
skSK("Minimálna výška")
srSP("")
trTR("Asgari boyut")
zhCN("最小高的")
zhTW("最小高度")

T_("Keep with next line")
csCZ("Svázat s následujícím řádkem")
deDE("Mit nächster Zeile zusammenhalten")
esES("Unir a l�nea siguiente")
fiFI("Pidä yhdessä seuraavan rivin kanssa")
frFR("Garder pour la prochaine ligne")
huHU("Következő sorral tartás")
itIT("Mantieni con la riga successiva")
nlNL("Met de volgende lijn behouden")
plPL("Trzymaj z następną linią")
roRO("Păstrează lângă linia urmatoare")
ruRU("Придерживаться следующей линии")
skSK("Zviazať s nasledujúcim riadkom")
srSP("Drži sa sledećom linijom")
trTR("Sonraki ile birlikte")
zhCN("与下一行保持一致")
zhTW("與下一行保持一致")


// Obsolete

T_("Indent")
csCZ("O&dsazení:")
deDE("Einrücken")
esES("Sangr�a")
fiFI("Sisennä")
frFR("Indenter")
huHU("Behúzás")
itIT("Indent")
nlNL("Inspringen")
plPL("Wcięcie")
roRO("Indentare")
ruRU("Отступ")
skSK("O&dsadenie:")
srSP("")
trTR("Girinti")
zhCN("缩进")
zhTW("縮排")

T_("Layout")
csCZ("Rozvržení")
deDE("Layout")
esES("Dise�o")
fiFI("Asettelu")
frFR("Agencement")
huHU("Elrendezés")
itIT("Layout")
nlNL("Opmaak")
plPL("Rozkład")
roRO("Structură")
ruRU("Раскладка")
skSK("Rozvrhnutie")
srSP("Raspored")
trTR("Düzen")
zhCN("布局")
zhTW("佈局")
