#!/bin/sh

if [ ! -d "out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared/" ]
then
	#./configure --prefix=/usr
	make
fi

if  [  -d "out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared/" ]
then
	if [ ! -h "bin" ]
	then
		ln -s out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared bin
	fi
	if [ -f "out/bin/trayicon" ]
	then
		cp bin/trayicon . -f

	fi

	if [ -f "bin/trayicon" ]
	then
	if [ ! -f "bin/some_image.png" ]
	then
		cp some_image.png bin/
	fi
	cd bin
	./trayicon
	fi
else
	echo "Something went wrong ! Sorry ! \n Can't run traytest"
fi
