#!/bin/sh
if [ -f  ~/upp/uppsrc/CtrlCore/CtrlCore.h ]
then
	echo "CtrlCore.h was found"
	#cp CtrlCore.h ~/upp/uppsrc/CtrlCore/CtrlCore.h -f
	result=$(patch --dry-run -s ~/upp/uppsrc/CtrlCore/CtrlCore.h CtrlCore.h.patch  -f  2>&1)
	if [[ "$result" != *FAILED* ]]
	then
		patch -s ~/upp/uppsrc/CtrlCore/CtrlCore.h CtrlCore.h.patch  -f
		echo "CtrlCore.h patched!"
	fi
else
	echo "Cannot find CtrlCore.h!!!!"
	exit
fi


if [ ! -d "out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared/" ]
then
	./configure --prefix=/usr
	make
fi

if  [  -d "out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared/" ]
then
	if [ ! -h "bin" ]
	then
		ln -s out/trayicon/GCC32-Gcc32-Gui-Linux-Main-Shared bin
	fi
	if [ -f "out/bin/trayicon" ]
	then
		cp bin/trayicon . -f

	fi

	if [ -f "bin/trayicon" ]
	then
	if [ ! -f "bin/some_image.png" ]
	then
		cp some_image.png bin/
	fi
	cd bin
	./trayicon
	fi
else
	echo "Something went wrong ! Sorry ! \n Can't run traytest"
fi
