K_BACK = 53000,
K_BACKSPACE,

K_TAB = 9,

K_SPACE = 32,

K_RETURN = 13,
K_ENTER = K_RETURN,

K_SHIFT_KEY,
K_CTRL_KEY,
K_ALT_KEY,
K_CAPSLOCK,

K_ESCAPE = kVK_Escape|K_DELTA,
K_PRIOR = kVK_PageUp|K_DELTA,
K_PAGEUP = kVK_PageUp|K_DELTA,
K_NEXT = kVK_PageDown|K_DELTA,
K_PAGEDOWN = kVK_PageDown|K_DELTA,
K_END = kVK_End|K_DELTA,
K_HOME = kVK_Home|K_DELTA,
K_LEFT = kVK_LeftArrow|K_DELTA,
K_UP = kVK_UpArrow|K_DELTA,
K_RIGHT = kVK_RightArrow|K_DELTA,
K_DOWN = kVK_DownArrow|K_DELTA,
K_INSERT = 0, // kVK_Insert|K_DELTA, // TODO
K_DELETE = kVK_Delete|K_DELTA,

K_NUMPAD0 = kVK_ANSI_Keypad0|K_DELTA,
K_NUMPAD1 = kVK_ANSI_Keypad1|K_DELTA,
K_NUMPAD2 = kVK_ANSI_Keypad2|K_DELTA,
K_NUMPAD3 = kVK_ANSI_Keypad3|K_DELTA,
K_NUMPAD4 = kVK_ANSI_Keypad4|K_DELTA,
K_NUMPAD5 = kVK_ANSI_Keypad5|K_DELTA,
K_NUMPAD6 = kVK_ANSI_Keypad6|K_DELTA,
K_NUMPAD7 = kVK_ANSI_Keypad7|K_DELTA,
K_NUMPAD8 = kVK_ANSI_Keypad8|K_DELTA,
K_NUMPAD9 = kVK_ANSI_Keypad9|K_DELTA,

K_MULTIPLY,
K_ADD,
K_SEPARATOR,
K_SUBTRACT,
K_DECIMAL,
K_DIVIDE,
K_SCROLL,

K_F1 = kVK_F1|K_DELTA,
K_F2 = kVK_F2|K_DELTA,
K_F3 = kVK_F3|K_DELTA,
K_F4 = kVK_F4|K_DELTA,
K_F5 = kVK_F5|K_DELTA,
K_F6 = kVK_F6|K_DELTA,
K_F7 = kVK_F7|K_DELTA,
K_F8 = kVK_F8|K_DELTA,
K_F9 = kVK_F9|K_DELTA,
K_F10 = kVK_F10|K_DELTA,
K_F11 = kVK_F11|K_DELTA,
K_F12 = kVK_F12|K_DELTA,

K_A = kVK_ANSI_A|K_DELTA,
K_B = kVK_ANSI_B|K_DELTA,
K_C = kVK_ANSI_C|K_DELTA,
K_D = kVK_ANSI_D|K_DELTA,
K_E = kVK_ANSI_E|K_DELTA,
K_F = kVK_ANSI_F|K_DELTA,
K_G = kVK_ANSI_G|K_DELTA,
K_H = kVK_ANSI_H|K_DELTA,
K_I = kVK_ANSI_I|K_DELTA,
K_J = kVK_ANSI_J|K_DELTA,
K_K = kVK_ANSI_K|K_DELTA,
K_L = kVK_ANSI_L|K_DELTA,
K_M = kVK_ANSI_M|K_DELTA,
K_N = kVK_ANSI_N|K_DELTA,
K_O = kVK_ANSI_O|K_DELTA,
K_P = kVK_ANSI_P|K_DELTA,
K_Q = kVK_ANSI_Q|K_DELTA,
K_R = kVK_ANSI_R|K_DELTA,
K_S = kVK_ANSI_S|K_DELTA,
K_T = kVK_ANSI_T|K_DELTA,
K_U = kVK_ANSI_U|K_DELTA,
K_V = kVK_ANSI_V|K_DELTA,
K_W = kVK_ANSI_W|K_DELTA,
K_X = kVK_ANSI_X|K_DELTA,
K_Y = kVK_ANSI_Y|K_DELTA,
K_Z = kVK_ANSI_Z|K_DELTA,
K_0 = kVK_ANSI_0|K_DELTA,
K_1 = kVK_ANSI_1|K_DELTA,
K_2 = kVK_ANSI_2|K_DELTA,
K_3 = kVK_ANSI_3|K_DELTA,
K_4 = kVK_ANSI_4|K_DELTA,
K_5 = kVK_ANSI_5|K_DELTA,
K_6 = kVK_ANSI_6|K_DELTA,
K_7 = kVK_ANSI_7|K_DELTA,
K_8 = kVK_ANSI_8|K_DELTA,
K_9 = kVK_ANSI_9|K_DELTA,

K_CTRL_LBRACKET,
K_CTRL_RBRACKET,
K_CTRL_MINUS,
K_CTRL_GRAVE,
K_CTRL_SLASH,
K_CTRL_BACKSLASH,
K_CTRL_COMMA,
K_CTRL_PERIOD,
K_CTRL_SEMICOLON,
K_CTRL_EQUAL,
K_CTRL_APOSTROPHE,

K_BREAK,

K_PLUS       = 0, // not yet defined
K_MINUS      = 0, // not yet defined
K_COMMA      = 0, // not yet defined
K_PERIOD     = 0, // not yet defined
K_SEMICOLON  = 0, // not yet defined
K_SLASH      = 0, // not yet defined
K_GRAVE      = 0, // not yet defined
K_LBRACKET   = 0, // not yet defined
K_BACKSLASH  = 0, // not yet defined
K_RBRACKET   = 0, // not yet defined
K_QUOTEDBL   = 0, // not yet defined
