#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// ScatterCtrl.cpp

T_("%s data file")
caES("")
esES("Fichero de datos %s")
euES("")
frFR("")
huHU("%s adatf\303\241jl")

T_("Scatter plot data")
caES("")
esES("Datos del gr\303\241fico")
euES("")
frFR("")
huHU("Sz\303\263r\303\241sdiagram adat")

T_("Loading plot data from file")
caES("")
esES("Leyendo gr\303\241fico del fichero")
euES("")
frFR("")
huHU("Diagram bet\303\266lt\303\251se f\303\241jlb\303\263l")

T_("Plot has not been loaded")
caES("")
esES("Gr\303\241fico no ha sido leido")
euES("")
frFR("")
huHU("Diagram nincs bet\303\266ltve")

T_("File format \"%s\" not found")
caES("Format \"%s\" no trobat")
esES("Formato \"%s\" no encontrado")
euES("Formatua \"%s\" ez da aurkitu")
frFR("Format de fichier \"%s\" est introuvable")
huHU("\"%s\" f\303\241jlform\303\241tum nem tal\303\241lhat\303\263")

T_("Saving plot data to file")
caES("")
esES("Salvando gr\303\241fico a fichero")
euES("")
frFR("")
huHU("Diagram f\303\241jlba ment\303\251se")

T_("Plot has not been saved")
caES("El gr\303\240fic no s'ha desat")
esES("El gr\303\241fico no ha sido guardado")
euES("Lurzatia ez da gorde")
frFR("Plot n'a pas \303\251t\303\251 enregistr\303\251")
huHU("Diagram nem mentett")

T_("\316\224")
caES("")
esES("\342\210\206")
euES("")
frFR("")
huHU("\316\224")

T_("Fit to data")
caES("Ajust a les dades")
esES("Ajustar a los datos")
euES("Datuak egokitzen")
frFR("Ajust\303\251 aux donn\303\251es")
huHU("Adatilleszt\303\251s")

T_("Zoom to fit visible all data")
caES("")
esES("Zoom para ver todos los datos")
euES("")
frFR("")
huHU("Nagy\303\255t\303\241s, hogy minden adat l\303\241that\303\263 legyen")

T_("Zoom +")
caES("")
esES("")
euES("")
frFR("")
huHU("Zoom +")

T_("Zoom in (closer)")
caES("")
esES("Zoom para acercar")
euES("")
frFR("")
huHU("Nagy\303\255t\303\241s (k\303\266zel\303\255t)")

T_("Zoom -")
caES("")
esES("")
euES("")
frFR("")
huHU("Zoom -")

T_("Zoom out (away)")
caES("")
esES("Zoom para alejar")
euES("")
frFR("")
huHU("Kicsiny\303\255t\303\251s (t\303\241vol\303\255t)")

T_("Attach X axis")
caES("")
esES("Fijar eje X")
euES("")
frFR("")
huHU("X tengely csatol\303\241sa")

T_("Fix X axis so no zoom or scroll is possible")
caES("")
esES("Fijar eje X evitando scroll y zoom")
euES("")
frFR("")
huHU("R\303\266gz\303\255tse az X tengelyt, \303\255gy a nagy\303\255t\303\241s vagy g\303\266rget\303\251s nem lehets\303\251ges")

T_("Scroll Left")
caES("Moure a l'esquerra")
esES("Mover a la izquierda")
euES("Korritu Ezker")
frFR("Faites d\303\251filer \303\240 gauche")
huHU("Balra g\303\266rget\303\251s")

T_("Scrolls plot to the left")
caES("")
esES("Mueve el gr\303\241fico a la izquierda")
euES("")
frFR("")
huHU("Diagram balra g\303\266rget\303\251se")

T_("Scroll Right")
caES("More a la dreta")
esES("Mover a la derecha")
euES("Korritu eskubidea")
frFR("Faites d\303\251filer \303\240 droite")
huHU("Jobbra g\303\266rget\303\251s")

T_("Scrolls plot to the right")
caES("")
esES("Mueve el gr\303\241fico a la derecha")
euES("")
frFR("")
huHU("Diagram jobbra g\303\266rget\303\251se")

T_("Attach Y axis")
caES("")
esES("Fijar eje Y")
euES("")
frFR("")
huHU("Y tengely csatol\303\241sa")

T_("Fix Y axis so no zoom or scroll is possible")
caES("")
esES("Fijar eje Y evitando scroll y zoom")
euES("")
frFR("")
huHU("R\303\266gz\303\255tse az Y tengelyt, \303\255gy a nagy\303\255t\303\241s vagy g\303\266rget\303\251s nem lehets\303\251ges")

T_("Scroll Up")
caES("Moure amunt")
esES("Mover arriba")
euES("Korritu gora")
frFR("D\303\251filement vers le haut")
huHU("Felfel\303\251 g\303\266rget\303\251s")

T_("Scrolls plot up")
caES("")
esES("Mueve el gr\303\241fico hacia arriba")
euES("")
frFR("")
huHU("Diagram g\303\266rget\303\251se a tetej\303\251re")

T_("Scroll Down")
caES("Moure baix")
esES("Mover abajo")
euES("Korritu behera")
frFR("D\303\251filement vers le bas")
huHU("Lefel\303\251 g\303\266rget\303\251s")

T_("Scrolls plot down")
caES("")
esES("Mueve el gr\303\241fico hacia abajo")
euES("")
frFR("")
huHU("Diagram g\303\266rget\303\251se az alj\303\241ra")

T_("Properties")
caES("Propietats")
esES("Propiedades")
euES("Propietateak")
frFR("Propri\303\251t\303\251s")
huHU("Tulajdons\303\241gok")

T_("Plot properties dialog")
caES("")
esES("Di\303\241logo de propiedades del gr\303\241fico")
euES("")
frFR("")
huHU("Diagram tulajdons\303\241gai dial\303\263gus")

T_("View Data")
caES("")
esES("Ver datos")
euES("")
frFR("")
huHU("Adatok megtekint\303\251se")

T_("Raw data table")
caES("")
esES("Tabla de datos base")
euES("")
frFR("")
huHU("Nyers adat t\303\241bl\303\241zat")

T_("Data Analysis")
caES("")
esES("An\303\241lisis de datos")
euES("")
frFR("")
huHU("Adatelemz\303\251s")

T_("Data processing dialog")
caES("")
esES("Di\303\241logo para procesado de datos")
euES("")
frFR("")
huHU("Adatfeldolgoz\303\241s dial\303\263gus")

T_("Copy image")
caES("")
esES("Copiar imagen")
euES("")
frFR("")
huHU("K\303\251p m\303\241sol\303\241sa")

T_("Copy image to clipboard")
caES("")
esES("Copiar imagen al portapapeles")
euES("")
frFR("")
huHU("K\303\251p m\303\241sol\303\241sa v\303\241g\303\263lapra")

T_("Save image")
caES("")
esES("Guardar imagen")
euES("")
frFR("")
huHU("K\303\251p ment\303\251se")

T_("Save image to file")
caES("")
esES("Guardar imagen en un fichero")
euES("")
frFR("")
huHU("K\303\251p ment\303\251se f\303\241jlba")

T_("Load plot")
caES("")
esES("Leer gr\303\241fico")
euES("")
frFR("")
huHU("Diagram bet\303\266lt\303\251se")

T_("Load plot from file")
caES("")
esES("Leer gr\303\241fico de fichero")
euES("")
frFR("")
huHU("Diagram bet\303\266lt\303\251se f\303\241jlb\303\263l")

T_("Save plot")
caES("")
esES("Salvar gr\303\241fico")
euES("")
frFR("")
huHU("Diagram ment\303\251se")

T_("Save plot to file")
caES("")
esES("Salvar gr\303\241fico a fichero")
euES("")
frFR("")
huHU("Diagram ment\303\251se f\303\241jlba")

T_("%s bitmap file")
caES("")
esES("Fichero de mapa de bits %s")
euES("")
frFR("")
huHU("%s bitmap f\303\241jl")

T_("%s vector file")
caES("")
esES("Fichero vectorial %s")
euES("")
frFR("")
huHU("%s vector f\303\241jl")

T_("Scatter plot")
caES("")
esES("Gr\303\241fico")
euES("")
frFR("")
huHU("Sz\303\263r\303\241sdiagram")

T_("Saving plot image to file")
caES("")
esES("Salvando imagen del gr\303\241fico a fichero")
euES("")
frFR("")
huHU("Diagram k\303\251pe ment\303\251se f\303\241jlba")

T_("Show raw data table")
caES("")
esES("Mostrar tabla de datos")
euES("")
frFR("")
huHU("Nyers adat t\303\241bl\303\241zat mutat\303\241sa")

// ScatterCtrl.h

T_("x")
caES("")
esES("")
euES("")
frFR("")

T_("y")
caES("")
esES("")
euES("")
frFR("")

T_("y right")
caES("")
esES("y derecha")
euES("")
frFR("")
huHU("bal y")

T_("z")
caES("")
esES("")
euES("")
frFR("")


// Properties.cpp

T_("Dash \"%s\"")
caES("")
esES("Guiones \"%s\"")
euES("")
frFR("")
huHU("Gondolatjel \"%s\"")

T_("X min has to be lower than X max")
caES("")
esES("X min tiene que ser menor que X max")
euES("")
frFR("")
huHU("X min \303\251rt\303\251k\303\251nek kisebbnek kell lennie mint X max-nak")

T_("Y min has to be lower than Y max")
caES("")
esES("Y min tiene que ser menor que Y max")
euES("")
frFR("")
huHU("Y min \303\251rt\303\251k\303\251nek kisebbnek kell lennie mint Y max-nak")

T_("Y min2 has to be lower than Y max2")
caES("")
esES("Y min2 tiene que ser menor que Y max2")
euES("")
frFR("")
huHU("Y min2 \303\251rt\303\251k\303\251nek kisebbnek kell lennie mint Y max2-nek")

T_("Draw")
caES("")
esES("'Draw'")
euES("")
frFR("")
huHU("Rajzol")

T_("Painter No Antialiased")
caES("")
esES("'Painter' sin antialias")
euES("")
frFR("")
huHU("\303\211lsim\303\255t\303\241s nincs bekapcsolva")

T_("Painter Antialiased")
caES("")
esES("'Painter' con antialias")
euES("")
frFR("")
huHU("\303\211lsim\303\255t\303\241s bekapcsolva")

T_("Painter Subpixel")
caES("")
esES("'Painter' con subpixel")
euES("")
frFR("")

T_("0\302\272")
caES("")
esES("")
euES("")
frFR("")

T_("90\302\272")
caES("")
esES("")
euES("")
frFR("")

T_("180\302\272")
caES("")
esES("")
euES("")
frFR("")

T_("270\302\272")
caES("")
esES("")
euES("")
frFR("")

T_("No mark")
caES("Sense marca")
esES("Sin marca")
euES("Marka gabe")
frFR("Sans marque")

T_("You are going to delete '%s' series.&Do you agree?")
caES("")
esES("Vas a borrar la serie '%s'.&\302\277Est\303\241s de acuerdo?")
euES("")
frFR("")
huHU("T\303\266rli a(z) '%s' r\303\251szt.&Egyet\303\251rt?")


// Processing.cpp

T_("Scatter properties")
caES("Propietats de gr\303\240fic")
esES("Propiedades de gr\303\241fico")
euES("Grafikoa propietateak")
frFR("Propri\303\251t\303\251s des graphes")
huHU("Sz\303\263r\303\241s tulajdons\303\241gai")

T_("Measures")
caES("Mesures")
esES("Medidas")
euES("Neurriak")
frFR("Mesures")
huHU("M\303\251retek")

T_("Texts")
caES("Textos")
esES("Textos")
euES("Testuak")
frFR("Textes")
huHU("Sz\303\266vegek")

T_("Legend")
caES("Llegenda")
esES("Leyenda")
euES("Kondaira")
frFR("L\303\251gende")
huHU("Felirat")

T_("Series")
caES("S\303\250ries")
esES("Series")
euES("Series")
frFR("S\303\250ries")
huHU("Sorozatok")

T_("General")
caES("")
esES("")
euES("")
frFR("")
huHU("\303\201ltal\303\241nos")

T_("Name")
caES("Nom")
esES("Nombre")
euES("Izena")
frFR("Nom")

T_("Id")
caES("")
esES("")
euES("")
frFR("")
huHU("Azonos\303\255t\303\263")

T_("Processing")
caES("")
esES("Procesado")
euES("")
frFR("")
huHU("Feldolgoz\303\241s")

T_("Frequency")
caES("")
esES("Frecuencia")
euES("")
frFR("")
huHU("Frekvencia")

T_("Operations")
caES("")
esES("Operaciones")
euES("")
frFR("")
huHU("M\305\261veletek")

T_("Best fit")
caES("")
esES("Mejor ajuste")
euES("")
frFR("")
huHU("Legjobban illeszked\305\221")

T_("Histogram")
caES("")
esES("Histograma")
euES("")
frFR("")
huHU("Hisztogram")

T_("Numerical derivative including derivative order and accuracy (related "
     "to window size)")
caES("")
esES("")
euES("")
frFR("")

T_("Implemented orders are 1 (first) and 2 (second derivative)")
caES("")
esES("Los ordenes incluidos son 1 (promera) and 2 (segunda derivada)")
euES("")
frFR("")

T_("Implemented accuracies are 2, 4, 6 and 8")
caES("")
esES("Las precisiones implementadas son 2, 4, 6 y 8")
euES("")
frFR("")

T_("Savitzky\342\200\223Golay filter including derivative order, window size "
     "and polynomial degree")
caES("")
esES("Filtro Savitzky\342\200\223Golay incluyendo el orden de la derivada, tama\303\261o de la ventana y grado del polinomio")
euES("")
frFR("")

T_("Implemented orders are 0 (just filter), 1 (first) and 2 (second derivative)")
caES("")
esES("Los ordenes implementados son 0 (solo filtro), 1 (primera) y 2 (segunda derivada)")
euES("")
frFR("")

T_("Window size")
caES("")
esES("Tama\303\261o de ventana")
euES("")
frFR("")

T_("Polynomial degree")
caES("")
esES("Grado del polinomio")
euES("")
frFR("")

T_("FFT filter indicating period from which and to which to filter")
caES("")
esES("Filtro FFT indicando per\303\255odo desde y hasta el cual filtrar")
euES("")
frFR("")

T_("Period from which to filter")
caES("")
esES("Per\303\255odo desde el cual filtrar")
euES("")
frFR("")

T_("Period to which to filter")
caES("")
esES("Per\303\255odo hasta el cual filtrar")
euES("")
frFR("")

T_("To show real equation coefficients with different precisions or just in "
     "text")
caES("")
esES("Para mostrar los coeficientes de la ecuaci\303\263n real con diferentes "
     "precisiones o solo en el texto")
euES("")
frFR("")

T_("Min. R2 to plot the equation")
caES("")
esES("M\303\255n. R2 para mostrar ecuaci\303\263n")
euES("")
frFR("")

T_("User suppled equation. Initial guess values separated with ';'")
caES("")
esES("Ecuaci\303\263n de usuario. Valores iniciales estimados separados con "
     "';'")
euES("")
frFR("")

T_("Type")
caES("")
esES("Tipo")
euES("")
frFR("")

T_("Equation")
caES("")
esES("Ecuaci\303\263n")
euES("")
frFR("")

T_("R2")
caES("")
esES("")
euES("")
frFR("")

T_("It tries to fit the series with the supported equations")
caES("")
esES("Intenta ajustar la serie con las ecuaciones incluidas")
euES("")
frFR("")

T_("X")
caES("")
esES("")
euES("")
frFR("")

T_("Y")
caES("")
esES("")
euES("")
frFR("")

T_("Select all")
caES("Seleccionar tot")
esES("Seleccionar todo")
euES("Hautatu guztiak")
frFR("S\303\251lectionner tout")

T_("Select all rows")
caES("Seleccionar totes les files")
esES("Seleccionar todas las filas")
euES("Hautatu errenkada guztiak")
frFR("S\303\251lectionnez toutes les lignes")

T_("Copy")
caES("Copiar")
esES("Copiar")
euES("Kopiatu")
frFR("Copier")

T_("Copy selected rows")
caES("")
esES("Copiar files selecc.")
euES("")
frFR("")

T_("Fitting...")
caES("")
esES("Ajustando...")
euES("")
frFR("")

T_("Searching for the function that best fits")
caES("")
esES("Buscando la funci\303\263n que mejor se ajusta")
euES("")
frFR("")

T_("'x >' has to be lower than 'x <'")
caES("")
esES("'x >' tiene que ser menor que 'x <'")
euES("")
frFR("")

T_("Max")
caES("")
esES("M\303\241x")
euES("")
frFR("")

T_("Min")
caES("")
esES("M\303\255n")
euES("")
frFR("")

T_("MovAvg")
caES("")
esES("MedMov")
euES("")
frFR("")

T_("SecAvg")
caES("")
esES("MedSeg")
euES("")
frFR("")

T_("CumAvg")
caES("")
esES("AcumProm")
euES("")
frFR("")

T_("Impossible to filter series")
caES("")
esES("")
euES("")
frFR("")

T_("Impossible to calculate FFT from a not sampled series")
caES("")
esES("Imposible calcular FFT de una serie no muestreada")
euES("")
frFR("")

T_("Insufficient data to calculate FFT")
caES("")
esES("Datos insufucientes para calcular FFT")
euES("")
frFR("")

T_("Sampling time changes from %f to %f")
caES("")
esES("El tiempo de muestreo varia entre %f y %f")
euES("")
frFR("")

T_("Processed")
caES("")
esES("Procesado")
euES("")
frFR("")

T_("Impossible to calculate histogram from a not sampled series")
caES("")
esES("")
euES("")
frFR("")

T_("Insufficient data to calculate histogram")
caES("")
esES("")
euES("")
frFR("")

T_("Average")
caES("")
esES("Promedio")
euES("")
frFR("")

T_("Linear")
caES("")
esES("Lineal")
euES("")
frFR("")

T_("Cuadratic")
caES("")
esES("Cuadr\303\241tico")
euES("")
frFR("")

T_("Cubic")
caES("")
esES("C\303\272bico")
euES("")
frFR("")

T_("Sinusoidal")
caES("")
esES("")
euES("")
frFR("")

T_("Sinusoidal tend")
caES("")
esES("Tend. sinusoidal")
euES("")
frFR("")

T_("Spline")
caES("")
esES("")
euES("")
frFR("")

T_("Der_%d")
caES("")
esES("")
euES("")
frFR("")

T_("S_G_%d")
caES("")
esES("")
euES("")
frFR("")

T_("FFT_filter")
caES("")
esES("Filtro FFT")
euES("")
frFR("")

T_("Incorrect sampling time")
caES("")
esES("Tiempo de muestreo incorrecto")
euES("")
frFR("")

T_("Error obtaining FFT")
caES("")
esES("Error obteniendo FFT")
euES("")
frFR("")

T_("FFT")
caES("")
esES("")
euES("")
frFR("")

T_("FFT-phase [rad]")
caES("")
esES("FFT-fase [rad]")
euES("")
frFR("")

T_("Power Spectral Density")
caES("")
esES("Espectro de densidad energ\303\251tica")
euES("")
frFR("")

T_("Frequency [Hz]")
caES("")
esES("Frecuencia [Hz]")
euES("")
frFR("")

T_("Period [sec]")
caES("")
esES("Periodo [seg]")
euES("")
frFR("")

T_("Min val %d has to be lower than Max val %f")
caES("")
esES("El valor minimo Min %d ha de ser menor que el m\303\241ximo Max %f")
euES("")
frFR("")

T_("Number")
caES("")
esES("N\303\272mero")
euES("")
frFR("")


// Properties.h

T_("Font")
caES("")
esES("Fuente")
euES("")
frFR("")


// Data.cpp

T_("Scatter data")
caES("Dades del gr\303\240fic")
esES("Datos del gr\303\241fico")
euES("Datuak taula")
frFR("Tableau de donn\303\251es")

T_("All")
caES("")
esES("Todo")
euES("")
frFR("")

T_("%s file")
caES("Fitxer %s")
esES("Fichero %s")
euES("Fitxategia %s")
frFR("Fichier %s")

T_("Comma separated values (.csv)")
caES("")
esES("Valores separados por coma (.csv)")
euES("")
frFR("")

T_("Saving plot data")
caES("")
esES("Salvando los datos del gr\303\241fico")
euES("")
frFR("")

T_("Plot data has not been saved")
caES("")
esES("Los datos del gr\303\241fico no han sido salvados")
euES("")
frFR("")

T_("No row selected")
caES("")
esES("Ninguna fila seleccionada")
euES("")
frFR("")

T_("Selected %d rows")
caES("")
esES("Seleccionadas %d filas")
euES("")
frFR("")

T_("Copy selected rows to clipboard")
caES("")
esES("Copiar filas seleccionadas al portapapeles")
euES("")
frFR("")

T_("Save to file")
caES("Guardar a fitxer")
esES("Guardar en fichero")
euES("Gorde fitxategira")
frFR("Enregistrer dans un fichier")

T_("Save to .csv file")
caES("")
esES("Salvar a fichero .csv")
euES("")
frFR("")


// PieCtrl.cpp

T_("Pie plot")
caES("")
esES("Gr\303\241fico de tarta")
euES("")
frFR("")

T_("Saving plot to PNG or JPEG file")
caES("Guardant gr\303\240fic en fitxer PNG o JPEG")
esES("Guardando gr\303\241fico en fichero PNG o JPEG")
euES("Aurrezteko grafikoa PNG edo JPEG fitxategia")
frFR("Enregistrement plot visant \303\240 fichier PNG ou JPEG")


// ScatterCtrl.lay

T_("OK")
caES("Continuar")
esES("Continuar")
euES("")
frFR("")

T_("Close this dialog")
caES("Tancar aquesta finestra")
esES("Cerrar este di\303\241logo")
euES("Itxi elkarrizketa hau")
frFR("Fermez cette bo\303\256te de dialogue")

T_("X max")
caES("")
esES("")
euES("")
frFR("")

T_("Y max 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y max")
caES("")
esES("")
euES("")
frFR("")

T_("Y min unit")
caES("")
esES("Y min unid")
euES("")
frFR("")

T_("Y major unit")
caES("")
esES("Y may unid")
euES("")
frFR("")

T_("X min unit")
caES("")
esES("X min unid")
euES("")
frFR("")

T_("X min")
caES("")
esES("")
euES("")
frFR("")

T_("Numbers")
caES("")
esES("")
euES("")
frFR("")

T_("Reticle")
caES("")
esES("Ret\303\255cula")
euES("")
frFR("")

T_("Attach")
caES("")
esES("Fijar")
euES("")
frFR("")

T_("Grid")
caES("")
esES("")
euES("")
frFR("")

T_("Color:")
caES("Color:")
esES("Color:")
euES("Kolorea")
frFR("Couleur")

T_("Dash:")
caES("Gui\303\263:")
esES("Gui\303\263n:")
euES("Marraz:")
frFR("Tiret:")

T_("Thickness:")
caES("Espessor:")
esES("Espesor")
euES("Lodiera:")
frFR("\303\211paisseur:")

T_("X major unit")
caES("")
esES("X may unid")
euES("")
frFR("")

T_("Y min 2")
caES("")
esES("")
euES("")
frFR("")

T_("Y min")
caES("")
esES("")
euES("")
frFR("")

T_("Label Y2:")
caES("Etiqueta Y2:")
esES("Etiqueta Y2:")
euES("Etiketa Y2:")
frFR("\303\211tiquette Y2:")

T_("Title:")
caES("T\303\255tol:")
esES("T\303\255tulo:")
euES("Izenburua:")
frFR("Titre:")

T_("Label X:")
caES("Etiqueta X:")
esES("Etiqueta X:")
euES("Etiketa X:")
frFR("\303\211tiquette X:")

T_("Top margin:")
caES("")
esES("Margen superior:")
euES("")
frFR("")

T_("Label Y:")
caES("Etiqueta Y:")
esES("Etiqueta Y:")
euES("Etiketa Y:")
frFR("\303\211tiquette Y:")

T_("Click to set background color")
caES("")
esES("")
euES("")
frFR("")

T_("Right margin:")
caES("")
esES("Margen derecho:")
euES("")
frFR("")

T_("Bottom margin:")
caES("")
esES("Margen inferior:")
euES("")
frFR("")

T_("Left margin:")
caES("")
esES("Margen izquierdo:")
euES("")
frFR("")

T_("Show Legend")
caES("Mostra llegenda")
esES("Mostrar leyenda")
euES("Erakutsi legenda")
frFR("Afficher la l\303\251gende")

T_("Top\nTable")
caES("Dalt\nTaula")
esES("Arriba\nTabla")
euES("Sortu\nTaula")
frFR("Haut\nTable")

T_("Position")
caES("Posici\303\263")
esES("Posici\303\263n")
euES("Kokaleku")
frFR("Position")

T_("Left-Top")
caES("Esq-Dalt")
esES("Izq-Arriba")
euES("Ezker-Sortu")
frFR("Gauche-Haut")

T_("Right-Top")
caES("Dret-Dalt")
esES("Der-Arriba")
euES("Esku-Sortu")
frFR("Droit-Haut")

T_("Left-Bottom")
caES("Esq-Fons")
esES("Izq-Abajo")
euES("Ezker-Behean")
frFR("Gauche-Bas")

T_("Right-Bottom")
caES("Dret-Fons")
esES("Der-Abajo")
euES("Esku-Behean")
frFR("Droit-Bas")

T_("Vertical:")
caES("Vertical:")
esES("Vertical:")
euES("Bertikal:")
frFR("Vertical:")

T_("Column number:")
caES("Nombre de columna:")
esES("N\303\272mero de columnas:")
euES("Zutabe kopurua:")
frFR("Num\303\251ro de colonne:")

T_("Row spacing:")
caES("Dist\303\240ncia entre l\303\255nies:")
esES("Distancia entre lineas:")
euES("Errenkada tartea:")
frFR("\303\211cartement des rangs:")

T_("Border color:")
caES("Color de la vora:")
esES("Color del borde:")
euES("Ertzean kolorea:")
frFR("Couleur de la bordure")

T_("Horiz.:")
caES("Horiz.:")
esES("Horiz.:")
euES("Horitz.:")
frFR("Horiz.:")

T_("Fill color:")
caES("Color de farciment:")
esES("Color de relleno:")
euES("Kolore betegarri:")
frFR("Couleur de remplissage:")

T_("Distance to corner")
caES("Dist\303\240ncia a la cantonada:")
esES("Distancia a la esquina:")
euES("Txoko distantzia:")
frFR("Distance \303\240 coin:")

T_("Anchor corner")
caES("Cantonada d'ancoratge")
esES("Esquina de anclaje")
euES("Txoko aingura")
frFR("Ancrage de coin")

T_("Table")
caES("Taula")
esES("Tabla")
euES("Taula")
frFR("Table")

T_("Rotate:")
caES("")
esES("Rotar:")
euES("")
frFR("")

T_("Painting method:")
caES("")
esES("Metodo pintado:")
euES("")
frFR("")

T_("Save dimensions")
caES("")
esES("Guardar dimensiones")
euES("")
frFR("")

T_("Height:")
caES("")
esES("Altura:")
euES("")
frFR("")

T_("Sensitivity:")
caES("")
esES("Sensibilidad:")
euES("")
frFR("")

T_("Width:")
caES("Ample:")
esES("Anchura:")
euES("Zabalera:")
frFR("Largeur:")

T_("Responsive")
caES("")
esES("Respuesta")
euES("")
frFR("")

T_("JPG quality:")
caES("")
esES("Calidad JPG:")
euES("")
frFR("")

T_("Apply to all plots")
caES("")
esES("")
euES("")
frFR("")

T_("Remove")
caES("")
esES("Borrar")
euES("")
frFR("")

T_("Primary")
caES("Prim\303\240ria")
esES("Primaria")
euES("Lehen")
frFR("Primaire")

T_("Visible")
caES("Visible")
esES("Visible")
euES("Ikusgai")
frFR("Visible")

T_("Units")
caES("Unitats")
esES("Unidades")
euES("Unitateak")
frFR("Unit\303\251s")

T_("Mark")
caES("Marca")
esES("Marca")
euES("Marka")
frFR("Marque")

T_("Type:")
caES("")
esES("Tipo:")
euES("")
frFR("")

T_("Fill:")
caES("Omplir:")
esES("Relleno:")
euES("Bete:")
frFR("Remplir:")

T_("X axis:")
caES("Eix X:")
esES("Eje X:")
euES("X ardatzean:")
frFR("Axe X:")

T_("Y axis:")
caES("Eix Y:")
esES("Eje Y:")
euES("Y ardatzean:")
frFR("Axe Y:")

T_("Line:")
caES("L\303\255nia:")
esES("L\303\255nea:")
euES("Line:")
frFR("Ligne:")

T_("Name:")
caES("Nom:")
esES("Nombre:")
euES("Izena:")
frFR("Nom:")

T_("Style:")
caES("Estil:")
esES("Estilo:")
euES("Tankera:")
frFR("Style:")

T_("Show legend")
caES("")
esES("Mostrar leyenda")
euES("")
frFR("")

T_("Close")
caES("Tancar")
esES("Cerrar")
euES("Itxi")
frFR("Fermer")

T_("Sin. tend.")
caES("")
esES("Tend. sin.")
euES("")
frFR("")

T_("Filter FFT")
caES("")
esES("Filtro FFT")
euES("")
frFR("")

T_("Filter S\342\200\223G")
caES("")
esES("Filtro S-G")
euES("")
frFR("")

T_("Show Eq.")
caES("")
esES("Most. eq.")
euES("")
frFR("")

T_("Max curve")
caES("")
esES("Curva m\303\241x.")
euES("")
frFR("")

T_("Min curve")
caES("")
esES("Curva m\303\255n.")
euES("")
frFR("")

T_("Moving Average")
caES("")
esES("Media m\303\263vil")
euES("")
frFR("")

T_("Cumulative Average")
caES("")
esES("Promedio acumulado")
euES("")
frFR("")

T_("Sector Average")
caES("")
esES("Promed. sector")
euES("")
frFR("")

T_("Autosens")
caES("")
esES("")
euES("")
frFR("")

T_("Max imp.:")
caES("")
esES("")
euES("")
frFR("")

T_("R2 coeff.")
caES("")
esES("R2 coef.")
euES("")
frFR("")

T_("Num decimals:")
caES("")
esES("N\303\272m decimales:")
euES("")
frFR("")

T_("Num. min:")
caES("")
esES("N\303\272m. min:")
euES("")
frFR("")

T_("Max:")
caES("")
esES("M\303\241x:")
euES("")
frFR("")

T_("MPM:")
caES("")
esES("")
euES("")
frFR("")

T_("Most probable maximum value")
caES("")
esES("M\303\241ximo m\303\241s probable")
euES("")
frFR("")

T_("Average:")
caES("")
esES("Promedio:")
euES("")
frFR("")

T_("Sensitivity")
caES("")
esES("Sensibilidad")
euES("")
frFR("")

T_("Statistical data")
caES("")
esES("Datos estadisticos")
euES("")
frFR("")

T_("RMS:")
caES("")
esES("Med. cuad.:")
euES("")
frFR("")

T_("Min:")
caES("")
esES("M\303\255n:")
euES("")
frFR("")

T_("To T:")
caES("")
esES("Hasta T:")
euES("")
frFR("")

T_("Order:")
caES("")
esES("Orden:")
euES("")
frFR("")

T_("Deg:")
caES("")
esES("Grad:")
euES("")
frFR("")

T_("Derivative")
caES("")
esES("Derivada")
euES("")
frFR("")

T_("Accuracy:")
caES("")
esES("Precisi\303\263n:")
euES("")
frFR("")

T_("W. Size:")
caES("")
esES("Tam. ven:")
euES("")
frFR("")

T_("Num. max:")
caES("")
esES("N\303\272m. max:")
euES("")
frFR("")

T_("StdDev:")
caES("")
esES("DevEst:")
euES("")
frFR("")

T_("From T:")
caES("")
esES("Desde T:")
euES("")
frFR("")

T_("x <")
caES("")
esES("")
euES("")
frFR("")

T_("Conditions")
caES("")
esES("Condiciones")
euES("")
frFR("")

T_("x >")
caES("")
esES("")
euES("")
frFR("")

T_("sec")
caES("")
esES("seg")
euES("")
frFR("")

T_("Sampling time:")
caES("")
esES("Tiempo de muestreo:")
euES("")
frFR("")

T_("Time\nFrequency")
caES("")
esES("Tiempo\nFrecuencia")
euES("")
frFR("")

T_("Subdivision")
caES("")
esES("Subdivisi\303\263n")
euES("")
frFR("")

T_("Spectral moments")
caES("")
esES("Momentos espectrales")
euES("")
frFR("")

T_("FFT\nPhase\nPSD")
caES("")
esES("FFT\nFase\nPSD")
euES("")
frFR("")

T_("Overlapping:")
caES("")
esES("Solapamiento:")
euES("")
frFR("")

T_("Number:")
caES("")
esES("N\303\272m:")
euES("")
frFR("")

T_("Window")
caES("")
esES("Ventana")
euES("")
frFR("")

T_("m0:")
caES("")
esES("")
euES("")
frFR("")

T_("m1:")
caES("")
esES("")
euES("")
frFR("")

T_("m2:")
caES("")
esES("")
euES("")
frFR("")

T_("m-1:")
caES("")
esES("")
euES("")
frFR("")

T_("X Axis")
caES("")
esES("Eje X")
euES("")
frFR("")

T_("Normal\nFull\nText")
caES("")
esES("Normal\nCompleto\nTexto")
euES("")
frFR("")

T_("Fit")
caES("")
esES("Ajustar")
euES("")
frFR("")

T_("Min R2:")
caES("")
esES("M\303\255n R2:")
euES("")
frFR("")

T_("Coefficients")
caES("")
esES("Coeficientes")
euES("")
frFR("")

T_("User equation:")
caES("")
esES("Ecuacion usuario:")
euES("")
frFR("")

T_("Number: ")
caES("")
esES("N\303\272mero: ")
euES("")
frFR("")

T_("Axis")
caES("")
esES("Ejes")
euES("")
frFR("")

T_("Val:")
caES("")
esES("Valor")
euES("")
frFR("")

T_("                         ")
caES("")
esES("")
euES("")
frFR("")

T_("Staggered")
caES("")
esES("")
euES("")
frFR("")

T_("Accumulative")
caES("")
esES("")
euES("")
frFR("")

T_("Normalize")
caES("")
esES("")
euES("")
frFR("")

T_("Bold")
caES("")
esES("Negrita")
euES("")
frFR("")

T_("Italic")
caES("")
esES("Cursiva")
euES("")
frFR("")

T_("NonAntiAliased")
caES("")
esES("NoAntialias")
euES("")
frFR("")


