#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// SqlArray.cpp

T_("Can't insert record.")
csCZ("Nelze vložit záznam.")
frFR("Impossible d'insérer un enregistrement")
nlNL("Kan record niet invoegen.")
zhTW("無法插入欄位.")

T_("Can't delete record.")
csCZ("Nelze smazat záznam.")
frFR("Impossible d'effacer un enregistrement")
nlNL("Kan record niet verwijderen.")
zhTW("無法刪除欄位.")

T_("Can't update record.")
csCZ("Nelze změnit záznam.")
frFR("Imùpossible de mettre à jour l'enregistrement")
nlNL("Kan record niet aanpassen.")
zhTW("無法更新欄位.")

T_("Do you really want to delete the selected %s ?")
csCZ("Smazat aktuální %s ?")
frFR("Voulez-vous réellement supprimer le %s sélectioné ?")
nlNL("Weet je zeker dat je de geselecteerde %s wilt verwijderen?")
zhTW("真的要刪除選擇的 %s 嗎? ")

T_("Insert %s")
csCZ("Vložit %s")
frFR("Insérer %s")
nlNL("Invoegen %s")
zhTW("插入 %s")

T_("Insert a new %s into the table.")
csCZ("Vložit do tabulky nový %s.")
frFR("Insère une nouvelle %d dans la table.")
nlNL("Voeg een nieuwe %s in de tabel.")
zhTW("插入新的 %s 到表格")

T_("Copy %s")
csCZ("Kopírovat %s")
frFR("Copier %s")
nlNL("Kopieër %s")
zhTW("複製 %s")

T_("Duplicate current table %s.")
csCZ("Vložit do tabulky duplikát aktuálního %s.")
frFR("Dupliquer la table %s sélectionnée.")
nlNL("Dupliceer huidige tabel %s.")
zhTW("複製目前表格 %s.")

T_("Edit %s")
csCZ("Opravit aktuální %s")
frFR("Editer %s")
nlNL("Bewerk %s")
zhTW("編輯 %s")

T_("Edit active %s.")
csCZ("Opravit aktuální %s.")
frFR("Editer %s actif.")
nlNL("Bewerk actieve %s.")
zhTW("編輯活動 %s")

T_("Delete %s\tDelete")
csCZ("Odstranit %s\tDelete")
frFR("Supprimer %s\tSupprimer")
nlNL("Verwijder %s\tVerwijder")
zhTW("刪除%s\t刪除")

T_("Delete active %s.")
csCZ("Odstranit aktuální %s.")
frFR("Supprimer %s actif.")
nlNL("Verwijder actieve %s.")
zhTW("刪除活動 %s")

T_("record")
csCZ("záznam")
frFR("Enregistrement")
nlNL("record")
zhTW("欄位")


// SqlDlg.cpp

T_("Database error")
csCZ("Chyba při práci s databází")
frFR("Erreur de database")
nlNL("Database fout")
zhTW("資料庫錯誤")

T_("The operation has failed")
csCZ("Při provádění operace došlo k chybě")
frFR("L'opération a echouée")
nlNL("De operatie is mislukt")
zhTW("操作失敗")

T_("The operation has failed.\nOperation was canceled")
csCZ("Při provádění operace došlo k chybě.\nOperace je stornována.")
frFR("L'opération a echouée.\nOpération annulée")
nlNL("De opertie is mislukt.\nDe operatie is gëannuleerd")
zhTW("操作失敗.\n動作已被取消")

T_("SQL error!")
csCZ("Chyba SQL!")
frFR("Erreur SQL!")
nlNL("SQL fout!")
zhTW("SQL 錯誤！")


// SqlConsole.cpp

T_("Defined macros")
csCZ("Definice maker")
frFR("Macros définies")
nlNL("Gëdefinieëerde macros")
zhTW("定義macros")

T_("Macro definition")
csCZ("Definovat makro")
frFR("Définition macro")
nlNL("Macro definitie")
zhTW("Macro 的定義")

T_("Macro OK")
csCZ("Makro OK")
frFR("Macro OK")
nlNL("Macro OK")
zhTW("Macro OK")

T_("Invalid macro")
csCZ("Chybné makro")
frFR("Macro invalide")
nlNL("Ongeldige macro")
zhTW("無效的macro")

T_("Invalid")
csCZ("Chyba")
frFR("Invalid")
nlNL("Ongeldig")
zhTW("無效")

T_("Error")
csCZ("Chyba")
frFR("Erreur")
nlNL("Fout")
zhTW("錯誤")

T_("Fetched %d line(s)")
csCZ("Načteno %d řádků")
frFR("")
nlNL("%d lijn(en) opgehaald")
zhTW("擷取 %d 行")

T_("%s (%d rows)")
csCZ("%s (%d řádků)")
frFR("%s (%d lignes)")
nlNL("%s (%d rijen)")
zhTW("%s (%d 列)")

T_("%d rows")
csCZ("%d řádků")
frFR("%d colonnes")
nlNL("%d rijen")
zhTW("%d 列")

T_("%d ms")
csCZ("%d ms")
frFR("")
nlNL("%d ms")
zhTW("%d毫秒")

T_("SQL Commander")
csCZ("SQL Commander")
frFR("")
nlNL("SQL Commander")
zhTW("SQL Commander")

T_("SQL scripts (*.sql)")
csCZ("SQL předpisy (*.sql)")
frFR("")
nlNL("SQL scripts (*.sql)")
zhTW("SQL 腳本 (*.sql)")

T_("Save trace as")
csCZ("Uložit protokol jako")
frFR("Enregistrer traces sous")
nlNL("Bewaar tracering als")
zhTW("Save trace as")

T_("Database connection doesn't support running scripts.")
csCZ("Databázové spojení neumožňuje spouštění skriptů.")
frFR("Connection Database ne supporte pas l'exécution de scripts")
nlNL("Database connectie ondersteunt geen lopende scripts.")
zhTW("資料庫連接並不支援目前的腳本")

T_("Run script")
csCZ("Provést skript")
frFR("Lancer script;\r\n\r\n")
nlNL("Start script")
zhTW("運行腳本")

T_("Executing script")
csCZ("Provádím skript")
frFR("")
nlNL("Script wordt gestart")
zhTW("執行腳本")

T_("Save as script..")
csCZ("Uložit jako skript..")
frFR("")
nlNL("Bewaar als script..")
zhTW("另存為腳本..")

T_("Run script..")
csCZ("Provést skript")
frFR("")
nlNL("Start script..")
zhTW("運行腳本..")

T_("Run script quietly..")
csCZ("")
frFR("")
nlNL("Start script rustig..")
zhTW("悄悄地運行腳本..")

T_("List macros..")
csCZ("Seznam maker..")
frFR("")
nlNL("Macro's lijst..")
zhTW("列出macros..")

T_("Print record")
csCZ("Tisk záznamu")
frFR("")
nlNL("Druk record af")
zhTW("列印記錄")

T_("Print list")
csCZ("Tisk výběru")
frFR("")
nlNL("Druk lijst af")
zhTW("列印清單")

T_("Export...")
csCZ("Export...")
frFR("")
nlNL("Exporteer...")
zhTW("輸出...")

T_("Column")
csCZ("Sloupec")
frFR("")
nlNL("Kolom")
zhTW("行")

T_("Value")
csCZ("Hodnota")
frFR("")
nlNL("Waarde")
zhTW("值")

T_("Command")
csCZ("Příkaz")
frFR("")
nlNL("Commando")
zhTW("命令")

T_("Result")
csCZ("Výsledek")
frFR("")
nlNL("Resultaat")
zhTW("結果")

T_("Duration")
csCZ("Doba")
frFR("")
nlNL("Duratie")
zhTW("Duration")

T_("&Schema")
csCZ("&Schéma")
frFR("")
nlNL("&Schema")
zhTW("綱要(&S)")


// SqlObjectTree.cpp

T_("Column name")
csCZ("Název sloupce")
frFR("")
nlNL("Kolom naam")
zhTW("行標題")

T_("Type")
csCZ("Typ")
frFR("Type")
nlNL("Type")
zhTW("類型")

T_("Width")
csCZ("Šířka")
frFR("")
nlNL("Breedte")
zhTW("寬")

T_("SQL query")
csCZ("SQL dotaz")
frFR("")
nlNL("SQL query")
zhTW("SQL 查詢")

T_(" export")
csCZ(" - export")
frFR("")
nlNL(" export")
zhTW(" 輸出")

T_("Error executing [* \001%s\001]: \001%s")
csCZ("Chyba při provádění [* \001%s\001]: \001%s")
frFR("")
nlNL("Fout tijdens starten [* \001%s\001]: \001%s")
zhTW("執行[* \001%s\001]: \001%s時發生錯誤")

T_("integer")
csCZ("celé číslo")
frFR("")
nlNL("integer")
zhTW("整數")

T_("real number")
csCZ("reálné číslo")
frFR("")
nlNL("reéel nummer")
zhTW("實數")

T_("string")
csCZ("řetězec")
frFR("")
nlNL("string")
zhTW("字串")

T_("date")
csCZ("datum")
frFR("")
nlNL("datum")
zhTW("日期")

T_("date/time")
csCZ("datum/čas")
frFR("")
nlNL("datum/tijd")
zhTW("日期/時間")

T_("BLOB")
csCZ("BLOB")
frFR("")
nlNL("BLOB")
zhTW("BLOB")

T_("CLOB")
csCZ("CLOB")
frFR("")
nlNL("CLOB")
zhTW("CLOB")

T_("No columns selected!")
csCZ("Nebyly vybrány žádné sloupce.")
frFR("")
nlNL("Geen kolommen geselecteerd!")
zhTW("沒有行被選取！")

T_("Text files (*.txt)")
csCZ("Textové soubory (*.txt)")
frFR("")
nlNL("Tekst bestanden (*.txt)")
zhTW("純文字 (*.txt)")

T_("Save export as")
csCZ("Uložit export do souboru")
frFR("")
nlNL("Bewar export als")
zhTW("另存為")

T_("Error creating file [* \001%s\001].")
csCZ("Nelze vytvořit soubor [* \001%s\001].")
frFR("Erreur en créant le fichier [* \001%s\001].")
nlNL("Fout tijdens aanmaken bestand [* \001%s\001].")
zhTW("建立檔案錯誤 [* \001%s\001].")

T_("Exporting row %d")
csCZ("Exportuji řádek %d")
frFR("")
nlNL("Exporteer rij %d")
zhTW("輸出列 %d")

T_("Export aborted!")
csCZ("Export byl přerušen.")
frFR("")
nlNL("Export afgebroken!")
zhTW("取消輸出！")

T_("Error writing file %s.")
csCZ("Chyba při zápisu do souboru %s.")
frFR("")
nlNL("Fout tijdens schrijven naar bestand %s.")
zhTW("寫入檔案 %s 錯誤.")

T_("SQL object tree")
csCZ("Strom SQL objektů")
frFR("")
nlNL("SQL objecten boom")
zhTW("SQL object tree")

T_("Schemas")
csCZ("Schémata")
frFR("")
nlNL("Schema's")
zhTW("綱要")

T_("Tables")
csCZ("Tabulky")
frFR("")
nlNL("Tabellen")
zhTW("表格")

T_("Views")
csCZ("Pohledy")
frFR("")
nlNL("Aanzichten")
zhTW("Views")

T_("Sequences")
csCZ("Sekvence")
frFR("")
nlNL("Opéenvolgingen")
zhTW("序列")

T_("Primary key: ")
csCZ("Primární klíč: ")
frFR("")
nlNL("Primaire sleutel: ")
zhTW("主鍵：")

T_("Export")
csCZ("Export")
frFR("")
nlNL("Exporteer")
zhTW("輸出")


// SqlCtrl.lay

T_("SQL error:")
csCZ("SQL chyba:")
frFR("")
nlNL("SQL fout:")
zhTW("SQL 錯誤：")

T_("Error statement:")
csCZ("Chybný SQL příkaz:")
frFR("")
nlNL("Fout verklaring:")
zhTW("錯誤的敘述：")

T_("Retry")
csCZ("Opakovat")
frFR("")
nlNL("Probeer opnieuw")
zhTW("重試")

T_("Cancel")
csCZ("Storno")
frFR("Annuler")
nlNL("Afbreken")
zhTW("取消")

T_("Format:")
csCZ("Formát:")
frFR("")
nlNL("Formaat:")
zhTW("格式：")

T_("text\nSQL script")
csCZ("text\nSQL skript")
frFR("")
nlNL("tekst\nSQL script")
zhTW("text\nSQL script")

T_("Delimiters:")
csCZ("Oddělovače:")
frFR("")
nlNL("Scheidingstekens:")
zhTW("分隔符號：")

T_("tab\nsemicolons")
csCZ("tabelátory\nstředníky")
frFR("")
nlNL("tab\npuntkomma")
zhTW("tab\nsemicolons")

T_("Quoted string values")
csCZ("Textové hodnoty v uvozovkách")
frFR("")
nlNL("Genoteerde string waardes")
zhTW("引號字串值")

T_("MS-SQL identity insert")
csCZ("Identity insert pro MS-SQL")
frFR("")
nlNL("MS-SQL identiteit ingevoegd")
zhTW("MS-SQL identity insert")

T_("Object name:")
csCZ("Název objektu:")
frFR("")
nlNL("Object naam:")
zhTW("物件名稱：")

T_("OK")
csCZ("OK")
frFR("Ok")
nlNL("OK")
zhTW("確定")
