topic "Ultimate++ vs Qt (R)";
[ $$0,0#00000000000000000000000000000000:Default]
[{_}%FR-FR 
[s0;= [7 Ultimate`+`+ comparÃ© Ã  Qt ][5 (R)]&]
[s0;>*R^topic`:`/`/uppweb`/www`/vsqt`$ru`-ru^1 &]
[s0;=*^topic`:`/`/uppweb`/www`/vsd`$ru`-ru^1 &]
[s0; [2 Pour comparer Ultimate`+`+ et Qt (R), nous avons dÃ©cidÃ© de 
rÃ©implÃ©menter l`'exemple de dÃ©monstration de Qtl `"AddressBook`". 
A gauche se trouve le code U`+`+, Ã  droite l`'exemple original 
fourni par Qt.]&]
[s0;/2 &]
[s0; [/0 Qt et le logo Qt sont des marques dÃ©posÃ©es de Trolltech 
en NorvÃ¨ge, aux Etats`-Unis et dans d`'autres pays.]&]
[s0;2 &]
[s0;= [2 
@@image:1778&1704
Šƒöá€€‚Ÿþ€€€€ø÷œíÝ¯˜ÛØ½Æñ—®Ü¸àÁ‚……€‹Š‚Š–ÜøðÁÀÁ‚‚€Ÿ‚€‚€‚—€„”„„„”¬ØØÐ°   
† à‚—˜¬€ˆ¨¨ÜØ˜ðŸÁµÇ¶¬¿ÇÓÇ’ìÙÒÏŸËïó¾çÑäÍáØþ¥ÿýæÌôäæ³ùØˆˆ’È¸¼ýúô»Žþþ¿Ï¢¢’¾©÷÷÷…á§
Òÿ¯‘‘‘«¦¾æøÿøúÅ—ûß¼ÌŒßìÆ¸ãÞüñíãÆÄ±žóåùüò‘ª²¾¹ß–‰ãïÞí¶þó½Ü¾æ«òö÷ßåñþËïž·ö÷ãý×ÅøÛ
­êøÈ«ïö›´Ï÷ã·µñéæ±¾Þîüó»çûÇñõåüÝæñüþ´¾Ù½¯÷ã÷Õñ¿ì÷›ÛññûÍïîŸ‡¼¹ÏšÎã÷ÛñÙùèüó˜ÿë·±
œÛ§¼»íè¿ÿ×ŒÏ·ãÿóÔøûíø®Î˜ëù¡¾þÿÿÃÛÃø‡ïÔø‡ÝøÊ‹ýêøÌ³òøÇ¿÷•ñ§ñÙÚ±¾ü¿Û¨Æîãž—Ç¿•Ç
ŸŸýé´¾¯ÝÆ×Õñ˜ŸÊÿãŸ«ãŸ‹ñ½Ãöã‡ûÔøØÿ˜ßü÷öü½ð¸–¶ÿ»ºó¾ÞíœÇ»ïÆøò¯Ûøÿ¹îÿåãã¾ØÞþøòÍî
íã´žòÐŒ¯ÉÞ¾î¿½î¿Ú­‡í÷»ïíøòñ¬ç£¯ûñÓìßïã·ÿúœÿ¬ŒÏÛ»íŸŸ·ç‹ü”šÿÚ¼ÿþéÓãø¸ý±þÓùüýþñ
ãûýéû·þí•Óî£˜ùÓÜžÿþ×ãøÜëþù´¾©Æ¿º×ÇãÞ•ÇÇåñ×·Ÿž·Þ÷ã¯Û÷ÿ–Èÿ¸Œ¿þÿÜŽ¿ÖÇÕññÿö›Çñß
¿»Æøþ¡º²¾ü»±þïîŒã»þø°¼ÉýÃ—ùâëÞ™·îïªþ´þŒû˜ÂÿÑ–ÅþÁûÏž·ž¯”µÿ²¬ü¯®žõþÅÁø¯â›ÂÿÙÖý—
ÍßÕµÿÝõü×íý—•Õ·Ç£½ðßýÕ‘üÆãüÝá¼É¾ÞÅø»ñûÇíúŸÆÂò•±žÔçõá¿©‹ÿ§õ£äß—ªïÜˆÿ¯úòøÔ¼þÂõ¥ñ÷ï
¦òÂ¯¦­ü¿ç”…ÿîëï§éãÒø‡íÿå±¼¾¿ì×„ëÿòñûå¡ýÖŸËÂÿ–ÐýØñ¼‰ÿýÞïÕÏªªïŽ‡Éª¿¯È¾±Þÿ€øœÿ®¤ß™
ÊÏªÿÜ¾ÈþýçÂõÍ±¤ú¶…äÏªßï¬ŸÔÿ¡Ðýî¥ûÍ±Ý“þã¿Þ–Ç£ößÖçµÿ®˜Ÿ…ÿîã»ðëÉŠžÿ¯ú“ð÷úüÿèª¾œ­É
êËãÑûµáÿ­µÖó”üõ½¬‰¿®úæØþÒý‡ô¸×û·›ªä«ãÇÂÛûÿÊª¾¬üéÃöÍø§±æ¤üòøýÃïÏÅžœÃÏ²“Ÿÿê»¶™üÕ
¥æ‰±ŸçòÏ½«³ù´Ò«³ÿù”Ø÷³÷ÓîÌþûÜÌþÉ½¨³ùçÙ™üêÕéÏ÷³ùÜþœþÇºÒÏ‹»ý¶³ù„ØËŠ³ù×©¹üíî¦ÿçüœþ 
Ïôäì½å¦ŸÿšÃ÷œÉ¿¼¤ä¦ÿ¶»“¯ÜäÞšÉ·ªýÄ¸û¯¨½¹“Ø¿¤»“ÿéœÿ™üÏ‰™ü›²ÂìÿÏ‰½¶‡“ÿš¿ÔçÝò­³÷ÜÌþ
»ã¸³ù½«ûû­½ï•žŸÃôŸæïß¿È«ýþ¤ü¶Ùû·ÿåÙûËÁ³÷Ì¯‡ÌÞ“óøËÒì½½ÜÓµ½§—ë’‹¶ß§„ß¶ûïúÈþö³÷ç§
›Ùû÷íËµÒÕÿýÍøí³÷÷„ê«³÷ÓÝØáöþ¬ýöãþ¬¹ûÏÌáÞË³÷¬ê³¿÷Œð‹ÙûýÂõöÞÕýúöÃþúãíŽÿ»¿ÙûÛìì½º
“Ï¨þ¸ûÿ•¨ˆ¿íöÞžíÛæïÉ¹ü éÙûÂøí³÷³–™üåöÞ®÷üÓì½«úÆ¯ìý×Úœþý¾±“¯ÎÞËË–´Ý¿Ïº×úÄîŽßíþÿ
ÜæÑ›½ï÷Žý±Ž¿ÿÌƒ×¡áŸîÞº™¼õøëð‹ÜŸ‡¿¢á‹”óëþäœþàøêüºü±óêëðÿ‡÷Ž¡ëð…·á­ÃÛ‡·Ž°ïþñëðå
“Ãß½Ò¶úùËÏù¹üñ¾Ð°üò¾²‡¹ÿ¦µ‡¿êºÁüñŽ¿ð¾Æ²‡·ŽïÞúº¼õø¥­Ã•·©½¦ü®ó¿ø­ä‹ÙûÉíòÕíŸŒßÜ
œÙÒýîŸÏÎåò¿ì¿Ê¾º±ó´×¿ÎØÏïëðµ»¨æíŸ•ã’¯œÙÃžÃ¿½íÛ‡Ñ·ŽïÞºüŽò×áïÊŒØ¡‡¯„þÐý·œ¯ÊóöÊºü
ôùå¦¬ö„ðÂŸÅÞì—›Åûì½ØŠÉ¯Ã¾—Û…í·®®ã¶“â¯öžô”îÞº¼õøÓëðËÞ‡ïêƒ½ûºüòŽß¾Þ´©Ù»¶ŽîßÖþ—Ïê“
üýÄ¾ºÝÿÕÜÓ¶Žßì×—çóµ‡×´€ÿÔýù¦ïåÞº¼õøëðÌËÜ‡¿ôŽÿœõÂÈ•éúõÈ¾³‡¯ÖàËóøòºüÝóéÕ½íëð
ççð§™ûÍðïÖá­ÃÛ‡·–Ž¿Úõøâ‚ðßÞûÏÏá“ÔË·Õï¹–“ïó¶Ÿ¢¹úÿÜåã¹¦¾Ž¿Þ—þçãªûß¶¹ü¹Ÿ›´ŽÔïÞº¼õø
·¹¯Ãßú³´æ¥¥×–çÒßÞéý¶¾³¹‡‰¯ýÓõóé¿¾¬÷ú”¾±Õ‡¿ÝúüÉøßÊäüø³´õåÕ±·æòÖ·á­ÃÛ‡·Ž‹¿¼õø‹ÿž
Þï¥±ŽïÕÞº¼õøù®™Ã¶¼ßËãÊÞº¼õøëùðóÛ‡¿ïŒÑßËãÞº¼Ìõøëð‹Ú‡ÎÿÚ“Ëÿ¯ÑßïÞº¼Ìõøëðþ¿¼
üõøëðÖá­ÍÃÛ‡¿äþ’Ú†—‘‘°áŒø‘‘¨áø‘ã‘¨áø‘‘¨˜áø‘‘¨áøî‘‘¨éâø»Šªû½Å¨¢¢¹óÌÇÃ÷Ú¯ð¢¢óˆÃ‹ˆ
šÄÍ°Ã×ÖéÁ’ÿêÄÄÄ¦ªÍßõøâÏ¦ÉµšÏò¢¢ó»Éåóøæ÷áðÅÄäŽ¹Šáà§ÿ–¢¢ÒÌÌõÏö¢¢óß‰ï´ŠˆÄƒÿÓª¢’µç
þÿùî®–É®Ÿ³ˆˆô‰¹ë¼ˆÈÔ°¼ˆÚÈÔ°¼ˆÈÔÖ°¼ˆÈÔ°¼µˆÈÔ°¼ˆÈ­Ô°¼ˆÈÔ°ë¼ˆÈÔ°¼ˆÚÈÔ°¼ˆÈÔÖ°¼ˆÈÔ°¼
µˆÈÔ°¼ˆÈ­Ô°¼ˆÈÔ°ë¼ˆÈÔ°¼ˆöÈÔô²üö˜ÆÅÄß“”‘Ù­ô±ü‚¦ùŒ¬¯¢²éìø…ùéýóüËà›…üÑáýÈÄ¨ÆÊàÃ¯å±
þ³¼ˆŒ”À†«Ÿüá„ü´¢Û² °üäÙÖµ£•‘……á§›Ï²ž­ˆ¬¨è×´üÓÔ½ÜØÕœÜþ¨áöšÛ–³—õèÅ¼äÁ™¡á‡ýÊøß¼»ò­
Ð¦‡ÿª†—‘ù‘òõÃ×¦ßÙó´üùÖëÙã•áÅäî¹¥£áïÊ¤÷ÖÖèé²»»¼’ü˜×ï’áÅäŒî™ÃðÍéïÉªžËêº¯óéÛ˜¾ó†Ôö
þ¬ÊÿìøðúÈ¾Ú‘‘áÙ§Áá·­²Ïî—“÷ÔüÞ»©ù–ëÇÞ¦¼†ÄŒ¤êÆøÎëÞùÑç¸áË²‡—¿ªùÆÔ‡¾÷ÚÇµ¿ÏÃòÖë½Ú‘‘
ÍîÙŠá·¥ÙÐöÿ¤ÝÒËÚŒ¯¢‹Ê­ÿ²Ú²¹ÃÞ¤æ…ÎùÃ÷ùÒçõÌÚ¸ãóæáž®‡÷ŒÃ‹ÙÈÈÙÐÿé½ë¢á·¥÷–ü·Îæ»ÏÛÁŒ
È¯¢óË¢ŒŸ¯´ñÙã§ï¶‹ä£•‘…å‘‡†ï›å¹óÙáÖÄ–”†Ÿê¼Ëú´¢² ¶°üäÙÖ£•í‘……á§Ï²†ž­ˆ¬¨Œ¯È¢’µ¿ù
ƒŸØ–‘™»Û‡¯Íð¢¢«Î‰Ã‹ˆÄÃó‹ˆÄÃ‹ˆ¼ÄÃ‹ˆä³©ù·Ì»¤ù£±‚Œ¯¢’ÏÖîñŸþùéÎÙÇºšáÅÄ†äúàøÏ›Ù†á
œÅÄ†…á§¿°…¢¢£…á§ ¿…¢¢£åÂýÃïÝÛý¦Ì¡ÁŒ¯¢òõœÆŒÿËæØöÒ™îüÓæàÌ¦”´üóïáÍþ¯¾æœ¾ÿ²êÛåÉ”Õ¼éµ
£­ÞÕ™ÖòêóÛÛÜæø½±ûÛ¼ÃðƒÿžÊéÚ¢¨Ëšä»ûÓê«½Ê“ßíû›‘ŒôßþÃíÛÃðçñ¢œõµ•·Æð×ýâ«í¼ïóáËº®
ÍË¼ãÿ¥š¾¤üùÔìßöÿßùŸÍ÷…µ¬ôÝ¤Ÿàóý±ïÜÒÙ®‚·šð´üù®”ÜÓÖÎùÏÛ¿—ÿš¶ëªã…‘ñìùÕáøÌ­Æ÷í†¿ûÌó
éÒŠÿ™¥“Ð©ªÓììÖ“õ¿ÓÕ¦¶»›ò—í‚ÒüÙ×Ë¾»ü¥´ùô’®ÉÞð›Üßžúæ®Ê±¡³üÀòÏßÌæîøäõÒ»ðð²®ÊÞ¢±Ó
üÝÄÍã×ÐêÔÕŒßì ÖÅ–’›É÷•©­Ìÿ‰Å¨âØ†î™¾éê¶ŸÇ¨°üñå¤÷ï­²®šü”ß¾íÃŒ¿žÖÏú±¹û¡íÍçðÛÐú™¾­±
¸€½ŒÎÁð—÷×ÞöžšÜÓ«áŒŸû²Ë¶¾ÓÚµ¼©•ÓÕÈÖÛÞ»½ƒŸ¼éìûÍÁÒÂð—æ˜Íáï™™˜þÓÅ¸þÊïÛí—žÜùÈÉ›œ»
éÉçÚ«¨ã¨÷•´ÚæøæÓåÏ”’ì ÿÏ·…æ®Ê³±ü¹‡Œ¿ªáïšêŒø¤þÏ«ˆÿÈ°˜Ã·ÝÔ„üûŠ±©š£ßŠÒ•®æ™†ûŸü‰ŠˆŒ”
ç­âîçÃ‹éˆŒÈÛÚÄÜÈè¾ò†—‘‰Òš†—‘‰š†”—‘‰š†—‘§‰š±¿Í·¹•—Â­·©ŸÇÎ¬ÑÕ÷ôÕßŽ³ÓíáóÕÏ¤ßé½ÿü
ð™ž´éö¦«Ä¶ôÕÝõçÿ¬ÙÊŠÛýöõà™çþ¢Ÿ–ŸÜßïäïî³’ÌÛ«ñò‡¶óÃèÊ×·éê¯Œá‡þ¥î›¼äòÃ»ÆÎÞüÝÞ‰ºÒÕ´
˜Ý±¼Ã÷õ¤ù¥êÊ×ÓöóÅðŒ¿ÞÕåã•¨«ÝÍÛÕ¾àÃ——÷‹½¦Œ¿æø¥êÊ¼×óëêŒá»Ýü±ÖäŸÞ½ÐÁ˜þîñÊÔŸ•®æÖÕÕŒ
ªÿÉŸÔæø°ýñÊÔ•®æÖ£ÕÕÿØ·©í¬ïÉŸÓ¾™¬öŒÃÏ¿Þÿ‰ºÒÕÜººó®áë¦Ïû¿¿¹¶Ó¶‡á—’‘¯ÄÝéêîàÝÝýŽßÛ®
¿ÍÏ»øü®ŠñÃ¯¥Þ‰ºÒÏÕÜºÊ›þó‘ËÃ²»µæ÷Ûî·¯ß“‰ÃùÏ­Þ‰ºÒÕÿÜººŠá¯å³ó¶½Œ¿ˆøâ¥êÊ×óëêÇŒáÛ¨¯¤
Ì”ûÊ·¦ë°òÌùÏÞÕŒ’¿«ø¥êÊ×ºóëê°áÇÈ’ÞéŒ¿óø¥ÑêÊ×óëê€£áïÒÜâõáùŸäòÃËÙ«¼Ë×ºÒÕ´Ýä°üÌ²¡á
ì§ÿî³Íó•Ê¸ùÃšíô¥é«›ô•¹ŒáÛî’ü¬Â×·ºÒÕÌºÊø…ìþöÌâø‘›‘¥§¹Ø¾ÃÏšœáÅÄ¢ó†áÅÄ¢†áœÅÄ¢†áÅÄ
ç¢†áÅÄ¢†¹áÅÄ¢†áÅÎÄ¢†áÅÄ¢ó†áÅÄ¢†áœÅÄ¢†áÅÄ»¢æª†¿ÕïÙÖ€ôãòÃ¿‹ˆÈâÂð¢Œ¢ÑÃð¢¢ÑãÃð¢¢ÑÃð
˜¢¢ÑÃð¢¢ÆÑÃð¢¢ÑÃñð¢¢ÑÓÑðã“ý¨¿€ ÷³êîèø©ÿ‰Æ¸€ Â—õ¬÷·üö˜¹îç´ªØåÅ±ãž•ûéŸŸúåæŒÃ÷ýŒ’‰
ÌÖ•»¬¨öÔÚâ·›Ýß‘ö¬Ÿ²†á§ùþòÁÈèÕ±ËŠ âÇ­öïøÏùŸ¶ÝÂðóÌÖ•»¬¨öÔúâçéøý½´ÝýÓ†µºï²µøæŠÜ±ØÍ
™öªíÞä”ôÖ©¶ùÀÞÙúÿÈê«ž¹áÛËçåµçèð¼é½û¾©Ò«”–û¶Ò†ŸÖ¡ìÕÚÚíÕù‘Ãïïåø¥æçì×Ëêóö‹¥£ÌÃŒ¿¬Ø
¿†¿¼Øƒáÿ›Ù”ÓüÜûó‘ÿ­×éŠÓÓ³ýÙÿåÿ¶éß—Ö¸¢Ñ÷£õÒü§­÷ùï¶Õõô¿Àð´÷¥’ûÚš¬Õïéûç˜Œ¸ðâ»ÞòÉ“²
ûž´™¾öŸ›ææø³Ç´ÏÓëªÎñßõø×¤áË‡·õ¸Ç¶þû®ÿåŠçÍ´×öÓþµ³°èôÜ‡Ï´ëœ¿¸ãµÖ«¿Øšá“ÿƒõêªÃ§ÏÑí¤
ìçŒ“¼¼Â§ÁãÏ¦ô÷Ëóõøõö¿¶á›êõÕú‹Ñãàèâ³ç¯Î¨é½õ¬öèø‡†¢ûŸû¯þ»æÁùÖÉþ–¦³íš¿ë˜É›¯žð´Žäøµ
ç÷ß÷Ç¾†µ×öšò‡­º‘×²üÛ½¡Ë½ëÞìÞð›ß˜žê©þ—Óù™çÂ¿ªÓ¼úøªÙ›ùäÛÔÞáÿíÅ¶Ÿ÷ÝÙ®²íµÝÖôö½à¹áø
òÑ‹½˜¾Ï‡´ì¦ýùøÚäû©íô—œ¼ùêÛæÀÏÃ×óÊÌèçÍý÷Ìµü³«ÌûÉ·ºòÿŒ“Áßøœå®¹äõ¼¶ÌÙð²¸ÚÞÕì²¢ØÑ‹
ÚåøàÑªâ—–•ÅŽÚìœŒÃŸüžŒÆ«®£¡Ø‘ÐìÈ­ìß÷Ã®ë´ø€Àü¸úœŠÞ®›­ªöÙòÑìø™ð‹åÜ™þæÑªâ—Þ•ÅŽ—Ùš¾
Ûø’áòŠ–—³¶Òêß‹åÕ–áÅÎþ —×˜Ûô¶Ééšÿü’˜§áËûàûÕÄÜçŸûÛš›™©Øá—«“±Æ•Éƒ’´­þ³ÏÏþû–çïøËÏï
çÚÂð·®–áÌÇªö’Ïõöå¤°üŒßü¾¢«¹æ°ßÞÏó—Ì½Œß«ù®Ùæ³ÛÕ¦÷¯áÛ®×¶í§šÖÓøæéÝæßïÉêêí‰å¾»¿ó¯
§ÍÓ”ü‘µ½“ò¾ÏêØÕ±¶ÏÃ·½ëÚöÂæÏÊÞšíÕ¶õ¿õì“É½±ëÌÛƒÍ×õÿ¾ÀÌµš”ÆéäÏüÂâ“¶õÙÓý£—Æ¿ò÷Òö©Ú®
ÿŒËŸÔÙÌÖ‰ðíç¹ã¹ëôøÝœí¬Ë­—™‹ª¦®µ×¹š¯¶ùú½äðçÆˆ¡“ŸéüåŽ»–á›ïßÑÍ÷ëäë¡§»á›÷ñ•§ õ¶ŒŸ¯×²
šü¯Ï»†ÜîóøäŒßñŠå½Ü†åÅç§ô®µÛ÷¼—ŒËá»¿÷µ˜¾½ãË†áÏ¶÷ËöÖ®†¿û•Í®¤×ºÜ³×ªªÃ§÷¸ÊÍ»÷ØýÌåî
ç¥»á³óø¾ê÷×¥ó´üçƒê›ìæçòÏõß’‚å€áËüÍ¶÷¬¼Ï³ÅÅ¶«Ë–ØìßÉ”ß¼£µÔ¢þÖƒç«Í›Ù ùêÚÎàþ¬³”Ç´™ü
Ø‘õ¹Åù§•Ù¸›ÙšÞ†ëçÂÖ”Í„®¬ö®ÊòŸÈ‰¯°ü¼Œèõñì«¿Æ”£ØÅ½‘É€¦˜‰É¿ùûòÜ¼èÕ±ËŠºâÇ‹ÃÇ‹Ö
æ•»¬¨ö¼Ì‡Óðµ¯´¦ïìéÙÑê­‹Íœ·¹¬ç³Ÿµ×Ò§Õ±£ÝŸÑ¨×ÿ´§®²ùØìßå‰ÏÎöŠ¶—¶öª½Šåø‘Š×½îÇ¶­¾†
Íç™žáï†ÿŸ°Ø¶í«Ü×Ñ…Ÿù¶çü†¶†¿Á¡ŒÿÃ¡áëßáµ·õ“·­­—·º¡ò‚¯©¶³ý§¶äæšÂÛÕçÝëÜµ¿íÜ’©¶ùÈ‡È
¯ Ë‰¨½’‹Ü›žõÄµ½Úæä³µü²´ÕÚóìòÓŠÓ—«Õæ‡¶õ®½™âóÛÉë³»óò¼»§ùÈÕºÿÚ™¦û±±Ã¤ðö£‹³Åçóââ˜¾¹
Í³¦¨ò“ì»îé…éÕê­½óÏÙËëåÉ´‚Ñ®®ßã¯­œä®øŽçî‘Îç³—á‡ÈàùìÆþœÛ‰ëµòè‹¬Ëðí¨û²·­°ƒÛâÝ“æÕìç
œó¯·Á¢èû¶€—øç†éåøü§çïªËÅµ¦Ø«šþÔº“·†Ã·½³·æŸìÊÂð·Î®¶­ÉÞ¥÷—ÚÃðíŒþçîÉƒçûâÎâ¾Ú¢‹²üç
»êÛîóÙ•ï—šíÅüƒŒîèõÁÎ˜Õ±ÍúÛ“¯É¶ë³¼ùŸ½ªÛ¾¤ã§ÛºÞ›™ÉÎ’Ï´Ù×ò°Ó·Ÿ“—–ù„™šçéøñ¹¤ÚÕì²’
î±üÕïèþïº÷×ÃÇ‹Ö¾•»¬ÜÌð«çÌä†‡€ŒÄçä†Ïœ Ã¢’ÕÅ®«Š¯àŒŸ¯ÚÕì²§¢Øñ²çÃçðîõÉŒè­ü§µÛäò‰Ñ
Ÿìí‹½ú¥õÏÔà“ÇðñÿÒåõ¢ÀÉ‹ õŠú•ûùÝŠ´­Þì™ðÇ€Ë¹ýŒŸ¯ŒÛ¿ˆâ‚ÞÅÁŽñ—Œ¿ŸÃï×¾¶Úïä÷ñ¬¶ýÅÔüº
ýõìÛëÌµŠ²íÛÞíá™âµÏÞœÝÚëøºðÇ»ºðôõ¦ùüÅ¿¯¿†Ü–áø»Æ«¨±û‰Ýáú¾ÞÌ²Ÿ¨Û«–Ûñ¼â³Ç®ªð‚Ì±í¦¿ª
Þ£‡Ú‡´ÐªåÏ¥§ïÀÞåúé’åš¾³×©ßÕº¿Þ ¶Õ»¥÷êööð±ƒ÷®­ðÒÞ†Ÿð¹ÞÅ¡ð×¹ýíïÊüŸí€ÌÐðù§Èðç³Ø
†ÄÝÛÞç®·šüò€…÷²ü…¯ã’ûêï–ý½ÎÁ…§áŒ‡÷¸¶—Å¦Ê—ŠÈ·ã—Û±öÂÞíáÃŒ”¿øúýáÝºòú†ÜÑÙ‡ÓŸÏŒ¿©½
‡ÏÖöøÑôÉï¾Õ³Ý¶Ôåíõ‹íþÂ³Í—÷ìôªöØ³åÚ¼»ƒïèÿÀéëøø›Ÿú¶ßÏ—ÌÓðÜòÉ´ªØååöæÅÞÕ™ü‰ß ŒŸ¯ÚÕ
ßì²¢Øñ²¹áá€£±¹á¹ï€ãÀð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á €ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á 
€ªŒ€ÑáøŠ€ˆŠÃƒÀÔ¸˜ž€¢Âð€´•†‡€¨°˜¼€Ä…á Ìªýõ¾õ²ÃÊƒÀ¢ØÊûëÇáŽ¹ÿô²ÃêƒÀ¢Ø›þÓ§Í—Ü³¼€
´¬‡†‡€¨°˜¼€Ä…á Üª‡Ãÿ²©çÐôëã¿ÃƒÀÂÒ¨™¾ýŒÃ²ƒÀ‚éÎáëÞ‡ÔüÏð€°æ”Ž†ÿ¨§¸ºõÿãðåýŒà€ËáïøÍ
¬¯µÜŸõÞ—ÛÉð€°”Žµ†ï÷ðÓÉŒœ€‹€á €ªŒ€Ñáøþ€ˆÊÖð½ŽÀçø€ØŠ÷ý§¹¢á»þí È¢¢·ËÕŒß¿ý÷Ò‹ˆÈ­
†ó¹áÅÄäñ˜áø‘‘¨áøÆ‘‘¨áø‘‘±¨áø‘‘¨áŒø‘‘¨áø‘ã‘¨áø‘‘¨˜áø‘‘¨©ŒÆ¿Éïá€€Œ¡ÊÓ€ÀÜþŸ‹®í¹Â

]&]
[s0;=2 &]
[ {{5000:5000^@7 [s0; [*2 Version Ultimate`+`+]]
:: [s0; [*2 Version Qt]]
::@2 [s0; [*C2 AddressBook.cpp]&]
[s0;C0 &]
[s0; [C0 #include <TCtrlLib/TCtrlLib.h>]&]
[s0;C0 &]
[s0; [C0 #define LAYOUTFILE <AddressBook/AddressBook.lay>]&]
[s0; [C0 #include <CtrlCore/lay.h>]&]
[s0;C0 &]
[s0; [C0 class AddressBook : public WithAddressBookLayout<TopWindow> 
`{]&]
[s0; [C0 -|WithModifyLayout<StaticRect> modify;]&]
[s0; [C0 -|WithSearchLayout<StaticRect> search;]&]
[s0; [C0 -|FileSel fs;]&]
[s0; [C0 -|String  filename;]&]
[s0; [C0 -|]&]
[s0; [C0 -|void SetupSearch();]&]
[s0; [C0 -|void Add();]&]
[s0; [C0 -|void Change();]&]
[s0; [C0 -|void Search();]&]
[s0; [C0 -|void Open();]&]
[s0; [C0 -|void Save();]&]
[s0; [C0 -|void SaveAs();]&]
[s0; [C0 -|void Print();]&]
[s0; [C0 -|void Quit();]&]
[s0; [C0 -|void FileMenu(Bar`& bar);]&]
[s0; [C0 -|void MainMenu(Bar`& bar);]&]
[s0;C0 &]
[s0; [C0 -|typedef AddressBook CLASSNAME;]&]
[s0;C0 &]
[s0; [C0 public:]&]
[s0; [C0 -|void Serialize(Stream`& s);]&]
[s0;C0 &]
[s0; [C0 -|AddressBook();]&]
[s0; [C0 `};]&]
[s0;C0 &]
[s0; [C0 AddressBook`::AddressBook()]&]
[s0; [C0 `{]&]
[s0; [C0 -|CtrlLayout(`*this, `"Address book`");]&]
[s0; [C0 -|CtrlLayout(modify);]&]
[s0; [C0 -|CtrlLayout(search);]&]
[s0; [C0 -|tab.Add(modify, `"Modify`");]&]
[s0; [C0 -|tab.Add(search, `"Search`");]&]
[s0; [C0 -|ActiveFocus(search.name);]&]
[s0; [C0 -|search.oname `= true;]&]
[s0; [C0 -|search.oname <<`= search.osurname <<`= search.oaddress]&]
[s0; [C0 -|             <<`= search.oemail <<`= THISBACK(SetupSearch);]&]
[s0; [C0 -|array.AddColumn(`"Name`");]&]
[s0; [C0 -|array.AddColumn(`"Surname`");]&]
[s0; [C0 -|array.AddColumn(`"Address`");]&]
[s0; [C0 -|array.AddColumn(`"Email`");]&]
[s0; [C0 -|modify.add <<`= THISBACK(Add);]&]
[s0; [C0 -|modify.change <<`= THISBACK(Change);]&]
[s0; [C0 -|search.search <<`= THISBACK(Search);]&]
[s0; [C0 -|SetupSearch();]&]
[s0; [C0 -|fs.AllFilesType();]&]
[s0; [C0 -|menu.Set(THISBACK(MainMenu));]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::FileMenu(Bar`& bar)]&]
[s0; [C0 `{]&]
[s0; [C0 -|bar.Add(`"Open..`", CtrlImg`::open(), THISBACK(Open));]&]
[s0; [C0 -|bar.Add(`"Save`", CtrlImg`::save(), THISBACK(Save));]&]
[s0; [C0 -|bar.Add(`"Save as..`", CtrlImg`::save`_as(), THISBACK(SaveAs));]&]
[s0; [C0 -|bar.Separator();]&]
[s0; [C0 -|bar.Add(`"Print`", CtrlImg`::print(), THISBACK(Print));]&]
[s0; [C0 -|bar.Separator();]&]
[s0; [C0 -|bar.Add(`"Quit`", THISBACK(Quit));]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::MainMenu(Bar`& bar)]&]
[s0; [C0 `{]&]
[s0; [C0 -|bar.Add(`"File`", THISBACK(FileMenu));]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::SetupSearch()]&]
[s0; [C0 `{]&]
[s0; [C0 -|search.name.Enable(search.oname);]&]
[s0; [C0 -|search.surname.Enable(search.osurname);]&]
[s0; [C0 -|search.address.Enable(search.oaddress);]&]
[s0; [C0 -|search.email.Enable(search.oemail);]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Add()]&]
[s0; [C0 `{]&]
[s0; [C0 -|array.Add(`~modify.name, `~modify.surname, `~modify.address, 
`~modify.email);]&]
[s0; [C0 -|array.GoEnd();]&]
[s0; [C0 -|modify.name <<`= modify.surname <<`= modify.address <<`= 
modify.email <<`= Null;]&]
[s0; [C0 -|ActiveFocus(modify.name);]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Change()]&]
[s0; [C0 `{]&]
[s0; [C0 -|if(array.IsCursor()) `{]&]
[s0; [C0 -|-|array.Set(0, `~modify.name);]&]
[s0; [C0 -|-|array.Set(1, `~modify.surname);]&]
[s0; [C0 -|-|array.Set(2, `~modify.address);]&]
[s0; [C0 -|-|array.Set(3, `~modify.email);]&]
[s0; [C0 -|`}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 bool Contains(const String`& text, const String`& substr)]&]
[s0; [C0 `{]&]
[s0; [C0 -|for(const char `*s `= text; s <`= text.End() `- substr.GetLength(); 
s`+`+)]&]
[s0; [C0 -|-|if(strncmp(s, substr, substr.GetLength()) `=`= 0)]&]
[s0; [C0 -|-|-|return true;]&]
[s0; [C0 -|return false;]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Search()]&]
[s0; [C0 `{]&]
[s0; [C0 -|if(!array.GetCount()) return;]&]
[s0; [C0 -|bool sc `= true;]&]
[s0; [C0 -|array.ClearSelection();]&]
[s0; [C0 -|for(int i `= 0; i < array.GetCount(); i`+`+) `{]&]
[s0; [C0 -|-|if((!search.oname `|`| Contains(array.Get(i, 0), `~search.name)) 
`&`&]&]
[s0; [C0 -|-|   (!search.osurname `|`| Contains(array.Get(i, 1), `~search.surname)) 
`&`&]&]
[s0; [C0 -|-|   (!search.oaddress `|`| Contains(array.Get(i, 2), `~search.address)) 
`&`&]&]
[s0; [C0 -|-|   (!search.oemail `|`| Contains(array.Get(i, 3), `~search.email))) 
`{]&]
[s0; [C0 -|-|-|array.Select(i);]&]
[s0; [C0 -|-|-|if(sc) `{]&]
[s0; [C0 -|-|-|-|array.SetCursor(i);]&]
[s0; [C0 -|-|-|-|array.CenterCursor();]&]
[s0; [C0 -|-|-|-|sc `= false;]&]
[s0; [C0 -|-|-|`};]&]
[s0; [C0 -|-|`}]&]
[s0; [C0 -|`}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Open()]&]
[s0; [C0 `{]&]
[s0; [C0 -|if(!fs.ExecuteOpen()) return;]&]
[s0; [C0 -|filename `= fs;]&]
[s0; [C0 -|FileIn in(filename);]&]
[s0; [C0 -|if(!in) `{]&]
[s0; [C0 -|-|Exclamation(`"Unable to open `" `+ filename);]&]
[s0; [C0 -|-|return;]&]
[s0; [C0 -|`}]&]
[s0; [C0 -|array.Clear();]&]
[s0; [C0 -|while(!in.IsEof()) `{]&]
[s0; [C0 -|-|Vector<Value> q;]&]
[s0; [C0 -|-|for(int i `= 0; i < 4; i`+`+)]&]
[s0; [C0 -|-|-|q.Add(in.GetLine());]&]
[s0; [C0 -|-|array.Add(q);]&]
[s0; [C0 -|`}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Save()]&]
[s0; [C0 `{]&]
[s0; [C0 -|if(IsEmpty(filename)) `{]&]
[s0; [C0 -|-|SaveAs();]&]
[s0; [C0 -|-|return;]&]
[s0; [C0 -|`}]&]
[s0; [C0 -|FileOut out(filename);]&]
[s0; [C0 -|if(!out) `{]&]
[s0; [C0 -|-|Exclamation(`"Unable to open `" `+ filename);]&]
[s0; [C0 -|-|return;]&]
[s0; [C0 -|`}]&]
[s0; [C0 -|for(int i `= 0; i < array.GetCount(); i`+`+) `{]&]
[s0; [C0 -|-|for(int q `= 0; q < 4; i`+`+)]&]
[s0; [C0 -|-|-|out.PutLine(String(array.Get(i, q)));]&]
[s0; [C0 -|`}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::SaveAs()]&]
[s0; [C0 `{]&]
[s0; [C0 -|if(!fs.ExecuteSaveAs()) return;]&]
[s0; [C0 -|filename `= fs;]&]
[s0; [C0 -|Save();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Print()]&]
[s0; [C0 `{]&]
[s0; [C0 -|String qtf;]&]
[s0; [C0 -|qtf `= `"`+`+Name`|`|Surname`|`|Address`|`|Email`";]&]
[s0; [C0 -|for(int i `= 0; i < array.GetCount(); i`+`+) `{]&]
[s0; [C0 -|-|qtf << `"`-`-`";]&]
[s0; [C0 -|-|for(int q `= 0; q < 4; q`+`+) `{]&]
[s0; [C0 -|-|-|if(q) qtf << `"`|`|`";]&]
[s0; [C0 -|-|-|qtf << DeQtf((String)array.Get(i, q));]&]
[s0; [C0 -|-|`}]&]
[s0; [C0 -|`}]&]
[s0; [C0 -|qtf << `"`+`+`";]&]
[s0; [C0 -|Report report;]&]
[s0; [C0 -|report << qtf;]&]
[s0; [C0 -|report.Perform();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Quit()]&]
[s0; [C0 `{]&]
[s0; [C0 -|Break();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void AddressBook`::Serialize(Stream`& s)]&]
[s0; [C0 `{]&]
[s0; [C0 -|int version `= 0;]&]
[s0; [C0 -|s / version;]&]
[s0; [C0 -|s % search.oname % search.osurname % search.oaddress % search.oemail;]&]
[s0; [C0 -|s % fs;]&]
[s0; [C0 -|SetupSearch();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 GUI`_APP`_MAIN]&]
[s0; [C0 `{]&]
[s0; [C0 -|AddressBook ab;]&]
[s0; [C0 -|LoadFromFile(ab);]&]
[s0; [C0 -|ab.Run();]&]
[s0; [C0 -|StoreToFile(ab);]&]
[s0; [C0 `}]&]
[s0;C0 ]
:: [s0; [*C2 mainwindow.h]&]
[s0;C0 &]
[s0; [C0 #ifndef AB`_MAINWINDOW`_H]&]
[s0; [C0 #define AB`_MAINWINDOW`_H]&]
[s0;C0 &]
[s0; [C0 #include <qmainwindow.h>]&]
[s0; [C0 #include <qstring.h>]&]
[s0;C0 &]
[s0; [C0 class QToolBar;]&]
[s0; [C0 class QPopupMenu;]&]
[s0; [C0 class ABCentralWidget;]&]
[s0;C0 &]
[s0; [C0 class ABMainWindow: public QMainWindow]&]
[s0; [C0 `{]&]
[s0; [C0     Q`_OBJECT]&]
[s0;C0 &]
[s0; [C0 public:]&]
[s0; [C0     ABMainWindow();]&]
[s0; [C0     `~ABMainWindow();]&]
[s0;C0 &]
[s0; [C0 protected slots:]&]
[s0; [C0     void fileNew();]&]
[s0; [C0     void fileOpen();]&]
[s0; [C0     void fileSave();]&]
[s0; [C0     void fileSaveAs();]&]
[s0; [C0     void filePrint();]&]
[s0; [C0     void closeWindow();]&]
[s0;C0 &]
[s0; [C0 protected:]&]
[s0; [C0     void setupMenuBar();]&]
[s0; [C0     void setupFileTools();]&]
[s0; [C0     void setupStatusBar();]&]
[s0; [C0     void setupCentralWidget();]&]
[s0;C0 &]
[s0; [C0     QToolBar `*fileTools;]&]
[s0; [C0     QString filename;]&]
[s0; [C0     ABCentralWidget `*view;]&]
[s0;C0 &]
[s0; [C0 `};]&]
[s0;C0 &]
[s0;C0 &]
[s0; [C0 #endif]&]
[s0;C0 &]
[s0; [*C2 mainwindow.cpp]&]
[s0;C0 &]
[s0; [C0 #include `"mainwindow.h`"]&]
[s0; [C0 #include `"centralwidget.h`"]&]
[s0;C0 &]
[s0; [C0 #include <qtoolbar.h>]&]
[s0; [C0 #include <qtoolbutton.h>]&]
[s0; [C0 #include <qpopupmenu.h>]&]
[s0; [C0 #include <qmenubar.h>]&]
[s0; [C0 #include <qstatusbar.h>]&]
[s0; [C0 #include <qapplication.h>]&]
[s0; [C0 #include <qfiledialog.h>]&]
[s0;C0 &]
[s0; [C0 ABMainWindow`::ABMainWindow()]&]
[s0; [C0     : QMainWindow( 0, `"example addressbook application`" ),]&]
[s0; [C0       filename( QString`::null )]&]
[s0; [C0 `{]&]
[s0; [C0     setupMenuBar();]&]
[s0; [C0     setupFileTools();]&]
[s0; [C0     setupStatusBar();]&]
[s0; [C0     setupCentralWidget();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0;C0 &]
[s0; [C0 ABMainWindow`::`~ABMainWindow()]&]
[s0; [C0 `{]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::setupMenuBar()]&]
[s0; [C0 `{]&]
[s0; [C0     QPopupMenu `*file `= new QPopupMenu( this );]&]
[s0; [C0     menuBar()`->insertItem( `"`&File`", file );]&]
[s0;C0 &]
[s0; [C0     file`->insertItem( `"New`", this, SLOT( fileNew() ), CTRL 
`+ Key`_N );]&]
[s0; [C0     file`->insertItem( QPixmap( `"fileopen.xpm`" ), `"Open`", 
this, SLOT( fileOpen() ), CTRL `+ Key`_O );]&]
[s0; [C0     file`->insertSeparator();]&]
[s0; [C0     file`->insertItem( QPixmap( `"filesave.xpm`" ), `"Save`", 
this, SLOT( fileSave() ), CTRL `+ Key`_S );]&]
[s0; [C0     file`->insertItem( `"Save As...`", this, SLOT( fileSaveAs() 
) );]&]
[s0; [C0     file`->insertSeparator();]&]
[s0; [C0     file`->insertItem( QPixmap( `"fileprint.xpm`" ), `"Print...`", 
this, SLOT( filePrint() ), CTRL `+ Key`_P );]&]
[s0; [C0     file`->insertSeparator();]&]
[s0; [C0     file`->insertItem( `"Close`", this, SLOT( closeWindow() 
), CTRL `+ Key`_W );]&]
[s0; [C0     file`->insertItem( `"Quit`", qApp, SLOT( quit() ), CTRL 
`+ Key`_Q );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::setupFileTools()]&]
[s0; [C0 `{]&]
[s0; [C0     //fileTools `= new QToolBar( this, `"file operations`" 
);]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::setupStatusBar()]&]
[s0; [C0 `{]&]
[s0; [C0     //statusBar()`->message( `"Ready`", 2000 );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::setupCentralWidget()]&]
[s0; [C0 `{]&]
[s0; [C0     view `= new ABCentralWidget( this );]&]
[s0; [C0     setCentralWidget( view );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::closeWindow()]&]
[s0; [C0 `{]&]
[s0; [C0     close();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::fileNew()]&]
[s0; [C0 `{]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::fileOpen()]&]
[s0; [C0 `{]&]
[s0; [C0     QString fn `= QFileDialog`::getOpenFileName( QString`::null, 
QString`::null, this );]&]
[s0; [C0     if ( !fn.isEmpty() ) `{]&]
[s0; [C0         filename `= fn;]&]
[s0; [C0         view`->load( filename );]&]
[s0; [C0     `}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::fileSave()]&]
[s0; [C0 `{]&]
[s0; [C0     if ( filename.isEmpty() ) `{]&]
[s0; [C0         fileSaveAs();]&]
[s0; [C0         return;]&]
[s0; [C0     `}]&]
[s0;C0 &]
[s0; [C0     view`->save( filename );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::fileSaveAs()]&]
[s0; [C0 `{]&]
[s0; [C0     QString fn `= QFileDialog`::getSaveFileName( QString`::null, 
QString`::null, this );]&]
[s0; [C0     if ( !fn.isEmpty() ) `{]&]
[s0; [C0         filename `= fn;]&]
[s0; [C0         fileSave();]&]
[s0; [C0     `}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABMainWindow`::filePrint()]&]
[s0; [C0 `{]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [*C2 centralwidget.h]&]
[s0;C0 &]
[s0; [C0 #ifndef AB`_CENTRALWIDGET`_H]&]
[s0; [C0 #define AB`_CENTRALWIDGET`_H]&]
[s0;C0 &]
[s0; [C0 #include <qwidget.h>]&]
[s0; [C0 #include <qstring.h>]&]
[s0;C0 &]
[s0; [C0 class QTabWidget;]&]
[s0; [C0 class QListView;]&]
[s0; [C0 class QGridLayout;]&]
[s0; [C0 class QLineEdit;]&]
[s0; [C0 class QPushButton;]&]
[s0; [C0 class QListViewItem;]&]
[s0; [C0 class QCheckBox;]&]
[s0;C0 &]
[s0; [C0 class ABCentralWidget : public QWidget]&]
[s0; [C0 `{]&]
[s0; [C0     Q`_OBJECT]&]
[s0;C0 &]
[s0; [C0 public:]&]
[s0; [C0     ABCentralWidget( QWidget `*parent, const char `*name `= 
0 );]&]
[s0;C0 &]
[s0; [C0     void save( const QString `&filename );]&]
[s0; [C0     void load( const QString `&filename );]&]
[s0;C0 &]
[s0; [C0 protected slots:]&]
[s0; [C0     void addEntry();]&]
[s0; [C0     void changeEntry();]&]
[s0; [C0     void itemSelected( QListViewItem`* );]&]
[s0; [C0     void selectionChanged();]&]
[s0; [C0     void toggleFirstName();]&]
[s0; [C0     void toggleLastName();]&]
[s0; [C0     void toggleAddress();]&]
[s0; [C0     void toggleEMail();]&]
[s0; [C0     void findEntries();]&]
[s0;C0 &]
[s0; [C0 protected:]&]
[s0; [C0     void setupTabWidget();]&]
[s0; [C0     void setupListView();]&]
[s0;C0 &]
[s0; [C0     QGridLayout `*mainGrid;]&]
[s0; [C0     QTabWidget `*tabWidget;]&]
[s0; [C0     QListView `*listView;]&]
[s0; [C0     QPushButton `*add, `*change, `*find;]&]
[s0; [C0     QLineEdit `*iFirstName, `*iLastName, `*iAddress, `*iEMail,]&]
[s0; [C0         `*sFirstName, `*sLastName, `*sAddress, `*sEMail;]&]
[s0; [C0     QCheckBox `*cFirstName, `*cLastName, `*cAddress, `*cEMail;]&]
[s0;C0 &]
[s0; [C0 `};]&]
[s0;C0 &]
[s0; [C0 #endif]&]
[s0;C0 &]
[s0; [*C2 centralwidget.cpp]&]
[s0;C0 &]
[s0; [C0 #include `"centralwidget.h`"]&]
[s0;C0 &]
[s0; [C0 #include <qtabwidget.h>]&]
[s0; [C0 #include <qlistview.h>]&]
[s0; [C0 #include <qlayout.h>]&]
[s0; [C0 #include <qwidget.h>]&]
[s0; [C0 #include <qlabel.h>]&]
[s0; [C0 #include <qpushbutton.h>]&]
[s0; [C0 #include <qlineedit.h>]&]
[s0; [C0 #include <qlabel.h>]&]
[s0; [C0 #include <qcheckbox.h>]&]
[s0; [C0 #include <qfile.h>]&]
[s0; [C0 #include <qtextstream.h>]&]
[s0;C0 &]
[s0; [C0 ABCentralWidget`::ABCentralWidget( QWidget `*parent, const 
char `*name )]&]
[s0; [C0     : QWidget( parent, name )]&]
[s0; [C0 `{]&]
[s0; [C0     mainGrid `= new QGridLayout( this, 2, 1, 5, 5 );]&]
[s0;C0 &]
[s0; [C0     setupTabWidget();]&]
[s0; [C0     setupListView();]&]
[s0;C0 &]
[s0; [C0     mainGrid`->setRowStretch( 0, 0 );]&]
[s0; [C0     mainGrid`->setRowStretch( 1, 1 );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::setupListView()]&]
[s0; [C0 `{]&]
[s0; [C0     listView `= new QListView( this );]&]
[s0; [C0     listView`->addColumn( `"First Name`" );]&]
[s0; [C0     listView`->addColumn( `"Last Name`" );]&]
[s0; [C0     listView`->addColumn( `"Address`" );]&]
[s0; [C0     listView`->addColumn( `"E`-Mail`" );]&]
[s0;C0 &]
[s0; [C0     listView`->setSelectionMode( QListView`::Single );]&]
[s0;C0 &]
[s0; [C0     connect( listView, SIGNAL( clicked( QListViewItem`* ) 
), this, SLOT( itemSelected( QListViewItem`* ) ) );]&]
[s0;C0 &]
[s0; [C0     mainGrid`->addWidget( listView, 1, 0 );]&]
[s0; [C0     listView`->setAllColumnsShowFocus( TRUE );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::save( const QString `&filename )]&]
[s0; [C0 `{]&]
[s0; [C0     if ( !listView`->firstChild() )]&]
[s0; [C0         return;]&]
[s0;C0 &]
[s0; [C0     QFile f( filename );]&]
[s0; [C0     if ( !f.open( IO`_WriteOnly ) )]&]
[s0; [C0         return;]&]
[s0;C0 &]
[s0; [C0     QTextStream t( `&f );]&]
[s0;C0 &]
[s0; [C0     QListViewItemIterator it( listView );]&]
[s0;C0 &]
[s0; [C0     for ( ; it.current(); `+`+it )]&]
[s0; [C0         for ( unsigned int i `= 0; i < 4; i`+`+ )]&]
[s0; [C0             t << it.current()`->text( i ) << `"n`";]&]
[s0;C0 &]
[s0; [C0     f.close();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::load( const QString `&filename )]&]
[s0; [C0 `{]&]
[s0; [C0     listView`->clear();]&]
[s0;C0 &]
[s0; [C0     QFile f( filename );]&]
[s0; [C0     if ( !f.open( IO`_ReadOnly ) )]&]
[s0; [C0         return;]&]
[s0;C0 &]
[s0; [C0     QTextStream t( `&f );]&]
[s0;C0 &]
[s0; [C0     while ( !t.atEnd() ) `{]&]
[s0; [C0         QListViewItem `*item `= new QListViewItem( listView 
);]&]
[s0; [C0         for ( unsigned int i `= 0; i < 4; i`+`+ )]&]
[s0; [C0             item`->setText( i, t.readLine() );]&]
[s0; [C0     `}]&]
[s0;C0 &]
[s0; [C0     f.close();]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::addEntry()]&]
[s0; [C0 `{]&]
[s0; [C0     if ( !iFirstName`->text().isEmpty() `|`| !iLastName`->text().isEmpty() 
`|`|]&]
[s0; [C0          !iAddress`->text().isEmpty() `|`| !iEMail`->text().isEmpty() 
) `{]&]
[s0; [C0         QListViewItem `*item `= new QListViewItem( listView 
);]&]
[s0; [C0         item`->setText( 0, iFirstName`->text() );]&]
[s0; [C0         item`->setText( 1, iLastName`->text() );]&]
[s0; [C0         item`->setText( 2, iAddress`->text() );]&]
[s0; [C0         item`->setText( 3, iEMail`->text() );]&]
[s0; [C0     `}]&]
[s0;C0 &]
[s0; [C0     iFirstName`->setText( `"`" );]&]
[s0; [C0     iLastName`->setText( `"`" );]&]
[s0; [C0     iAddress`->setText( `"`" );]&]
[s0; [C0     iEMail`->setText( `"`" );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::changeEntry()]&]
[s0; [C0 `{]&]
[s0; [C0     QListViewItem `*item `= listView`->currentItem();]&]
[s0;C0 &]
[s0; [C0     if ( item `&`&]&]
[s0; [C0          ( !iFirstName`->text().isEmpty() `|`| !iLastName`->text().isEmpty() 
`|`|]&]
[s0; [C0            !iAddress`->text().isEmpty() `|`| !iEMail`->text().isEmpty() 
) ) `{]&]
[s0; [C0         item`->setText( 0, iFirstName`->text() );]&]
[s0; [C0         item`->setText( 1, iLastName`->text() );]&]
[s0; [C0         item`->setText( 2, iAddress`->text() );]&]
[s0; [C0         item`->setText( 3, iEMail`->text() );]&]
[s0; [C0     `}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::selectionChanged()]&]
[s0; [C0 `{]&]
[s0; [C0     iFirstName`->setText( `"`" );]&]
[s0; [C0     iLastName`->setText( `"`" );]&]
[s0; [C0     iAddress`->setText( `"`" );]&]
[s0; [C0     iEMail`->setText( `"`" );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::itemSelected( QListViewItem `*item )]&]
[s0; [C0 `{]&]
[s0; [C0     if ( !item )]&]
[s0; [C0         return;]&]
[s0; [C0     item`->setSelected( TRUE );]&]
[s0; [C0     item`->repaint();]&]
[s0;C0 &]
[s0; [C0     iFirstName`->setText( item`->text( 0 ) );]&]
[s0; [C0     iLastName`->setText( item`->text( 1 ) );]&]
[s0; [C0     iAddress`->setText( item`->text( 2 ) );]&]
[s0; [C0     iEMail`->setText( item`->text( 3 ) );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::toggleFirstName()]&]
[s0; [C0 `{]&]
[s0; [C0     sFirstName`->setText( `"`" );]&]
[s0;C0 &]
[s0; [C0     if ( cFirstName`->isChecked() ) `{]&]
[s0; [C0         sFirstName`->setEnabled( TRUE );]&]
[s0; [C0         sFirstName`->setFocus();]&]
[s0; [C0     `}]&]
[s0; [C0     else]&]
[s0; [C0         sFirstName`->setEnabled( FALSE );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::toggleLastName()]&]
[s0; [C0 `{]&]
[s0; [C0     sLastName`->setText( `"`" );]&]
[s0;C0 &]
[s0; [C0     if ( cLastName`->isChecked() ) `{]&]
[s0; [C0         sLastName`->setEnabled( TRUE );]&]
[s0; [C0         sLastName`->setFocus();]&]
[s0; [C0     `}]&]
[s0; [C0     else]&]
[s0; [C0         sLastName`->setEnabled( FALSE );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::toggleAddress()]&]
[s0; [C0 `{]&]
[s0; [C0     sAddress`->setText( `"`" );]&]
[s0;C0 &]
[s0; [C0     if ( cAddress`->isChecked() ) `{]&]
[s0; [C0         sAddress`->setEnabled( TRUE );]&]
[s0; [C0         sAddress`->setFocus();]&]
[s0; [C0     `}]&]
[s0; [C0     else]&]
[s0; [C0         sAddress`->setEnabled( FALSE );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::toggleEMail()]&]
[s0; [C0 `{]&]
[s0; [C0     sEMail`->setText( `"`" );]&]
[s0;C0 &]
[s0; [C0     if ( cEMail`->isChecked() ) `{]&]
[s0; [C0         sEMail`->setEnabled( TRUE );]&]
[s0; [C0         sEMail`->setFocus();]&]
[s0; [C0     `}]&]
[s0; [C0     else]&]
[s0; [C0         sEMail`->setEnabled( FALSE );]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [C0 void ABCentralWidget`::findEntries()]&]
[s0; [C0 `{]&]
[s0; [C0     if ( !cFirstName`->isChecked() `&`&]&]
[s0; [C0          !cLastName`->isChecked() `&`&]&]
[s0; [C0          !cAddress`->isChecked() `&`&]&]
[s0; [C0          !cEMail`->isChecked() ) `{]&]
[s0; [C0         listView`->clearSelection();]&]
[s0; [C0         return;]&]
[s0; [C0     `}]&]
[s0;C0 &]
[s0; [C0     QListViewItemIterator it( listView );]&]
[s0;C0 &]
[s0; [C0     for ( ; it.current(); `+`+it ) `{]&]
[s0; [C0         bool select `= TRUE;]&]
[s0;C0 &]
[s0; [C0         if ( cFirstName`->isChecked() ) `{]&]
[s0; [C0             if ( select `&`& it.current()`->text( 0 ).contains( 
sFirstName`->text() ) )]&]
[s0; [C0                 select `= TRUE;]&]
[s0; [C0             else]&]
[s0; [C0                 select `= FALSE;]&]
[s0; [C0         `}]&]
[s0; [C0         if ( cLastName`->isChecked() ) `{]&]
[s0; [C0             if ( select `&`& it.current()`->text( 1 ).contains( 
sLastName`->text() ) )]&]
[s0; [C0                 select `= TRUE;]&]
[s0; [C0             else]&]
[s0; [C0                 select `= FALSE;]&]
[s0; [C0         `}]&]
[s0; [C0         if ( cAddress`->isChecked() ) `{]&]
[s0; [C0             if ( select `&`& it.current()`->text( 2 ).contains( 
sAddress`->text() ) )]&]
[s0; [C0                 select `= TRUE;]&]
[s0; [C0             else]&]
[s0; [C0                 select `= FALSE;]&]
[s0; [C0         `}]&]
[s0; [C0         if ( cEMail`->isChecked() ) `{]&]
[s0; [C0             if ( select `&`& it.current()`->text( 3 ).contains( 
sEMail`->text() ) )]&]
[s0; [C0                 select `= TRUE;]&]
[s0; [C0             else]&]
[s0; [C0                 select `= FALSE;]&]
[s0; [C0         `}]&]
[s0;C0 &]
[s0; [C0         if ( select )]&]
[s0; [C0             it.current()`->setSelected( TRUE );]&]
[s0; [C0         else]&]
[s0; [C0             it.current()`->setSelected( FALSE );]&]
[s0; [C0         it.current()`->repaint();]&]
[s0; [C0     `}]&]
[s0; [C0 `}]&]
[s0;C0 &]
[s0; [*C2 main.cpp]&]
[s0;C0 &]
[s0; [C0 #include <qapplication.h>]&]
[s0;C0 &]
[s0; [C0 #include `"mainwindow.h`"]&]
[s0;C0 &]
[s0; [C0 int main( int argc, char `*`* argv )]&]
[s0; [C0 `{]&]
[s0; [C0     QApplication a( argc, argv );]&]
[s0;C0 &]
[s0; [C0     ABMainWindow `*mw `= new ABMainWindow();]&]
[s0; [C0     mw`->setCaption( `"Qt Example `- Addressbook`" );]&]
[s0; [C0     a.setMainWidget( mw );]&]
[s0; [C0     mw`->show();]&]
[s0;C0 &]
[s0; [C0     a.connect( `&a, SIGNAL( lastWindowClosed() ), `&a, SLOT( 
quit() ) );]&]
[s0; [C0     int result `= a.exec();]&]
[s0; [C0     delete mw;]&]
[s0; [C0     return result;]&]
[s0; [C0 `}]&]
[s0;=2 ]}}&]
[s0;=2 &]
[ {{5000:5000@(255.255.200)-1 [s0; [/2 Pour que la comparaison sot plus juste, nous avons omis les 
parties suivantes qui sont gÃ©nÃ©rÃ©es par le `"Layout designer`" 
d`'Ultimate`+`+ d`'une part, et qui pourraient Ãªtre gÃ©nÃ©rÃ©es 
par `"Qt designer`" d`'autre part.]]
::@2 [s0;%- ]
::^@7 [s0; [*2 Version Ultimate`+`+]]
:: [s0; [*2 Version Qt]]
::@2 [s0; [*C2 AddressBook.lay]&]
[s0; [/C2 (crÃ©Ã© avec le Layout Designer)]&]
[s0;/C2 &]
[s0; [C0 #ifdef LAYOUTFILE]&]
[s0;C0 &]
[s0; [C0 LAYOUT(AddressBookLayout, 496, 456)]&]
[s0; [C0 -|ITEM(MenuBar, menu, LeftPosZ(0, 200).TopPosZ(0, 20))]&]
[s0; [C0 -|ITEM(TabCtrl, tab, LeftPosZ(8, 480).TopPosZ(32, 84))]&]
[s0; [C0 -|ITEM(ArrayCtrl, array, LeftPosZ(8, 480).TopPosZ(124, 324))]&]
[s0; [C0 END`_LAYOUT]&]
[s0;C0 &]
[s0; [C0 LAYOUT(ModifyLayout, 480, 52)]&]
[s0; [C0 -|ITEM(Label, dv`_`_`_0, SetLabel(`"`&Name`").LeftPosZ(8, 48).TopPosZ(8, 
15))]&]
[s0; [C0 -|ITEM(EditField, name, LeftPosZ(8, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Label, dv`_`_`_2, SetLabel(`"`&Surname`").LeftPosZ(108, 
48).TopPosZ(8, 15))]&]
[s0; [C0 -|ITEM(EditField, surname, LeftPosZ(108, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Label, dv`_`_`_4, SetLabel(`"`&Address`").LeftPosZ(208, 
48).TopPosZ(8, 15))]&]
[s0; [C0 -|ITEM(EditField, address, LeftPosZ(208, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Label, dv`_`_`_6, SetLabel(`"`&Email`").LeftPosZ(308, 
48).TopPosZ(8, 15))]&]
[s0; [C0 -|ITEM(EditField, email, LeftPosZ(308, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Button, add, SetLabel(`"Ad`&d`").LeftPosZ(416, 56).TopPosZ(4, 
20))]&]
[s0; [C0 -|ITEM(Button, change, SetLabel(`"`&Change`").LeftPosZ(416, 
56).TopPosZ(28, 20))]&]
[s0; [C0 END`_LAYOUT]&]
[s0;C0 &]
[s0; [C0 LAYOUT(SearchLayout, 480, 56)]&]
[s0; [C0 -|ITEM(Option, oname, SetLabel(`"`&Name`").LeftPosZ(8, 56).TopPosZ(8, 
18))]&]
[s0; [C0 -|ITEM(EditField, name, LeftPosZ(8, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Option, osurname, SetLabel(`"`&Surname`").LeftPosZ(108, 
64).TopPosZ(8, 18))]&]
[s0; [C0 -|ITEM(EditField, surname, LeftPosZ(108, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Option, oaddress, SetLabel(`"`&Address`").LeftPosZ(208, 
64).TopPosZ(8, 18))]&]
[s0; [C0 -|ITEM(EditField, address, LeftPosZ(208, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Option, oemail, SetLabel(`"`&Email`").LeftPosZ(308, 
52).TopPosZ(8, 18))]&]
[s0; [C0 -|ITEM(EditField, email, LeftPosZ(308, 96).TopPosZ(28, 19))]&]
[s0; [C0 -|ITEM(Button, search, SetLabel(`"`&Search`").LeftPosZ(416, 
56).TopPosZ(28, 20))]&]
[s0; [C0 END`_LAYOUT]&]
[s0;C0 &]
[s0; [C0 #endif]]
:: [s0; [C0 void ABCentralWidget`::setupTabWidget()]&]
[s0; [C0 `{]&]
[s0; [C0     tabWidget `= new QTabWidget( this );]&]
[s0;C0 &]
[s0; [C0     QWidget `*input `= new QWidget( tabWidget );]&]
[s0; [C0     QGridLayout `*grid1 `= new QGridLayout( input, 2, 5, 5, 
5 );]&]
[s0;C0 &]
[s0; [C0     QLabel `*liFirstName `= new QLabel( `"First `&Name`", 
input );]&]
[s0; [C0     liFirstName`->resize( liFirstName`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( liFirstName, 0, 0 );]&]
[s0;C0 &]
[s0; [C0     QLabel `*liLastName `= new QLabel( `"`&Last Name`", input 
);]&]
[s0; [C0     liLastName`->resize( liLastName`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( liLastName, 0, 1 );]&]
[s0;C0 &]
[s0; [C0     QLabel `*liAddress `= new QLabel( `"Add`&ress`", input 
);]&]
[s0; [C0     liAddress`->resize( liAddress`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( liAddress, 0, 2 );]&]
[s0;C0 &]
[s0; [C0     QLabel `*liEMail `= new QLabel( `"`&E`-Mail`", input );]&]
[s0; [C0     liEMail`->resize( liEMail`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( liEMail, 0, 3 );]&]
[s0;C0 &]
[s0; [C0     add `= new QPushButton( `"A`&dd`", input );]&]
[s0; [C0     add`->resize( add`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( add, 0, 4 );]&]
[s0; [C0     connect( add, SIGNAL( clicked() ), this, SLOT( addEntry() 
) );]&]
[s0;C0 &]
[s0; [C0     iFirstName `= new QLineEdit( input );]&]
[s0; [C0     iFirstName`->resize( iFirstName`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( iFirstName, 1, 0 );]&]
[s0; [C0     liFirstName`->setBuddy( iFirstName );]&]
[s0;C0 &]
[s0; [C0     iLastName `= new QLineEdit( input );]&]
[s0; [C0     iLastName`->resize( iLastName`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( iLastName, 1, 1 );]&]
[s0; [C0     liLastName`->setBuddy( iLastName );]&]
[s0;C0 &]
[s0; [C0     iAddress `= new QLineEdit( input );]&]
[s0; [C0     iAddress`->resize( iAddress`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( iAddress, 1, 2 );]&]
[s0; [C0     liAddress`->setBuddy( iAddress );]&]
[s0;C0 &]
[s0; [C0     iEMail `= new QLineEdit( input );]&]
[s0; [C0     iEMail`->resize( iEMail`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( iEMail, 1, 3 );]&]
[s0; [C0     liEMail`->setBuddy( iEMail );]&]
[s0;C0 &]
[s0; [C0     change `= new QPushButton( `"`&Change`", input );]&]
[s0; [C0     change`->resize( change`->sizeHint() );]&]
[s0; [C0     grid1`->addWidget( change, 1, 4 );]&]
[s0; [C0     connect( change, SIGNAL( clicked() ), this, SLOT( changeEntry() 
) );]&]
[s0;C0 &]
[s0; [C0     tabWidget`->addTab( input, `"`&Add/Change Entry`" );]&]
[s0;C0 &]
[s0; [C0     // `-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-`-
`-`-]&]
[s0;C0 &]
[s0; [C0     QWidget `*search `= new QWidget( this );]&]
[s0; [C0     QGridLayout `*grid2 `= new QGridLayout( search, 2, 5, 
5, 5 );]&]
[s0;C0 &]
[s0; [C0     cFirstName `= new QCheckBox( `"First `&Name`", search 
);]&]
[s0; [C0     cFirstName`->resize( cFirstName`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( cFirstName, 0, 0 );]&]
[s0; [C0     connect( cFirstName, SIGNAL( clicked() ), this, SLOT( 
toggleFirstName() ) );]&]
[s0;C0 &]
[s0; [C0     cLastName `= new QCheckBox( `"`&Last Name`", search );]&]
[s0; [C0     cLastName`->resize( cLastName`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( cLastName, 0, 1 );]&]
[s0; [C0     connect( cLastName, SIGNAL( clicked() ), this, SLOT( toggleLastName() 
) );]&]
[s0;C0 &]
[s0; [C0     cAddress `= new QCheckBox( `"Add`&ress`", search );]&]
[s0; [C0     cAddress`->resize( cAddress`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( cAddress, 0, 2 );]&]
[s0; [C0     connect( cAddress, SIGNAL( clicked() ), this, SLOT( toggleAddress() 
) );]&]
[s0;C0 &]
[s0; [C0     cEMail `= new QCheckBox( `"`&E`-Mail`", search );]&]
[s0; [C0     cEMail`->resize( cEMail`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( cEMail, 0, 3 );]&]
[s0; [C0     connect( cEMail, SIGNAL( clicked() ), this, SLOT( toggleEMail() 
) );]&]
[s0;C0 &]
[s0; [C0     sFirstName `= new QLineEdit( search );]&]
[s0; [C0     sFirstName`->resize( sFirstName`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( sFirstName, 1, 0 );]&]
[s0;C0 &]
[s0; [C0     sLastName `= new QLineEdit( search );]&]
[s0; [C0     sLastName`->resize( sLastName`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( sLastName, 1, 1 );]&]
[s0;C0 &]
[s0; [C0     sAddress `= new QLineEdit( search );]&]
[s0; [C0     sAddress`->resize( sAddress`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( sAddress, 1, 2 );]&]
[s0;C0 &]
[s0; [C0     sEMail `= new QLineEdit( search );]&]
[s0; [C0     sEMail`->resize( sEMail`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( sEMail, 1, 3 );]&]
[s0;C0 &]
[s0; [C0     find `= new QPushButton( `"F`&ind`", search );]&]
[s0; [C0     find`->resize( find`->sizeHint() );]&]
[s0; [C0     grid2`->addWidget( find, 1, 4 );]&]
[s0; [C0     connect( find, SIGNAL( clicked() ), this, SLOT( findEntries() 
) );]&]
[s0;C0 &]
[s0; [C0     cFirstName`->setChecked( TRUE );]&]
[s0; [C0     sFirstName`->setEnabled( TRUE );]&]
[s0; [C0     sLastName`->setEnabled( FALSE );]&]
[s0; [C0     sAddress`->setEnabled( FALSE );]&]
[s0; [C0     sEMail`->setEnabled( FALSE );]&]
[s0;C0 &]
[s0; [C0     tabWidget`->addTab( search, `"`&Search`" );]&]
[s0;C0 &]
[s0; [C0     mainGrid`->addWidget( tabWidget, 0, 0 );]&]
[s0; [C0 `}]&]
[s0;C0 ]}}&]
[s0;=2 &]
[s0;%% ]