TABLE_(LISTS)
	INT_     (ID) PRIMARY_KEY
	STRING_  (NAME, 255)
	INT_     (POS)
END_TABLE

TABLE_(PLAYLISTS)
	INT_    (IDPL) PRIMARY_KEY
	INT     (ID)
	INT     (POS)
	STRING_ (FILENAME, 500)
	INT_	(LENGTH)
	STRING_ (TITLE, 255)
	STRING_ (ARTIST, 255)
	STRING_ (ALBUM, 255)
	STRING_ (YEAR, 4)
	INT_    (GENRE)
	STRING_ (TRACK, 3)
END_TABLE