T_("Exit")
plPL("Koniec")

T_("To tray")
plPL("Schowek")

T_("Files")
plPL("Pliki")
T_("Options")
plPL("Opcje")

T_("Open")
plPL("Otwórz")
T_("Save as")
plPL("Zapisz jako")
T_("Import")
plPL("Importuj")
T_("Export")
plPL("Eksportuj")

T_("Language")
plPL("Język")
T_("File associations")
plPL("Powiązania plików")
T_("Go to played file")
plPL("Idź do otwarzanego utworu")
T_("Follow played file")
plPL("Podążaj za odtwarzanym utworem")
T_("Play last file on startup")
plPL("Odtwarzaj ostatni odgrwany utwór")
T_("Go to last file on startup")
plPL("Ustawiaj się na ostatnim wskazanym utworze")
T_("Bring player to front when loading from explorer")
plPL("Pokaż okno aplikacji przy ładowaniu plików z exploratora")

T_("Register at startup")
plPL("Rejestruj przy starcie")

T_("Add files")
plPL("Dodaj pliki")
T_("Add folder")
plPL("Dodaj katalog")
T_("Insert files")
plPL("Wstaw pliki")
T_("Insert folder")
plPL("Wstaw katalog")

T_("Add playlist")
plPL("Dodaj listę utworów")
T_("Add folder as playlist")
plPL("Dodaj katalog jako listę utworów")
T_("Insert playlist")
plPL("Wstaw listę utworów")
T_("Insert folder as playlist")
plPL("Wstaw katalog jako listę utworów")

T_("Change playlist name")
plPL("Zmień nazwę listy")


T_("Position")
plPL("Pozycja")
T_("Volume")
plPL("Głośność")

T_("Playlists")
plPL("Listy utworów")

T_("Title")
plPL("Tytuł")
T_("Artist")
plPL("Wykonawca")
T_("Album")
plPL("Album")
T_("Length")
plPL("Długość")

T_("Bring player on top when loading stream from explorer")
plPL("Przenieś okno odtwarzacza na wierzch przy ładowaniu strumienia z explorera")

T_("Load")
plPL("Załaduj")

T_("File %s does not exists")
plPL("Plik %s nie istnieje")

T_("Cancel")
plPL("Anuluj")

T_("Select music folder")
plPL("Wybierz katalog z muzyką")
T_("Select music file")
plPL("Wybierz plik")

T_("Playing..")
plPL("Odtwarzanie..")
T_("Playing paused")
plPL("Odtawrzanie wstrzymane")

T_("Pause")
plPL("Wstrzymaj")
T_("Play")
plPL("Odtwarzaj")

T_("Next song")
plPL("Następny utwór")
T_("Previous song")
plPL("Poprzedni utwór")
T_("Order mode")
plPL("Kolejność odtwarzania")
T_("Repeat mode")
plPL("Tryb powtarzania")
T_("Exit player")
plPL("Wyjdź z programu")
T_("Hide player to tray")
plPL("Ukryj do schowka")
T_("Play/Pause")
plPL("Odtwarzaj/Wstrzymaj")
T_("Stop")
plPL("Zatrzymaj")
