#!/bin/bash
# dostable
# quick go to create deb package from my stable repo
#
#################################################################
#		REPLACE VALUES WITH YOUR OWN			#
# SVN repository full path
STABLE_PATH="/home/massimo/sources/uppstable"
#
# Destination path for generated debian
DEST_PATH="/home/massimo/sources/uppdeb"
#
# Mantainer name and email
export MAINTAINER="Massimo Del Fedele"
#
export EMAIL="max@veneto.com"
#################################################################
#
# checks if stable repo and destination path are ok
if [ ! -d $STABLE_PATH/uppsrc ]
then
	echo "ERROR - UPP path not found in '$STABLE_PATH'"
	echo "Please modify current script to fit your Upp development path"
	exit 1
fi

if [ ! -d $DEST_PATH ]
then
	echo "ERROR - Invalid destinatio path '$DEST_PATH'"
	echo "Please modify current script to fit your destination path"
	exit 1
fi

#locates 'uppstable2deb' script - first try on path
uppstable2deb="`which uppstable2deb`"
if [ x$uppstable2deb = x ]
then
	# couldn't find it on path, just try on this script's path
	LSOF=$(lsof -p $$ 2>/dev/null | grep -E "/"$(basename $0)"$")
	uppstable2deb=$(echo $LSOF | sed -r s/'^([^\/]+)\/'/'\/'/1 2>/dev/null)
	uppstable2deb=$(dirname $uppstable2deb)/uppstable2deb
fi
if [ ! -f $uppstable2deb ]
then
	echo "ERROR - Could not find 'uppstable2deb' script"
	echo "Please check if it's on current path"
	exit 1
fi

#just run uppstable2deb with my params
$uppstable2deb $STABLE_PATH $DEST_PATH

