#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// PushCtrl.h

T_("(default)")
caES("(per defecte)")
csCZ("(výchozí)")
deDE("(Voreinstellung)")
esES("(por defecto)")
fiFI("(oletus)")
frFR("Par défaut")
huHU("(alapértelmezett)")
itIT("(predefinito)")
nlNL("(standaard)")
plPL("(domyślny)")
roRO("(implicit)")
ruRU("(по умолчанию)")
skSK("(predvolené)")
srSP("")
trTR("(varsayılan")
zhCN("(缺省)")
zhTW("(預設)")


// EditField.cpp

T_("Undo")
caES("Desfer")
csCZ("Zpět")
deDE("Rückgängig")
esES("Deshacer")
fiFI("Kumoa")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
nlNL("Ondoen")
plPL("Cofnij")
roRO("Anulează ultima operație")
ruRU("Отменить")
skSK("Späť")
srSP("Undo")
trTR("Geri Al")
zhCN("撤销")
zhTW("復原")

T_("Cut")
caES("Tallar")
csCZ("Vyjmout")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
nlNL("Knippen")
plPL("Wytnij")
roRO("Decupează")
ruRU("Вырезать")
skSK("Vystrihnúť")
srSP("Iseci")
trTR("Kes")
zhCN("剪切")
zhTW("剪下")

T_("Copy")
caES("Copiar")
csCZ("Kopírovat")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
nlNL("Kopieëren")
plPL("Kopiuj")
roRO("Copiază")
ruRU("Копировать")
skSK("Kopírovať")
srSP("Kopiraj")
trTR("Kopyala")
zhCN("复制")
zhTW("複製")

T_("Paste")
caES("Enganxa")
csCZ("Vložit")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
nlNL("Plakken")
plPL("Wklej")
roRO("Lipește")
ruRU("Вставить")
skSK("Prilepiť")
srSP("Zalepi")
trTR("Yapıştır")
zhCN("粘贴")
zhTW("貼上")

T_("Erase")
caES("Esborrar")
csCZ("Vymazat")
deDE("Löschen")
esES("Borrar")
fiFI("Pyyhi")
frFR("Effacer")
huHU("Törlés")
itIT("Cancella")
nlNL("Verwijder")
plPL("Usuń")
roRO("Şterge")
ruRU("Стереть")
skSK("Vymazať")
srSP("Obriši")
trTR("Sil")
zhCN("清除")
zhTW("清除")

T_("Select all")
caES("Seleccionar tot")
csCZ("Vybrat vše")
deDE("Alles auswählen")
esES("Seleccionar todo")
fiFI("Valitse kaikki")
frFR("Tout sélectionner")
huHU("Minden kiválasztása")
itIT("Seleziona tutto")
nlNL("Selecteer alles")
plPL("Zaznacz wszystko")
roRO("Alege tot")
ruRU("Выделить всё")
skSK("Vybrať všetko")
srSP("Izaberi sve")
trTR("Tümünü Seç")
zhCN("全选")
zhTW("全選")


// Text.cpp

T_("Redo")
caES("Refer")
csCZ("Znovu")
deDE("Wiederherstellen")
esES("Rehacer")
fiFI("Toista")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
nlNL("Herdoen")
plPL("Powtórz")
roRO("Refă ultima operație")
ruRU("Повторить")
skSK("Znovu")
srSP("Redo")
trTR("Yinele")
zhCN("重做")
zhTW("重做")


// ArrayCtrl.cpp

T_("Do you really want to delete the selected %s ?")
caES("Realment vols esborrar les %s seleccionades?")
csCZ("Smazat aktuální %s ?")
deDE("Möchten Sie die ausgewählte %s wirklich löschen?")
esES("¿Realmente quieres borrar las %s seleccionadas?")
fiFI("Haluatko varmasti poistaa valitun %s ?")
frFR("Voulez-vous réellement supprimer le %s sélectioné ?")
huHU("Biztosan töröljük a kijelölt %s ?")
itIT("Cancellare i %s selezionati ?")
nlNL("Weet je zeker dat je de geselecteerde %s wilt verwijderen?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
roRO("Doriţi să ştergeţi %s ales/aleasă?")
ruRU("Вы действительно желаете удалить выбр. "
     "%s ?")
skSK("Zmazať aktuálny %s ?")
srSP("Da li stvarno želite da obrišete izabran %s?")
trTR("%s öğesini silmeyi gerçekten istiyor musunuz ?")
zhCN("真的要删除选择的 %s 吗? ")
zhTW("真的要刪除選擇的 %s 嗎? ")

T_("Insert %s")
caES("Inserir %s")
csCZ("Vložit %s")
deDE("%s einfügen")
esES("Insertar %s")
fiFI("Lisää %s")
frFR("Insérer %s")
huHU("Beszúrás")
itIT("Inserzione %d")
nlNL("Invoegen %s")
plPL("Wstaw %s")
roRO("Inserează %s")
ruRU("Вставить %s")
skSK("Vložiť %s")
srSP("Ubaci %s")
trTR("%s öğesini araya ekle")
zhCN("插入 %s")
zhTW("插入 %s")

T_("Insert a new %s into the table.")
caES("Inserir un nou %s a la taula.")
csCZ("Vložit do tabulky nový %s.")
deDE("Neue %s in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla.")
fiFI("Lisää uusi %s taulukkoon.")
frFR("Insère une nouvelle %d dans la table.")
huHU("Új %s beszúrása a táblázatba")
itIT("Inserire un nuovo %s in tabella.")
nlNL("Voeg een nieuwe %s in de tabel.")
plPL("Wstawia nowy %s do tabeli.")
roRO("Înserează un nou/o nouă %s în tabel")
ruRU("Вставить нов. %s в таблицу.")
skSK("Vložiť nový %s do tabuľky.")
srSP("Ubaci u tabelu novi %s.")
trTR("Tabloya yeni bir %s ekle.")
zhCN("插入新的 %s 到表格")
zhTW("插入新的 %s 到表格")

T_("Insert %s before")
caES("Inseriu %s abans")
csCZ("Vložit %s před")
deDE("%s vorher einfügen")
esES("Insertar %s antes")
fiFI("Lisää %s ennen")
frFR("Insérer %s avant")
huHU("%s beszúrása elé")
itIT("Inserisci %s sopra")
nlNL("Voeg %s in hiervoor")
plPL("Wstaw %s przed")
roRO("Inserează %s înainte")
ruRU("Вставить %s перед")
skSK("Vložiť %s pred")
srSP("Ubaci %s pre")
trTR("%s öğesini öne ekle")
zhCN("前插 %s")
zhTW("前插 %s")

T_("Insert a new %s into the table before current")
caES("Inserir una nova %s en la taula abans de l'actual")
csCZ("Vložit nový %s před aktuální")
deDE("Neue %s vor der aktuellen in die Tabelle einfügen")
esES("Insertar una nueva %s en la tabla antes de la actual")
fiFI("Lisää uusi %s taulukkoon ennen nykyistä")
frFR("Insérer une nouvelle %d dans la table avant l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
itIT("Inserisci una nuova %s in tabella dopo la corrente")
nlNL("Voeg een nieuwe %s in de voorgaande tabel")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
roRO("Înserează un nou/o nouă %s în tabel înainte de cel curent")
ruRU("Вставить новый %s в таблицу перед существующим")
skSK("Vložiť nový %s pred aktuálny")
srSP("Ubaci novi %s u tabeli pre trenutne")
trTR("Seçili olanın önüne yeni bir %s öğesi ekle")
zhCN("在表格中当前项前插入新的 %s")
zhTW("在表格中目前項前插入新的 %s")

T_("Insert %s after")
caES("Inseriu %s després de")
csCZ("Vložit %s za")
deDE("%s danach einfügen")
esES("Insertar %s después")
fiFI("Lisää %s jälkeen")
frFR("Insérer %s après")
huHU("% beszúrása mögé")
itIT("Inserisci %s sotto")
nlNL("Voeg %s in hierna")
plPL("Wstaw %s po")
roRO("Inserează %s după")
ruRU("Вставить %s после")
skSK("Vložiť %s za")
srSP("Ubaci %s posle")
trTR("%s öğesini sona ekle")
zhCN("后插 %s")
zhTW("後插 %s")

T_("Insert a new %s into the table after current")
caES("Inserir una nova %s en la taula després de l'actual")
csCZ("Vložit %s za aktuální")
deDE("Neue %s hinter der aktuellen in die Tabelle einfügen")
esES("Insertar una nueva %s en la tabla después de la actual")
fiFI("Lisää uusi %s taulukkoon nykyisen jälkeen")
frFR("Insérer une nouvelle %d dans la table après l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
itIT("Inserisci una nuova %s in tabella dopo la corrente")
nlNL("Voeg een nieuwe %s in de volgende tabel")
plPL("Wstawia nowy %s do tabeli po aktualnym")
roRO("Înserează un nou/o nouă %s în tabel după de cel curent")
ruRU("Вставить новый %s в таблицу после существующего")
skSK("Vložiť %s za aktuálny")
srSP("Ubaci novi %s u tabeli posle trenutne")
trTR("Seçili olanın ardına yeni bir %s öğesi ekle")
zhCN("在表格中当前项后插入新的 %s")
zhTW("在表格中目前項後插入新的 %s")

T_("Append %s")
caES("Annexar %s")
csCZ("Přidat %s")
deDE("%s hinzufügen")
esES("Añadir %s")
fiFI("Lisää %s jälkeen")
frFR("Ajouter %s")
huHU("%s hozzáfűzése")
itIT("Aggiungi %s")
nlNL("Plaats %s")
plPL("Dodaj %s")
roRO("Adaugă %s la capăt")
ruRU("Добавить %s")
skSK("Pridať %s")
srSP("Dodaj %s")
trTR("%s öğesini iliştir")
zhCN("添加 %s")
zhTW("添加 %s")

T_("Append a new %s at the end of the table.")
caES("Afegeix una nova %s al final de la taula.")
csCZ("Přidat nový %s na konec")
deDE("Neue %s am Ende der Tabelle hinzufügen")
esES("Añadir una nueva %s en el final de la tabla.")
fiFI("Lisää uusi %s taulukon loppuun.")
frFR("Ajouter une nouvelle %s à la fin de la table.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
itIT("Aggiungi una nuova %s a fine tabella.")
nlNL("Plaats een nieuwe %s op het einde van de tabel.")
plPL("Dodaje nowy %s na końcu tabeli.")
roRO("Adaugă un nou/o nouă %s la capătul tabelului")
ruRU("Добавить новый %s в конце таблицы.")
skSK("Pridať nový %s na koniec tabuľky")
srSP("Dodaj novi %s na kraju tabele.")
trTR("Tablonun sonuna yeni bir %s öğesi iliştir.")
zhCN("在表格末尾插入新的 %s")
zhTW("在表格末尾插入新的 %s")

T_("Duplicate %s")
caES("Duplicar %s")
csCZ("Duplikovat %s")
deDE("%s duplizieren")
esES("Duplicar %s")
fiFI("Kahdenna %s")
frFR("Dupliquer %s")
huHU("%s megkettőzése")
itIT("Duplica %s")
nlNL("Dupliceer %s")
plPL("Zduplikuj %s")
roRO("Crează un duplicat pentru %s")
ruRU("Дублировать %s")
skSK("Duplikovať %s")
srSP("Dupliraj %s")
trTR("%s öğesini kopyala")
zhCN("复制 %s")
zhTW("複製 %s")

T_("Duplicate current table %s.")
caES("Duplicar %s de la taula actual.")
csCZ("Vložit do tabulky duplikát aktuálního %s.")
deDE("Aktuelle %s der Tabelle duplizieren")
esES("Duplicar %s de la tabla actual.")
fiFI("Kahdenna tämänhetkinen taulukko %s.")
frFR("Dupliquer la table %s sélectionnée.")
huHU("Az aktuális táblázat megkettőzése")
itIT("Duplica la tabella corrente %s.")
nlNL("Dupliceer huidige tabel %s.")
plPL("Utwórz duplikat aktualnej tabeli %s.")
roRO("Duplică tabelul curent %s.")
ruRU("Дублировать тек. %s")
skSK("Duplikovať aktuálny %s.")
srSP("Dupliraj trenutni %s tabele.")
trTR("Seçili %s tablosunu kopyala")
zhCN("复制当前表格 %s.")
zhTW("複製目前表格 %s.")

T_("Edit %s")
caES("Editar %s")
csCZ("Opravit aktuální %s")
deDE("%s bearbeiten")
esES("Editar %s")
fiFI("Muokkaa %s")
frFR("Editer %s")
huHU("%s szerkesztése")
itIT("Modifica %s")
nlNL("Bewerk %s")
plPL("Edytuj %s")
roRO("Editează %s")
ruRU("Редактировать %s")
skSK("Upraviť aktuálny %s")
srSP("Promeni %s")
trTR("%s öğesini düzenle")
zhCN("编辑 %s")
zhTW("編輯 %s")

T_("Edit active %s.")
caES("Editar %s actiu.")
csCZ("Opravit aktuální %s.")
deDE("Aktive %s bearbeiten")
esES("Editar %s activo.")
fiFI("Muokkaa aktiivista %s.")
frFR("Editer %s actif.")
huHU("Az aktuális %s szerkesztése")
itIT("Modifica la %s attiva.")
nlNL("Bewerk actieve %s.")
plPL("Edytowanie aktualnego %s.")
roRO("Editează %s activ(e).")
ruRU("Редактировать активн. %s")
skSK("Upraviť aktuálny %s.")
srSP("Promeni aktivni %s.")
trTR("Seçili %s öğesini düzenle")
zhCN("编辑活动 %s")
zhTW("編輯活動 %s")

T_("Delete %s\tDelete")
caES("Suprimir %s\tBorrar")
csCZ("Odstranit %s\tDelete")
deDE("%s löschen\tLöschen")
esES("Borrar %s\tBorrar")
fiFI("Poista %s\tPoista")
frFR("Supprimer %s\tSupprimer")
huHU("Törlés %s\tTörlés")
itIT("Cancella %s")
nlNL("Verwijder %s\tVerwijder")
plPL("Usuń %s\tUsuń")
roRO("Şterge %s\tŞterge")
ruRU("Удалить %s\tУдалить")
skSK("Odstrániť %s\tDelete")
srSP("Obriši %s\tObriši")
trTR("%s öğesini sil")
zhCN("删除%s\t删除")
zhTW("刪除%s\t刪除")

T_("Delete active %s.")
caES("Suprimir %s actiu.")
csCZ("Odstranit aktuální %s.")
deDE("Aktive %s löschen")
esES("Borrar %s activo.")
fiFI("Poista aktiivinen %s.")
frFR("Supprimer %s actif.")
huHU("Az aktív %s törlése")
itIT("Cancella %s attivo.")
nlNL("Verwijder actieve %s.")
plPL("Usuwa aktualny %s.")
roRO("Șterge %s activ(e).")
ruRU("Удалить активн. %s.")
skSK("Odstrániť aktuálny %s.")
srSP("Obriši aktivni %s.")
trTR("Etkin %s öğesini sil")
zhCN("删除活动 %s")
zhTW("刪除活動 %s")

T_("Move %s up")
caES("Moure %s amunt")
csCZ("Posunout %s nahoru")
deDE("%s nach oben verschieben")
esES("Mover %s arriba")
fiFI("Siirrä %s ylöspäin")
frFR("Monter %s")
huHU("%s felfelé mozgatása")
itIT("Sposta %s su")
nlNL("Verplaats %s naar boven")
plPL("Przesuń %s do góry")
roRO("Mută %s sus")
ruRU("Двигать %s вверх")
skSK("Posunúť %s hore")
srSP("Pomeri %s na gore")
trTR("%s öğesini yukarı taşı")
zhCN("上移%s")
zhTW("上移%s")

T_("Swap %s with previous thus moving it up.")
caES("Intercanviar %s amb l'anterior movent amunt.")
csCZ("Vyměnit aktuální %s s předchozím a tak ho posunout nahoru.")
deDE("%s mit der vorigen vertauschen und so nach oben verschieben")
esES("Intercambiar %s con el anterior moviendolo arriba.")
fiFI("Vaihda %s yläpuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le précédent.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
itIT("Scambio $s con la precedente spostandola su.")
nlNL("Wissel %s om met de voorgaande.")
plPL("Zamienia %s z poprzednim przesuwając go do góry.")
roRO("Interschimbă %s cu cel precedent, mutându-l în sus.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
skSK("Vymeniť aktuálny %s s predošlým a tak ho posunúť hore.")
srSP("Zameni %s sa prethodnim, pomeri ga na gore.")
trTR(" %s öğesini yukarıya taşıyarak bir öncekiyle yerini değiştir.")
zhCN("将%s与前面换位上移之")
zhTW("將%s與前面換位上移之")

T_("Move %s down")
caES("Moure %s avall")
csCZ("Posunout %s dolů")
deDE("%s nach unten verschieben")
esES("Mover %s abajo")
fiFI("Siirrä %s alaspäin")
frFR("Descendre %s")
huHU("%s lefelé mozgatása")
itIT("Sposta %s giu")
nlNL("Verplaats %s naar beneden")
plPL("Przesuń %s w dół")
roRO("Mută %s jos")
ruRU("Двигать %s вниз")
skSK("Posunúť %s dole")
srSP("Pomeri %s dole")
trTR("%s öğesini aşağı taşı")
zhCN("下移%s")
zhTW("下移%s")

T_("Swap %s with next thus moving it down.")
caES("Intercanviar %s amb el següent movent-baix")
csCZ("Vyměnit aktuální %s s dalším a tak ho posunout dolů.")
deDE("%s mit der nächsten vertauschen und so nach unten verschieben")
esES("Intercambiar %s con el siguiente moviendolo abajo")
fiFI("Vaihda %s alapuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le suivant.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
itIT("Scambio %s con la seguente spostandola giù")
nlNL("Wissel %s om met de volgende.")
plPL("Zamienia %s z następnym przesuwając go w dół.")
roRO("Interschimbă %s cu următorul, mutându-l în jos.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
skSK("Vymeniť aktuálny %s s ďalším a tak ho posunúť dole.")
srSP("Zameni %s sa sledećim, pomeri ga na dole.")
trTR("%s öğesini aşağıya taşıyarak bir sonrakiyle yerini değiştir")
zhCN("将%s与后面换位下移之")
zhTW("將%s與後面換位下移之")

T_("Select all table rows")
caES("Seleccionar totes les files de la taula")
csCZ("Vybrat všechny řádky v tabulce")
deDE("Alle Zeilen der Tabelle auswählen")
esES("Seleccionar todas las filas de la tabla")
fiFI("Valitse kaikki taulukon rivit")
frFR("Sélectionner toutes les lignes")
huHU("Az összes sor kijelölése")
itIT("Seleziona tutte le righe")
nlNL("Selecteer alle tabel rijen")
plPL("Zaznacz wszystkie wiersze tabeli")
roRO("Selecteză toate liniile tabelului")
ruRU("Выделить все ряды таблицы")
skSK("Vybrať všetky riadky v tabuľke")
srSP("Izaberi sve redove tabele")
trTR("Tüm satırları seç")
zhCN("全选表格行")
zhTW("全選表格列")

T_("row")
caES("fila")
csCZ("řádek")
deDE("Zeile")
esES("fila")
fiFI("rivi")
frFR("ligne")
huHU("sor")
itIT("riga")
nlNL("rijen")
plPL("wiersz")
roRO("linie")
ruRU("ряды")
skSK("riadok")
srSP("red")
trTR("satır")
zhCN("行")
zhTW("列")


// Progress.cpp

T_("Working...")
caES("S'està treballant...")
csCZ("Pracuji...")
deDE("Bearbeitung läuft ...")
esES("Trabajando...")
fiFI("Työskentelee...")
frFR("En cours d'exécution...")
huHU("Folyamatban...")
itIT("Esecuzione...")
nlNL("Bezig...")
plPL("Pracuję...")
roRO("Se lucrează...")
ruRU("Обработка...")
skSK("Pracujem...")
srSP("Radim...")
trTR("işlem yapılıyor...")
zhCN("工作中...")
zhTW("工作中...")


// AKeys.cpp

T_("Configure keyboard shortcuts")
caES("Configura dreceres de teclat")
csCZ("Nastavit klávesy")
deDE("Tasten zuweisen")
esES("Configurar atajos de teclado")
fiFI("Aseta pikanäppäimet")
frFR("Configurer les raccourcis")
huHU("Billentyűk beállítása")
itIT("Selezione tasti veloci")
nlNL("Configureer toetsenbord snelkoppelingen")
plPL("Ustawienia klawiszy")
roRO("Configurează scurtăturile de tastatură")
ruRU("Настроить горячие клавиши")
skSK("Nastaviť klávesy")
srSP("Podesi tastere")
trTR("Tuş Ayarları")
zhCN("设置键值")
zhTW("設定鍵值")

T_("Group")
caES("Agrupa")
csCZ("Skupina")
deDE("Gruppe")
esES("Grupo")
fiFI("Ryhmä")
frFR("Groupe")
huHU("Csoport")
itIT("Gruppo")
nlNL("Groep")
plPL("Grupa")
roRO("Grup")
ruRU("Группа")
skSK("Skupina")
srSP("Grupa")
trTR("Grup")
zhCN("组")
zhTW("群組")

T_("Action")
caES("Acció")
csCZ("Akce")
deDE("Aktion")
esES("Acción")
fiFI("Toiminto")
frFR("Action")
huHU("Művelet")
itIT("Azione")
nlNL("Actie")
plPL("Akcja")
roRO("Acţiune")
ruRU("Действие")
skSK("Akcia")
srSP("Akcija")
trTR("Eylem")
zhCN("动作")
zhTW("動作")

T_("Primary")
caES("Primària")
csCZ("Primární")
deDE("Taste 1")
esES("Primaria")
fiFI("Näppäin 1")
frFR("Touche 1")
huHU("1. billentyű")
itIT("Combinazione 1")
nlNL("Primair")
plPL("Klawisz 1")
roRO("Primar")
ruRU("Первично")
skSK("Primárny")
srSP("Taster 1")
trTR("1. Tuş")
zhCN("键1")
zhTW("鍵1")

T_("Secondary")
caES("Secundari")
csCZ("Sekundární")
deDE("Taste 2")
esES("Secundario")
fiFI("Näppäin 2")
frFR("Touche 2")
huHU("2. billentyű")
itIT("Combinazione 2")
nlNL("Secundair")
plPL("Klawisz 2")
roRO("Secundar")
ruRU("Вторично")
skSK("Sekundárny")
srSP("Taster 2")
trTR("2. Tuş")
zhCN("键2")
zhTW("鍵2")


// Prompt.cpp

T_("OK")
caES("Continuar")
csCZ("OK")
deDE("OK")
esES("Continuar")
fiFI("OK")
frFR("Ok")
huHU("Rendben")
itIT("OK")
nlNL("OK")
plPL("OK")
roRO("OK")
ruRU("ОК")
skSK("OK")
srSP("OK")
trTR("Tamam")
zhCN("确定")
zhTW("確定")

T_("Cancel")
caES("Cancel·lar")
csCZ("Storno")
deDE("Abbrechen")
esES("Cancelar")
fiFI("Peruuta")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
nlNL("Afbreken")
plPL("Anuluj")
roRO("Anulează")
ruRU("Отмена")
skSK("Storno")
srSP("Otkaži")
trTR("İptal")
zhCN("取消")
zhTW("取消")

T_("&Yes")
caES("&Sí")
csCZ("&Ano")
deDE("&Ja")
esES("&Sí")
fiFI("&Kyllä")
frFR("&Oui")
huHU("&Igen")
itIT("&Si")
nlNL("&Ja")
plPL("&Tak")
roRO("&Da")
ruRU("&Да")
skSK("&Áno")
srSP("&Da")
trTR("&Evet")
zhCN("是(&Y)")
zhTW("是(&Y)")

T_("&No")
caES("&No")
csCZ("&Ne")
deDE("&Nein")
esES("&No")
fiFI("&Ei")
frFR("&Non")
huHU("&Nem")
itIT("&No")
nlNL("&Nee")
plPL("&Nie")
roRO("&Nu")
ruRU("&Нет")
skSK("&Nie")
srSP("&Ne")
trTR("&Hayır")
zhCN("否(&N)")
zhTW("否(&N)")

T_("&Abort")
caES("&Avortar")
csCZ("&Přerušit")
deDE("&Abbrechen")
esES("&Abortar")
fiFI("&Keskeytä")
frFR("&Interrompre")
huHU("&Megszakítás")
itIT("&Interrompi")
nlNL("&Afbreken")
plPL("&Przerwij")
roRO("&Abandonează")
ruRU("&Прервать")
skSK("&Prerušiť")
srSP("&Prekini")
trTR("&İptal")
zhCN("放弃(&A)")
zhTW("放棄(&A)")

T_("&Retry")
caES("&Reintentar")
csCZ("&Opakovat")
deDE("&Erneut versuchen")
esES("&Reintentar")
fiFI("&Yritä uudelleen")
frFR("&Réessayer")
huHU("&Újra")
itIT("&Riprova")
nlNL("&Opnieuw proberen")
plPL("Po&wtórz")
roRO("&Reîncearcă")
ruRU("П&овторить")
skSK("&Opakovať")
srSP("&Ponovi")
trTR("&Tekrar Dene")
zhCN("重试(&R)")
zhTW("重試(&R)")

T_("&Ignore")
caES("&Ignorar")
csCZ("&Ignorovat")
deDE("&Ignorieren")
esES("&Ignorar")
fiFI("&Jätä huomiotta")
frFR("Ignorer")
huHU("&Ignore")
itIT("Ignora")
nlNL("&Negeer")
plPL("")
roRO("&Ignoră")
ruRU("Пропустить")
skSK("&Ignorovať")
srSP("")
trTR("&Ignore")
zhCN("忽略")
zhTW("忽略(&I)")


// Help.cpp

T_("Go Back")
caES("Tornar")
csCZ("Předchozí téma")
deDE("Rückwärts")
esES("Volver atrás")
fiFI("Palaa takaisin")
frFR("Précédent")
huHU("Visszalépés")
itIT("Indietro")
nlNL("Ga Terug")
plPL("Idź wstecz")
roRO("Înapoi")
ruRU("Назад")
skSK("Predošlá téma")
srSP("Nazad")
trTR(" Geri Git")
zhCN("回退")
zhTW("退回")

T_("Go Forward")
caES("Anar cap endavant")
csCZ("Další téma")
deDE("Vorwärts")
esES("Ir adelante")
fiFI("Siirry eteenpäin")
frFR("Suivant")
huHU("Előrelépés")
itIT("Avanti")
nlNL("Ga Heen")
plPL("Idź do przodu")
roRO("Înainte")
ruRU("Вперёд")
skSK("Ďalšia téma")
srSP("Napred")
trTR("İleri Git")
zhCN("向前")
zhTW("向前")

T_("Font size")
caES("Mida de la lletra")
csCZ("Velikost")
deDE("Schriftgrad")
esES("Tamaño del font")
fiFI("Kirjasinkoko")
frFR("Taille de police")
huHU("Betűméret")
itIT("Dimensione font")
nlNL("Lettertype grootte")
plPL("Rozmiar czcionki")
roRO("Dimensiunea fontului")
ruRU("Размер шрифта")
skSK("Veľkosť")
srSP("Veličina fonta")
trTR("Yazı tipi boyutu")
zhCN("字体大小")
zhTW("字體大小")

T_("Print")
caES("Imprimir")
csCZ("Tisk")
deDE("Drucken")
esES("Imprimir")
fiFI("Tulosta")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
nlNL("Afdrukken")
plPL("Drukuj")
roRO("Listează")
ruRU("Печать")
skSK("Tlač")
srSP("Štampa")
trTR("Yazdır")
zhCN("打印")
zhTW("列印")

T_("Help")
caES("Ajuda")
csCZ("Nápověda")
deDE("Hilfe")
esES("Ayuda")
fiFI("Apua")
frFR("Aide")
huHU("Súgó")
itIT("Aiuto")
nlNL("Help")
plPL("Pomoc")
roRO("Ajutor")
ruRU("Помощь")
skSK("Nápoveda")
srSP("Pomoć")
trTR("Yardım")
zhCN("帮助")
zhTW("說明")


// DateTimeCtrl.cpp

T_("Previous month")
caES("El mes anterior")
csCZ("Minulý měsíc")
deDE("Voriger Monat")
esES("Mes anterior")
fiFI("Edellinen kuukausi")
frFR("Mois précédent")
huHU("Előző hónap")
itIT("Mese precedente")
nlNL("Voorgaand maand")
plPL("Poprzedni miesiąc")
roRO("Luna trecută")
ruRU("Пред. месяц")
skSK("Predošlý mesiac")
srSP("")
trTR("Önceki ay")
zhCN("上个月")
zhTW("前一個月")

T_("Next month")
caES("El mes que ve")
csCZ("Další měsíc")
deDE("Nächster Monat")
esES("Mes siguiente")
fiFI("Seuraava kuukausi")
frFR("Mois suivant")
huHU("Következő hónap")
itIT("Mese successivo")
nlNL("Volgend maand")
plPL("Następny miesiąc")
roRO("Luna viitoare")
ruRU("След. месяц")
skSK("Ďalší mesiac")
srSP("")
trTR("Sonraki ay")
zhCN("下个月")
zhTW("下一個月")

T_("Previous year")
caES("L'any anterior")
csCZ("Minulý rok")
deDE("Voriges Jahr")
esES("Año anterior")
fiFI("Edellinen vuosi")
frFR("Année précédente")
huHU("Előző év")
itIT("Anno precedente")
nlNL("Voorgaand jaar")
plPL("Poprzedni rok")
roRO("Anul trecut")
ruRU("Пред. год")
skSK("Predošlý rok")
srSP("")
trTR("Önceki yıl")
zhCN("去年")
zhTW("去年")

T_("Next year")
caES("L'any que ve")
csCZ("Další rok")
deDE("Nächstes Jahr")
esES("Año siguiente")
fiFI("Seuraava vuosi")
frFR("Année suivante")
huHU("Következő év")
itIT("Anno successivo")
nlNL("Volgend jaar")
plPL("Następny rok")
roRO("Anul viitor")
ruRU("След. год")
skSK("Ďalší rok")
srSP("")
trTR("Sonraki yıl")
zhCN("明年")
zhTW("明年")

T_("Today")
caES("Avui")
csCZ("Dnes")
deDE("Heute")
esES("Hoy")
fiFI("Tänään")
frFR("Aujourd'hui")
huHU("Ma")
itIT("Oggi")
nlNL("Vandaag")
plPL("Dziś")
roRO("Azi")
ruRU("Сегодня")
skSK("Dnes")
srSP("")
trTR("Bugün")
zhCN("今天")
zhTW("今天")

T_("Wk")
caES("Sem")
csCZ("Tý")
deDE("Wo.")
esES("Sem")
fiFI("Vko")
frFR("Wk")
huHU("H")
itIT("Sett")
nlNL("Wk")
plPL("Ty.")
roRO("Sp")
ruRU("Нед.")
skSK("Tý.")
srSP("")
trTR("Hft.")
zhCN("星期")
zhTW("Wk")

T_("Previous hour")
caES("Hora anterior")
csCZ("Předchozí hodina")
deDE("Vorige Stunde")
esES("Hora anterior")
fiFI("Edellinen tunti")
frFR("Heure précédente")
huHU("Előző óra")
itIT("Ora precedente")
nlNL("Voorgaand uur")
plPL("")
roRO("Ora trecută")
ruRU("Час назад")
skSK("Predošlá hodina")
srSP("")
trTR("")
zhCN("前一小时")
zhTW("前一小時")

T_("Next hour")
caES("Hora següent")
csCZ("Další hodina")
deDE("Nächste Stunde")
esES("Hora siguiente")
fiFI("Seuraava tunti")
frFR("Heure suivante")
huHU("Következő óra")
itIT("Ora successiva")
nlNL("Volgend uur")
plPL("")
roRO("Ora viitoare")
ruRU("Через час")
skSK("Ďalšia hodina")
srSP("")
trTR("")
zhCN("后一小时")
zhTW("下一小時")

T_("Previous minute")
caES("Minut anterior")
csCZ("Předchozí minuta")
deDE("Vorige Minute")
esES("Minuto anterior")
fiFI("Edellinen minuutti")
frFR("Minute précédente")
huHU("Előző perc")
itIT("Minuto precedente")
nlNL("Voorgaand minuut")
plPL("")
roRO("Minutul trecut")
ruRU("Минуту назад")
skSK("Predošlá minúta")
srSP("")
trTR("")
zhCN("前一分钟")
zhTW("前一分鐘")

T_("Next minute")
caES("Minut següent")
csCZ("Další minuta")
deDE("Nächste Minute")
esES("Minuto siguiente")
fiFI("Seuraava minuutti")
frFR("Minute suivante")
huHU("Következő perc")
itIT("Minuto successivo")
nlNL("Volgend minuut")
plPL("")
roRO("Minutul următor")
ruRU("Через минуту")
skSK("Ďalšia minúta")
srSP("")
trTR("")
zhCN("后一分钟")
zhTW("下一分鐘")


// StatusBar.cpp

T_("Ready")
caES("Preparat")
csCZ("Připraven")
deDE("Fertig")
esES("Preparado")
fiFI("Valmis")
frFR("Prêt")
huHU("Kész")
itIT("Pronto")
nlNL("Gereed")
plPL("Gotowy")
roRO("Gata")
ruRU("Готов")
skSK("Pripravený")
srSP("Spreman")
trTR("Hazır")
zhCN("待命")
zhTW("待命")


// TabCtrl.cpp

T_("Apply")
caES("Aplicar")
csCZ("Použít")
deDE("Übernehmen")
esES("Aplicar")
fiFI("Käytä")
frFR("Appliquer")
huHU("Alkalmaz")
itIT("Applica")
nlNL("Toepassen")
plPL("Zastosuj")
roRO("Aplică")
ruRU("Применить")
skSK("Použiť")
srSP("Primeni")
trTR("Uygula")
zhCN("应用")
zhTW("應用")

T_("Close")
caES("Tancar")
csCZ("Zavřít")
deDE("Schließen")
esES("Cerrar")
fiFI("Sulje")
frFR("Fermer")
huHU("Bezár")
itIT("Chiudi")
nlNL("Sluiten")
plPL("Zamknij")
roRO("Închide")
ruRU("Закрыть")
skSK("Zatvoriť")
srSP("Zatvori")
trTR("Kapat")
zhCN("关闭")
zhTW("關閉")


// DlgColor.cpp

T_("(no color)")
caES("(sense color)")
csCZ("(bez barvy)")
deDE("(keine Farbe)")
esES("(sin color)")
fiFI("(ei väriä)")
frFR("(aucune couleur)")
huHU("(nincs szín)")
itIT("(nessun colore)")
nlNL("(geen kleur)")
plPL("(bez koloru)")
roRO("(fără culoare)")
ruRU("нет цвета")
skSK("(bez farby)")
srSP("(bez boje)")
trTR("(renk yok)")
zhCN("(无颜色)")
zhTW("(無顏色)")

T_("Set color")
caES("Establir color")
csCZ("Nastavit barvu")
deDE("Farbe festlegen")
esES("Establecer color")
fiFI("Aseta väri")
frFR("Appliquer la couleur")
huHU("Szín beállítása")
itIT("(Imposta colore)")
nlNL("Stel kleur in")
plPL("(Ustaw kolor)")
roRO("Setează culoarea")
ruRU("Установить цвет")
skSK("Nastaviť farbu")
srSP("Postavi boju")
trTR("Rengi ayarla")
zhCN("设置颜色")
zhTW("設定顏色")

T_("Write current color to selected palette slot")
caES("Desar el color actual al slot seleccionat en la paleta")
csCZ("Nastavit barvu pole v paletě na aktuální kreslicí barvu")
deDE("Palettenplatz mit aktueller Farbe belegen")
esES("Guardar el color actual en el slot seleccionado en la paleta")
fiFI("Aseta tämänhetkinen väri valittuun paletin soluun")
frFR("Ecrire la couleur courante dans l'emplacement sélectionné de la palette")
huHU("Aktuális szín beírása a kijelölt palettamezőbe")
itIT("Salva il colore corrente nella casella selezionata della tavolozza")
nlNL("Schrijf huidige kleur naar het palet vak")
plPL("Zapisz aktualny kolor do wskazanego miejsca w palecie kolorów")
roRO("Scrie culoarea curentă în locaţia din paletă selectată")
ruRU("Записать текущий цвет в выделенный слот "
     "палитры")
skSK("Nastaviť farbu poľa v palete na aktuálnu kresliacu farbu")
srSP("Zapiši trenutnu boju u izabranu paletu boja")
trTR("Seçilen palet slotunu geçerli renkle değiştir")
zhCN("写当前颜色到选择的调色板槽")
zhTW("寫目前顏色到選擇的調色盤槽")

T_("Default palette")
caES("Paleta per defecte")
csCZ("Standardní paleta")
deDE("Vorgabepalette")
esES("Paleta por defecto")
fiFI("Oletuspaletti")
frFR("Palette par défaut")
huHU("Alapértelmezett paletta")
itIT("Tavolozza predefinita")
nlNL("Standaard palet")
plPL("Domyślna paleta kolorów")
roRO("Paletă implicită")
ruRU("Палитра по умолчанию")
skSK("Predvolená paleta")
srSP("Podrazumevana paleta")
trTR("Varsayılan renk paleti")
zhCN("缺省调色板")
zhTW("預設調色盤")

T_("Restore default system palette")
caES("Restaurar la paleta per defecte del sistema")
csCZ("Nastavit standardní systémovou paletu")
deDE("Voreingestellte Systempalette wiederherstellen")
esES("Restaurar la paleta por defecto del sistema")
fiFI("Palauta järjestelmän oletuspaletti")
frFR("Restaurer la palette système par défaut")
huHU("Alapértelmezett rendszer paletta visszaállítása")
itIT("Ripristina la tavolozza predefinita")
nlNL("Herstel standaard systeem palet")
plPL("Przywróc standardową systemową paletę kolorów")
roRO("Restaurează paleta implictă a sistemului")
ruRU("Восстановить системную палитру по умолчанию")
skSK("Nastaviť predvolenú systémovú paletu")
srSP("Vrati standardnu paletu sistema")
trTR("Varsayılan sistem renk paletini geri yükle")
zhCN("恢复到缺省系统调色板")
zhTW("恢復到預設系統調色盤")

T_("Save as..")
caES("Desar com..")
csCZ("Uložit jako...")
deDE("Speichern unter ...")
esES("Guardar como..")
fiFI("Tallenna nimellä...")
frFR("Enregistrer sous..")
huHU("Mentés másként..")
itIT("Salva come..")
nlNL("Bewaar als..")
plPL("Zapisz jako...")
roRO("Salvează ca..")
ruRU("Сохранить как...")
skSK("Uložiť ako...")
srSP("Sačuvaj kao..")
trTR("Farklı kaydet...")
zhCN("保存为")
zhTW("儲存為")

T_("Store palette information into a disk file")
caES("Guardar en disc la informació de la paleta")
csCZ("Uložit paletu do souboru")
deDE("Paletteninformationen in einer Datei speichern")
esES("Guardar la información de la paleta en disco")
fiFI("Tallenna paletti tiedostoon")
frFR("Enregistrer la palette dans un fichier ")
huHU("Palettainformáció tárolása fájlba")
itIT("salva la tavolozza su disco")
nlNL("Sla de palet informatie op in een bestand")
plPL("Zapisz informacje o palecie kolorów do pliku")
roRO("Salvează informaţia despre paletă pe disc")
ruRU("Сохранить информацию о палитре в файл "
     "на диск")
skSK("Uložiť paletu do súboru")
srSP("Sačuvaj paletu u fajl na disku")
trTR("Renk paleti bilgisini dosyada sakla")
zhCN("保存调色板信息到磁盘文件")
zhTW("儲存調色盤資訊到磁片檔案")

T_("Load")
caES("Carrega")
csCZ("Načíst...")
deDE("Laden")
esES("Cargar")
fiFI("Lataa")
frFR("Charger")
huHU("Betöltés")
itIT("Carica")
nlNL("Laad")
plPL("Ładuj")
roRO("Încarcă")
ruRU("Загрузить")
skSK("Načítať...")
srSP("Učitaj")
trTR("Yükle")
zhCN("装载")
zhTW("載入")

T_("Load previously saved palette")
caES("Carregar paleta guardada prèviament")
csCZ("Načíst paletu z dříve uloženého souboru")
deDE("Zuvor gespeicherte Palette laden")
esES("Cargar la paleta guardada previamente")
fiFI("Lataa aiemmin tallennettu paletti")
frFR("Charger une palette précédemment sauvée")
huHU("Az előző tárolt paletta betöltése")
itIT("Carica una tavolozza precedentemente salvata")
nlNL("Laad een voorgaand bewaard palet")
plPL("Ładuj ostatnio zapisaną paletę kolorów")
roRO("Încarcă o paletă salvată")
ruRU("Загрузить сохранённую палитру")
skSK("Načítať paletu z predtým uloženého súboru")
srSP("Učitaj prethodno sačuvanu paletu")
trTR("Daha önce kaydedilmiş olan renk paletini yükle")
zhCN("载入以前保存的调色板")
zhTW("載入以前儲存的調色盤")

T_("Small")
caES("Petita")
csCZ("Malá")
deDE("Klein")
esES("Pequeño")
fiFI("Pieni")
frFR("Petit")
huHU("Kicsi")
itIT("Piccolo")
nlNL("Klein")
plPL("Mały")
roRO("Mic")
ruRU("Маленький")
skSK("Malá")
srSP("Mali")
trTR("Küçük")
zhCN("小")
zhTW("小")

T_("Set up palette size 4 times 4 colors")
caES("Configurar la mida de la paleta 4 vegades en 4 colors")
csCZ("Nastavit rozměry palety 4 x 4 polí")
deDE("Palette in der Größe von 4 mal 4 Farben erstellen")
esES("Establecer el tamaño de la paleta 4 veces 4 colores")
fiFI("Aseta paletin kooksi 4x4 väriä")
frFR("Modifier la taille de la palette à 4x4")
huHU("Palettaméret 4x4 színre állítása")
itIT("Imposta la tavolozza a 4 colori alla volta")
nlNL("Stel de palet grootte in op 4 maal 4 kleuren")
plPL("Ustaw rozmiar palety 4 na 4 kolory")
roRO("Setează dimensiunea paletei la 4 ori 4 culori")
ruRU("Установить размер палитры 16 цветов")
skSK("Nastaviť rozmery palety 4 x 4 polí")
srSP("Podesi veličinu palete na 4x4 boje")
trTR("16 renkli palet oluştur")
zhCN("设置调色板大小为4倍4颜色")
zhTW("設定調色盤大小為4倍4顏色")

T_("Medium")
caES("Mitjana")
csCZ("Střední")
deDE("Mittel")
esES("Medio")
fiFI("Keskikokoinen")
frFR("Moyen")
huHU("Közepes")
itIT("Medio")
nlNL("Middel")
plPL("Średni")
roRO("Mediu")
ruRU("Средний")
skSK("Stredná")
srSP("Srednji")
trTR("Orta")
zhCN("中")
zhTW("中")

T_("Set up palette size 8 times 8 colors")
caES("Set up palette size 8 times 8 colors")
csCZ("Nastavit rozměry palety 8 x 8 polí")
deDE("Palette in der Größe von 8 mal 8 Farben erstellen")
esES("Establecer el tamaño de la la paleta 8 veces 8 colores")
fiFI("Aseta paletin kooksi 8x8 väriä")
frFR("Modifier la taille de la palette à 8x8")
huHU("Palettaméret 8x8 színre állítása")
itIT("Imposta la tavolozza a 8 colori alla volta")
nlNL("Stel de palet grootte in op 8 maal 8 kleuren")
plPL("Ustaw rozmiar palety 8 na 8 kolorów")
roRO("Setează dimensiunea paletei la 8 ori 8 culori")
ruRU("Установить размер палитры 64 цветов")
skSK("Nastaviť rozmery palety 8 x 8 polí")
srSP("Podesi veličinu palete na 8x8 boja")
trTR("64 renkli palet oluştur")
zhCN("设置调色板大小为8倍8颜色")
zhTW("設定調色盤大小為8倍8顏色")

T_("Large")
caES("Gran")
csCZ("Velká")
deDE("Groß")
esES("Grande")
fiFI("Suuri")
frFR("Large")
huHU("Nagy")
itIT("Largo")
nlNL("Groot")
plPL("Duży")
roRO("Mare")
ruRU("Большой")
skSK("Veľká")
srSP("Velika")
trTR("Büyük")
zhCN("大")
zhTW("大")

T_("Set up palette size 16 times 16 colors (maximum size)")
caES("Set up palette size 16 times 16 colors (mida màxima)")
csCZ("Nastavit rozměry palety 16 x 16 polí (max. velikost)")
deDE("Palette in der Größe von 16 mal 16 Farben erstellen (Maximalgröße)")
esES("Establecer el tamaño de la paleta 16 veces 16 colores (tamaño máximo)")
fiFI("Aseta paletin kooksi 16x16 väriä (maksimikoko)")
frFR("Modifier la taille de la palette à 16x16")
huHU("Palettaméret 16x16 színre állítása")
itIT("Imposta la tavolozza a 16 colori alla volta (dimensione massima)")
nlNL("Stel de palet grootte in op 16 maal 16 kleuren (maximale grootte)")
plPL("Ustaw rozmiar palety 16 na 16 kolorów")
roRO("Setează dimensiunea paletei la 16 ori 16 culori (dimensiunea maximă)")
ruRU("Установить размер палитры 256 цветов (максимальный "
     "размер)")
skSK("Nastaviť rozmery palety 16 x 16 polí (max. veľkosť)")
srSP("Podesi veličinu palete na 16x16 boja (maksimalna veličina)")
trTR("256 renkli palet oluştur")
zhCN("设置调色板大小为16倍16颜色(最大)")
zhTW("設定調色盤大小為16倍16顏色(最大)")

T_("Custom...")
caES("Personalitzat...")
csCZ("Vlastní...")
deDE("Eigen ...")
esES("Personalizar...")
fiFI("Mukautettu...")
frFR("Personnalisé...")
huHU("Választott...")
itIT("Personalizzato...")
nlNL("Aangepast...")
plPL("Własny...")
roRO("Definit de utilizator...")
ruRU("Пользовательская...")
skSK("Vlastná...")
srSP("Proizvoljno...")
trTR("Özel...")
zhCN("定制...")
zhTW("自訂...")

T_("Select custom palette size")
caES("Seleccioneu la mida de paleta personalitzada")
csCZ("Zvolit vlastní počet polí v paletě")
deDE("Eigene Palettengröße auswählen")
esES("Seleccionar el tamaño personal de la paleta")
fiFI("Valitse mukautettu paletin koko")
frFR("Sélectionner une taille personnalisée de palette")
huHU("Választott palettaméret beállítása")
itIT("Seleziona tavolozza di dimensione personalizzata")
nlNL("Selecteer aangepaste palet grootte")
plPL("Ustaw własny rozmiar palety kolorów")
roRO("Alege dimensiunea paletei")
ruRU("Выберите размер пользовательской палитры")
skSK("Zvoliť vlastný počet polí v palete")
srSP("Izaberi proizvoljnu veličinu palete")
trTR("Özel palet boyutunu seç")
zhCN("选择定制调色板大小")
zhTW("選擇自訂調色盤大小")

T_("Palette (*.pal)")
caES("Paleta (*.pal)")
csCZ("Paleta (*.pal)")
deDE("Palette (*.pal)")
esES("Paleta (*.pal)")
fiFI("Paletti (*.pal)")
frFR("Palette (*.pal)")
huHU("Paletta (*.pal)")
itIT("Tavolozza (*.pal)")
nlNL("Palet (*.pal)")
plPL("Paleta (*.pal)")
roRO("Paletă (*.pal)")
ruRU("Палитра (*.pal)")
skSK("Paleta (*.pal)")
srSP("Paleta (*.pal)")
trTR("Palet (*.pal)")
zhCN("调色板(*.pal)")
zhTW("調色盤(*.pal)")

T_("*.pal")
caES("*.pal")
csCZ("*.pal")
deDE("*.pal")
esES("*.pal")
fiFI("*.pal")
frFR("*.pal")
huHU("*.pal")
itIT("*.pal")
nlNL("*.pal")
plPL("*.pal")
roRO("*.pal")
ruRU("")
skSK("*.pal")
srSP("*.pal")
trTR("*.pal")
zhCN("*.pal")
zhTW("*.pal")

T_("pal")
caES("pal")
csCZ("pal")
deDE("pal")
esES("pal")
fiFI("pal")
frFR("pal")
huHU("pal")
itIT("pal")
nlNL("pal")
plPL("pal")
roRO("pal")
ruRU("")
skSK("pal")
srSP("pal")
trTR("pal")
zhCN("pal")
zhTW("pal")

T_("Save palette as..")
caES("Guardar paleta com ..")
csCZ("Uložit paletu jako...")
deDE("Palette speichern unter ...")
esES("Guardar paleta como..")
fiFI("Tallenna paletti nimellä...")
frFR("Sauver la palette sous..")
huHU("Paletta mentése más néven..")
itIT("Salva tavolozza come..")
nlNL("Bewaar palet als..")
plPL("Zapisz paletę kolorów jako...")
roRO("Salvează paleta ca..")
ruRU("Сохранить палитру как...")
skSK("Uložiť paletu ako...")
srSP("Sačuvajte paletu kao...")
trTR("Paleti farklı kaydet...")
zhCN("保存调色板为..")
zhTW("儲存調色盤為..")

T_("Error writing file [* \001%s\001].")
caES("Error escrivint arxiu [* \001%s\001].")
csCZ("Chyba při zápisu do souboru [* \001%s\001].")
deDE("Fehler beim Schreiben der Datei [* \001%s\001]")
esES("Error escribiendo archivo [* \001%s\001].")
fiFI("Virhe tallennettaessa tiedostoa  [* \001%s\001].")
frFR("Erreur d'écriture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl írásakor")
itIT("Errore di scrittura file [* \001%s\001].")
nlNL("Fout tijdens schrijven naar bestand [* \001%s\001].")
plPL("Błąd zapisu pliku [* \001%s\001].")
roRO("Eroare la salvarea fişierului [* \001%s\001].")
ruRU("Ошибка записи файла [* \001%s\001].")
skSK("Chyba pri zápise do súboru [* \001%s\001].")
srSP("Greška prilikom pisanja fajla [* \001%s\001].")
trTR("Dosya yazma hatası: veriler [* \001%s\001] dosyasına yazılamıyor.")
zhCN("写文件错误[* \001%s\001].")
zhTW("寫入檔案錯誤[* \001%s\001].")

T_("Load palette..")
caES("Carregar paleta..")
csCZ("Načíst paletu...")
deDE("Palette laden ...")
esES("Cargar paleta..")
fiFI("Lataa paletti...")
frFR("Charger la palette..")
huHU("Paletta betöltése..")
itIT("Carica tavolozza..")
nlNL("Laad palet..")
plPL("Ładuj paletę kolorów...")
roRO("Încarcă paleta")
ruRU("Загрузить палитру...")
skSK("Načítať paletu...")
srSP("Učitaj paletu..")
trTR("Renk paleti yükle...")
zhCN("装载调色板..")
zhTW("載入調色盤..")

T_("Error opening file [* \001%s\001].")
caES("Error obrint arxiu [* \001%s\001].")
csCZ("Nelze otevřít soubor [* \001%s\001].")
deDE("Fehler beim Öffnen der Datei [* \001%s\001]")
esES("Error abriendo archivo [* \001%s\001].")
fiFI("Virhe avattaessa tiedostoa [* \001%s\001].")
frFR("Erreur d'ouverture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl megnyitásakor")
itIT("Errore di apertura file [* \001%s\001].")
nlNL("Fout tijdens openen bestand [* \001%s\001].")
plPL("Błąd otwarcia pliku [* \001%s\001].")
roRO("Eroare la deschiderea fişierului [* \001%s\001].")
ruRU("Ошибка открытия файла [* \001%s\001].")
skSK("Nemožno otvoriť súbor [* \001%s\001].")
srSP("Greška prilikom otvaranja fajla [* \001%s\001].")
trTR("Dosya yazma hatası: [* \001%s\001] dosyası açılamıyor.")
zhCN("打开文件错误[* \001%s\001].")
zhTW("開啟檔案錯誤[* \001%s\001].")

T_("Error reading palette from file [* \001%s\001].")
caES("Error llegint paleta des arxiu [* \001%s\001].")
csCZ("Chyba při načítání palety ze souboru [* \001%s\001].")
deDE("Fehler beim Lesen der Palette aus der Datei [* \001%s\001]")
esES("Error leyendo paleta desde archivo [* \001%s\001].")
fiFI("Virhe luettaessa palettia tiedostosta [* \001%s\001].")
frFR("Erreur de lecture du fichier de palette [* \001%s\001].")
huHU("Hiba a paletta beolvasásakor a [* \001%s\001] fájlból")
itIT("Errore di lettura tavolozza dal file [* \001%s\001].")
nlNL("Fout tijdens lezen bestand [* \001%s\001].")
plPL("Błąd czytania palety kolorów z pliku [* \001%s\001].")
roRO("Eroare la citirea paletei din fişierul [* \001%s\001].")
ruRU("Ошибка чтения палитры из файла [* \001%s\001].")
skSK("Chyba pri načítaní palety zo súboru [* \001%s\001].")
srSP("Greška prilikom čitanja fajla [* \001%s\001].")
trTR("Dosya okuma hatası: palet [* \001%s\001] dosyasından okunamıyor.")
zhCN("从文件[* \001%s\001]. 读调色板错")
zhTW("從檔案[* \001%s\001]. 讀取調色盤錯誤")

T_("Palette dimensions")
caES("Dimensions de paleta")
csCZ("Rozměry palety")
deDE("Palettenmaße")
esES("Tamaño de la paleta")
fiFI("Paletin dimensiot")
frFR("Dimensions de la palette")
huHU("Paletta dimenziói")
itIT("Dimensioni tavolozza")
nlNL("Palet dimensies")
plPL("Rozmiary palety kolorów")
roRO("Dimensiunile paletei")
ruRU("Размер палитры")
skSK("Rozmery palety")
srSP("Dimenzije palete")
trTR("Palet boyutları")
zhCN("调色板维度")
zhTW("調色盤維度")

T_("(transparent)")
caES("(transparent)")
csCZ("(průhledná)")
deDE("(transparent)")
esES("(transparente)")
fiFI("(läpinäkyvä)")
frFR("transparent")
huHU("(átlátszó)")
itIT("(trasparente)")
nlNL("(transparant)")
plPL("(przezroczysty)")
roRO("(transparent)")
ruRU("(прозрачный)")
skSK("(priehľadná)")
srSP("(transparenta)")
trTR("(saydam)")
zhCN("(透明)")
zhTW("(透明)")

T_("Palette")
caES("Paleta")
csCZ("Paleta")
deDE("Palette")
esES("Paleta")
fiFI("Paletti")
frFR("Palette")
huHU("Paletta")
itIT("Tavolozza")
nlNL("Palet")
plPL("Paleta")
roRO("Paletă")
ruRU("Палитра")
skSK("Paleta")
srSP("Paleta")
trTR("Palet")
zhCN("调色板")
zhTW("調色盤")

T_("Wheel")
caES("Roda")
csCZ("Kolo")
deDE("Farbkreis")
esES("Rueda")
fiFI("Pyörä")
frFR("Molette")
huHU("Korong")
itIT("Ruota")
nlNL("Wiel")
plPL("Koło")
roRO("Roată")
ruRU("Колесо")
skSK("Koleso")
srSP("Točak")
trTR("Teker")
zhCN("滚轮")
zhTW("滾輪")

T_("Hue")
caES("Matís")
csCZ("Odstín")
deDE("Farbton")
esES("Sat")
fiFI("Sävy (Hue)")
frFR("Tinte")
huHU("Színezet")
itIT("Tinta")
nlNL("Tint")
plPL("Odcień")
roRO("Hue")
ruRU("Оттенок")
skSK("Odtieň")
srSP("Obojenost")
trTR("Renk (Hue)")
zhCN("色调")
zhTW("色調")

T_("RGB")
caES("RGB")
csCZ("RGB")
deDE("RGB")
esES("RGB")
fiFI("RGB")
frFR("RVB")
huHU("RGB")
itIT("RGB")
nlNL("RGB")
plPL("RGB")
roRO("RGB")
ruRU("")
skSK("RGB")
srSP("RGB")
trTR("RGB")
zhCN("RGB")
zhTW("RGB")

T_("HSV")
caES("HSV")
csCZ("HSV")
deDE("FSH")
esES("HSV")
fiFI("HSV")
frFR("HSV")
huHU("HSB")
itIT("HSV")
nlNL("HSV")
plPL("HSV")
roRO("HSV")
ruRU("")
skSK("HSV")
srSP("HSV")
trTR("HSV")
zhCN("HSV")
zhTW("HSV")

T_("Select color")
caES("Seleccionar color")
csCZ("Výběr barvy")
deDE("Farbe auswählen")
esES("Seleccionar de color")
fiFI("Valitse väri")
frFR("Sélectionner la couleur")
huHU("Szín választása")
itIT("Seleziona colore")
nlNL("Selecteer kleur")
plPL("Wybrany kolor")
roRO("Alege culoarea")
ruRU("Выбирите цвет")
skSK("Výber farby")
srSP("Izaberi boju")
trTR("Renk Seçin")
zhCN("选择颜色")
zhTW("選擇顏色")


// FileSel.cpp

T_("Network")
caES("Xarxa")
csCZ("")
deDE("")
esES("Red")
fiFI("")
frFR("")
huHU("")
itIT("Rete")
nlNL("")
plPL("")
roRO("Rețea")
ruRU("Сеть")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("[A3* Unable to read the directory !]&&")
caES("A3* No es pot llegir el directori !]&&")
csCZ("[A3* Nelze načíst obsah adresáře !]&&")
deDE("[A3* Verzeichnis kann nicht gelesen werden!]&&")
esES("[A3* ¡No se puede leer el directorio!]&&")
fiFI("[A3* Kansiota ei kyetä lukemaan !]&&")
frFR("[A3* Impossible de lire le répertoire !]&&")
huHU("[A3* Nem sikerült olvasni a mappát!]&&")
itIT("[A3* Impossibile leggere la cartella !]&&")
nlNL("[A3* Kan de map niet uitlezen !]&&")
plPL("[A3* Nie można odczytać katalogu !]&&")
roRO("[A3* Directorul nu poate fi citit !]&&")
ruRU("[A3* Не могу прочитать папку!]&&")
skSK("[A3* Nemožno načítať obsah priečinka !]&&")
srSP("[A3* Ne mogu da pročitam folder!]&&")
trTR("[A3* Klasör okunamıyor !]&&")
zhCN("[A3* 不能读取目录 !]&&")
zhTW("[A3* 不能讀取目錄 !]&&")

T_(" is directory.")
caES(" és directori.")
csCZ(" je adresář.")
deDE(" ist ein Verzeichnis.")
esES(" es directorio.")
fiFI(" on kansio.")
frFR(" est un répertoire.")
huHU("mappa")
itIT(" è una cartella.")
nlNL(" is een map.")
plPL(" jest katalogiem.")
roRO(" este director")
ruRU(" папка.")
skSK(" je priečinok.")
srSP(" je folder.")
trTR(" bir klasördür")
zhCN(" 为目录.")
zhTW(" 為目錄.")

T_(" already exists.&Do you want to continue ?")
caES(" ja existeix.&Voleu continuar ?")
csCZ(" již existuje.&Přejete si pokračovat ?")
deDE(" existiert bereits. &Möchten Sie fortfahren?")
esES(" ya existe.&Quieres continuar?")
fiFI(" on jo olemassa.&Haluatko silti jatkaa?")
frFR(" existe déjà.&Voulez-vous continuer ?")
huHU("már létezik. &Folytatás?")
itIT(" esiste già.&Desideri proseguire ?")
nlNL(" bestaat alreeds.&Wil je doorgaan ?")
plPL(" już istnieje. &Czy chcesz kontynuować ?")
roRO(" există deja.&Doriţi să continuaţi ?")
ruRU(" уже существует. &Вы хотите продолжить?")
skSK(" už existuje.&Prajete si pokračovať ?")
srSP(" već postoji. &Da li želite da nastavite?")
trTR(" zaten var.&Yine de devam etmek istiyor musunuz?")
zhCN(" 已经存在.继续(&D)?")
zhTW(" 已經存在.繼續(&D)?")

T_(" does not exist.")
caES(" no existeix.")
csCZ(" neexistuje.")
deDE(" existiert nicht.")
esES(" no existe.")
fiFI(" ei ole olemassa.")
frFR(" n'existe pas.")
huHU("nem létezik")
itIT(" non esistono.")
nlNL(" bestaat niet.")
plPL(" nie istnieje.")
roRO(" nu există")
ruRU(" не существует.")
skSK(" neexistuje.")
srSP(" ne postoji.")
trTR(" yok.")
zhCN("不存在")
zhTW("不存在")

T_("&do not exist.")
caES("&no existeix.")
csCZ("&neexistují.")
deDE("existieren nicht")
esES("&no existe.")
fiFI("&ei ole olemassa.")
frFR("&n'existe pas")
huHU("&nem létezik")
itIT(" non esiste")
nlNL("&bestaat niet.")
plPL(" &nie istnieje.")
roRO("&nu există")
ruRU("&не существует.")
skSK("&neexistujú.")
srSP("&ne postoji.")
trTR("& yok.")
zhCN("不存在(&d)")
zhTW("不存在(&d)")

T_("&Do you want to continue ?")
caES("&Voleu continuar ?")
csCZ("&Přejete si pokračovat ?")
deDE("&Möchten Sie fortfahren?")
esES("¿&Quieres continuar?")
fiFI("&Haluatko jatkaa?")
frFR("&Voulez-vous continuer ?")
huHU("&Folytatás?")
itIT("&Desideri proseguire ?")
nlNL("&Wil je doorgaan ?")
plPL("&Czy chcesz kontynuować ?")
roRO("&Doriţi să continuaţi ?")
ruRU("&Вы хотите продолжить?")
skSK("&Prajete si pokračovať ?")
srSP("&Da li želite da nastavite?")
trTR("&Devam etmek istiyor musunuz?")
zhCN("继续(&D)?")
zhTW("繼續(&D)?")

T_("Custom file type (")
caES("Tipus d'arxiu personalitzat (")
csCZ("Jiný typ souboru (")
deDE("Eigener Dateityp (")
esES("Tipo de archivo personalizado(")
fiFI("Mukautettu tiedostotyyppi (")
frFR("Type de fichier personnalisé (")
huHU("Választott fájltípus (")
itIT("Tipo file personalizzato (")
nlNL("Aangepaste bestandstype (")
plPL("Własny typ pliku (")
roRO("Tip de fișier ales de utilizator")
ruRU("Свой тип файла (")
skSK("Iný typ súboru (")
srSP("Proizvoljni tip fajla (")
trTR("Özel dosya türü(")
zhCN("定制文件类型 (")
zhTW("自訂檔案類型 (")

T_("New directory")
caES("Nou directori")
csCZ("Nový adresář")
deDE("Neues Verzeichnis")
esES("Nuevo directorio")
fiFI("Uusi kansio")
frFR("Nouveau répertoire")
huHU("Új mappa")
itIT("Nuova cartella")
nlNL("Nieuwe map")
plPL("Nowy katalog")
roRO("Director nou")
ruRU("Новая папка")
skSK("Nový priečinok")
srSP("Novi folder")
trTR("Yeni klasör")
zhCN("新建文件夹")
zhTW("建立資料夾")

T_("Name")
caES("Nom")
csCZ("Jméno")
deDE("Name")
esES("Nombre")
fiFI("Nimi")
frFR("Nom")
huHU("Név")
itIT("Nome")
nlNL("Naam")
plPL("Nazwa")
roRO("Nume")
ruRU("Имя")
skSK("Názov")
srSP("Ime")
trTR("İsim")
zhCN("名称")
zhTW("名稱")

T_("[A3* Creating directory failed !&&]")
caES("[A3* Error a la Creació del Directori !&&]")
csCZ("[A3* Chyba při vytváření adresáře !&&]")
deDE("[A3* Verzeichnis konnte nicht erstellt werden!&&]")
esES("[A3* Falló la creación del directorio !&&]")
fiFI("[A3* Kansion luominen epäonnistui!&&]")
frFR("[A3* La création du répertoire a échoué !&&]")
huHU("[A3* A mappa létrehozása sikertelen!&&]")
itIT("[A3* Creazione cartella fallita !&&]")
nlNL("[A3* Map aanmaken mislukt !&&]")
plPL("[A3* Tworzenie katalogu nie powiodło się !&&]")
roRO("[A3* Crearea directorului a eşuat !&&]")
ruRU("[A3* Не удалось создать папку!&&]")
skSK("[A3* Chyba pri vytváraní priečinka !&&]")
srSP("[A3* Pravljenje foldera nije uspelo!&&]")
trTR("[A3* Klasör oluşturulamadı !]&&")
zhCN("[A3* 创建文件夹失败 !&&]")
zhTW("[A3* 建立資料夾失敗 !&&]")

T_("Mask")
caES("Màscara")
csCZ("Maska")
deDE("Maske")
esES("Máscara")
fiFI("Maski")
frFR("Masque")
huHU("Maszk")
itIT("Maschera")
nlNL("Masker")
plPL("Maska")
roRO("Mască")
ruRU("Маска")
skSK("Maska")
srSP("Maska")
trTR("Maske")
zhCN("掩码")
zhTW("遮罩")

T_("Add to selection")
caES("Afegir a la selecció")
csCZ("Přidat k výběru")
deDE("Zur Auswahl hinzufügen")
esES("Añadir a la selección")
fiFI("Lisää valintaan")
frFR("Ajouter à la sélection")
huHU("Hozzáadás a kijelöléshez")
itIT("Aggiungi alla selezione")
nlNL("Toevoegen aan selectie")
plPL("Dodaj do zaznaczonych")
roRO("Adaugă la selecţie")
ruRU("Добавить к выделению")
skSK("Pridať k výberu")
srSP("Dodaj u izbor")
trTR("Seçilenlere ekle")
zhCN("选上")
zhTW("選上")

T_("Remove from selection")
caES("Eliminar de la selecció")
csCZ("Odebrat od výběru")
deDE("Aus der Auswahl entfernen")
esES("Eliminar de la selección")
fiFI("Poista valinnasta")
frFR("Enlever de la sélection")
huHU("Eltávolítás a kijelölésből")
itIT("Rimuovi dalla selezione")
nlNL("Verwijderen uit selectie")
plPL("Usuń z zaznaczonych")
roRO("Înlătură din selecţie")
ruRU("Убрать из выделения")
skSK("Odobrať od výberu")
srSP("Ukloni iz selekcije")
trTR("Seçilenlerden çıkar")
zhCN("去选")
zhTW("去選")

T_("  Drive")
caES(" Unitat")
csCZ("  Disková jednotka")
deDE("  Laufwerk")
esES("  Disco")
fiFI("  Levyasema")
frFR("  Disque")
huHU("  Meghajtó")
itIT("  Disco")
nlNL("  Schijf")
plPL("  Napęd")
roRO("  Unitate")
ruRU("  Диск")
skSK("  Disková jednotka")
srSP("  Disk")
trTR("  Sürücü")
zhCN("  驱动")
zhTW("  驅動")

T_("Directory  ")
caES("Directori  ")
csCZ("Adresář  ")
deDE("Verzeichnis  ")
esES("Directorio")
fiFI("Kansio  ")
frFR("Répertoire")
huHU("Mappa")
itIT("Cartella ")
nlNL("Map  ")
plPL("Katalog  ")
roRO("Director  ")
ruRU("Папка  ")
skSK("Priečinok  ")
srSP("Folder ")
trTR(" Klasör ")
zhCN("文件夹  ")
zhTW("資料夾  ")

T_(" drive(s)")
caES(" unitat(s)")
csCZ(" disk(y)")
deDE("Laufwerk(e)")
esES(" unidad(es)")
fiFI("")
frFR("")
huHU(" meghajtó(k)")
itIT(" disco/i")
nlNL(" schij(f)(ven)")
plPL("")
roRO(" unitate(unitati)")
ruRU("диск(и)")
skSK(" disk(y)")
srSP("")
trTR("")
zhCN(" 驱动(s)")
zhTW("")

T_(" folder(s)")
caES(" carpeta(s)")
csCZ(" adresář(e)")
deDE("Ordner")
esES(" carpeta(s)")
fiFI("")
frFR("")
huHU(" mappá(k)")
itIT("cartella/e")
nlNL(" map(pen)")
plPL("")
roRO(" director(directoare)")
ruRU("папка(и)")
skSK(" priečinok(ky)")
srSP("")
trTR("")
zhCN(" 文件夹(s)")
zhTW(" 個資料夾")

T_(" file(s)")
caES(" arxiu(s)")
csCZ(" soubor(y)")
deDE("Datei(en)")
esES(" archivo(s)")
fiFI("")
frFR("")
huHU(" fájl(ok)")
itIT("file")
nlNL(" bestand(en)")
plPL("")
roRO(" fişier(e)")
ruRU("файл(ы)")
skSK(" súbor(y)")
srSP("")
trTR("")
zhCN(" 文件(s)")
zhTW(" 個檔案")

T_("Open")
caES("Obrir")
csCZ("Otevřít")
deDE("Öffnen")
esES("Abrir")
fiFI("Avaa")
frFR("Ouvrir")
huHU("Megnyitás")
itIT("Apri")
nlNL("Openen")
plPL("Otwórz")
roRO("Deschide")
ruRU("Открыть")
skSK("Otvoriť")
srSP("Otvori")
trTR("Aç")
zhCN("打开")
zhTW("開啟")

T_("Save")
caES("Desar")
csCZ("Uložit")
deDE("Speichern")
esES("Guardar")
fiFI("Tallenna")
frFR("Sauver")
huHU("Mentés")
itIT("Salva")
nlNL("Bewaren")
plPL("Zapisz")
roRO("Salvează")
ruRU("Сохранить")
skSK("Uložiť")
srSP("Sačuvaj")
trTR("Kaydet")
zhCN("保存")
zhTW("儲存")

T_("[A3* Renaming of file failed !&&]")
caES("[A3* Error al canvi de nom de fitxer !&&]")
csCZ("[A3* Chyba při přejmenovávání souboru !&&]")
deDE("[A3* Datei konnte nicht umbenannt werden!&&]")
esES("[A3* Error al renombrar el archivo !&&]")
fiFI("[A3* Tiedoston uudelleennimeäminen epäonnistui!&&]")
frFR("[A3* Le renommage du fichier a échoué !&&]")
huHU("[A3* A fájl átnevezése sikertelen!&&]")
itIT("[A3* Rinomina fallito !&&]")
nlNL("[A3* Hernoemen bestand mislukt !&&]")
plPL("[A3* Zmiana nazwy pliku nie powiodła się !&&]")
roRO("[A3* Redenumirea fişierului a eşuat !&&]")
ruRU("[A3* Не удалось переименовать файл!&&]")
skSK("[A3* Chyba pri premenovávaní súboru !&&]")
srSP("[A3* Promena imena fajla nije uspela!&&]")
trTR("[A3* Dosya yeniden adlandırılamadı !]&&")
zhCN("[A3* 文件重命名失败 !&&]")
zhTW("[A3* 檔案重新命名失敗 !&&]")

T_("All files")
caES("Tots els fitxers")
csCZ("Všechny soubory")
deDE("Alle Dateien")
esES("Todos los archivos")
fiFI("Kaikki tiedostot")
frFR("Tous les fichiers")
huHU("Az összes fájl")
itIT("Tutti i files")
nlNL("Alle bestanden")
plPL("Wszystkie pliki")
roRO("Toate fişierele")
ruRU("Все файлы")
skSK("Všetky súbory")
srSP("Svi fajlovi")
trTR("Tüm dosyalar")
zhCN("所有文件")
zhTW("所有檔案")

T_("&Select")
caES("&Seleccionar")
csCZ("&Vybrat")
deDE("&Auswählen")
esES("&Seleccionar")
fiFI("&Valitse")
frFR("&Sélectionner")
huHU("&Kijelölés")
itIT("Seleziona")
nlNL("&Selecteer")
plPL("&Wybierz")
roRO("&Selectează")
ruRU("&Выбрать")
skSK("&Vybrať")
srSP("&Izaberi")
trTR("&Seç")
zhCN("选择(&S)")
zhTW("選擇(&S)")

T_("Save as")
caES("Guardar com")
csCZ("Uložit jako")
deDE("Speichern unter")
esES("Guardar como")
fiFI("Tallenna nimellä")
frFR("Sauver sous")
huHU("Mentés más néven")
itIT("Salva come")
nlNL("Bewaar als")
plPL("Zapisz jako")
roRO("Salvează ca")
ruRU("Сохранить как")
skSK("Uložiť ako")
srSP("Sačuvaj kao")
trTR("Farklı kaydet")
zhCN("另存为")
zhTW("另存為")

T_("Select directory")
caES("Seleccionar directori")
csCZ("Vybrat adresář")
deDE("Verzeichnis auswählen")
esES("Seleccionar directorio")
fiFI("Valitse kansio")
frFR("Sélectionner un répertoire")
huHU("Mappa kijelölése")
itIT("Seleziona cartella")
nlNL("Selecteer map")
plPL("Wybierz katalog")
roRO("Alege directorul")
ruRU("Выберите папку")
skSK("Vybrať priečinok")
srSP("Izaberi folder")
trTR("Klasör seç")
zhCN("选择文件夹")
zhTW("選擇資料夾")

T_("Home")
caES("Inici")
csCZ("")
deDE("")
esES("Inicio")
fiFI("")
frFR("")
huHU("Home")
itIT("Home")
nlNL("")
plPL("")
roRO("")
ruRU("Домашняя папка")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Desktop")
caES("Escriptori")
csCZ("")
deDE("")
esES("Escritorio")
fiFI("")
frFR("")
huHU("")
itIT("Scrivania")
nlNL("")
plPL("")
roRO("")
ruRU("Рабочий стол")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Music")
caES("Música")
csCZ("")
deDE("")
esES("Música")
fiFI("")
frFR("")
huHU("")
itIT("Musica")
nlNL("")
plPL("")
roRO("")
ruRU("Музыка")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Pictures")
caES("Imatges")
csCZ("")
deDE("")
esES("Imágenes")
fiFI("")
frFR("")
huHU("")
itIT("Immagini")
nlNL("")
plPL("")
roRO("")
ruRU("Картинки")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Videos")
caES("Vídeos")
csCZ("")
deDE("")
esES("Vídeos")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("")
ruRU("Видео")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Documents")
caES("Documents")
csCZ("")
deDE("")
esES("Documentos")
fiFI("")
frFR("")
huHU("")
itIT("Documenti")
nlNL("")
plPL("")
roRO("")
ruRU("Документы")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Downloads")
caES("Descàrregues")
csCZ("")
deDE("")
esES("Descargas")
fiFI("")
frFR("")
huHU("")
itIT("Scaricati")
nlNL("")
plPL("")
roRO("")
ruRU("Загрузки")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Dir up")
caES("Dir dalt")
csCZ("Nadřazený adresář")
deDE("Übergeordnetes Vwerzeichnis")
esES("Directorio superior")
fiFI("Ylemmän tason kansio")
frFR("Répertoire parent")
huHU("Szülőmappa")
itIT("Cartella su")
nlNL("Map omhoog")
plPL("Katalog w górę")
roRO("Directorul părinte")
ruRU("Папка вверх")
skSK("Nadradený priečinok")
srSP("Folder iznad")
trTR("Üst klasöre çık")
zhCN("向上")
zhTW("向上")

T_("Create directory")
caES("Crear directori")
csCZ("Vytvořit adresář")
deDE("Verzeichnis erstellen")
esES("Crear directorio")
fiFI("Luo kansio")
frFR("Créer un répertoire")
huHU("Mappa létrehozása")
itIT("Crea nuova cartella")
nlNL("Map aanmaken")
plPL("Utwórz katalog")
roRO("Crează director")
ruRU("Создать папку")
skSK("Vytvoriť priečinok")
srSP("Napravi folder")
trTR("Klasör oluştur")
zhCN("创建文件夹")
zhTW("建立資料夾")

T_("Select files")
caES("Seleccioneu els fitxers")
csCZ("Označit soubory")
deDE("Dateien auswählen")
esES("Seleccionar archivos")
fiFI("Valitse tiedostot")
frFR("Sélectionner les fichiers")
huHU("Fájlok kijelölése")
itIT("Seleziona i files")
nlNL("Selecteer bestanden")
plPL("Wybierz pliki")
roRO("Selectează fişierele")
ruRU("Выделить файлы")
skSK("Označiť súbory")
srSP("Izaberite fajlove")
trTR("Dosyaları seç")
zhCN("选择文件")
zhTW("選擇檔案")

T_("Unselect files")
caES("No seleccionar els arxius")
csCZ("Odznačit soubory")
deDE("Dateien abwählen")
esES("Desmarcar archivos")
fiFI("Poista tiedostojen valinta")
frFR("Désélectionner les fichiers")
huHU("Fájlkijelölés megszüntetése")
itIT("Deseleziona i files")
nlNL("Deselecteren bestanden")
plPL("Odznacz pliki")
roRO("Deselectează fişierele")
ruRU("Убрать выделение файлов")
skSK("Odznačiť súbory")
srSP("Deselektujte fajlove")
trTR("Seçili dosyaları iptal et")
zhCN("取消选择文件")
zhTW("取消選擇檔案")

T_("Toggle files")
caES("Canviar els arxius")
csCZ("Inverze označení")
deDE("Dateiauswahl umkehren")
esES("Intercambiar archivos")
fiFI("Käänteinen tiedostojen valinta")
frFR("Invertir la sélection")
huHU("Kijelölés felcserélése")
itIT("Inverti selezione")
nlNL("Flip bestanden")
plPL("Odwróć zaznaczone pliki")
roRO("Alternează fișierele")
ruRU("Поменять выделение файлов")
skSK("Inverzné označenie")
srSP("Invertuj izabrane")
trTR("Seçili dosyaları değiştir")
zhCN("Toggle files")
zhTW("Toggle files")


// FileSelUtil.cpp

T_("Unable to open [* \001")
caES("No es pot obrir [* \001")
csCZ("")
deDE("")
esES("No es posible abrir [* \001")
fiFI("")
frFR("")
huHU("")
itIT("Impossibile aprire [* \001")
nlNL("")
plPL("")
roRO("Nu am putut deschide [* \001")
ruRU("Невозможно открыть [* \001")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("\001] for reading!")
caES("\001] per llegir!")
csCZ("")
deDE("")
esES("\001] para lectura!")
fiFI("")
frFR("")
huHU("")
itIT("\001] in lettura!")
nlNL("")
plPL("")
roRO("\001] pentru citire!")
ruRU("\001] для чтения!")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("\001] for writing!")
caES("\001] per escriure!")
csCZ("")
deDE("")
esES("\001] para escritura!")
fiFI("")
frFR("")
huHU("")
itIT("\001] in scrittura!")
nlNL("")
plPL("")
roRO("\001] pentru scriere!")
ruRU("\001] для записи!")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")


// Windows.cpp

T_("Activate window")
caES("Activar finestra")
csCZ("Aktivovat okno")
deDE("Fenster aktivieren")
esES("Activar ventana")
fiFI("Aktivoi ikkuna")
frFR("Activer la fenêtre")
huHU("Ablak aktiválása")
itIT("Attiva finestra")
nlNL("Activeer raam")
plPL("Aktywuj okno")
roRO("Activează fereastră")
ruRU("Активное окно")
skSK("Aktivovať okno")
srSP("Aktviraj prozor")
trTR("Pencereyi etkinleştir")
zhCN("激活窗口")
zhTW("啟動視窗")

T_("Activate this window")
caES("Activar aquesta finestra")
csCZ("Aktivovat toto okno")
deDE("Dieses Fenster aktivieren")
esES("Activar esta ventana")
fiFI("Aktivoi tämä ikkuna")
frFR("Activer cette fenêtre")
huHU("Ez az ablak aktív")
itIT("Attiva questa finestra")
nlNL("Activeer deze raam")
plPL("Aktywuj to okno")
roRO("Activează această fereastră")
ruRU("Сделать активным это окно")
skSK("Aktivovať toto okno")
srSP("Aktiviraj ovaj prozor")
trTR("Bu pencereyi etkinleştir")
zhCN("激活当前窗口")
zhTW("啟動目前視窗")

T_("More windows..")
caES("Més finestres..")
csCZ("Další okna..")
deDE("Weitere Fenster ...")
esES("Más ventanas..")
fiFI("Lisää ikkunoita...")
frFR("Plus de fenêtres..")
huHU("Több ablak..")
itIT("Altre finestre..")
nlNL("Meer ramen..")
plPL("Więcej okien..")
roRO("Mai multe ferestre..")
ruRU("Ещё окна...")
skSK("Ďalšie okná..")
srSP("Još prozora..")
trTR("Daha fazla pencere...")
zhCN("更多窗口")
zhTW("更多視窗")


// Win32.cpp

T_("Open..")
caES("Obrir..")
csCZ("Otevřít..")
deDE("Öffnen ...")
esES("Abrir..")
fiFI("Avaa...")
frFR("Ouvrir..")
huHU("Megnyitás..")
itIT("Apri..")
nlNL("Openen..")
plPL("Otwórz..")
roRO("Deschide..")
ruRU("Открыть...")
skSK("Otvoriť..")
srSP("Otvori..")
trTR("Aç...")
zhCN("打开..")
zhTW("開啟..")


// CtrlUtil.cpp

T_("Invalid data.")
caES("Dades no vàlids.")
csCZ("Chybný údaj.")
deDE("Ungültige Daten")
esES("Dato incorrecto.")
fiFI("Virheellinen data.")
frFR("Donnée invalide.")
huHU("Érvénytelen adat")
itIT("Dato non valido.")
nlNL("Ongeldige data.")
plPL("Niepoprawna data.")
roRO("Date invalide.")
ruRU("Неверные данные.")
skSK("Nesprávny údaj.")
srSP("Nevalidni podaci.")
trTR("Geçersiz veri.")
zhCN("无效数据")
zhTW("無效數據")


// Update.cpp

T_("Updating ")
caES("Actualitzant ")
csCZ("Aktualizuji ")
deDE("Updaten von ")
esES("Actualizando ")
fiFI("Päivittää ")
frFR("Mise à jour de ")
huHU("Frissítés ")
itIT("Aggiornamento ")
nlNL("Updaten ")
plPL("Aktualizacja ")
roRO("Se actualizează ")
ruRU("Обновление ")
skSK("Aktualizujem ")
srSP("Ažuriram ")
trTR("Güncelliyor")
zhCN("更新中 ")
zhTW("更新中 ")

T_("Error creating file [* \001%s\001].")
caES("Error creant fitxer [*  001% s  001].")
csCZ("Nelze vytvořit soubor [* \001%s\001].")
deDE("Fehler beim Erstellen der Datei [* \001%s\001]")
esES("Error creando fichero [* \001%s\001].")
fiFI("Virhe luotaessa tiedostoa [* \001%s\001].")
frFR("Erreur en créant le fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl létrehozásánál")
itIT("Errore nella creazione del file [* \001%s\001].")
nlNL("Fout tijdens aanmaken bestand [* \001%s\001].")
plPL("Błąd tworzenia pliku [* \001%s\001].")
roRO("Eroare la crearea fişierului [* \001%s\001].")
ruRU("Ошибка создания файла [* \001%s\001].")
skSK("Nemožno vytvoriť súbor [* \001%s\001].")
srSP("Greška pri pravljenju fajla [* \001%s\001].")
trTR("Dosya oluşturma hatası: [* \001%s\001] dosyası oluşturulamadı.")
zhCN("创建文件错误 [* \001%s\001].")
zhTW("建立檔案錯誤 [* \001%s\001].")

T_("Aborting update is likely to cause trouble when running the application "
     "for the next time.\nContinue?")
caES("Avortar l'actualització podria ser la causa d'un problema en l'execució "
     "de l'aplicació la propera vegada. ¿Continuar?")
csCZ("Přerušení aktualizace může vést k velkým problémům při příštím "
     "spuštění aplikace.\nPokračovat?")
deDE("Abbruch des Updates wird wahrscheinlich beim nächsten Start der Anwendung "
     "Probleme hervorrufen.\nFortfahren?")
esES("Abortar la actualización podría ser la causa de un problema en la ejecución "
     "de la aplicación la próxima vez.\n¿Continuar?")
fiFI("Päivityksen keskeyttäminen aiheuttaa todennäköisesti ongelmia kun "
     "sovellusta seuraavan kerran käytetään.\nJatketaanko?")
frFR("Interrompre une mise à jour peut causer de sérieux problèmes lors du "
     "prochain démarrage de l'application.\nContinuer ?")
huHU("A frissítés megszakítása problémákat okozhataz alkalmazás futtatásánál.\n"
     "Folytatás?")
itIT("Interrompere l'aggiornamento può causare seri problemi al prossimo avvio.\n"
     "Continuare?")
nlNL("Update afbreken zal zeer waarschijnlijk problemen veroorzaken wanneer "
     "je hetprogramma voor de volgende keer start.\nDoorgaan?")
plPL("Przerwanie aktualizacji najprawdopodobniej spowoduje kłopoty przy ponownym "
     "uruchomieniu aplikacji.\nKontynuować?")
roRO("Anularea operţiei de actualizare poate provoca probleme la următoarea "
     "lansare a aplicaţiei\nDoriți să continuați?")
ruRU("Отмена обновления может повести за собой "
     "проблемы при запуске приложения в следующий "
     "раз.\nПродолжить?")
skSK("Prerušenie aktualizácie môže viesť k veľkým problémom pri budúcom "
     "spustení aplikáce.\nPokračovať?")
srSP("Prekid ažuriranja će verovatno prouzrokovati nevolje kada startujete "
     "aplikaciju sledeći put.\nNastaviti?")
trTR("Güncellemenin iptal edilmesi durumunda, uygulama düzgün çalışmayabilir.Bu "
     "tehlikeye rağmen devam etmek istiyor musunuz?\nEvet")
zhCN("放弃可能导致下次运行本程序出现问题.\n继续?")
zhTW("放棄可能導致下次運行本程式出現問題.\n繼續?")

T_("Overwriting %s")
caES("Sobreescrivint %s")
csCZ("Přepisuji %s")
deDE("%s wird überschrieben")
esES("Sobreescribiendo %s")
fiFI("Korvataan %s")
frFR("")
huHU("%s felülírása")
itIT("Sovrascrivere &s")
nlNL("Overschrijven %s")
plPL("")
roRO("Se suprascrie %s")
ruRU("Переписать %s")
skSK("Prepisujem %s")
srSP("")
trTR("Overwriting %s")
zhCN("%s dosyasının üzerine yazılıyor")
zhTW("%s dosyasının üzerine yazılıyor")


// Ctrl.lay

T_("Test")
caES("Verificació")
csCZ("Test")
deDE("Test")
esES("Prueba")
fiFI("Testi")
frFR("Tester")
huHU("Próba")
itIT("Test")
nlNL("Test")
plPL("Test")
roRO("Test")
ruRU("Тест")
skSK("Test")
srSP("Test")
trTR("Deneme")
zhCN("测试")
zhTW("測試")

T_("&Directory")
caES("&Directori")
csCZ("&Adresář")
deDE("&Verzeichnis")
esES("&Directorio")
fiFI("&Kansio")
frFR("&Répertoire")
huHU("&Mappa")
itIT("&Cartella")
nlNL("&Map")
plPL("&Katalog")
roRO("&Director")
ruRU("&Папка")
skSK("&Priečinok")
srSP("&Folder")
trTR("&Klasör")
zhCN("文件夹(&D)")
zhTW("資料夾(&D)")

T_("&File")
caES("&Fitxer")
csCZ("&Soubor")
deDE("&Datei")
esES("&Archivo")
fiFI("&Tiedosto")
frFR("&Fichier")
huHU("&Fájl")
itIT("&File")
nlNL("&Bestand")
plPL("&Plik")
roRO("&Fişier")
ruRU("&Файл")
skSK("&Súbor")
srSP("&Fajl")
trTR("&Dosya")
zhCN("文件(&F)")
zhTW("檔案(&F)")

T_("&Type")
caES("&Tipus")
csCZ("&Typ")
deDE("&Typ")
esES("&Tipo")
fiFI("&Tyyppi")
frFR("&Type")
huHU("&Típus")
itIT("&Tipo")
nlNL("&Type")
plPL("&Typ")
roRO("&Tip")
ruRU("&Тип")
skSK("&Typ")
srSP("&Tip")
trTR("&Tür")
zhCN("类型(&T)")
zhTW("類型(&T)")

T_("&Sort by")
caES("&Ordenar per")
csCZ("&Třídit dle")
deDE("&Sortiert nach")
esES("&Ordenar por")
fiFI("&Järjestys")
frFR("&Trier par")
huHU("&Rendezés")
itIT("&Ordina per")
nlNL("&Sorteer op")
plPL("&Sortuj w/g")
roRO("&Sortează după")
ruRU("&Cортировать по")
skSK("&Triediť podľa")
srSP("&Sortiraj po")
trTR("&Şuna göre sırala:")
zhCN("排序(&S)于")
zhTW("排序(&S)於")

T_("Name\nExtension")
caES("Nom\nExtensió")
csCZ("Jména\nPřípony")
deDE("Name\nErweiterung")
esES("Nombre\nExtensión")
fiFI("Nimi\nPääte")
frFR("Nom\nExtension")
huHU("Név\nKiterjesztés")
itIT("Nome\nEstensione")
nlNL("Naam\nExtensie")
plPL("Nazwy\nRozszerzenia")
roRO("Nume\nExtensie")
ruRU("Имя\nРасширение")
skSK("Názvy\nPrípony")
srSP("Ime\nEkstenzija")
trTR("İsim")
zhCN("名称\n扩展")
zhTW("名稱\n擴展")

T_("Read only")
caES("Només de lectura")
csCZ("Jen číst")
deDE("Schreibgeschützt")
esES("Sólo lectura")
fiFI("Vain luku")
frFR("Lecture seule")
huHU("Csak olvasható")
itIT("Sola lettura")
nlNL("Alleen lezen")
plPL("Tylko do odczytu")
roRO("Modificare nepermisă")
ruRU("Только для чтения")
skSK("Iba čítať")
srSP("Samo za čitanje")
trTR("Salt okunur")
zhCN("只读")
zhTW("唯讀")

T_("Show hidden items")
caES("Mostra elements ocults")
csCZ("")
deDE("")
esES("Mostrar elementos ocultos")
fiFI("")
frFR("")
huHU("")
itIT("Mostra elementi nascosti")
nlNL("Toon verborgen items")
plPL("")
roRO("Arată obiectele ascunse")
ruRU("Показывать скрытые")
skSK("Zobraziť skryté položky")
srSP("")
trTR("")
zhCN("显示隐藏内容")
zhTW("顯示隱藏內容")

T_("Show hidden files")
caES("Mostra fitxers ocults")
csCZ("")
deDE("")
esES("Mostrar ficheros ocultos")
fiFI("")
frFR("")
huHU("")
itIT("Mostra files nascosti")
nlNL("Toon verborgen bestanden")
plPL("")
roRO("Arată fișierele ascunse")
ruRU("Показывать скрытые файлы")
skSK("Zobraziť skryté súbory")
srSP("")
trTR("")
zhCN("显示隐藏文件")
zhTW("顯示隱藏檔")

T_("Color:")
caES("Color:")
csCZ("B&arva:")
deDE("Farbe:")
esES("Color:")
fiFI("Väri:")
frFR("Couleur :")
huHU("Szín:")
itIT("Colore")
nlNL("Kleur:")
plPL("Kolor:")
roRO("Culoare:")
ruRU("Цвет:")
skSK("F&arba:")
srSP("Boja:")
trTR("Renk:")
zhCN("颜色")
zhTW("顏色")

T_("R:")
caES("R:")
csCZ("&R:")
deDE("R:")
esES("R:")
fiFI("R:")
frFR("R :")
huHU("R:")
itIT("R:")
nlNL("R:")
plPL("R:")
roRO("R:")
ruRU("")
skSK("R:")
srSP("R:")
trTR("R:")
zhCN("R:")
zhTW("R:")

T_("G:")
caES("G:")
csCZ("&G:")
deDE("G:")
esES("G:")
fiFI("G:")
frFR("V :")
huHU("G:")
itIT("G:")
nlNL("G:")
plPL("G:")
roRO("G:")
ruRU("")
skSK("G:")
srSP("G:")
trTR("G:")
zhCN("G:")
zhTW("G:")

T_("B:")
caES("B:")
csCZ("&B:")
deDE("B:")
esES("B:")
fiFI("B:")
frFR("B :")
huHU("B:")
itIT("B:")
nlNL("B:")
plPL("B:")
roRO("B:")
ruRU("")
skSK("B:")
srSP("B:")
trTR("B:")
zhCN("B:")
zhTW("B:")

T_("H:")
caES("H:")
csCZ("&H:")
deDE("F:")
esES("H:")
fiFI("H:")
frFR("H :")
huHU("H:")
itIT("H:")
nlNL("H:")
plPL("H:")
roRO("H:")
ruRU("")
skSK("H:")
srSP("H:")
trTR("H:")
zhCN("H:")
zhTW("H:")

T_("S:")
caES("S:")
csCZ("&S:")
deDE("S:")
esES("S:")
fiFI("S:")
frFR("S :")
huHU("S:")
itIT("S:")
nlNL("S:")
plPL("S:")
roRO("S:")
ruRU("")
skSK("S:")
srSP("S:")
trTR("S:")
zhCN("S:")
zhTW("S:")

T_("V:")
caES("V:")
csCZ("&V:")
deDE("H:")
esES("V:")
fiFI("V:")
frFR("V :")
huHU("V:")
itIT("V:")
nlNL("V:")
plPL("V:")
roRO("V:")
ruRU("")
skSK("V:")
srSP("V:")
trTR("V:")
zhCN("V:")
zhTW("V:")

T_("&Rows:")
caES("&Files")
csCZ("Řa&dy:")
deDE("&Zeilen:")
esES("&Filas:")
fiFI("&Rivit:")
frFR("&Lignes :")
huHU("&Sorok:")
itIT("&Righe")
nlNL("&Rijen:")
plPL("&Wiersze:")
roRO("&Linii")
ruRU("&Ряды:")
skSK("&Riadky:")
srSP("&Redovi:")
trTR("&Satırlar:")
zhCN("行(&R)")
zhTW("列(&R)")

T_("&Columns:")
caES("&Columnes;")
csCZ("&Sloupce:")
deDE("&Spalten:")
esES("&Columnas:")
fiFI("&Sarakkeet:")
frFR("&Colonnes :")
huHU("&Oszlopok:")
itIT("&Colonne")
nlNL("&Kolommen:")
plPL("&Kolumny:")
roRO("&Coloane")
ruRU("&Колонки:")
skSK("&Stĺpce")
srSP("&Kolone:")
trTR("S&ütunlar:")
zhCN("列(&C)")
zhTW("行(&C)")

T_("Defaults")
caES("Predefinits")
csCZ("")
deDE("")
esES("Por defecto")
fiFI("")
frFR("")
huHU("")
itIT("Predefiniti")
nlNL("Standaarden")
plPL("")
roRO("Implicite")
ruRU("По умолчанию")
skSK("Predvolené")
srSP("")
trTR("")
zhCN("还原为默认值")
zhTW("預設")

T_("Printer")
caES("Impressora")
csCZ("Tiskárna")
deDE("Drucker")
esES("Impresora")
fiFI("Tulostin")
frFR("Imprimante")
huHU("Nyomtató")
itIT("Stampante")
nlNL("Drukker")
plPL("Drukarka")
roRO("Imprimantă")
ruRU("Принтер")
skSK("Tlačiareň")
srSP("")
trTR("Yazıcı")
zhCN("打印机")
zhTW("印表機")

T_("Paper size")
caES("Mida del paper")
csCZ("Velikost papíru")
deDE("Papiergröße")
esES("Tamaño del papel")
fiFI("Paperin koko")
frFR("Taille papier")
huHU("Papírméret")
itIT("Dimensioni carta")
nlNL("Papier grootte")
plPL("Rozmiar strony")
roRO("Dimensiune hărtie")
ruRU("Размер бумаги")
skSK("Veľkosť papiera")
srSP("")
trTR("Kağıt Boyutu")
zhCN("纸张大小")
zhTW("紙張大小")

T_("Input slot")
caES("Safata d'entrada")
csCZ("Vstup")
deDE("Papierzufuhr")
esES("Bandeja de entrada")
fiFI("Syöttökaukalo")
frFR("Bac d'entrée")
huHU("Input slot")
itIT("Caricatore carta")
nlNL("Invoer sleuf")
plPL("Slot wejściowy")
roRO("Slot de intrare")
ruRU("Лоток")
skSK("Vstup")
srSP("")
trTR("Yazıcı Girişi")
zhCN("输入槽")
zhTW("輸入槽")

T_("Pages per sheet")
caES("Pàgines per full")
csCZ("Stránek na list")
deDE("Seiten pro Blatt")
esES("Páginas por hoja")
fiFI("Sivuja per arkki")
frFR("Pages par feuille")
huHU("Laponkénti oldalak")
itIT("Pagine per foglio")
nlNL("Pagina's per vel")
plPL("Stron na arkusz")
roRO("Pagini per coală")
ruRU("Страниц на лист")
skSK("Stránok na list")
srSP("")
trTR("Kağıt başına düşen sayfa sayısı")
zhCN("每sheet页数")
zhTW("每sheet頁數")

T_("Print range")
caES("Àrea d'impressió")
csCZ("Rozsah tisku")
deDE("Seitenbereich")
esES("Rango de impresión")
fiFI("Tulosta sivut")
frFR("")
huHU("Nyomtatási tartomány")
itIT("Selezione di stampa")
nlNL("Drukgebied")
plPL("Zakres drukowania")
roRO("Demeniul de imprimare")
ruRU("Печатаемый интервал")
skSK("Rozsah tlače")
srSP("")
trTR("Yazdırma aralığı")
zhCN("打印范围")
zhTW("列印範圍")

T_("All pages\nCurrent page\nPages from")
caES("Totes les pàgines \nCurrent page\nPàginas des")
csCZ("Vše\nAktulí stránku\nRozsah")
deDE("Alle Seiten\nAktuelle Seite\nSeiten von")
esES("Todas las páginas\nPágina actual\nPáginas a partir de")
fiFI("Kaikki sivut\nTämä sivu\nSivut väliltä")
frFR("Toutes les pages\nPage courante\nA partir de")
huHU("Minden oldal\nAktuális oldal\nOldalak a következőtől")
itIT("Tutte le pagine\nPagina corrente\nPagine da")
nlNL("Alle pagina's\nHuidige pagina\nPagina's vanaf")
plPL("Wszystkie strony\nBieżąca strona\nStrony od")
roRO("Toate paginile\nPagina curentă\nPagini de la")
ruRU("Все страницы\nТекущая страница\nСтраницы "
     "от")
skSK("Všetko\nAktuálnu stránku\nRozsah")
srSP("")
trTR("Tüm sayfalar\nGeçerli sayfa\nSayfa aralığı")
zhCN("所有页\n当前页\n始于页")
zhTW("所有頁\n目前頁\n始於頁")

T_("to")
caES("a")
csCZ("až")
deDE("bis")
esES("hasta")
fiFI("-")
frFR("à")
huHU("-")
itIT("a")
nlNL("naar")
plPL("do")
roRO("până")
ruRU("в")
skSK("do")
srSP("")
trTR("to")
zhCN("到")
zhTW("到")

T_("Copies")
caES("Còpies")
csCZ("Kopie")
deDE("Exemplare")
esES("Copias")
fiFI("Kopiot")
frFR("Copies")
huHU("Példány")
itIT("Copie")
nlNL("Kopieën")
plPL("Kopie")
roRO("Copii")
ruRU("Копий")
skSK("Kópie")
srSP("")
trTR("Kopya sayısı")
zhCN("份数")
zhTW("份數")

T_("Collate")
caES("Reuneix")
csCZ("Seřadit")
deDE("Zusammenstellen")
esES("Cotejar")
fiFI("Lajittele")
frFR("")
huHU("Collate")
itIT("Fascicola")
nlNL("Verzamelen")
plPL("Zestaw")
roRO("Legare")
ruRU("Подобрать")
skSK("Zoradiť")
srSP("")
trTR("Harmanla")
zhCN("比较")
zhTW("比較")

T_("Portrait\nLandscape")
caES("Retrat\nApaïsat")
csCZ("Na výšku\nNa šířku")
deDE("Hochformat\nQuerformat")
esES("Horizontal\nApaisado")
fiFI("Pysty\nVaaka")
frFR("Portrait\nPaysage")
huHU("Álló\nFekvő")
itIT("Verticale\nOrizzontale")
nlNL("Portret\nLandschap")
plPL("Portret\nKrajobraz")
roRO("Portret\nPeisaj")
ruRU("Портрет\nАльбом")
skSK("Na výšku\nNa šírku")
srSP("")
trTR("Dikey\nYatay")
zhCN("纵向\n横向")
zhTW("縱向\n橫向")

T_("Placement")
caES("Emplaçament")
csCZ("Umístění")
deDE("Ausrichtung")
esES("Disposición")
fiFI("Sijoittelu")
frFR("")
huHU("Elhelyezés")
itIT("Posizionamento")
nlNL("Plaatsing")
plPL("Umiejscowienie")
roRO("Poziție")
ruRU("Размещение")
skSK("Umiestnenie")
srSP("")
trTR("Sayfa yerleşimi")
zhCN("布局")
zhTW("佈局")


// Obsolete

T_("Video")
caES("Video")
csCZ("")
deDE("")
esES("Vídeo")
fiFI("")
frFR("")
huHU("")
itIT("Video")
nlNL("")
plPL("")
roRO("")
ruRU("Видео")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Show hidden")
caES("Mostra ocults")
csCZ("Zobrazit skryté")
deDE("Aufdecken")
esES("Mostrar ocultos")
fiFI("")
frFR("Montrer cachés")
huHU("Mutassa a rejtetteket")
itIT("Mostra nascosti")
nlNL("Toon verborgen")
plPL("")
roRO("Arată ascunse")
ruRU("Показать скрытые")
skSK("Zobraziť skryté")
srSP("")
trTR("")
zhCN("显示隐藏")
zhTW("顯示隱藏檔")

T_("Default")
caES("Predeterminat")
csCZ("Základní")
deDE("Voreinstellung")
esES("Por defecto")
fiFI("Oletus")
frFR("Par défaut")
huHU("Alapértelmezett")
itIT("Predefiniti")
nlNL("Standaard")
plPL("Domyślny")
roRO("Implicit")
ruRU("По умолчанию")
skSK("Predvolené")
srSP("Podrazumevano")
trTR("Varsayılan")
zhCN("缺省")
zhTW("預設")

T_("&Cancel")
caES("&Cancelar")
csCZ("&Zrušit")
deDE("&Abbrechen")
esES("&Cancelar")
fiFI("&Peruuta")
frFR("&Annuler")
huHU("Mégsem")
itIT("&Annulla")
nlNL("&Afbreken")
plPL("&Anuluj")
roRO("&Anulează")
ruRU("&Отменить")
skSK("&Zrušiť")
srSP("&Otkaži")
trTR("&İptal")
zhCN("取消(&C)")
zhTW("取消(&C)")

T_("Week")
caES("Setmana")
csCZ("Týden")
deDE("Woche")
esES("Semana")
fiFI("Viikko")
frFR("semaine")
huHU("Hét")
itIT("Settimana")
nlNL("Week")
plPL("Tydzień")
roRO("Săptămână")
ruRU("Неделя")
skSK("Týždeň")
srSP("")
trTR("Hafta")
zhCN("星期")
zhTW("週")

T_("1 / 1")
caES("1 / 1")
csCZ("1 / 1")
deDE("1 / 1")
esES("1 / 1")
fiFI("1 / 1")
frFR("1 / 1")
huHU("1 / 1")
itIT("1 / 1")
nlNL("1 / 1")
plPL("1 / 1")
roRO("1 / 1")
ruRU("1 / 1")
skSK("1 / 1")
srSP("1 / 1")
trTR("1 / 1")
zhCN("1 / 1")
zhTW("1 / 1")

T_("Sideways")
caES("Marges")
csCZ("Na šířku")
deDE("Querformat")
esES("Márgenes")
fiFI("Sivuttain")
frFR("Direction")
huHU("Oldalsáv")
itIT("Direzione")
nlNL("Zijdelings")
plPL("Liczba stron")
roRO("Prin lateral")
ruRU("Размещение")
skSK("Na šírku")
srSP("Sa strane")
trTR("Yanlama")
zhCN("侧边")
zhTW("側邊")

T_("&1 page\n&2 pages\n&4 pages\n&8 pages")
caES("&1 pàgina\n&2 pàgines\n&4 pàgines\n&8 pàgines")
csCZ("&1 strana\n&2 strany\n&4 strany\n&8 stran")
deDE("&1 Seite\n&2 Seiten\n&4 Seiten\n&8 Seiten")
esES("&1 página\n&2 páginas\n&4 páginas\n&8 páginas")
fiFI("&1 sivu\n&2 sivua\n&4 sivua\n&8 sivua")
frFR("&1 page\n&2 pages\n&4 pages\n&8 pages")
huHU("&1 oldal\n&2 oldal\n&4 oldal\n&8 oldal")
itIT("&1 pagina\n&2 pagine\n&4 pagine\n&8 pagine")
nlNL("&1 pagina\n&2 pagina's\n&4 pagina's\n&8 pagina's")
plPL("&1 strona\n&2 strony\n&4 strony\n&8 stron")
roRO("&1 pagină\n&2 pagini\n&4 pagini\n&8 pagini")
ruRU("&1 страница\n&2 страницы\n&4 страницы\n&8 страниц")
skSK("&1 strana\n&2 strany\n&4 strany\n&8 strán")
srSP("&1 strana\n&2 strane\n&4 strane\n&8 strana")
trTR("&1 sayfa\n&2 sayfa\n&4 sayfa\n&8 sayfa")
zhCN("&1 页\n&2 页\n&4 页\n&8 页")
zhTW("&1 頁\n&2 頁\n&4 頁\n&8 頁")

T_("Page &numbers")
caES("&Números de pàgina")
csCZ("Čísla &stránek")
deDE("&Seitenzahlen")
esES("&Números de página")
fiFI("&Sivunumerot")
frFR("&Numéros de page")
huHU("&Oldalszámok")
itIT("&Numero pagine")
nlNL("Pagina &nummers")
plPL("Numery &stron")
roRO("&Numere de pagină")
ruRU("&Номера страниц")
skSK("Čísla &stránok")
srSP("&Broj strana")
trTR("Sayfa &numaraları")
zhCN("页码(&n)")
zhTW("頁碼(&n)")

T_("PDF export..")
caES("Exportar PDF ..")
csCZ("PDF export..")
deDE("PDF-Export ...")
esES("Exportar PDF..")
fiFI("PDF export...")
frFR("Export PDF..")
huHU("PDF export..")
itIT("Esporta PDF..")
nlNL("PDF exporteren..")
plPL("Eksportuj PDF..")
roRO("Exportă PDF..")
ruRU("Экспорт в PDF")
skSK("PDF export..")
srSP("PDF eksport..")
trTR("PDF dosyasını içe aktar...")
zhCN("输出PDF..")
zhTW("輸出PDF..")

T_("Report")
caES("Informe")
csCZ("Výstupní sestava")
deDE("Bericht")
esES("Informe")
fiFI("Raportti")
frFR("Rapport")
huHU("Jelentés")
itIT("Report")
nlNL("Rapport")
plPL("Raport")
roRO("Raport")
ruRU("Отчёт")
skSK("Výstupná zostava")
srSP("Izveštaj")
trTR("Bildir")
zhCN("报告")
zhTW("報告")

T_("&Print")
caES("&Imprimir")
csCZ("&Tisk")
deDE("&Drucken")
esES("&Imprimir")
fiFI("&Tulosta")
frFR("&Imprimer")
huHU("&Nyomtatás")
itIT("&Stampa")
nlNL("&Afdrukken")
plPL("&Drukuj")
roRO("&Imprimă")
ruRU("&Печать")
skSK("&Tlač")
srSP("&Štampa")
trTR("&Yazdır")
zhCN("打印(&P)")
zhTW("列印(&P)")
