#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// PushCtrl.h

T_("(default)")
csCZ("(výchozí)")
deDE("(Voreinstellung)")
esES("(por defecto)")
fiFI("(oletus)")
frFR("")
huHU("(alapértelmezett)")
itIT("(predefinito)")
plPL("(domyślny)")
roRO("(implicit)")
ruRU("")
srSP("")
trTR("(varsayılan")
zhCN("(缺省)")
zhTW("(預設)")


// EditField.cpp

T_("Undo")
csCZ("Zpět")
deDE("Rückgängig")
esES("Deshacer")
fiFI("Kumoa")
frFR("Annuler")
huHU("Visszavonás")
itIT("Annulla")
plPL("Cofnij")
roRO("Anulează ultima operație")
ruRU("Отменить")
srSP("Undo")
trTR("Geri Al")
zhCN("撤销")
zhTW("復原")

T_("Cut")
csCZ("Vyjmout")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
frFR("Couper")
huHU("Kivágás")
itIT("Taglia")
plPL("Wytnij")
roRO("Decupează")
ruRU("Вырезать")
srSP("Iseci")
trTR("Kes")
zhCN("剪切")
zhTW("剪下")

T_("Copy")
csCZ("Kopírovat")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
frFR("Copier")
huHU("Másolás")
itIT("Copia")
plPL("Kopiuj")
roRO("Copiază")
ruRU("Копировать")
srSP("Kopiraj")
trTR("Kopyala")
zhCN("复制")
zhTW("複製")

T_("Paste")
csCZ("Vložit")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
frFR("Coller")
huHU("Beillesztés")
itIT("Incolla")
plPL("Wklej")
roRO("Lipește")
ruRU("Вставить")
srSP("Zalepi")
trTR("Yapıştır")
zhCN("粘贴")
zhTW("貼上")

T_("Erase")
csCZ("Vymazat")
deDE("Löschen")
esES("Borrar")
fiFI("Pyyhi")
frFR("Effacer")
huHU("Törlés")
itIT("Cancella")
plPL("Usuń")
roRO("Şterge")
ruRU("Стереть")
srSP("Obriši")
trTR("Sil")
zhCN("清除")
zhTW("清除")

T_("Select all")
csCZ("Vybrat vše")
deDE("Alles auswählen")
esES("Seleccionar todo")
fiFI("Valitse kaikki")
frFR("Tout sélectionner")
huHU("Minden kiválasztása")
itIT("Seleziona tutto")
plPL("Zaznacz wszystko")
roRO("Alege tot")
ruRU("Выделить всё")
srSP("Izaberi sve")
trTR("Tümünü Seç")
zhCN("全选")
zhTW("全選")


// Text.cpp

T_("Redo")
csCZ("Znovu")
deDE("Wiederherstellen")
esES("Rehacer")
fiFI("Toista")
frFR("Refaire")
huHU("Újra végrehajtás")
itIT("Ripeti")
plPL("Powtórz")
roRO("Refă ultima operație")
ruRU("Повторить")
srSP("Redo")
trTR("Yinele")
zhCN("重做")
zhTW("重做")


// ArrayCtrl.cpp

T_("Do you really want to delete the selected %s ?")
csCZ("Smazat aktuální %s ?")
deDE("Möchten Sie die ausgewählte %s wirklich löschen?")
esES("¿ Realmente quieres eliminar la selección %s ?")
fiFI("Haluatko varmasti poistaa valitun %s ?")
frFR("Voulez-vous réellement supprimer le %s sélectioné ?")
huHU("Biztosan töröljük a kijelölt %s ?")
itIT("Vuoi realmente cancellare la %s selezionata ?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
roRO("Doriţi să ştergeţi %s ales/aleasă?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")
srSP("Da li stvarno želite da obrišete izabran %s?")
trTR("%s öğesini silmeyi gerçekten istiyor musunuz ?")
zhCN("真的要删除选择的 %s 吗? ")
zhTW("真的要刪除選擇的 %s 嗎? ")

T_("Insert %s")
csCZ("Vložit %s")
deDE("%s einfügen")
esES("Insertar %s")
fiFI("Lisää %s")
frFR("Insérer %s")
huHU("Beszúrás")
itIT("Inserisci %s")
plPL("Wstaw %s")
roRO("Inserează %s")
ruRU("Вставить %s")
srSP("Ubaci %s")
trTR("%s öğesini araya ekle")
zhCN("插入 %s")
zhTW("插入 %s")

T_("Insert a new %s into the table.")
csCZ("Vložit do tabulky nový %s.")
deDE("Neue %s in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla.")
fiFI("Lisää uusi %s taulukkoon.")
frFR("Insère une nouvelle %d dans la table.")
huHU("Új %s beszúrása a táblázatba")
itIT("Inserisce una nuova %s nella tabella.")
plPL("Wstawia nowy %s do tabeli.")
roRO("Înserează un nou/o nouă %s în tabel")
ruRU("Вставить новый %s в таблицу.")
srSP("Ubaci u tabelu novi %s.")
trTR("Tabloya yeni bir %s ekle.")
zhCN("插入新的 %s 到表格")
zhTW("插入新的 %s 到表格")

T_("Insert %s before")
csCZ("Vložit %s před")
deDE("%s vorher einfügen")
esES("Insertar %s antes")
fiFI("Lisää %s ennen")
frFR("Insérer %s avant")
huHU("%s beszúrása elé")
itIT("Inserisci %s sopra")
plPL("Wstaw %s przed")
roRO("Inserează %s înainte")
ruRU("Вставить %s перед")
srSP("Ubaci %s pre")
trTR("%s öğesini öne ekle")
zhCN("前插 %s")
zhTW("前插 %s")

T_("Insert a new %s into the table before current")
csCZ("Vložit nový %s před aktuální")
deDE("Neue %s vor der aktuellen in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla antes del actual")
fiFI("Lisää uusi %s taulukkoon ennen nykyistä")
frFR("Insérer une nouvelle %d dans la table avant l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
itIT("Inserisce una nuova %s prima di quella selezioanta")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
roRO("Înserează un nou/o nouă %s în tabel înainte de cel curent")
ruRU("Вставить новый %s в таблицу перед существующим")
srSP("Ubaci novi %s u tabeli pre trenutne")
trTR("Seçili olanın önüne yeni bir %s öğesi ekle")
zhCN("在表格中当前项前插入新的 %s")
zhTW("在表格中目前項前插入新的 %s")

T_("Insert %s after")
csCZ("Vložit %s za")
deDE("%s danach einfügen")
esES("Insertar %s después")
fiFI("Lisää %s jälkeen")
frFR("Insérer %s après")
huHU("% beszúrása mögé")
itIT("Inserisci %s sotto")
plPL("Wstaw %s po")
roRO("Inserează %s după")
ruRU("Вставить %s после")
srSP("Ubaci %s posle")
trTR("%s öğesini sona ekle")
zhCN("后插 %s")
zhTW("後插 %s")

T_("Insert a new %s into the table after current")
csCZ("Vložit %s za aktuální")
deDE("Neue %s hinter der aktuellen in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla después de la actual")
fiFI("Lisää uusi %s taulukkoon nykyisen jälkeen")
frFR("Insérer une nouvelle %d dans la table après l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
itIT("Inserisce una nuova %s dopo quella selezioanta")
plPL("Wstawia nowy %s do tabeli po aktualnym")
roRO("Înserează un nou/o nouă %s în tabel după de cel curent")
ruRU("Вставить новый %s в таблицу после существующего")
srSP("Ubaci novi %s u tabeli posle trenutne")
trTR("Seçili olanın ardına yeni bir %s öğesi ekle")
zhCN("在表格中当前项后插入新的 %s")
zhTW("在表格中目前項後插入新的 %s")

T_("Append %s")
csCZ("Přidat %s")
deDE("%s hinzufügen")
esES("Añadir %s")
fiFI("Lisää %s jälkeen")
frFR("Ajouter %s")
huHU("%s hozzáfűzése")
itIT("Aggiungi %s")
plPL("Dodaj %s")
roRO("Adaugă %s la capăt")
ruRU("Добавить %s")
srSP("Dodaj %s")
trTR("%s öğesini iliştir")
zhCN("添加 %s")
zhTW("添加 %s")

T_("Append a new %s at the end of the table.")
csCZ("Přidat nový %s na konec")
deDE("Neue %s am Ende der Tabelle hinzufügen")
esES("Añadir un nuevo %s en el final de la tabla.")
fiFI("Lisää uusi %s taulukon loppuun.")
frFR("Ajouter une nouvelle %s à la fin de la table.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
itIT("Aggiunge una nuova %s al fondo della tabella.")
plPL("Dodaje nowy %s na końcu tabeli.")
roRO("Adaugă un nou/o nouă %s la capătul tabelului")
ruRU("Добавить новый %s в конце таблицы.")
srSP("Dodaj novi %s na kraju tabele.")
trTR("Tablonun sonuna yeni bir %s öğesi iliştir.")
zhCN("在表格末尾插入新的 %s")
zhTW("在表格末尾插入新的 %s")

T_("Duplicate %s")
csCZ("Duplikovat %s")
deDE("%s duplizieren")
esES("Duplicar %s")
fiFI("Kahdenna %s")
frFR("Dupliquer %s")
huHU("%s megkettőzése")
itIT("Duplica %s")
plPL("Zduplikuj %s")
roRO("Crează un duplicat pentru %s")
ruRU("Дублировать %s")
srSP("Dupliraj %s")
trTR("%s öğesini kopyala")
zhCN("复制 %s")
zhTW("複製 %s")

T_("Duplicate current table %s.")
csCZ("Vložit do tabulky duplikát aktuálního %s.")
deDE("Aktuelle %s der Tabelle duplizieren")
esES("Duplicar la tabla actual %s.")
fiFI("Kahdenna tämänhetkinen taulukko %s.")
frFR("Dupliquer la table %s sélectionnée.")
huHU("Az aktuális táblázat megkettőzése")
itIT("Duplica la tabella %s selezionata.")
plPL("Utwórz duplikat aktualnej tabeli %s.")
roRO("Duplifică tabelul curent %s.")
ruRU("Дублировать текущий %s таблицы.")
srSP("Dupliraj trenutni %s tabele.")
trTR("Seçili %s tablosunu kopyala")
zhCN("复制当前表格 %s.")
zhTW("複製目前表格 %s.")

T_("Edit %s")
csCZ("Opravit aktuální %s")
deDE("%s bearbeiten")
esES("Editar %s")
fiFI("Muokkaa %s")
frFR("Editer %s")
huHU("%s szerkesztése")
itIT("Edita %s")
plPL("Edytuj %s")
roRO("Editează %s")
ruRU("Редактировать %s")
srSP("Promeni %s")
trTR("%s öğesini düzenle")
zhCN("编辑 %s")
zhTW("編輯 %s")

T_("Edit active %s.")
csCZ("Opravit aktuální %s.")
deDE("Aktive %s bearbeiten")
esES("Editar activa %s")
fiFI("Muokkaa aktiivista %s.")
frFR("Editer %s actif.")
huHU("Az aktuális %s szerkesztése")
itIT("Edita la %s attiva.")
plPL("Edytowanie aktualnego %s.")
roRO("Editează %s activ(e).")
ruRU("Редактировать активный %s.")
srSP("Promeni aktivni %s.")
trTR("Seçili %s öğesini düzenle")
zhCN("编辑活动 %s")
zhTW("編輯活動 %s")

T_("Delete %s\tDelete")
csCZ("Odstranit %s\tDelete")
deDE("%s löschen\tLöschen")
esES("Borrar %s\tBorrar")
fiFI("Poista %s\tPoista")
frFR("Supprimer %s\tSupprimer")
huHU("Törlés %s\tTörlés")
itIT("Cancella %s\tCancella")
plPL("Usuń %s\tUsuń")
roRO("Şterge %s\tŞterge")
ruRU("Удалить %s\tУдалить")
srSP("Obriši %s\tObriši")
trTR("%s öğesini sil")
zhCN("删除%s\t删除")
zhTW("刪除%s\t刪除")

T_("Delete active %s.")
csCZ("Odstranit aktuální %s.")
deDE("Aktive %s löschen")
esES("Borrar activa %s.")
fiFI("Poista aktiivinen %s.")
frFR("Supprimer %s actif.")
huHU("Az aktív %s törlése")
itIT("Cancella %s attiva.")
plPL("Usuwa aktualny %s.")
roRO("Șterge %s activ(e).")
ruRU("Удалить активный %s.")
srSP("Obriši aktivni %s.")
trTR("Etkin %s öğesini sil")
zhCN("删除活动 %s")
zhTW("刪除活動 %s")

T_("Move %s up")
csCZ("Posunout %s nahoru")
deDE("%s nach oben verschieben")
esES("Mover %s arriba")
fiFI("Siirrä %s ylöspäin")
frFR("Monter %s")
huHU("%s felfelé mozgatása")
itIT("Sposta %s su")
plPL("Przesuń %s do góry")
roRO("Mută %s sus")
ruRU("Двигать %s вверх")
srSP("Pomeri %s na gore")
trTR("%s öğesini yukarı taşı")
zhCN("上移%s")
zhTW("上移%s")

T_("Swap %s with previous thus moving it up.")
csCZ("Vyměnit aktuální %s s předchozím a tak ho posunout nahoru.")
deDE("%s mit der vorigen vertauschen und so nach oben verschieben")
esES("Intercambiar %s con el anterior y así moverlo arriba.")
fiFI("Vaihda %s yläpuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le précédent.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
itIT("Inverte la %s con la precedente.")
plPL("Zamienia %s z poprzednim przesuwając go do góry.")
roRO("Interschimbă %s cu cel precedent, mutându-l în sus.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
srSP("Zameni %s sa prethodnim, pomeri ga na gore.")
trTR(" %s öğesini yukarıya taşıyarak bir öncekiyle yerini değiştir.")
zhCN("将%s与前面换位上移之")
zhTW("將%s與前面換位上移之")

T_("Move %s down")
csCZ("Posunout %s dolů")
deDE("%s nach unten verschieben")
esES("Mover %s abajo")
fiFI("Siirrä %s alaspäin")
frFR("Descendre %s")
huHU("%s lefelé mozgatása")
itIT("Sposta %s giu")
plPL("Przesuń %s w dół")
roRO("Mută %s jos")
ruRU("Двигать %s вниз")
srSP("Pomeri %s dole")
trTR("%s öğesini aşağı taşı")
zhCN("下移%s")
zhTW("下移%s")

T_("Swap %s with next thus moving it down.")
csCZ("Vyměnit aktuální %s s dalším a tak ho posunout dolů.")
deDE("%s mit der nächsten vertauschen und so nach unten verschieben")
esES("Intercambiar %s con el siguiente y así moverlo abajo")
fiFI("Vaihda %s alapuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le suivant.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
itIT("Inverte la %s la successiva.")
plPL("Zamienia %s z następnym przesuwając go w dół.")
roRO("Interschimbă %s cu următorul, mutându-l în jos.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
srSP("Zameni %s sa sledećim, pomeri ga na dole.")
trTR("%s öğesini aşağıya taşıyarak bir sonrakiyle yerini değiştir")
zhCN("将%s与后面换位下移之")
zhTW("將%s與後面換位下移之")

T_("Select all table rows")
csCZ("Vybrat všechny řádky v tabulce")
deDE("Alle Zeilen der Tabelle auswählen")
esES("Seleccionar todas las filas de la tabla")
fiFI("Valitse kaikki taulukon rivit")
frFR("Sélectionner toutes les lignes")
huHU("Az összes sor kijelölése")
itIT("Seleziona tutte le righe")
plPL("Zaznacz wszystkie wiersze tabeli")
roRO("Selecteză toate liniile tabelului")
ruRU("Выделить все ряды таблицы")
srSP("Izaberi sve redove tabele")
trTR("Tüm satırları seç")
zhCN("全选表格行")
zhTW("全選表格列")

T_("row")
csCZ("řádek")
deDE("Zeile")
esES("fila")
fiFI("rivi")
frFR("ligne")
huHU("sor")
itIT("riga")
plPL("wiersz")
roRO("linie")
ruRU("ряды")
srSP("red")
trTR("satır")
zhCN("行")
zhTW("列")


// Progress.cpp

T_("Working...")
csCZ("Pracuji...")
deDE("Bearbeitung läuft ...")
esES("Trabajando...")
fiFI("Työskentelee...")
frFR("En cours d'exécution...")
huHU("Folyamatban...")
itIT("Esecuzione...")
plPL("Pracuję...")
roRO("Se lucrează...")
ruRU("Обработка...")
srSP("Radim...")
trTR("işlem yapılıyor...")
zhCN("工作中...")
zhTW("工作中...")


// AKeys.cpp

T_("Configure keyboard shortcuts")
csCZ("Nastavit klávesy")
deDE("Tasten zuweisen")
esES("Teclas de configuración")
fiFI("Aseta pikanäppäimet")
frFR("Configurer les raccourcis")
huHU("Billentyűk beállítása")
itIT("Selezione tasti veloci")
plPL("Ustawienia klawiszy")
roRO("Configurează scurtăturile de tastatură")
ruRU("Настроить горячие клавиши")
srSP("Podesi tastere")
trTR("Tuş Ayarları")
zhCN("设置键值")
zhTW("設定鍵值")

T_("Group")
csCZ("Skupina")
deDE("Gruppe")
esES("Grupo")
fiFI("Ryhmä")
frFR("Groupe")
huHU("Csoport")
itIT("Gruppo")
plPL("Grupa")
roRO("Grup")
ruRU("Группа")
srSP("Grupa")
trTR("Grup")
zhCN("组")
zhTW("群組")

T_("Action")
csCZ("Akce")
deDE("Aktion")
esES("Actión")
fiFI("Toiminto")
frFR("Action")
huHU("Művelet")
itIT("Azione")
plPL("Akcja")
roRO("Acţiune")
ruRU("Действие")
srSP("Akcija")
trTR("Eylem")
zhCN("动作")
zhTW("動作")

T_("Primary")
csCZ("Primární")
deDE("Taste 1")
esES("Tecla 1")
fiFI("Näppäin 1")
frFR("Touche 1")
huHU("1. billentyű")
itIT("Combinazione 1")
plPL("Klawisz 1")
roRO("Primar")
ruRU("Первично")
srSP("Taster 1")
trTR("1. Tuş")
zhCN("键1")
zhTW("鍵1")

T_("Secondary")
csCZ("Sekundární")
deDE("Taste 2")
esES("Tecla 2")
fiFI("Näppäin 2")
frFR("Touche 2")
huHU("2. billentyű")
itIT("Combinazione 2")
plPL("Klawisz 2")
roRO("Secundar")
ruRU("Вторично")
srSP("Taster 2")
trTR("2. Tuş")
zhCN("键2")
zhTW("鍵2")


// Prompt.cpp

T_("OK")
csCZ("OK")
deDE("OK")
esES("Aceptar")
fiFI("OK")
frFR("Ok")
huHU("Rendben")
itIT("Ok")
plPL("OK")
roRO("OK")
ruRU("OK")
srSP("OK")
trTR("Tamam")
zhCN("确定")
zhTW("確定")

T_("Cancel")
csCZ("Storno")
deDE("Abbrechen")
esES("Cancelar")
fiFI("Peruuta")
frFR("Annuler")
huHU("Mégsem")
itIT("Annulla")
plPL("Anuluj")
roRO("Anulează")
ruRU("Отмена")
srSP("Otkaži")
trTR("İptal")
zhCN("取消")
zhTW("取消")

T_("&Yes")
csCZ("&Ano")
deDE("&Ja")
esES("&Sí")
fiFI("&Kyllä")
frFR("&Oui")
huHU("&Igen")
itIT("&Si")
plPL("&Tak")
roRO("&Da")
ruRU("&Да")
srSP("&Da")
trTR("&Evet")
zhCN("是(&Y)")
zhTW("是(&Y)")

T_("&No")
csCZ("&Ne")
deDE("&Nein")
esES("&No")
fiFI("&Ei")
frFR("&Non")
huHU("&Nem")
itIT("&No")
plPL("&Nie")
roRO("&Nu")
ruRU("&Нет")
srSP("&Ne")
trTR("&Hayır")
zhCN("否(&N)")
zhTW("否(&N)")

T_("&Abort")
csCZ("&Přerušit")
deDE("&Abbrechen")
esES("&Abortar")
fiFI("&Keskeytä")
frFR("&Interrompre")
huHU("&Megszakítás")
itIT("&Interrompi")
plPL("&Przerwij")
roRO("&Abandonează")
ruRU("&Прервать")
srSP("&Prekini")
trTR("&İptal")
zhCN("放弃(&A)")
zhTW("放棄(&A)")

T_("&Retry")
csCZ("&Opakovat")
deDE("&Erneut versuchen")
esES("&Reintentar")
fiFI("&Yritä uudelleen")
frFR("&Réessayer")
huHU("&Újra")
itIT("&Riprova")
plPL("Po&wtórz")
roRO("&Reîncearcă")
ruRU("П&овторить")
srSP("&Ponovi")
trTR("&Tekrar Dene")
zhCN("重试(&R)")
zhTW("重試(&R)")

T_("&Ignore")
csCZ("&Ignorovat")
deDE("&Ignorieren")
esES("&Ignorar")
fiFI("&Jätä huomiotta")
frFR("")
huHU("&Ignore")
itIT("")
plPL("")
roRO("&Ignoră")
ruRU("Пропустить")
srSP("")
trTR("&Ignore")
zhCN("")
zhTW("忽略(&I)")


// Help.cpp

T_("Go Back")
csCZ("Předchozí téma")
deDE("Rückwärts")
esES("Volver atrás")
fiFI("Palaa takaisin")
frFR("Précédent")
huHU("Visszalépés")
itIT("Indiatro")
plPL("Idź wstecz")
roRO("Înapoi")
ruRU("Назад")
srSP("Nazad")
trTR(" Geri Git")
zhCN("回退")
zhTW("退回")

T_("Go Forward")
csCZ("Další téma")
deDE("Vorwärts")
esES("Ir adelante")
fiFI("Siirry eteenpäin")
frFR("Suivant")
huHU("Előrelépés")
itIT("Avanti")
plPL("Idź do przodu")
roRO("Înainte")
ruRU("Вперёд")
srSP("Napred")
trTR("İleri Git")
zhCN("向前")
zhTW("向前")

T_("Font size")
csCZ("Velikost")
deDE("Schriftgrad")
esES("Tamaño del font")
fiFI("Kirjasinkoko")
frFR("Taille de police")
huHU("Betűméret")
itIT("Dimensione font")
plPL("Rozmiar czcionki")
roRO("Dimensiunea fontului")
ruRU("Размер шрифта")
srSP("Veličina fonta")
trTR("Yazı tipi boyutu")
zhCN("字体大小")
zhTW("字體大小")

T_("Print")
csCZ("Tisk")
deDE("Drucken")
esES("Imprimir")
fiFI("Tulosta")
frFR("Imprimer")
huHU("Nyomtatás")
itIT("Stampa")
plPL("Drukuj")
roRO("Listează")
ruRU("Печать")
srSP("Štampa")
trTR("Yazdır")
zhCN("打印")
zhTW("列印")

T_("Help")
csCZ("Nápověda")
deDE("Hilfe")
esES("Ayuda")
fiFI("Apua")
frFR("Aide")
huHU("Súgó")
itIT("Aiuto")
plPL("Pomoc")
roRO("Ajutor")
ruRU("Помощь")
srSP("Pomoć")
trTR("Yardım")
zhCN("帮助")
zhTW("說明")


// DateTimeCtrl.cpp

T_("Previous month")
csCZ("Minulý měsíc")
deDE("Voriger Monat")
esES("Mes anterior")
fiFI("Edellinen kuukausi")
frFR("")
huHU("Előző hónap")
itIT("")
plPL("Poprzedni miesiąc")
roRO("Luna trecută")
ruRU("Пред. месяц")
srSP("")
trTR("Önceki ay")
zhCN("")
zhTW("前一個月")

T_("Next month")
csCZ("Další měsíc")
deDE("Nächster Monat")
esES("Mes siguiente")
fiFI("Seuraava kuukausi")
frFR("")
huHU("Következő hónap")
itIT("")
plPL("Następny miesiąc")
roRO("Luna viitoare")
ruRU("След. месяц")
srSP("")
trTR("Sonraki ay")
zhCN("")
zhTW("下一個月")

T_("Previous year")
csCZ("Minulý rok")
deDE("Voriges Jahr")
esES("Año siguiente")
fiFI("Edellinen vuosi")
frFR("")
huHU("Előző év")
itIT("")
plPL("Poprzedni rok")
roRO("Anul trecut")
ruRU("Пред. год")
srSP("")
trTR("Önceki yıl")
zhCN("")
zhTW("去年")

T_("Next year")
csCZ("Další rok")
deDE("Nächstes Jahr")
esES("Año anterior")
fiFI("Seuraava vuosi")
frFR("")
huHU("Következő év")
itIT("")
plPL("Następny rok")
roRO("Anul viitor")
ruRU("След. год")
srSP("")
trTR("Sonraki yıl")
zhCN("")
zhTW("明年")

T_("Today")
csCZ("Dnes")
deDE("Heute")
esES("Hoy")
fiFI("Tänään")
frFR("")
huHU("Ma")
itIT("")
plPL("Dziś")
roRO("Azi")
ruRU("Сегодня")
srSP("")
trTR("Bugün")
zhCN("")
zhTW("今天")

T_("Wk")
csCZ("Tý")
deDE("Wo.")
esES("Sem")
fiFI("Vko")
frFR("")
huHU("H")
itIT("")
plPL("Ty.")
roRO("Sp")
ruRU("")
srSP("")
trTR("Hft.")
zhCN("")
zhTW("")

T_("Previous hour")
csCZ("Předchozí hodina")
deDE("Vorige Stunde")
esES("Hora anterior")
fiFI("Edellinen tunti")
frFR("")
huHU("Előző óra")
itIT("")
plPL("")
roRO("Ora trecută")
ruRU("Час назад")
srSP("")
trTR("")
zhCN("")
zhTW("前一小時")

T_("Next hour")
csCZ("Další hodina")
deDE("Nächste Stunde")
esES("Hora siguiente")
fiFI("Seuraava tunti")
frFR("")
huHU("Következő óra")
itIT("")
plPL("")
roRO("Ora viitoare")
ruRU("Через час")
srSP("")
trTR("")
zhCN("")
zhTW("下一小時")

T_("Previous minute")
csCZ("Předchozí minuta")
deDE("Vorige Minute")
esES("Minuto anterior")
fiFI("Edellinen minuutti")
frFR("")
huHU("Előző perc")
itIT("")
plPL("")
roRO("Minutul trecut")
ruRU("Минуту назад")
srSP("")
trTR("")
zhCN("")
zhTW("前一分鐘")

T_("Next minute")
csCZ("Další minuta")
deDE("Nächste Minute")
esES("Minuto siguiente")
fiFI("Seuraava minuutti")
frFR("")
huHU("Következő perc")
itIT("")
plPL("")
roRO("Minutul următor")
ruRU("Через минуту")
srSP("")
trTR("")
zhCN("")
zhTW("下一分鐘")


// StatusBar.cpp

T_("Ready")
csCZ("Připraven")
deDE("Fertig")
esES("Preparado")
fiFI("Valmis")
frFR("Prêt")
huHU("Kész")
itIT("Pronto")
plPL("Gotowy")
roRO("Gata")
ruRU("Готов")
srSP("Spreman")
trTR("Hazır")
zhCN("待命")
zhTW("待命")


// TabCtrl.cpp

T_("Apply")
csCZ("Použít")
deDE("Übernehmen")
esES("Aplicar")
fiFI("Käytä")
frFR("Appliquer")
huHU("Alkalmaz")
itIT("Applica")
plPL("Zastosuj")
roRO("Aplică")
ruRU("Применить")
srSP("Primeni")
trTR("Uygula")
zhCN("应用")
zhTW("應用")

T_("Close")
csCZ("Zavřít")
deDE("Schließen")
esES("Cerra")
fiFI("Sulje")
frFR("Fermer")
huHU("Bezár")
itIT("Chiudi")
plPL("Zamknij")
roRO("Închide")
ruRU("Закрыть")
srSP("Zatvori")
trTR("Kapat")
zhCN("关闭")
zhTW("關閉")


// DlgColor.cpp

T_("(no color)")
csCZ("(bez barvy)")
deDE("(keine Farbe)")
esES("(sin color)")
fiFI("(ei väriä)")
frFR("(aucune couleur)")
huHU("(nincs szín)")
itIT("(nessun colore)")
plPL("(bez koloru)")
roRO("(fără culoare)")
ruRU("нет цвета")
srSP("(bez boje)")
trTR("(renk yok)")
zhCN("(无颜色)")
zhTW("(無顏色)")

T_("Set color")
csCZ("Nastavit barvu")
deDE("Farbe festlegen")
esES("Establecer color")
fiFI("Aseta väri")
frFR("Appliquer la couleur")
huHU("Szín beállítása")
itIT("(Set colore)")
plPL("(Ustaw kolor)")
roRO("Setează culoarea")
ruRU("Установить цвет")
srSP("Postavi boju")
trTR("Rengi ayarla")
zhCN("设置颜色")
zhTW("設定顏色")

T_("Write current color to selected palette slot")
csCZ("Nastavit barvu pole v paletě na aktuální kreslicí barvu")
deDE("Palettenplatz mit aktueller Farbe belegen")
esES("Guardar el color actual al slot seleccionado en la paleta")
fiFI("Aseta tämänhetkinen väri valittuun paletin soluun")
frFR("Ecrire la couleur courante dans l'emplacement sélectionné de la palette")
huHU("Aktuális szín beírása a kijelölt palettamezőbe")
itIT("Salva il colore corrente nello slot selezionato della tavolozza")
plPL("Zapisz aktualny kolor do wskazanego miejsca w palecie kolorów")
roRO("Scrie culoarea curentă în locaţia din paletă selectată")
ruRU("Записать текущий цвет в выделенный слот "
     "палитры")
srSP("Zapiši trenutnu boju u izabranu paletu boja")
trTR("Seçilen palet slotunu geçerli renkle değiştir")
zhCN("写当前颜色到选择的调色板槽")
zhTW("寫目前顏色到選擇的調色盤槽")

T_("Default palette")
csCZ("Standardní paleta")
deDE("Vorgabepalette")
esES("Paleta por defecto")
fiFI("Oletuspaletti")
frFR("Palette par défaut")
huHU("Alapértelmezett paletta")
itIT("Tavolozza di default")
plPL("Domyślna paleta kolorów")
roRO("Paletă implicită")
ruRU("Палитра по умолчанию")
srSP("Podrazumevana paleta")
trTR("Varsayılan renk paleti")
zhCN("缺省调色板")
zhTW("預設調色盤")

T_("Restore default system palette")
csCZ("Nastavit standardní systémovou paletu")
deDE("Voreingestellte Systempalette wiederherstellen")
esES("Restaurar la paleta por defecto del sistema")
fiFI("Palauta järjestelmän oletuspaletti")
frFR("Restaurer la palette système par défaut")
huHU("Alapértelmezett rendszer paletta visszaállítása")
itIT("Ripristina la tavolozza di default")
plPL("Przywróc standardową systemową paletę kolorów")
roRO("Restaurează paleta implictă a sistemului")
ruRU("Восстановить системную палитру по умолчанию")
srSP("Vrati standardnu paletu sistema")
trTR("Varsayılan sistem renk paletini geri yükle")
zhCN("恢复到缺省系统调色板")
zhTW("恢復到預設系統調色盤")

T_("Save as..")
csCZ("Uložit jako...")
deDE("Speichern unter ...")
esES("Guardar como..")
fiFI("Tallenna nimellä...")
frFR("Enregistrer sous..")
huHU("Mentés másként..")
itIT("Salva come..")
plPL("Zapisz jako...")
roRO("Salvează ca..")
ruRU("Сохранить как...")
srSP("Sačuvaj kao..")
trTR("Farklı kaydet...")
zhCN("保存为")
zhTW("儲存為")

T_("Store palette information into a disk file")
csCZ("Uložit paletu do souboru")
deDE("Paletteninformationen in einer Datei speichern")
esES("Guardar en disco la información de la paleta")
fiFI("Tallenna paletti tiedostoon")
frFR("Enregistrer la palette dans un fichier ")
huHU("Palettainformáció tárolása fájlba")
itIT("salva la tavolozza in un file su disco")
plPL("Zapisz informacje o palecie kolorów do pliku")
roRO("Salvează informaţia despre paletă pe disc")
ruRU("Сохранить информацию о палитре в файл "
     "на диск")
srSP("Sačuvaj paletu u fajl na disku")
trTR("Renk paleti bilgisini dosyada sakla")
zhCN("保存调色板信息到磁盘文件")
zhTW("儲存調色盤資訊到磁片檔案")

T_("Load")
csCZ("Načíst...")
deDE("Laden")
esES("Cargar")
fiFI("Lataa")
frFR("Charger")
huHU("Betöltés")
itIT("Carica")
plPL("Ładuj")
roRO("Încarcă")
ruRU("Загрузить")
srSP("Učitaj")
trTR("Yükle")
zhCN("装载")
zhTW("載入")

T_("Load previously saved palette")
csCZ("Načíst paletu z dříve uloženého souboru")
deDE("Zuvor gespeicherte Palette laden")
esES("Cargar la paleta guardada previamente")
fiFI("Lataa aiemmin tallennettu paletti")
frFR("Charger une palette précédemment sauvée")
huHU("Az előző tárolt paletta betöltése")
itIT("Carica la tavolozza precedentemente salvata")
plPL("Ładuj ostatnio zapisaną paletę kolorów")
roRO("Încarcă o paletă salvată")
ruRU("Загрузить сохранённую палитру")
srSP("Učitaj prethodno sačuvanu paletu")
trTR("Daha önce kaydedilmiş olan renk paletini yükle")
zhCN("载入以前保存的调色板")
zhTW("載入以前儲存的調色盤")

T_("Small")
csCZ("Malá")
deDE("Klein")
esES("Pequeño")
fiFI("Pieni")
frFR("Petit")
huHU("Kicsi")
itIT("Piccolo")
plPL("Mały")
roRO("Mic")
ruRU("Маленький")
srSP("Mali")
trTR("Küçük")
zhCN("小")
zhTW("小")

T_("Set up palette size 4 times 4 colors")
csCZ("Nastavit rozměry palety 4 x 4 polí")
deDE("Palette in der Größe von 4 mal 4 Farben erstellen")
esES("Establezca el tamaño de la paleta 4 veces 4 colores")
fiFI("Aseta paletin kooksi 4x4 väriä")
frFR("Modifier la taille de la palette à 4x4")
huHU("Palettaméret 4x4 színre állítása")
itIT("Imposta la tavolozza a 4 colori alla volta")
plPL("Ustaw rozmiar palety 4 na 4 kolory")
roRO("Setează dimensiunea paletei la 4 ori 4 culori")
ruRU("Установить размер палитры 16 цветов")
srSP("Podesi veličinu palete na 4x4 boje")
trTR("16 renkli palet oluştur")
zhCN("设置调色板大小为4倍4颜色")
zhTW("設定調色盤大小為4倍4顏色")

T_("Medium")
csCZ("Střední")
deDE("Mittel")
esES("Medio")
fiFI("Keskikokoinen")
frFR("Moyen")
huHU("Közepes")
itIT("Medio")
plPL("Średni")
roRO("Mediu")
ruRU("Средний")
srSP("Srednji")
trTR("Orta")
zhCN("中")
zhTW("中")

T_("Set up palette size 8 times 8 colors")
csCZ("Nastavit rozměry palety 8 x 8 polí")
deDE("Palette in der Größe von 8 mal 8 Farben erstellen")
esES("Establezca el tamaño de la la paleta 8 veces 8 colores")
fiFI("Aseta paletin kooksi 8x8 väriä")
frFR("Modifier la taille de la palette à 8x8")
huHU("Palettaméret 8x8 színre állítása")
itIT("Imposta la tavolozza a 8 colori alla volta")
plPL("Ustaw rozmiar palety 8 na 8 kolorów")
roRO("Setează dimensiunea paletei la 8 ori 8 culori")
ruRU("Установить размер палитры 64 цветов")
srSP("Podesi veličinu palete na 8x8 boja")
trTR("64 renkli palet oluştur")
zhCN("设置调色板大小为8倍8颜色")
zhTW("設定調色盤大小為8倍8顏色")

T_("Large")
csCZ("Velká")
deDE("Groß")
esES("Grande")
fiFI("Suuri")
frFR("Large")
huHU("Nagy")
itIT("Largo")
plPL("Duży")
roRO("Mare")
ruRU("Большой")
srSP("Velika")
trTR("Büyük")
zhCN("大")
zhTW("大")

T_("Set up palette size 16 times 16 colors (maximum size)")
csCZ("Nastavit rozměry palety 16 x 16 polí (max. velikost)")
deDE("Palette in der Größe von 16 mal 16 Farben erstellen (Maximalgröße)")
esES("Establezca el tamaño de la paleta 16 veces 16 colores (tamaño máximo)")
fiFI("Aseta paletin kooksi 16x16 väriä (maksimikoko)")
frFR("Modifier la taille de la palette à 16x16")
huHU("Palettaméret 16x16 színre állítása")
itIT("Imposta la tavolozza a 16 colori alla volta (dimensione massima)")
plPL("Ustaw rozmiar palety 16 na 16 kolorów")
roRO("Setează dimensiunea paletei la 16 ori 16 culori (dimensiunea maximă)")
ruRU("Установить размер палитры 256 цветов (максимальный "
     "размер)")
srSP("Podesi veličinu palete na 16x16 boja (maksimalna veličina)")
trTR("256 renkli palet oluştur")
zhCN("设置调色板大小为16倍16颜色(最大)")
zhTW("設定調色盤大小為16倍16顏色(最大)")

T_("Custom...")
csCZ("Vlastní...")
deDE("Eigen ...")
esES("Personalizar...")
fiFI("Mukautettu...")
frFR("Personnalisé...")
huHU("Választott...")
itIT("Personalizzato...")
plPL("Własny...")
roRO("Definit de utilizator...")
ruRU("Пользовательская...")
srSP("Proizvoljno...")
trTR("Özel...")
zhCN("定制...")
zhTW("自訂...")

T_("Select custom palette size")
csCZ("Zvolit vlastní počet polí v paletě")
deDE("Eigene Palettengröße auswählen")
esES("Seleccione el tamaño personal de la paleta")
fiFI("Valitse mukautettu paletin koko")
frFR("Sélectionner une taille personnalisée de palette")
huHU("Választott palettaméret beállítása")
itIT("Seleziona tavolozza di dimensione personalizzata")
plPL("Ustaw własny rozmiar palety kolorów")
roRO("Alege dimensiunea paletei")
ruRU("Выберите размер пользовательской палитры")
srSP("Izaberi proizvoljnu veličinu palete")
trTR("Özel palet boyutunu seç")
zhCN("选择定制调色板大小")
zhTW("選擇自訂調色盤大小")

T_("Palette (*.pal)")
csCZ("Paleta (*.pal)")
deDE("Palette (*.pal)")
esES("Paleta (*.pal)")
fiFI("Paletti (*.pal)")
frFR("Palette (*.pal)")
huHU("Paletta (*.pal)")
itIT("Tavolozza (*.pal)")
plPL("Paleta (*.pal)")
roRO("Paletă (*.pal)")
ruRU("Палитра (*.pal)")
srSP("Paleta (*.pal)")
trTR("Palet (*.pal)")
zhCN("调色板(*.pal)")
zhTW("調色盤(*.pal)")

T_("*.pal")
csCZ("*.pal")
deDE("*.pal")
esES("*.pal")
fiFI("*.pal")
frFR("*.pal")
huHU("*.pal")
itIT("*.pal")
plPL("*.pal")
roRO("*.pal")
ruRU("")
srSP("*.pal")
trTR("*.pal")
zhCN("*.pal")
zhTW("*.pal")

T_("pal")
csCZ("pal")
deDE("pal")
esES("pal")
fiFI("pal")
frFR("pal")
huHU("pal")
itIT("pal")
plPL("pal")
roRO("pal")
ruRU("")
srSP("pal")
trTR("pal")
zhCN("pal")
zhTW("pal")

T_("Save palette as..")
csCZ("Uložit paletu jako...")
deDE("Palette speichern unter ...")
esES("Guardar paleta como..")
fiFI("Tallenna paletti nimellä...")
frFR("Sauver la palette sous..")
huHU("Paletta mentése más néven..")
itIT("Salva tavolozza come..")
plPL("Zapisz paletę kolorów jako...")
roRO("Salvează paleta ca..")
ruRU("Сохранить палитру как...")
srSP("Sačuvajte paletu kao...")
trTR("Paleti farklı kaydet...")
zhCN("保存调色板为..")
zhTW("儲存調色盤為..")

T_("Error writing file [* \001%s\001].")
csCZ("Chyba při zápisu do souboru [* \001%s\001].")
deDE("Fehler beim Schreiben der Datei [* \001%s\001]")
esES("Error escribiendo archivo [* \001%s\001].")
fiFI("Virhe tallennettaessa tiedostoa  [* \001%s\001].")
frFR("Erreur d'écriture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl írásakor")
itIT("Errore di scrittura file [* \001%s\001].")
plPL("Błąd zapisu pliku [* \001%s\001].")
roRO("Eroare la salvarea fişierului [* \001%s\001].")
ruRU("Ошибка записи файла [* \001%s\001].")
srSP("Greška prilikom pisanja fajla [* \001%s\001].")
trTR("Dosya yazma hatası: veriler [* \001%s\001] dosyasına yazılamıyor.")
zhCN("写文件错误[* \001%s\001].")
zhTW("寫入檔案錯誤[* \001%s\001].")

T_("Load palette..")
csCZ("Načíst paletu...")
deDE("Palette laden ...")
esES("Cargar paleta..")
fiFI("Lataa paletti...")
frFR("Charger la palette..")
huHU("Paletta betöltése..")
itIT("Carica tavolozza..")
plPL("Ładuj paletę kolorów...")
roRO("Încarcă paleta")
ruRU("Загрузить палитру...")
srSP("Učitaj paletu..")
trTR("Renk paleti yükle...")
zhCN("装载调色板..")
zhTW("載入調色盤..")

T_("Error opening file [* \001%s\001].")
csCZ("Nelze otevřít soubor [* \001%s\001].")
deDE("Fehler beim Öffnen der Datei [* \001%s\001]")
esES("Error abriendo archivo [* \001%s\001].")
fiFI("Virhe avattaessa tiedostoa [* \001%s\001].")
frFR("Erreur d'ouverture du fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl megnyitásakor")
itIT("Errore di aprtura file [* \001%s\001].")
plPL("Błąd otwarcia pliku [* \001%s\001].")
roRO("Eroare la deschiderea fişierului [* \001%s\001].")
ruRU("Ошибка открытия файла [* \001%s\001].")
srSP("Greška prilikom otvaranja fajla [* \001%s\001].")
trTR("Dosya yazma hatası: [* \001%s\001] dosyası açılamıyor.")
zhCN("打开文件错误[* \001%s\001].")
zhTW("開啟檔案錯誤[* \001%s\001].")

T_("Error reading palette from file [* \001%s\001].")
csCZ("Chyba při načítání palety ze souboru [* \001%s\001].")
deDE("Fehler beim Lesen der Palette aus der Datei [* \001%s\001]")
esES("Error leyendo paleta desde archivo [* \001%s\001].")
fiFI("Virhe luettaessa palettia tiedostosta [* \001%s\001].")
frFR("Erreur de lecture du fichier de palette [* \001%s\001].")
huHU("Hiba a paletta beolvasásakor a [* \001%s\001] fájlból")
itIT("Errore di lettura tavolozza dal file [* \001%s\001].")
plPL("Błąd czytania palety kolorów z pliku [* \001%s\001].")
roRO("Eroare la citirea paletei din fişierul [* \001%s\001].")
ruRU("Ошибка чтения палитры из файла [* \001%s\001].")
srSP("Greška prilikom čitanja fajla [* \001%s\001].")
trTR("Dosya okuma hatası: palet [* \001%s\001] dosyasından okunamıyor.")
zhCN("从文件[* \001%s\001]. 读调色板错")
zhTW("從檔案[* \001%s\001]. 讀取調色盤錯誤")

T_("Palette dimensions")
csCZ("Rozměry palety")
deDE("Palettenmaße")
esES("Tamaño de la paleta")
fiFI("Paletin dimensiot")
frFR("Dimensions de la palette")
huHU("Paletta dimenziói")
itIT("Dimensioni tavolozza")
plPL("Rozmiary palety kolorów")
roRO("Dimensiunile paletei")
ruRU("Размер палитры")
srSP("Dimenzije palete")
trTR("Palet boyutları")
zhCN("调色板维度")
zhTW("調色盤維度")

T_("(transparent)")
csCZ("(průhledná)")
deDE("(transparent)")
esES("(transparente)")
fiFI("(läpinäkyvä)")
frFR("transparent")
huHU("(átlátszó)")
itIT("(trasparente)")
plPL("(przezroczysty)")
roRO("(transparent)")
ruRU("(прозрачный)")
srSP("(transparenta)")
trTR("(saydam)")
zhCN("(透明)")
zhTW("(透明)")

T_("Palette")
csCZ("Paleta")
deDE("Palette")
esES("Paleta")
fiFI("Paletti")
frFR("Palette")
huHU("Paletta")
itIT("Tavolozza")
plPL("Paleta")
roRO("Paletă")
ruRU("Палитра")
srSP("Paleta")
trTR("Palet")
zhCN("调色板")
zhTW("調色盤")

T_("Wheel")
csCZ("Kolo")
deDE("Farbkreis")
esES("Rueda")
fiFI("Pyörä")
frFR("Molette")
huHU("Korong")
itIT("Ruota")
plPL("Koło")
roRO("Roată")
ruRU("Колесо")
srSP("Točak")
trTR("Teker")
zhCN("滚轮")
zhTW("滾輪")

T_("Hue")
csCZ("Odstín")
deDE("Farbton")
esES("Hue")
fiFI("Sävy (Hue)")
frFR("Tinte")
huHU("Színezet")
itIT("Tinta")
plPL("Odcień")
roRO("Hue")
ruRU("Оттенок")
srSP("Obojenost")
trTR("Renk (Hue)")
zhCN("色调")
zhTW("色調")

T_("RGB")
csCZ("RGB")
deDE("RGB")
esES("RGB")
fiFI("RGB")
frFR("RVB")
huHU("RGB")
itIT("RGB")
plPL("RGB")
roRO("RGB")
ruRU("")
srSP("RGB")
trTR("RGB")
zhCN("RGB")
zhTW("RGB")

T_("HSV")
csCZ("HSV")
deDE("FSH")
esES("HSV")
fiFI("HSV")
frFR("HSV")
huHU("HSB")
itIT("HSV")
plPL("HSV")
roRO("HSV")
ruRU("")
srSP("HSV")
trTR("HSV")
zhCN("HSV")
zhTW("HSV")

T_("Select color")
csCZ("Výběr barvy")
deDE("Farbe auswählen")
esES("Selección de color")
fiFI("Valitse väri")
frFR("Sélectionner la couleur")
huHU("Szín választása")
itIT("Seleziona colore")
plPL("Wybrany kolor")
roRO("Alege culoarea")
ruRU("Выбирите цвет")
srSP("Izaberi boju")
trTR("Renk Seçin")
zhCN("选择颜色")
zhTW("選擇顏色")


// FileSel.cpp

T_("[A3* Unable to read the directory !]&&")
csCZ("[A3* Nelze načíst obsah adresáře !]&&")
deDE("[A3* Verzeichnis kann nicht gelesen werden!]&&")
esES("[A3* No se puede leer el directorio !]&&")
fiFI("[A3* Kansiota ei kyetä lukemaan !]&&")
frFR("[A3* Impossible de lire le répertoire !]&&")
huHU("[A3* Nem sikerült olvasni a mappát!]&&")
itIT("[A3* Impossibile leggere la cartella !]&&")
plPL("[A3* Nie można odczytać katalogu !]&&")
roRO("[A3* Directorul nu poate fi citit !]&&")
ruRU("[A3* Не могу прочитать папку!]&&")
srSP("[A3* Ne mogu da pročitam folder!]&&")
trTR("[A3* Klasör okunamıyor !]&&")
zhCN("[A3* 不能读取目录 !]&&")
zhTW("[A3* 不能讀取目錄 !]&&")

T_(" is directory.")
csCZ(" je adresář.")
deDE(" ist ein Verzeichnis.")
esES("es directorio")
fiFI(" on kansio.")
frFR(" est un répertoire.")
huHU("mappa")
itIT(" è una cartella.")
plPL(" jest katalogiem.")
roRO(" este director")
ruRU(" папка.")
srSP(" je folder.")
trTR(" bir klasördür")
zhCN(" 为目录.")
zhTW(" 為目錄.")

T_(" already exists.&Do you want to continue ?")
csCZ(" již existuje.&Přejete si pokračovat ?")
deDE(" existiert bereits. &Möchten Sie fortfahren?")
esES("ya existe.&¿Quieres continuar?")
fiFI(" on jo olemassa.&Haluatko silti jatkaa?")
frFR(" existe déjà.&Voulez-vous continuer ?")
huHU("már létezik. &Folytatás?")
itIT(" esiste già.&Desideri proseguire ?")
plPL(" już istnieje. &Czy chcesz kontynuować ?")
roRO(" există deja.&Doriţi să continuaţi ?")
ruRU(" уже существует. &Вы хотите продолжить?")
srSP(" već postoji. &Da li želite da nastavite?")
trTR(" zaten var.&Yine de devam etmek istiyor musunuz?")
zhCN(" 已经存在.继续(&D)?")
zhTW(" 已經存在.繼續(&D)?")

T_(" does not exist.")
csCZ(" neexistuje.")
deDE(" existiert nicht.")
esES(" no existe.")
fiFI(" ei ole olemassa.")
frFR(" n'existe pas.")
huHU("nem létezik")
itIT(" non esistono.")
plPL(" nie istnieje.")
roRO(" nu există")
ruRU(" не существует.")
srSP(" ne postoji.")
trTR(" yok.")
zhCN("不存在")
zhTW("不存在")

T_("&do not exist.")
csCZ("&neexistují.")
deDE("existieren nicht")
esES("&no existe.")
fiFI("&ei ole olemassa.")
frFR("&n'existe pas")
huHU("&nem létezik")
itIT(" non esiste")
plPL(" &nie istnieje.")
roRO("&nu există")
ruRU("&не существует.")
srSP("&ne postoji.")
trTR("& yok.")
zhCN("不存在(&d)")
zhTW("不存在(&d)")

T_("&Do you want to continue ?")
csCZ("&Přejete si pokračovat ?")
deDE("&Möchten Sie fortfahren?")
esES("¿&Quieres continuar?")
fiFI("&Haluatko jatkaa?")
frFR("&Voulez-vous continuer ?")
huHU("&Folytatás?")
itIT("&Desideri proseguire ?")
plPL("&Czy chcesz kontynuować ?")
roRO("&Doriţi să continuaţi ?")
ruRU("&Вы хотите продолжить?")
srSP("&Da li želite da nastavite?")
trTR("&Devam etmek istiyor musunuz?")
zhCN("继续(&D)?")
zhTW("繼續(&D)?")

T_("Custom file type (")
csCZ("Jiný typ souboru (")
deDE("Eigener Dateityp (")
esES("Tipo de archivo personalizado(")
fiFI("Mukautettu tiedostotyyppi (")
frFR("Type de fichier personnalisé (")
huHU("Választott fájltípus (")
itIT("Tipo file personalizzato (")
plPL("Własny typ pliku (")
roRO("Tip de fișier ales de utilizator")
ruRU("Свой тип файла (")
srSP("Proizvoljni tip fajla (")
trTR("Özel dosya türü(")
zhCN("定制文件类型 (")
zhTW("自訂檔案類型 (")

T_("New directory")
csCZ("Nový adresář")
deDE("Neues Verzeichnis")
esES("Nuevo directorio")
fiFI("Uusi kansio")
frFR("Nouveau répertoire")
huHU("Új mappa")
itIT("Nuova cartella")
plPL("Nowy katalog")
roRO("Director nou")
ruRU("Новая папка")
srSP("Novi folder")
trTR("Yeni klasör")
zhCN("新建文件夹")
zhTW("建立資料夾")

T_("Name")
csCZ("Jméno")
deDE("Name")
esES("Nombre")
fiFI("Nimi")
frFR("Nom")
huHU("Név")
itIT("Nome")
plPL("Nazwa")
roRO("Nume")
ruRU("Имя")
srSP("Ime")
trTR("İsim")
zhCN("名称")
zhTW("名稱")

T_("[A3* Creating directory failed !&&]")
csCZ("[A3* Chyba při vytváření adresáře !&&]")
deDE("[A3* Verzeichnis konnte nicht erstellt werden!&&]")
esES("[A3* Falló la creación del directorio !&&]")
fiFI("[A3* Kansion luominen epäonnistui!&&]")
frFR("[A3* La création du répertoire a échoué !&&]")
huHU("[A3* A mappa létrehozása sikertelen!&&]")
itIT("[A3* Creazione cartella fallita !&&]")
plPL("[A3* Tworzenie katalogu nie powiodło się !&&]")
roRO("[A3* Crearea directorului a eşuat !&&]")
ruRU("[A3* Не удалось создать папку!&&]")
srSP("[A3* Pravljenje foldera nije uspelo!&&]")
trTR("[A3* Klasör oluşturulamadı !]&&")
zhCN("[A3* 创建文件夹失败 !&&]")
zhTW("[A3* 建立資料夾失敗 !&&]")

T_("Mask")
csCZ("Maska")
deDE("Maske")
esES("Máscara")
fiFI("Maski")
frFR("Masque")
huHU("Maszk")
itIT("Maschera")
plPL("Maska")
roRO("Mască")
ruRU("Маска")
srSP("Maska")
trTR("Maske")
zhCN("掩码")
zhTW("遮罩")

T_("Add to selection")
csCZ("Přidat k výběru")
deDE("Zur Auswahl hinzufügen")
esES("Añadir a la selección")
fiFI("Lisää valintaan")
frFR("Ajouter à la sélection")
huHU("Hozzáadás a kijelöléshez")
itIT("Aggiungi alla selezione")
plPL("Dodaj do zaznaczonych")
roRO("Adaugă la selecţie")
ruRU("Добавить к выделению")
srSP("Dodaj u izbor")
trTR("Seçilenlere ekle")
zhCN("选上")
zhTW("選上")

T_("Remove from selection")
csCZ("Odebrat od výběru")
deDE("Aus der Auswahl entfernen")
esES("Eliminar de la selección")
fiFI("Poista valinnasta")
frFR("Enlever de la sélection")
huHU("Eltávolítás a kijelölésből")
itIT("Rimuovi dalla selezione")
plPL("Usuń z zaznaczonych")
roRO("Înlătură din selecţie")
ruRU("Убрать из выделения")
srSP("Ukloni iz selekcije")
trTR("Seçilenlerden çıkar")
zhCN("去选")
zhTW("去選")

T_("  Drive")
csCZ("  Disková jednotka")
deDE("  Laufwerk")
esES("  Disco")
fiFI("  Levyasema")
frFR("  Disque")
huHU("  Meghajtó")
itIT("  Disco")
plPL("  Napęd")
roRO("  Unitate")
ruRU("  Диск")
srSP("  Disk")
trTR("  Sürücü")
zhCN("  驱动")
zhTW("  驅動")

T_("Directory  ")
csCZ("Adresář  ")
deDE("Verzeichnis  ")
esES("Directorio")
fiFI("Kansio  ")
frFR("Répertoire")
huHU("Mappa")
itIT("Cartella ")
plPL("Katalog  ")
roRO("Director  ")
ruRU("Папка  ")
srSP("Folder ")
trTR(" Klasör ")
zhCN("文件夹  ")
zhTW("資料夾  ")

T_(" drive(s)")
csCZ(" disk(y)")
deDE("Laufwerk(e)")
esES(" unidad(es)")
fiFI("")
frFR("")
huHU(" meghajtó(k)")
itIT("")
plPL("")
roRO(" unitate(unitati)")
ruRU("диск(и)")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_(" folder(s)")
csCZ(" adresář(e)")
deDE("Ordner")
esES(" carpeta(s)")
fiFI("")
frFR("")
huHU(" mappá(k)")
itIT("")
plPL("")
roRO(" director(directoare)")
ruRU("папка(и)")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_(" file(s)")
csCZ(" soubor(y)")
deDE("Datei(en)")
esES(" archivo(s)")
fiFI("")
frFR("")
huHU(" fájl(ok)")
itIT("")
plPL("")
roRO(" fişier(e)")
ruRU("файл(ы)")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Open")
csCZ("Otevřít")
deDE("Öffnen")
esES("Abrir")
fiFI("Avaa")
frFR("Ouvrir")
huHU("Megnyitás")
itIT("Apri")
plPL("Otwórz")
roRO("Deschide")
ruRU("Открыть")
srSP("Otvori")
trTR("Aç")
zhCN("打开")
zhTW("開啟")

T_("Save")
csCZ("Uložit")
deDE("Speichern")
esES("Guardar")
fiFI("Tallenna")
frFR("Sauver")
huHU("Mentés")
itIT("Salva")
plPL("Zapisz")
roRO("Salvează")
ruRU("Сохранить")
srSP("Sačuvaj")
trTR("Kaydet")
zhCN("保存")
zhTW("儲存")

T_("[A3* Renaming of file failed !&&]")
csCZ("[A3* Chyba při přejmenovávání souboru !&&]")
deDE("[A3* Datei konnte nicht umbenannt werden!&&]")
esES("[A3* Error al renombrar el archivo !&&]")
fiFI("[A3* Tiedoston uudelleennimeäminen epäonnistui!&&]")
frFR("[A3* Le renommage du fichier a échoué !&&]")
huHU("[A3* A fájl átnevezése sikertelen!&&]")
itIT("[A3* Rinomina fallito !&&]")
plPL("[A3* Zmiana nazwy pliku nie powiodła się !&&]")
roRO("[A3* Redenumirea fişierului a eşuat !&&]")
ruRU("[A3* Не удалось переименовать файл!&&]")
srSP("[A3* Promena imena fajla nije uspela!&&]")
trTR("[A3* Dosya yeniden adlandırılamadı !]&&")
zhCN("[A3* 文件重命名失败 !&&]")
zhTW("[A3* 檔案重新命名失敗 !&&]")

T_("All files")
csCZ("Všechny soubory")
deDE("Alle Dateien")
esES("Todos los archivos")
fiFI("Kaikki tiedostot")
frFR("Tous les fichiers")
huHU("Az összes fájl")
itIT("Titti i files")
plPL("Wszystkie pliki")
roRO("Toate fişierele")
ruRU("Все файлы")
srSP("Svi fajlovi")
trTR("Tüm dosyalar")
zhCN("所有文件")
zhTW("所有檔案")

T_("&Select")
csCZ("&Vybrat")
deDE("&Auswählen")
esES("&Seleccionar")
fiFI("&Valitse")
frFR("&Sélectionner")
huHU("&Kijelölés")
itIT("Seleziona")
plPL("&Wybierz")
roRO("&Selectează")
ruRU("&Выбрать")
srSP("&Izaberi")
trTR("&Seç")
zhCN("选择(&S)")
zhTW("選擇(&S)")

T_("Save as")
csCZ("Uložit jako")
deDE("Speichern unter")
esES("Guardar como")
fiFI("Tallenna nimellä")
frFR("Sauver sous")
huHU("Mentés más néven")
itIT("Salva come")
plPL("Zapisz jako")
roRO("Salvează ca")
ruRU("Сохранить как")
srSP("Sačuvaj kao")
trTR("Farklı kaydet")
zhCN("另存为")
zhTW("另存為")

T_("Select directory")
csCZ("Vybrat adresář")
deDE("Verzeichnis auswählen")
esES("Seleccionar directorio")
fiFI("Valitse kansio")
frFR("Sélectionner un répertoire")
huHU("Mappa kijelölése")
itIT("Seleziona cartella")
plPL("Wybierz katalog")
roRO("Alege directorul")
ruRU("Выберите папку")
srSP("Izaberi folder")
trTR("Klasör seç")
zhCN("选择文件夹")
zhTW("選擇資料夾")

T_("Dir up")
csCZ("Nadřazený adresář")
deDE("Übergeordnetes Vwerzeichnis")
esES("Directorio superior")
fiFI("Ylemmän tason kansio")
frFR("Répertoire parent")
huHU("Szülőmappa")
itIT("Cartella su")
plPL("Katalog w górę")
roRO("Directorul părinte")
ruRU("Папка вверх")
srSP("Folder iznad")
trTR("Üst klasöre çık")
zhCN("向上")
zhTW("向上")

T_("Create directory")
csCZ("Vytvořit adresář")
deDE("Verzeichnis erstellen")
esES("Crear directorio")
fiFI("Luo kansio")
frFR("Créer un répertoire")
huHU("Mappa létrehozása")
itIT("Crea nuova cartella")
plPL("Utwórz katalog")
roRO("Crează director")
ruRU("Создать папку")
srSP("Napravi folder")
trTR("Klasör oluştur")
zhCN("创建文件夹")
zhTW("建立資料夾")

T_("Select files")
csCZ("Označit soubory")
deDE("Dateien auswählen")
esES("Seleccionar archivos")
fiFI("Valitse tiedostot")
frFR("Sélectionner les fichiers")
huHU("Fájlok kijelölése")
itIT("Seleziona i files")
plPL("Wybierz pliki")
roRO("Selectează fişierele")
ruRU("Выделить файлы")
srSP("Izaberite fajlove")
trTR("Dosyaları seç")
zhCN("选择文件")
zhTW("選擇檔案")

T_("Unselect files")
csCZ("Odznačit soubory")
deDE("Dateien abwählen")
esES("Desmarcar archivos")
fiFI("Poista tiedostojen valinta")
frFR("Désélectionner les fichiers")
huHU("Fájlkijelölés megszüntetése")
itIT("Deseleziona i files")
plPL("Odznacz pliki")
roRO("Deselectează fişierele")
ruRU("Убрать выделение файлов")
srSP("Deselektujte fajlove")
trTR("Seçili dosyaları iptal et")
zhCN("取消选择文件")
zhTW("取消選擇檔案")

T_("Toggle files")
csCZ("Inverze označení")
deDE("Dateiauswahl umkehren")
esES("Intercambiar archivos")
fiFI("Käänteinen tiedostojen valinta")
frFR("Invertir la sélection")
huHU("Kijelölés felcserélése")
itIT("Inverti selezione")
plPL("Odwróć zaznaczone pliki")
roRO("Alternează fișierele")
ruRU("Поменять выделение файлов")
srSP("Invertuj izabrane")
trTR("Seçili dosyaları değiştir")
zhCN("Toggle files")
zhTW("Toggle files")


// Windows.cpp

T_("Activate window")
csCZ("Aktivovat okno")
deDE("Fenster aktivieren")
esES("Activar ventana")
fiFI("Aktivoi ikkuna")
frFR("Activer la fenêtre")
huHU("Ablak aktiválása")
itIT("Attiva finestra")
plPL("Aktywuj okno")
roRO("Activează fereastră")
ruRU("Активное окно")
srSP("Aktviraj prozor")
trTR("Pencereyi etkinleştir")
zhCN("激活窗口")
zhTW("啟動視窗")

T_("Activate this window")
csCZ("Aktivovat toto okno")
deDE("Dieses Fenster aktivieren")
esES("Activar esta ventana")
fiFI("Aktivoi tämä ikkuna")
frFR("Activer cette fenêtre")
huHU("Ez az ablak aktív")
itIT("Attiva questa finestra")
plPL("Aktywuj to okno")
roRO("Activează această fereastră")
ruRU("Сделать активным это окно")
srSP("Aktiviraj ovaj prozor")
trTR("Bu pencereyi etkinleştir")
zhCN("激活当前窗口")
zhTW("啟動目前視窗")

T_("More windows..")
csCZ("Další okna..")
deDE("Weitere Fenster ...")
esES("Más ventanas..")
fiFI("Lisää ikkunoita...")
frFR("Plus de fenêtres..")
huHU("Több ablak..")
itIT("Altre finestre")
plPL("Więcej okien..")
roRO("Mai multe ferestre..")
ruRU("Ещё окна...")
srSP("Još prozora..")
trTR("Daha fazla pencere...")
zhCN("更多窗口")
zhTW("更多視窗")


// Win32.cpp

T_("Open..")
csCZ("Otevřít..")
deDE("Öffnen ...")
esES("Abrir..")
fiFI("Avaa...")
frFR("Ouvrir..")
huHU("Megnyitás..")
itIT("Apri..")
plPL("Otwórz..")
roRO("Deschide..")
ruRU("Открыть...")
srSP("Otvori..")
trTR("Aç...")
zhCN("打开..")
zhTW("開啟..")


// CtrlUtil.cpp

T_("Invalid data.")
csCZ("Chybný údaj.")
deDE("Ungültige Daten")
esES("Dato incorrecto.")
fiFI("Virheellinen data.")
frFR("Donnée invalide.")
huHU("Érvénytelen adat")
itIT("Dato non valido.")
plPL("Niepoprawna data.")
roRO("Date invalide.")
ruRU("Неверные данные.")
srSP("Nevalidni podaci.")
trTR("Geçersiz veri.")
zhCN("无效数据")
zhTW("無效數據")


// Update.cpp

T_("Updating ")
csCZ("Aktualizuji ")
deDE("Updaten von ")
esES("Actualizando ")
fiFI("Päivittää ")
frFR("Mise à jour de ")
huHU("Frissítés ")
itIT("Aggiornamento")
plPL("Aktualizacja ")
roRO("Se actualizează ")
ruRU("Обновление ")
srSP("Ažuriram ")
trTR("Güncelliyor")
zhCN("更新中 ")
zhTW("更新中 ")

T_("Error creating file [* \001%s\001].")
csCZ("Nelze vytvořit soubor [* \001%s\001].")
deDE("Fehler beim Erstellen der Datei [* \001%s\001]")
esES("Error al crear el archivo [* \001%s\001].")
fiFI("Virhe luotaessa tiedostoa [* \001%s\001].")
frFR("Erreur en créant le fichier [* \001%s\001].")
huHU("Hiba a [* \001%s\001] fájl létrehozásánál")
itIT("Errore creazione file [* \001%s\001].")
plPL("Błąd tworzenia pliku [* \001%s\001].")
roRO("Eroare la crearea fişierului [* \001%s\001].")
ruRU("Ошибка создания файла [* \001%s\001].")
srSP("Greška pri pravljenju fajla [* \001%s\001].")
trTR("Dosya oluşturma hatası: [* \001%s\001] dosyası oluşturulamadı.")
zhCN("创建文件错误 [* \001%s\001].")
zhTW("建立檔案錯誤 [* \001%s\001].")

T_("Aborting update is likely to cause trouble when running the application "
     "for the next time.\nContinue?")
csCZ("Přerušení aktualizace může vést k velkým problémům při příštím "
     "spuštění aplikace.\nPokračovat?")
deDE("Abbruch des Updates wird wahrscheinlich beim nächsten Start der Anwendung "
     "Probleme hervorrufen.\nFortfahren?")
esES("Abortar la actualización podría ser la causa de un problema en la ejecución "
     "de la aplicación la próxima vez.¿Continuar?")
fiFI("Päivityksen keskeyttäminen aiheuttaa todennäköisesti ongelmia kun "
     "sovellusta seuraavan kerran käytetään.\nJatketaanko?")
frFR("Interrompre une mise à jour peut causer de sérieux problèmes lors du "
     "prochain démarrage de l'application.\nContinuer ?")
huHU("A frissítés megszakítása problémákat okozhataz alkalmazás futtatásánál.\n"
     "Folytatás?")
itIT("Interrompere l'aggiornamento può causare seri problemi al prossimo avvio.\n"
     "Continuare?")
plPL("Przerwanie aktualizacji najprawdopodobniej spowoduje kłopoty przy ponownym "
     "uruchomieniu aplikacji.\nKontynuować?")
roRO("Anularea operţiei de actualizare poate provoca probleme la următoarea "
     "lansare a aplicaţiei\nDoriți să continuați?")
ruRU("Отмена обновления может повести за собой "
     "проблемы при запуске приложения в следующий "
     "раз.\nПродолжить?")
srSP("Prekid ažuriranja će verovatno prouzrokovati nevolje kada startujete "
     "aplikaciju sledeći put.\nNastaviti?")
trTR("Güncellemenin iptal edilmesi durumunda, uygulama düzgün çalışmayabilir.Bu "
     "tehlikeye rağmen devam etmek istiyor musunuz?\nEvet")
zhCN("放弃可能导致下次运行本程序出现问题.\n继续?")
zhTW("放棄可能導致下次運行本程式出現問題.\n繼續?")

T_("Overwriting %s")
csCZ("Přepisuji %s")
deDE("%s wird überschrieben")
esES("Sobreescribiendo %s")
fiFI("Korvataan %s")
frFR("")
huHU("%s felülírása")
itIT("")
plPL("")
roRO("Se suprascrie %s")
ruRU("Переписать %s")
srSP("")
trTR("Overwriting %s")
zhCN("%s dosyasının üzerine yazılıyor")
zhTW("%s dosyasının üzerine yazılıyor")


// Ctrl.lay

T_("Test")
csCZ("Test")
deDE("Test")
esES("Prueba")
fiFI("Testi")
frFR("Tester")
huHU("Próba")
itIT("Test")
plPL("Test")
roRO("Test")
ruRU("Тест")
srSP("Test")
trTR("Deneme")
zhCN("测试")
zhTW("測試")

T_("&Directory")
csCZ("&Adresář")
deDE("&Verzeichnis")
esES("&Directorio")
fiFI("&Kansio")
frFR("&Répertoire")
huHU("&Mappa")
itIT("&Cartella")
plPL("&Katalog")
roRO("&Director")
ruRU("&Папка")
srSP("&Folder")
trTR("&Klasör")
zhCN("文件夹(&D)")
zhTW("資料夾(&D)")

T_("&File")
csCZ("&Soubor")
deDE("&Datei")
esES("&Archivo")
fiFI("&Tiedosto")
frFR("&Fichier")
huHU("&Fájl")
itIT("&File")
plPL("&Plik")
roRO("&Fişier")
ruRU("&Файл")
srSP("&Fajl")
trTR("&Dosya")
zhCN("文件(&F)")
zhTW("檔案(&F)")

T_("&Type")
csCZ("&Typ")
deDE("&Typ")
esES("&Tipo")
fiFI("&Tyyppi")
frFR("&Type")
huHU("&Típus")
itIT("&Tipo")
plPL("&Typ")
roRO("&Tip")
ruRU("&Тип")
srSP("&Tip")
trTR("&Tür")
zhCN("类型(&T)")
zhTW("類型(&T)")

T_("&Sort by")
csCZ("&Třídit dle")
deDE("&Sortiert nach")
esES("&Ordenar por")
fiFI("&Järjestys")
frFR("&Trier par")
huHU("&Rendezés")
itIT("&Ordina per")
plPL("&Sortuj w/g")
roRO("&Sortează după")
ruRU("&Cортировать по")
srSP("&Sortiraj po")
trTR("&Şuna göre sırala:")
zhCN("排序(&S)于")
zhTW("排序(&S)於")

T_("Name\nExtension")
csCZ("Jména\nPřípony")
deDE("Name\nErweiterung")
esES("Nombre\nExtensión")
fiFI("Nimi\nPääte")
frFR("Nom\nExtension")
huHU("Név\nKiterjesztés")
itIT("Nome\nEstensione")
plPL("Nazwy\nRozszerzenia")
roRO("Nume\nExtensie")
ruRU("Имя\nРасширение")
srSP("Ime\nEkstenzija")
trTR("İsim")
zhCN("名称\n扩展")
zhTW("名稱\n擴展")

T_("Read only")
csCZ("Jen číst")
deDE("Schreibgeschützt")
esES("Sólo lectura")
fiFI("Vain luku")
frFR("Lecture seule")
huHU("Csak olvasható")
itIT("Sola lettura")
plPL("Tylko do odczytu")
roRO("Modificare nepermisă")
ruRU("Только для чтения")
srSP("Samo za čitanje")
trTR("Salt okunur")
zhCN("只读")
zhTW("唯讀")

T_("Show hidden")
csCZ("Zobrazit skryté")
deDE("Aufdecken")
esES("Mostrar ocultos")
fiFI("")
frFR("")
huHU("Mutassa a rejtetteket")
itIT("")
plPL("")
roRO("Arată ascunse")
ruRU("Показать скрытые")
srSP("")
trTR("")
zhCN("")
zhTW("顯示隱藏檔")

T_("Color:")
csCZ("B&arva:")
deDE("Farbe:")
esES("Color:")
fiFI("Väri:")
frFR("Couleur :")
huHU("Szín:")
itIT("Colore")
plPL("Kolor:")
roRO("Culoare:")
ruRU("Цвет:")
srSP("Boja:")
trTR("Renk:")
zhCN("颜色")
zhTW("顏色")

T_("R:")
csCZ("&R:")
deDE("R:")
esES("R:")
fiFI("R:")
frFR("R :")
huHU("R:")
itIT("R:")
plPL("R:")
roRO("R:")
ruRU("")
srSP("R:")
trTR("R:")
zhCN("R:")
zhTW("R:")

T_("G:")
csCZ("&G:")
deDE("G:")
esES("G:")
fiFI("G:")
frFR("V :")
huHU("G:")
itIT("G:")
plPL("G:")
roRO("G:")
ruRU("")
srSP("G:")
trTR("G:")
zhCN("G:")
zhTW("G:")

T_("B:")
csCZ("&B:")
deDE("B:")
esES("B:")
fiFI("B:")
frFR("B :")
huHU("B:")
itIT("B:")
plPL("B:")
roRO("B:")
ruRU("")
srSP("B:")
trTR("B:")
zhCN("B:")
zhTW("B:")

T_("H:")
csCZ("&H:")
deDE("F:")
esES("H:")
fiFI("H:")
frFR("H :")
huHU("H:")
itIT("h:")
plPL("H:")
roRO("H:")
ruRU("")
srSP("H:")
trTR("H:")
zhCN("H:")
zhTW("H:")

T_("S:")
csCZ("&S:")
deDE("S:")
esES("S:")
fiFI("S:")
frFR("S :")
huHU("S:")
itIT("S:")
plPL("S:")
roRO("S:")
ruRU("")
srSP("S:")
trTR("S:")
zhCN("S:")
zhTW("S:")

T_("V:")
csCZ("&V:")
deDE("H:")
esES("V:")
fiFI("V:")
frFR("V :")
huHU("V:")
itIT("V:")
plPL("V:")
roRO("V:")
ruRU("")
srSP("V:")
trTR("V:")
zhCN("V:")
zhTW("V:")

T_("&Rows:")
csCZ("Řa&dy:")
deDE("&Zeilen:")
esES("&Filas:")
fiFI("&Rivit:")
frFR("&Lignes :")
huHU("&Sorok:")
itIT("&Righe")
plPL("&Wiersze:")
roRO("&Linii")
ruRU("&Ряды:")
srSP("&Redovi:")
trTR("&Satırlar:")
zhCN("行(&R)")
zhTW("列(&R)")

T_("&Columns:")
csCZ("&Sloupce:")
deDE("&Spalten:")
esES("&Columnas:")
fiFI("&Sarakkeet:")
frFR("&Colonnes :")
huHU("&Oszlopok:")
itIT("&Colonne")
plPL("&Kolumny:")
roRO("&Coloane")
ruRU("&Колонки:")
srSP("&Kolone:")
trTR("S&ütunlar:")
zhCN("列(&C)")
zhTW("行(&C)")

T_("Defaults")
csCZ("")
deDE("")
esES("")
fiFI("")
frFR("")
huHU("")
itIT("")
plPL("")
roRO("")
ruRU("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Printer")
csCZ("Tiskárna")
deDE("Drucker")
esES("Impresora")
fiFI("Tulostin")
frFR("")
huHU("Nyomtató")
itIT("")
plPL("Drukarka")
roRO("Imprimantă")
ruRU("Принтер")
srSP("")
trTR("Yazıcı")
zhCN("打印机")
zhTW("印表機")

T_("Paper size")
csCZ("Velikost papíru")
deDE("Papiergröße")
esES("Tamaño del papel")
fiFI("Paperin koko")
frFR("")
huHU("Papírméret")
itIT("")
plPL("Rozmiar strony")
roRO("Dimensiune hărtie")
ruRU("Размер бумаги")
srSP("")
trTR("Kağıt Boyutu")
zhCN("纸张大小")
zhTW("紙張大小")

T_("Input slot")
csCZ("Vstup")
deDE("Papierzufuhr")
esES("¿Input slot?")
fiFI("Syöttökaukalo")
frFR("")
huHU("Input slot")
itIT("")
plPL("Slot wejściowy")
roRO("Slot de intrare")
ruRU("Лоток")
srSP("")
trTR("Yazıcı Girişi")
zhCN("输入槽")
zhTW("輸入槽")

T_("Pages per sheet")
csCZ("Stránek na list")
deDE("Seiten pro Blatt")
esES("Páginas por sheet")
fiFI("Sivuja per arkki")
frFR("")
huHU("Laponkénti oldalak")
itIT("")
plPL("Stron na arkusz")
roRO("Pagini per coală")
ruRU("Страниц на лист")
srSP("")
trTR("Kağıt başına düşen sayfa sayısı")
zhCN("每sheet页数")
zhTW("每sheet頁數")

T_("Print range")
csCZ("Rozsah tisku")
deDE("Seitenbereich")
esES("Rango de impresión")
fiFI("Tulosta sivut")
frFR("")
huHU("Nyomtatási tartomány")
itIT("")
plPL("Zakres drukowania")
roRO("Demeniul de imprimare")
ruRU("")
srSP("")
trTR("Yazdırma aralığı")
zhCN("打印范围")
zhTW("列印範圍")

T_("All pages\nCurrent page\nPages from")
csCZ("Vše\nAktulí stránku\nRozsah")
deDE("Alle Seiten\nAktuelle Seite\nSeiten von")
esES("Todas las páginas\nLa página acutal\nPáginas a partir de")
fiFI("Kaikki sivut\nTämä sivu\nSivut väliltä")
frFR("")
huHU("Minden oldal\nAktuális oldal\nOldalak a következőtől")
itIT("")
plPL("Wszystkie strony\nBieżąca strona\nStrony od")
roRO("Toate paginile\nPagina curentă\nPagini de la")
ruRU("")
srSP("")
trTR("Tüm sayfalar\nGeçerli sayfa\nSayfa aralığı")
zhCN("所有页\n当前页\n始于页")
zhTW("所有頁\n目前頁\n始於頁")

T_("to")
csCZ("až")
deDE("bis")
esES("hasta")
fiFI("-")
frFR("")
huHU("-")
itIT("")
plPL("do")
roRO("până")
ruRU("в")
srSP("")
trTR("to")
zhCN("到")
zhTW("到")

T_("Copies")
csCZ("Kopie")
deDE("Exemplare")
esES("Copias")
fiFI("Kopiot")
frFR("")
huHU("Példány")
itIT("")
plPL("Kopie")
roRO("Copii")
ruRU("Копий")
srSP("")
trTR("Kopya sayısı")
zhCN("份数")
zhTW("份數")

T_("Collate")
csCZ("Seřadit")
deDE("Zusammenstellen")
esES("Cotejar")
fiFI("Lajittele")
frFR("")
huHU("Collate")
itIT("")
plPL("Zestaw")
roRO("Legare")
ruRU("Подобрать")
srSP("")
trTR("Harmanla")
zhCN("比较")
zhTW("比較")

T_("Portrait\nLandscape")
csCZ("Na výšku\nNa šířku")
deDE("Hochformat\nQuerformat")
esES("Horizontal\nApaisado")
fiFI("Pysty\nVaaka")
frFR("")
huHU("Álló\nFekvő")
itIT("")
plPL("Portret\nKrajobraz")
roRO("Portret\nPeisaj")
ruRU("Портрет\nАльбом")
srSP("")
trTR("Dikey\nYatay")
zhCN("纵向\n横向")
zhTW("縱向\n橫向")

T_("Placement")
csCZ("Umístění")
deDE("Ausrichtung")
esES("Disposición")
fiFI("Sijoittelu")
frFR("")
huHU("Elhelyezés")
itIT("")
plPL("Umiejscowienie")
roRO("Poziție")
ruRU("Размещение")
srSP("")
trTR("Sayfa yerleşimi")
zhCN("布局")
zhTW("佈局")


// Obsolete

T_("Default")
csCZ("Základní")
deDE("Voreinstellung")
esES("Por defecto")
fiFI("Oletus")
frFR("Par défaut")
huHU("Alapértelmezett")
itIT("Predefiniti")
plPL("Domyślny")
roRO("Implicit")
ruRU("По умолчанию")
srSP("Podrazumevano")
trTR("Varsayılan")
zhCN("缺省")
zhTW("預設")

T_("&Cancel")
csCZ("&Zrušit")
deDE("&Abbrechen")
esES("&Cancelar")
fiFI("&Peruuta")
frFR("&Annuler")
huHU("Mégsem")
itIT("&Annulla")
plPL("&Anuluj")
roRO("&Anulează")
ruRU("&Отменить")
srSP("&Otkaži")
trTR("&İptal")
zhCN("取消(&C)")
zhTW("取消(&C)")

T_("Week")
csCZ("Týden")
deDE("Woche")
esES("Semana")
fiFI("Viikko")
frFR("")
huHU("Hét")
itIT("")
plPL("Tydzień")
roRO("Săptămână")
ruRU("Неделя")
srSP("")
trTR("Hafta")
zhCN("")
zhTW("")

T_("1 / 1")
csCZ("1 / 1")
deDE("1 / 1")
esES("1 / 1")
fiFI("1 / 1")
frFR("1 / 1")
huHU("1 / 1")
itIT("1 / 1")
plPL("1 / 1")
roRO("1 / 1")
ruRU("1 / 1")
srSP("1 / 1")
trTR("1 / 1")
zhCN("1 / 1")
zhTW("1 / 1")

T_("Sideways")
csCZ("Na šířku")
deDE("Querformat")
esES("¿Sideways?")
fiFI("Sivuttain")
frFR("Direction")
huHU("Oldalsáv")
itIT("Direzione")
plPL("Liczba stron")
roRO("Prin lateral")
ruRU("По бокам")
srSP("Sa strane")
trTR("Yanlama")
zhCN("侧边")
zhTW("側邊")

T_("&1 page\n&2 pages\n&4 pages\n&8 pages")
csCZ("&1 strana\n&2 strany\n&4 strany\n&8 stran")
deDE("&1 Seite\n&2 Seiten\n&4 Seiten\n&8 Seiten")
esES("&1 página\n&2 páginas\n&4 páginas\n&8 páginas")
fiFI("&1 sivu\n&2 sivua\n&4 sivua\n&8 sivua")
frFR("&1 page\n&2 pages\n&4 pages\n&8 pages")
huHU("&1 oldal\n&2 oldal\n&4 oldal\n&8 oldal")
itIT("&1 pagina\n&2 pagine\n&4 pagine\n&8 pagine")
plPL("&1 strona\n&2 strony\n&4 strony\n&8 stron")
roRO("&1 pagină\n&2 pagini\n&4 pagini\n&8 pagini")
ruRU("&1 страница\n&2 страницы\n&4 страницы\n&8 страниц")
srSP("&1 strana\n&2 strane\n&4 strane\n&8 strana")
trTR("&1 sayfa\n&2 sayfa\n&4 sayfa\n&8 sayfa")
zhCN("&1 页\n&2 页\n&4 页\n&8 页")
zhTW("&1 頁\n&2 頁\n&4 頁\n&8 頁")

T_("Page &numbers")
csCZ("Čísla &stránek")
deDE("&Seitenzahlen")
esES("&Numeros de página")
fiFI("&Sivunumerot")
frFR("&Numéros de page")
huHU("&Oldalszámok")
itIT("&Numero pagine")
plPL("Numery &stron")
roRO("&Numere de pagină")
ruRU("&Номера страниц")
srSP("&Broj strana")
trTR("Sayfa &numaraları")
zhCN("页码(&n)")
zhTW("頁碼(&n)")

T_("PDF export..")
csCZ("PDF export..")
deDE("PDF-Export ...")
esES("Exportar a PDF..")
fiFI("PDF export...")
frFR("Export PDF..")
huHU("PDF export..")
itIT("")
plPL("Eksportuj PDF..")
roRO("Exportă PDF..")
ruRU("Экспорт в PDF")
srSP("PDF eksport..")
trTR("PDF dosyasını içe aktar...")
zhCN("输出PDF..")
zhTW("輸出PDF..")

T_("Report")
csCZ("Výstupní sestava")
deDE("Bericht")
esES("Informe")
fiFI("Raportti")
frFR("Rapport")
huHU("Jelentés")
itIT("Report")
plPL("Raport")
roRO("Raport")
ruRU("Отчёт")
srSP("Izveštaj")
trTR("Bildir")
zhCN("报告")
zhTW("報告")

T_("&Print")
csCZ("&Tisk")
deDE("&Drucken")
esES("&Imprimir")
fiFI("&Tulosta")
frFR("&Imprimer")
huHU("&Nyomtatás")
itIT("&Stampa")
plPL("&Drukuj")
roRO("&Imprimă")
ruRU("&Печать")
srSP("&Štampa")
trTR("&Yazdır")
zhCN("打印(&P)")
zhTW("列印(&P)")
