#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// topictree.cpp

T_("This page has not been translated yet")
caES("Aquesta pàgina no s'ha traduït encara")
csCZ("Tato stránka ještě nebyla přeložena")
esES("Esta página aún no ha sido traducida")
frFR("Cette page n'a pas encore été traduite")
roRO("Aceasta pagina nu a fost inca tradusa")
ruRU("Эта страница еще не переведена")
zhTW("本頁面還沒有被翻譯")

T_("Do you want to translate it?")
caES("Vols traduirla?")
csCZ("Chcete ji přeložit?")
esES("¿Quieres traducirla?")
frFR("Voulez-vous traduire cela ?")
roRO("Doriti sa o traduceti?")
ruRU("Вы хотите перевести?")
zhTW("你要協助翻譯嗎？")


// www.cpp

T_("Using %s")
caES("Utilitzant %s")
csCZ("Pomocí %s")
esES("Usando %s")
frFR("En utilisant %s")
roRO("Folosind %s")
ruRU("Использован %s")
zhTW("使用%s")

T_("%s reference")
caES("Referència de l'%s")
csCZ("%s manuál")
esES("Referencia de %s")
frFR("Référence de %s")
roRO("Referinta la %s")
ruRU("%s ссылка")
zhTW("%s 的參考")

T_("Last edit by %s on %s")
caES("Última edició per %s el %s")
csCZ("Naposledy upravil %s %s")
esES("Ultima edición por %s el %s")
frFR("Dernière édition par %s le %s")
roRO("Ultima editare de catre %s in %s")
ruRU("Последнее изменение %s в %s")
zhTW("最後編輯由%s在%s")

T_("and")
caES("i")
csCZ("a")
esES("y")
frFR("et")
roRO("si")
ruRU("и")
zhTW("且")

T_("This page is also in %s")
caES("Aquesta pàgina també està en %s")
csCZ("Tato stránka je také dostupná %s")
esES("Esta página está también en %s")
frFR("Cette page est aussi en %s")
roRO("Aceasta pagina este deasemenea in %s")
ruRU("Страница доступна на %s языке")
zhTW("本頁也正在%s中")

T_("Do you want to contribute?")
caES("Vols col.laborar?")
csCZ("Chcete přispět?")
esES("¿Quieres ayudar?")
frFR("Vous voulez nous aider ?")
roRO("Doriti sa contribuiti?")
ruRU("Вы хотите внести вклад?")
zhTW("你想幫忙嗎?")

T_("Overview")
caES("Informació general")
csCZ("Přehled")
esES("Información general")
frFR("Vue d'ensemble")
roRO("Informatii generale")
ruRU("Обзор")
zhTW("第一印象")

T_("Examples")
caES("Exemples")
csCZ("Příklady")
esES("Ejemplos")
frFR("Exemples")
roRO("Exemple")
ruRU("Примеры")
zhTW("範例程式")

T_("Screenshots")
caES("Pantallas")
csCZ("Screenshoty")
esES("Pantallas")
frFR("Captures d'écrans")
roRO("Imagini ecran")
ruRU("Скриншоты")
zhTW("截圖")

T_("Comparisons")
caES("Comparacions")
csCZ("Srovnání")
esES("Comparaciones")
frFR("Comparaisons")
roRO("Comparatii")
ruRU("Сравнения")
zhTW("與其它函式庫比較")

T_("Applications")
caES("Aplicacions")
csCZ("Aplikace")
esES("Aplicaciones")
frFR("Applications")
roRO("Aplicatii")
ruRU("Приложения")
zhTW("相關應用")

T_("Download")
caES("Descarregar")
csCZ("Stažení")
esES("Descargar")
frFR("Télécharger")
roRO("Descarca")
ruRU("Загрузить")
zhTW("下載")

T_("Manual")
caES("Manual")
csCZ("Manuál")
esES("Manual")
frFR("Manuel")
roRO("Manual")
ruRU("Руководства")
zhTW("教學文件")

T_("Bazaar")
caES("\"El Mercat\"")
csCZ("Bazar")
esES("\"El Mercado\"")
frFR("Bazaar")
roRO("Bazar")
ruRU("Базар")
zhTW("作品展示(Bazaar)")

T_("Status & Roadmap")
caES("Estat i Pla de treball")
csCZ("Stav & Plány")
esES("Estado y Plan de trabajo")
frFR("État et Feuille de route")
roRO("Statut si Foaie de parcurs")
ruRU("Статус и История")
zhTW("現狀及發展藍圖")

T_("FAQ")
caES("Preguntes més freqüents")
csCZ("FAQ - Často kladené dotazy")
esES("Preguntas más frecuentes")
frFR("Foire aux questions")
roRO("Intrebari frecvente")
ruRU("Частые вопросы (FAQ)")
zhTW("常見問題(FAQ)")

T_("Authors & License")
caES("Autors i Llicència")
csCZ("Autoři & Licence")
esES("Autores y Licencia")
frFR("Auteurs & licence")
roRO("Autori si Licenta")
ruRU("Авторы и лицензия")
zhTW("作者與授權")

T_("Forums")
caES("Fòrums")
csCZ("Forum")
esES("Foros")
frFR("Forums")
roRO("Forum")
ruRU("Форум")
zhTW("論壇")

T_("Funding Ultimate++")
caES("Finançament de l'U++")
csCZ("Financování U++")
esES("Financiación de U++")
frFR("Financement de U++")
roRO("Finantarea Ultimate++")
ruRU("Помощь проекту")
zhTW("資助Ultimate++")

T_("Search on this site")
caES("Cerca en aquesta web")
csCZ("Hledej na tomto webu")
esES("Busca en esta página")
frFR("Recherche sur ce site")
roRO("Cauta in acest site")
ruRU("Поиск по сайту")
zhTW("搜尋本網站")
