#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// httpsrv.cpp

T_("If you're not redirected automatically please use %s.")
csCZ("Pokud nebudete automaticky přesměrováni, použijte prosím %s.")
deDE("Wenn Sie nicht automatisch weitergeleitet werden, benutzen Sie bitte %s")
esES("Si no es redirigido autom�ticamente, utilice %s.")
fiFI("Jos toiminto ei etene automaattisesti, käytä %s.")
frFR("Si vous n'êtes pas automatiquement redirigé, veuillez utiliser %s.")
huHU("Ha nem történik automatikus átirányítás használja %s")
itIT("")
nlNL("Als je niet automatisch bent omgeleid gebruik gaarne %s.")
plPL("Jeśli nie zostałeś automatycznie przekierowany użyj proszę %s.")
roRO("Dacă nu sunteţi redirectaţi automat folosiţi %s.")
ruRU("Если Вы не перенаправлены автоматически, "
     "пожайлуста, используйте %s.")
skSK("Ak nebudete automaticky presmerovaní, použite prosím %s.")
srSP("")
trTR("Eğer otomatik olarak yönlendirlmediyseniz lütfen %s bağlantısını "
     "kullanın.")
zhCN("如果没有自动重定向,请使用%s.")
zhTW("如果沒有自動重新導向，請使用 %s.")

T_("this link")
csCZ("tento odkaz")
deDE(" diesen Link.")
esES("este enlace")
fiFI("tämä linkki")
frFR("ce lien")
huHU("ezt a hivatkozást")
itIT("")
nlNL("deze link")
plPL("tego odnośnika")
roRO("acest link")
ruRU("эту ссылку")
skSK("tento odkaz")
srSP("")
trTR("bu bağlantı")
zhCN("本链接")
zhTW("此鏈接")

T_("Redirection to another web address")
csCZ("Přesměrování na jinou adresu")
deDE("Weiterleitung zu einer anderen Netzadresse")
esES("Redirecci�n a otra direcci�n web")
fiFI("Reititys toiseen web -osoitteeseen")
frFR("Redirection vers une autre adresse web")
huHU("Átirányítás másik webcímre")
itIT("")
nlNL("Omleiding naar een ander web adres")
plPL("Przekierowanie do innej strony")
roRO("Redirectare spre o altă adresă web")
ruRU("Перенаправление на другой веб адрес")
skSK("Presmerovanie na inú adresu")
srSP("")
trTR("başka bir ağ adresine yönlendiriliyor")
zhCN("重定向到其他web地址")
zhTW("重新導向到其它web位址")

T_("... (total length: %d bytes)")
csCZ("... (celková délka: %d bytů)")
deDE("... (Gesamtgröße: %d Bytes)")
esES("... (tama�o total: %d bytes)")
fiFI("... (kokonaispituus: %d tavua)")
frFR("(longueur totale : %d octets")
huHU("... (teljes hossz: %d bájt)")
itIT("")
nlNL("... (totale lengte: %d bytes)")
plPL("... (całkowita długość: %d bajtów)")
roRO("... (lungime totală: %d bytes)")
ruRU("... (полный размер: %d байт)")
skSK("... (celková dĺžka: %d bytov)")
srSP("")
trTR("... (toplam boyut: %d byte)")
zhCN("... (总长: %d 字节)")
zhTW("... (總長度： %d 位元組)")

T_("The web server is unable to satisfy your request:\n<p>\n")
csCZ("Internetový server nebyl schopen vyřídit požadavek:\n<p>\n")
deDE("Der Netzserver kann Ihre Anforderung nicht erfüllen:\n<p>\n")
esES("El servidor web no puede satisfacer su solicitud:\n<p>\n")
fiFI("Web palvelin ei kykene täyttämään pyyntöäsi:\n<p>\n")
frFR("Ce serveur web ne peut pas satisfaire votre requête :\n<p>\n")
huHU("A webkiszolgáló nem tudja teljesíteni a kérést:\n<p>\n")
itIT("")
nlNL("Deze web server kan niet uw aanvraag behandelen:\n<p>\n")
plPL("Ten serwer sieciowy nie jest w stanie odpowiedzieć na twoje żądanie:\n"
     "<p>\n")
roRO("Serverul nu este în masură să va satisfacă cererea:\n<p>\n")
ruRU("Этот веб сервер не может удовлетворить "
     "Ваш запрос:\n<p>\n")
skSK("Internetový server nebol schopný vybaviť požiadavku:\n<p>\n")
srSP("")
trTR("Ağ sunucusu isteğinizi yerine getiremiyor:\n<p>\n")
zhCN("web服务器不支持您的请求:\n<p>\n")
zhTW("web伺服器不支援您的請求：\n<p>\n ")

T_("Reason:")
csCZ("Důvod chyby: ")
deDE("Grund:")
esES("Raz�n:")
fiFI("Syy:")
frFR("Raison :")
huHU("Ok:")
itIT("")
nlNL("Reden:")
plPL("Powód:")
roRO("Motiv:")
ruRU("Причина:")
skSK("Dôvod chyby: ")
srSP("")
trTR("Sebep:")
zhCN("原因:")
zhTW("原因：")

T_("Detailed query data:")
csCZ("Detailní informace o dotazu:")
deDE("Genaue Abfragedaten:")
esES("Datos detallados de consulta:")
fiFI("Yksityiskohtainen kysely tieto:")
frFR("Données détaillées de la requête :")
huHU("Részletes lekérési adatok:")
itIT("")
nlNL("Gëdetaileerde query data:")
plPL("Szczegółowe dane zapytania:")
roRO("Date detaliate despre cerere:")
ruRU("Детали запроса:")
skSK("Detailné informácie o dotaze:")
srSP("")
trTR("Detaylı sorgulama verileri:")
zhCN("详细查询数据")
zhTW("詳細查詢資料：")

T_("Web server error")
csCZ("Chyba internetového serveru")
deDE("Netzserverfehler")
esES("Error de servidor Web")
fiFI("Web -palvelin virhe")
frFR("Erreur du serveur web")
huHU("Webkiszolgáló hiba")
itIT("")
nlNL("Web server fout")
plPL("Błąd serwera sieciowego")
roRO("Eroare de server web")
ruRU("Ошибка веб сервера")
skSK("Chyba internetového serveru")
srSP("")
trTR("Sunucu hatası")
zhCN("Web服务器错误")
zhTW("Web伺服器錯誤")


// httpcli.cpp

T_("%s:%d receiving headers timed out")
csCZ("%s:%d vypršel časový limit při načítání hlaviček")
deDE("%s:%d Timeout beim Headerempfang")
esES("%s:%d recibiendo encabezados, tiempo de espera agotado")
fiFI("%s:%d headerien vastaanotto aikakatkaistu")
frFR("%s:%d temps dépassé à la réception de l'en-tête")
huHU("%s:%d időtúllépés fejlécek fogadása közben")
itIT("")
nlNL("%s:%d headers zijn niet op tijd ontvangen")
plPL("%s:%d przekroczono czas odbierania nagłówka")
roRO("%s:%d obținerea antetelor a depășit limita de timp")
ruRU("%s:%d превишен интервал ожидания при получении "
     "заголовков")
skSK("%s:%d uplynul časový limit pre načítanie hlavičiek")
srSP("")
trTR("%s:%d: Üstbilgi alışverişi zaman aşımına uğradı.")
zhCN("%s:%d 接收头超时")
zhTW("%s:%d 接收標頭逾時")

T_("%s:%d: connecting to host timed out")
csCZ("%s:%d: vypršel časový limit pro připojení k hostiteli")
deDE("%s:%d Timeout bei der Verbindungsaufnahme mit dem Server")
esES("%s:%d: tiempo de espera agotado conectando al host")
fiFI("%s:%d: kytkeytyminen isäntään aikakatkaistu")
frFR("%s:%d : l'hôte n'a pas accepté la connexion dans le temps imparti")
huHU("%s:%d: időtúllépés a szerverhez kapcsolódás közben")
itIT("")
nlNL("%s:%d: niet op tijd verbonden met de host")
plPL("%s:%d przekroczono czas łączenia się z hostem")
roRO("%s:%d: depășire de limită de timp la conectare")
ruRU("%s:%d превишен интервал ожидания при подключении "
     "к серверу")
skSK("%s:%d: uplynul časový limit pre pripojenie k hostiteľovi")
srSP("")
trTR("%s:%d: Sunucu bağlantısı zaman aşımına uğradı")
zhCN("%s:%d: 连接到主机超时")
zhTW("%s:%d: 連接到主機逾時")

T_("%s:%d: timed out sending request to server")
csCZ("%s:%d: vypršel časový limit při odesílání požadavku")
deDE("%s:%d Timeout beim Übermitteln der Abfrage an den Server")
esES("%s:%d: tiempo de espera agotado enviado respuesta a servidor")
fiFI("%s:%d: palvelupyynnön lähettäminen palvelimelle aikakatkaistu")
frFR("%s:%d : le serveur n'a pas répondu dans le temps imparti")
huHU("%s:%d: időtúllépés a kérés elküldésénél")
itIT("")
nlNL("%s:%d: aanvragen niet op tijd verzonden naar de server")
plPL("%s:%d: przekroczono czas wysyłania żądania do serwera")
roRO("%s:%d: depășire de limită de timp la trimitere cerere spre server")
ruRU("%s:%d: таймаут отправки запроса на сервер")
skSK("%s:%d: uplynul časový limit pre odoslanie požiadavky")
srSP("")
trTR("%s:%d: İstek zaman aşımına uğradı")
zhCN("%s:%d: 发送请求到服务器超时")
zhTW("%s:%d: 發送請求到伺服器逾時")

T_("%s:%d: invalid server response: %s")
csCZ("%s:%d: neplatná odezva ze serveru: %s")
deDE("%s:%d: Ungültige Serverantwort: %s")
esES("%s:%d: respuesta inv�lida del servidor: %s")
fiFI("%s:%d: virheellinen palvelinvastine: %s")
frFR("%s:%d : réponse du serveur invalide : %s")
huHU("%s:%d: érvénytelen kiszolgálói válasz")
itIT("")
nlNL("%s:%d: ongeldige reactie van de server: %s")
plPL("%s:%d: niepoprawna odpowiedź serwera: %s")
roRO("%s:%d: răspuns invalid de la server: %s")
ruRU("%s:%d: неправильный ответ сервера: %s")
skSK("%s:%d: neplatná odozva zo servera: %s")
srSP("")
trTR("%s:%d: Sunucudan gelen yanıt geçersiz")
zhCN("%s:%d: 无效服务器反应: %s")
zhTW("%s:%d: 無效的伺服器反應: %s")

T_("%s:%d: maximum data length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka dat (%d B)")
deDE("%s:%d: Maximale Datenlänge überschritten (%d B)")
esES("%s:%d: longitud de datos m�xima excedida (%d B)")
fiFI("%s:%d: datan enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale des données (%d O)")
huHU("%s:%d: maximális adathossz túllépése (%d B)")
itIT("")
nlNL("%s:%d: maximum data lengte overschreden (%d B)")
plPL("%s:%d: przekroczono dopuszczalny rozmiar danych (%d B)")
roRO("%s:%d: dimeniunea maximă a datelor a fost depășită (%d B)")
ruRU("%s:%d: превышен максимальный размер данных "
     "(%d B)")
skSK("%s:%d: byla prekročená maximálna dĺžka dát (%d B)")
srSP("")
trTR("%s:%d: maksimum veri boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大数据长度(%d B)")
zhTW("%s:%d: 超過最大資料長度(%d B)")

T_("%s:%d: maximum header length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka hlaviček (%d B)")
deDE("%s:%d: Maximale Headerlänge überschritten (%d B)")
esES("%s:%d: longitud de encabezado m�xima excedida (%d B)")
fiFI("%s:%d: headerin enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale de l'en-tête (%d O)")
huHU("%s:%d: maximális fejléchossz túllépése (%d B)")
itIT("")
nlNL("%s:%d: maximum header lengte overschreden (%d B)")
plPL("%s:%d: przekroczono dopuszczalną długość nagłówka (%d B)")
roRO("%s:%d: dimeniunea maximă a antetului a fost depășită (%d B)")
ruRU("%s:%d: превышен максимальный размер заголовка "
     "(%d B)")
skSK("%s:%d: bola prekročená maximálna dĺžka hlavičiek (%d B)")
srSP("")
trTR("%s:%d:Maksimum üstbilgi boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大头长度(%d B)")
zhTW("%s:%d: 超過最大標頭長度(%d B)")

T_("%s:%d: timed out when receiving server response")
csCZ("%s:%d: vypršel časový limit při načítání odpovědi")
deDE("%s:%d: Timeout beim Empfang der Serverantwort")
esES("%s:%d: tiempo de espera agotado esperando respuesta del servidor")
fiFI("%s:%d: palvelinvastineen vastaanotto aikakatkaistu")
frFR("%s%d : temps dépassé à la réception de la réponse du serveur")
huHU("%s:%d: időtúllépés a kiszolgáló válaszára várva")
itIT("")
nlNL("%s:%d: te lang gewacht op reactie van de server")
plPL("%s:%d: przekroczono czas oczekiwania na odpowiedź serwera")
roRO("%s:%d: limită de timp depășită la primirea răspunsului de la server")
ruRU("%s:%d: таймаут при приёме ответа от сервера")
skSK("%s:%d: uplynul časový limit pri načítanie odpovede")
srSP("")
trTR("%s:%d: Sunucudan  yanıt beklenirken zaman aşımı meydana geldi")
zhCN("%s:%d: 接收服务器反应时超时")
zhTW("%s:%d: 接收伺服器反應逾時")

T_("Maximum content size exceeded: %d")
csCZ("Překročena maximální povolená délka datového obsahu: %d")
deDE("Maximaler Datenumfang überschritten: %d")
esES("Tama�o de contenido m�ximo excedido: %d")
fiFI("Sisällön enimmäiskoko ylitetty: %d")
frFR("Taille max du contenu dépassée")
huHU("A maximális tartalomhossz túllépve: %d")
itIT("")
nlNL("Maximum inhoud grootte overschreden: %d")
plPL("Przekroczono dopuszczalny rozmiar zawartości: %d")
roRO("Dimeniunea maximă a conținutului depășită: %d")
ruRU("Превышен максимальный размер содержимого: "
     "%d")
skSK("Prekročená maximálna povolená dĺžka dátového obsahu: %d")
srSP("")
trTR("Maksimum içerik boyutu aşıldı: %d")
zhCN("最大内容长度超出:%d")
zhTW("最大內容長度超過： %d")

T_("Partial input: %d out of %d")
csCZ("Přijata neúplná data: %d z %d")
deDE("Unvollständiger Empfang: %d von %d")
esES("Entrada parcial: %d de %d")
fiFI("Osittainen syöte: %d / %d")
frFR("Saisie partielle : %d de %d")
huHU("Részleges beolvasás: %d a %d-ból")
itIT("")
nlNL("Gedeeltelijke invoer: %d van de %d")
plPL("Dane częściowe: %d z %d")
roRO("Intrări parțiale: %d din %d")
ruRU("Частичный ввод: %d из %d")
skSK("Přijaté neúplné dáta: %d z %d")
srSP("")
trTR("Kısmi girdi: %d/%d")
zhCN("部分输入: %d out of %d")
zhTW("部分輸入: %d out of %d")


// auth.cpp

T_("Username:&nbsp;")
csCZ("Uživatelské jméno:&nbsp;")
deDE("")
esES("Usuario:&nbsp;")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Utilizator:&nbsp;")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Password:&nbsp;")
csCZ("Pøístupové heslo:&nbsp;")
deDE("")
esES("Palabra clave:&nbsp;")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Parola:&nbsp;")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Connection succeeded")
csCZ("Pøipojení bylo úspìšné")
deDE("")
esES("Conexi�n correcta")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Conexiune reusită")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("\n\n<p>Connection to remote computer has succeeded. ")
csCZ("\n\n<p>Pøipojení ke vzdálenému poèítaèi probìhlo úspìšnì. ")
deDE("")
esES("\n\n<p>Conexi�n a ordenador remoto realizada correctamente. ")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("\n\n<p>Conexiunea cu computerul de la distanță a reușit. ")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Access code will loose validity after half hour of client inactivity or "
     "on explicit request.\n")
csCZ("Pøístupový kód ztratí platnost po pùlhodinové neèinnosti klienta "
     "nebo na výslovnou žádost o odhlášení.\n")
deDE("")
esES("El c�digo de acceso perder� validez al de media hora de inactividad en "
     "el cliente o por petici�n expl�cita.\n")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Codul de acces își va pierde valabilitatea după jumătate de ora de "
     "inactivitate sau explicit la cerere.\n")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Change password:&nbsp;")
csCZ("Zmìna hesla:&nbsp;")
deDE("")
esES("Cambiar palabra clave:&nbsp;")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Schimbă parola:&nbsp;")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Repeat password:&nbsp;")
csCZ("Opakovat heslo:&nbsp;")
deDE("")
esES("Repetir palabra clave:&nbsp;")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Repetă parola:&nbsp;")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_(" Continue ")
csCZ(" Pokraèovat ")
deDE("")
esES(" Continuar ")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO(" Continuă ")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Please enter a new password.")
csCZ("Zadejte prosím nové pøístupové heslo.")
deDE("")
esES("Por favor introduzca una nueva palabra de paso")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Introduceți noua parolă.")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Please enter the password twice.")
csCZ("Zadejte prosím do obou polí stejné heslo.")
deDE("")
esES("Por favor introduzca la palabra de paso dos veces.")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Introduceți parola de două ori.")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Password has expired. Please login again.")
csCZ("Platnost pøístupového kódu vypršela. Zadejte prosím znovu uživatelské "
     "jméno a heslo.")
deDE("")
esES("La palabra de paso ha caducado. Por favor inicie el sistema de nuevo.")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Parola a expirat. Autentifică-te din nou.")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Invalid password and/or username")
csCZ("Zadané uživatelské jméno nebo heslo je neplatné!")
deDE("")
esES("Palabra de paso y/o usuario incorrecto")
fiFI("")
frFR("")
huHU("")
itIT("")
nlNL("")
plPL("")
roRO("Parolă și/sau utilizator greșit")
ruRU("")
skSK("")
srSP("")
trTR("")
zhCN("")
zhTW("")


// smtp.cpp

T_("Communication Failure: Timeout.")
csCZ("Porucha komunikace: vypršel časový limit.")
deDE("Kommunikationsfehler: Timeout")
esES("Fallo de comunicaci�n: Tiempo de espera agotado.")
fiFI("Viestintävirhe: Aikakatkaisu.")
frFR("Erreur de communication: Timout.")
huHU("Kommunikációs hiba: Időtúllépés")
itIT("")
nlNL("Communicatie Mislukt: Te lang moeten wachten")
plPL("")
roRO("Eroare în comunicare: Limită de timp depășită.")
ruRU("Ошибка связи. Таймаут.")
skSK("Porucha komunikácie: uplynul časový limit.")
srSP("")
trTR("Bağlantı başarısız: Zaman aşımı.")
zhCN("通信失败:超时。")
zhTW("通訊失敗：逾時.")

T_("Error writing data to socket: communication port closed.")
csCZ("Chyba při zápisu dat do socketu: komunikační kanál byl uzavřen.")
deDE("Socketfehler beim Schreiben der Daten: Port wurde geschlossen.")
esES("Error escribiendo datos de socket: puerto de comunicaci�n cerrado.")
fiFI("Virhe socketiin kirjoitettaessa: kommunikointiportti suljettu.")
frFR("Erreur d'écriture sur la socket: port de communication fermé.")
huHU("Hiba az adatok socket-re írásakor: kommunikációs port zárva.")
itIT("")
nlNL("Fout tijdens schrijven naar socket: communicatie poort gesloten.")
plPL("")
roRO("Eroare la scriere în soclu: portul de comunicare este închis.")
ruRU("Ошибка посылки данных в сокет: порт связи "
     "закрыт")
skSK("Chyba pri zápise dát do soketu: komunikačný kanál bol uzatvorený.")
srSP("")
trTR("Sokete yazma hatası: bağlantı kesildi.")
zhCN("socket写入数据错误:通信端口关闭")
zhTW("輸出資料錯誤：通訊埠已經關閉.")

T_("Error writing data to socket, error code: ")
csCZ("Chyba při zápisu dat do socketu, kód chyby: ")
deDE("Socketfehler beim Schreiben der Daten, Fehlercode: ")
esES("Error escribiendo datos a socket, c�digo de error: ")
fiFI("Virhe socketiin kirjoitettaessa, virhe koodi: ")
frFR("Erreur d'écriture sur la socket, code d'erreur:")
huHU("Hiba az adatok socket-re írásakor, hibakód: ")
itIT("")
nlNL("Fout tijdens schrijven naar socket, fout code: ")
plPL("")
roRO("Eroare la scriere în soclu, cod:")
ruRU("Ошибка посылки данных в сокет: код оибки: ")
skSK("Chyba pri zápise dát do soketu, kód chyby: ")
srSP("")
trTR("Sokete yazma hatası meydana geldi. Hata kodu: ")
zhCN("socket写入数据错误，错误代码:")
zhTW("輸出資料錯誤，錯誤代碼：")

T_("Error reading data from socket: communication port closed.")
csCZ("")
deDE("")
esES("Error leyendo datos de socket: puerto de comunicaciones cerrado: ")
fiFI("")
frFR("Erreur de lecture sur la socket: port de communication fermé")
huHU("")
itIT("")
nlNL("Fout tijdens lezen vanuit socket: communicatie poort gesloten.")
plPL("")
roRO("Eroare la citirea datelor din socket: portul de comunicație este închis.")
ruRU("Ошибка чтения данных из сокета: порт связи "
     "закрыт")
skSK("Chyba pri čítaní dát zo soketu: komunikačný port uzavretý.")
srSP("")
trTR("")
zhCN("从socket读数据错误:通信端口关闭")
zhTW("讀取資料錯誤：通訊埠已經關閉.")

T_("Error reading socket, error code: %s")
csCZ("")
deDE("")
esES("Error leyendo socket, c�digo de error: %s")
fiFI("")
frFR("Erreur de lecture sur la socket, code d'erreur: %s")
huHU("")
itIT("")
nlNL("Fout tijdens lezen vanuit socket, fout code: %s")
plPL("")
roRO("Eroare citire socket, code de eroare: %s")
ruRU("Ошибка чтения данных из сокета, код ошибки: "
     "%s")
skSK("Chyba pri čítaní soketu, chybový kód: %s")
srSP("")
trTR("")
zhCN("读取socket错误，错误代码: %s")
zhTW("讀取資料錯誤，錯誤代碼：%s")

T_("Host not set.")
csCZ("Hostitel není zadán.")
deDE("Host nicht eingerichtet")
esES("Host no especificado.")
fiFI("Isäntää ei ole asetettu.")
frFR("Hôte non configuré")
huHU("A távoli gép nincs megadva.")
itIT("")
nlNL("Host niet ingesteld.")
plPL("")
roRO("Host-ul nu este ales.")
ruRU("Сервер не определен")
skSK("Hostiteľ nie je zadaný.")
srSP("")
trTR("Host hazır değil.")
zhCN("主机未设置。")
zhTW("沒有設定主機.")

T_("Recipient not set.")
csCZ("Není zadán příjemce.")
deDE("Empfänger nicht eingerichtet")
esES("Recipiente no especificado.")
fiFI("Vastaanottajaa ei ole asetettu.")
frFR("Client non configuré")
huHU("A fogadó gép nincs megadva.")
itIT("")
nlNL("Ontvanger niet ingesteld.")
plPL("")
roRO("Receptorul nu este ales")
ruRU("Получатель не определен")
skSK("Nie je zadaný príjemca.")
srSP("")
trTR("Alıcı hazır değil.")
zhCN("接收机未设置")
zhTW("沒有設定收件人.")


// sproc.cpp

T_("pipe() error; error code = %d")
csCZ("chyba pipe(); kód chyby = %d")
deDE("pipe()-Fehler; Fehlercode = %d")
esES("error en pipe(); codigo = %d")
fiFI("pipe() virhe; virhe koodi = %d")
frFR("erreur pipe(); code d'erreur = %d")
huHU("pipe() hiba; hibakód = %d")
itIT("")
nlNL("pijp() fout; fout code = %d")
plPL("błąd pipe(); kod błędu = %d")
roRO("eroare pipe(); cod = %d")
ruRU("ошибка pipe(); код ошибки = %d")
skSK("chyba pipe(); kód chyby = %d")
srSP("")
trTR("pipe() hatası; hata kodu = %d")
zhCN("pipe() error; error code = %d")
zhTW("pipe()錯誤；錯誤代碼 = %d")

T_("fork() error; error code = %d")
csCZ("chyba fork(); kód chyby = %d")
deDE("fork()-Fehler; Fehlercode = %d")
esES("error en fork(); codigo = %d")
fiFI("fork() virhe; virhe koodi = %d")
frFR("erreur fork(); code d'erreur = %d")
huHU("fork() hiba; hibakód = %d")
itIT("")
nlNL("vork() fout; fout code = %d")
plPL("błąd fork(); kod błędu = %d")
roRO("eroare fork(): cod = %d")
ruRU("ошибка fork(); код ошибки = %d")
skSK("chyba fork(); kód chyby = %d")
srSP("")
trTR("fork() hatası; hata kodu = %d")
zhCN("fork() error; error code = %d")
zhTW("fork()錯誤；錯誤代碼 = %d ")

T_("Opening host '%s' / port %d failed, error = %s")
csCZ("Připojování k hostiteli '%s' / port %d selhalo, chyba = %s")
deDE("Zugriff auf den Host '%s' / port %d fehlgeschlagen, Fehler = %s")
esES("Abriendo host '%s' / fall� puerto %d, error = %s")
fiFI("Kytkentä isäntään '%s' / portti %d epäonnistui, virhe = %s")
frFR("Erreur d'ouverture de '%s' / port %d, erreur = %s")
huHU("A '%s' gép / %d port megnyitása sikertelen, hiba = %s")
itIT("")
nlNL("Openen host '%s' / poort %d mislukt, fout = %s")
plPL("Łączenie z hostem '%s' / port %d nie powiodło się, błąd = %s")
roRO("Se deschide host-ul '%s' / eșuare pe portul %d, eroare = %s")
ruRU("Подсоединение к хосту '%s' / порту %d не удачно, "
     "ошибка = %s")
skSK("Pripájanie k hostiteľovi '%s' / port %d zlyhalo, chyba = %s")
srSP("")
trTR("'%s' hostuna '%d' portundan bağlanma girişi başarısız oldu. Hata "
     "= %s")
zhCN("Opening host '%s' / port %d failed, error = %s")
zhTW("開啟主機 '%s' / 埠 %d 失敗, 錯誤 = %s ")

T_("Error running process: %s\nCommand: %s")
csCZ("Chyba při spouštění procesu: %s\nPříkaz: %s")
deDE("Fehler beim Ausführen des Prozesses: %s\nBefehl: %s")
esES("Error ejecutando proceso: %s\nComando: %s")
fiFI("Virhe prosessin suorittamisessa: %s\nCommand: %s")
frFR("Erreur d'exécution du programme : %s\nCommande : %s")
huHU("Hiba a %s folyamat\n%s parancs futtatásánál")
itIT("")
nlNL("Fout tijdens het belopen van het proces: %s\nCommando: %s")
plPL("Błąd uruchamiania procesu: %s\nKomenda: %s")
roRO("Eroare execuție proces: %s\nComanda: %s")
ruRU("Ошибка при запуске процесса: %s\nКоманда: "
     "%s")
skSK("Chyba pri spustení procesu: %s\nPríkaz: %s")
srSP("")
trTR("'%s' işleminin çalıştırılması sırasında hata oluştu\nKomut: "
     "%s")
zhCN("运行进城错误:%s\n命令: %s")
zhTW("執行中的行程發生錯誤：%s\n指令: %s")

T_("Communication error; process = %s")
csCZ("Chyba spojení; proces = %s")
deDE("Kommunikationsfehler; Prozess = %s")
esES("Error de comunicaci�n; proceso = %s")
fiFI("Kommunikointi virhe; prosessi = %s")
frFR("Erreur de communication ; processus = %s")
huHU("Kommunikációs hiba; folyamat = %s")
itIT("")
nlNL("Communicatie fout; proces = %s")
plPL("Błąd komunikacji; proces = %s")
roRO("Erare de comunicare, procesul = %s")
ruRU("Ошибка коммуникации; процесс = %s")
skSK("Chyba spojenia; proces = %s")
srSP("")
trTR("İletişim hatası; işlem = %s")
zhCN("通信错误; 进城 = %s")
zhTW("通訊錯誤；行程 = %s")

T_("Missing command line (host = %s).")
csCZ("Chybí příkazová řádka (hostitel = %s).")
deDE("Fehlende Befehlszeile (Host = %s)")
esES("L�nea de comandos ausente (host=%s).")
fiFI("Puuttuva komentorivi (isäntä = %s).")
frFR("Ligne de commande manquante (hôte = %s).")
huHU("Hiányzó parancssor (gép = %s)")
itIT("")
nlNL("Missende commando regel (host = %s)")
plPL("Brak linii poleceń (host = %s).")
roRO("Linie de comandă negasită (host = %s)")
ruRU("Не указана командная строка (хост = %s)")
skSK("Chýba príkazový riadok (hostiteľ = %s).")
srSP("")
trTR("Eksik komut satırı (Host = %s).")
zhCN("缺少命令行(主机 = %s).")
zhTW("缺少命令列(主機 = %s).")


// Obsolete

T_("Error reading data from socket: commuication port closed.")
csCZ("Chyba při čtení dat ze socketu: komunikační kanál byl uzavřen.")
deDE("Socketfehler beim Lesen der Daten: Port wurde geschlossen.")
esES("Error leyendo datos de socket: puerto de comunicaci�n cerrado.")
fiFI("Virhe socketista luettaessa: kommunikointiportti suljettu.")
frFR("Erreur de lecture sur la socket: port de communication fermé")
huHU("Hiba az adatok socket-ről olvasásakor:  kommunikációs port zárva.")
itIT("")
nlNL("Fout tijdens lezen data vanuit socket: communicatie poort gesloten.")
plPL("")
roRO("Eroare la citire din soclu: portul de comunicare este închis.")
ruRU("Ошибка чтения данных из сокета: порт связи "
     "закрыт")
skSK("Chyba pri čítaní dát zo soketu: komunikačný kanál bol uzatvorený.")
srSP("")
trTR("Soket okuma hatası: bağlantı kesildi.")
zhCN("从socket读数据错误:通信端口关闭")
zhTW("讀取資料錯誤：通訊埠已關閉.")

T_("Cannot open socket %s:%d: %s")
csCZ("Nelze otevřít socket %s:%d: %s")
deDE("Socket %s:%d: %s kann nicht geöffnet werden.")
esES("No puedo abrir socket %s:%d: %s")
fiFI("Socketia ei voi avata %s:%d: %s")
frFR("Impossible d'ouvrir la socket %s:%d: %s")
huHU("Sikertelen socket-megnyitás %s:%d: %s")
itIT("")
nlNL("Kan socket niet openen %s:%d: %s")
plPL("")
roRO("Nu se poate deschide soclul %s:%d: %s")
ruRU("Не могу открыть сокет %s:%d: %s")
skSK("Nemožno otvoríť soket %s:%d: %s")
srSP("")
trTR("Hata: Soket açılamadı. %s:%d: %s")
zhCN("不能打开socket %s:%d: %s")
zhTW("無法開啟socket %s:%d: %s")
