#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// httpsrv.cpp

T_("If you're not redirected automatically please use %s.")
csCZ("Pokud nebudete automaticky přesměrováni, použijte prosím %s.")
deDE("Wenn Sie nicht automatisch weitergeleitet werden, benutzen Sie bitte %s")
esES("Si no es redirigido automáticamente, utilice %s.")
fiFI("Jos toiminto ei etene automaattisesti, käytä %s.")
frFR("Si vous n'êtes pas automatiquement redirigé, veuillez utiliser %s.")
huHU("Ha nem történik automatikus átirányítás használja %s")
itIT("")
plPL("Jeśli nie zostałeś automatycznie przekierowany użyj proszę %s.")
roRO("Dacă nu sunteţi redirectaţi automat folosiţi %s.")
ruRU("Если Вы не перенаправлены автоматически, "
     "пожайлуста, используйте %s.")
srSP("")
trTR("Eğer otomatik olarak yönlendirlmediyseniz lütfen %s bağlantısını "
     "kullanın.")
zhCN("如果没有自动重定向,请使用%s.")
zhTW("")

T_("this link")
csCZ("tento odkaz")
deDE(" diesen Link.")
esES("este enlace")
fiFI("tämä linkki")
frFR("ce lien")
huHU("ezt a hivatkozást")
itIT("")
plPL("tego odnośnika")
roRO("acest link")
ruRU("эту ссылку")
srSP("")
trTR("bu bağlantı")
zhCN("本链接")
zhTW("")

T_("Redirection to another web address")
csCZ("Přesměrování na jinou adresu")
deDE("Weiterleitung zu einer anderen Netzadresse")
esES("Redirección a otra dirección web")
fiFI("Reititys toiseen web -osoitteeseen")
frFR("Redirection vers une autre adresse web")
huHU("Átirányítás másik webcímre")
itIT("")
plPL("Przekierowanie do innej strony")
roRO("Redirectare spre o altă adresă web")
ruRU("Перенаправление на другой веб адрес")
srSP("")
trTR("başka bir ağ adresine yönlendiriliyor")
zhCN("重定向到其他web地址")
zhTW("")

T_("... (total length: %d bytes)")
csCZ("... (celková délka: %d bytů)")
deDE("... (Gesamtgröße: %d Bytes)")
esES("... (tamaño total: %d bytes)")
fiFI("... (kokonaispituus: %d tavua)")
frFR("(longueur totale : %d octets")
huHU("... (teljes hossz: %d bájt)")
itIT("")
plPL("... (całkowita długość: %d bajtów)")
roRO("... (lungime totală: %d bytes)")
ruRU("... (полный размер: %d байт)")
srSP("")
trTR("... (toplam boyut: %d byte)")
zhCN("... (总长: %d 字节)")
zhTW("")

T_("The web server is unable to satisfy your request:\n<p>\n")
csCZ("Internetový server nebyl schopen vyřídit požadavek:\n<p>\n")
deDE("Der Netzserver kann Ihre Anforderung nicht erfüllen:\n<p>\n")
esES("El servidor web no puede satisfacer su solicitud:\n<p>\n")
fiFI("Web palvelin ei kykene täyttämään pyyntöäsi:\n<p>\n")
frFR("Ce serveur web ne peut pas satisfaire votre requête :\n<p>\n")
huHU("A webkiszolgáló nem tudja teljesíteni a kérést:\n<p>\n")
itIT("")
plPL("Ten serwer sieciowy nie jest w stanie odpowiedzieć na twoje żądanie:\n"
     "<p>\n")
roRO("Serverul nu este în masură să va satisfacă cererea:\n<p>\n")
ruRU("Этот веб сервер не может удовлетворить "
     "Ваш запрос:\n<p>\n")
srSP("")
trTR("Ağ sunucusu isteğinizi yerine getiremiyor:\n<p>\n")
zhCN("web服务器不支持您的请求:\n<p>\n")
zhTW("")

T_("Reason:")
csCZ("Důvod chyby: ")
deDE("Grund:")
esES("Razón:")
fiFI("Syy:")
frFR("Raison :")
huHU("Ok:")
itIT("")
plPL("Powód:")
roRO("Motiv:")
ruRU("Причина:")
srSP("")
trTR("Sebep:")
zhCN("原因:")
zhTW("")

T_("Detailed query data:")
csCZ("Detailní informace o dotazu:")
deDE("Genaue Abfragedaten:")
esES("Datos detallados de consulta:")
fiFI("Yksityiskohtainen kysely tieto:")
frFR("Données détaillées de la requête :")
huHU("Részletes lekérési adatok:")
itIT("")
plPL("Szczegółowe dane zapytania:")
roRO("Date detaliate despre cerere:")
ruRU("Детали запроса:")
srSP("")
trTR("Detaylı sorgulama verileri:")
zhCN("详细查询数据")
zhTW("")

T_("Web server error")
csCZ("Chyba internetového serveru")
deDE("Netzserverfehler")
esES("Error de servidor Web")
fiFI("Web -palvelin virhe")
frFR("Erreur du serveur web")
huHU("Webkiszolgáló hiba")
itIT("")
plPL("Błąd serwera sieciowego")
roRO("Eroare de server web")
ruRU("Ошибка веб сервера")
srSP("")
trTR("Sunucu hatası")
zhCN("Web服务器错误")
zhTW("")


// httpcli.cpp

T_("%s:%d receiving headers timed out")
csCZ("%s:%d vypršel časový limit při načítání hlaviček")
deDE("%s:%d Timeout beim Headerempfang")
esES("%s:%d recibiendo encabezados, tiempo de espera agotado")
fiFI("%s:%d headerien vastaanotto aikakatkaistu")
frFR("%s:%d temps dépassé à la réception de l'en-tête")
huHU("%s:%d időtúllépés fejlécek fogadása közben")
itIT("")
plPL("%s:%d przekroczono czas odbierania nagłówka")
roRO("%s:%d obținerea antetelor a depășit limita de timp")
ruRU("%s:%d превишен интервал ожидания при получении "
     "заголовков")
srSP("")
trTR("%s:%d: Üstbilgi alışverişi zaman aşımına uğradı.")
zhCN("%s:%d 接收头超时")
zhTW("")

T_("%s:%d: connecting to host timed out")
csCZ("%s:%d: vypršel časový limit pro připojení k hostiteli")
deDE("%s:%d Timeout bei der Verbindungsaufnahme mit dem Server")
esES("%s:%d: tiempo de espera agotado conectando al host")
fiFI("%s:%d: kytkeytyminen isäntään aikakatkaistu")
frFR("%s:%d : l'hôte n'a pas accepté la connexion dans le temps imparti")
huHU("%s:%d: időtúllépés a szerverhez kapcsolódás közben")
itIT("")
plPL("%s:%d przekroczono czas łączenia się z hostem")
roRO("%s:%d: depășire de limită de timp la conectare")
ruRU("%s:%d превишен интервал ожидания при подключении "
     "к серверу")
srSP("")
trTR("%s:%d: Sunucu bağlantısı zaman aşımına uğradı")
zhCN("%s:%d: 连接到主机超时")
zhTW("")

T_("%s:%d: timed out sending request to server")
csCZ("%s:%d: vypršel časový limit při odesílání požadavku")
deDE("%s:%d Timeout beim Übermitteln der Abfrage an den Server")
esES("%s:%d: tiempo de espera agotado enviado respuesta a servidor")
fiFI("%s:%d: palvelupyynnön lähettäminen palvelimelle aikakatkaistu")
frFR("%s:%d : le serveur n'a pas répondu dans le temps imparti")
huHU("%s:%d: időtúllépés a kérés elküldésénél")
itIT("")
plPL("%s:%d: przekroczono czas wysyłania żądania do serwera")
roRO("%s:%d: depășire de limită de timp la trimitere cerere spre server")
ruRU("%s:%d: таймаут отправки запроса на сервер")
srSP("")
trTR("%s:%d: İstek zaman aşımına uğradı")
zhCN("%s:%d: 发送请求到服务器超时")
zhTW("")

T_("%s:%d: invalid server response: %s")
csCZ("%s:%d: neplatná odezva ze serveru: %s")
deDE("%s:%d: Ungültige Serverantwort: %s")
esES("%s:%d: respuesta inválida del servidor: %s")
fiFI("%s:%d: virheellinen palvelinvastine: %s")
frFR("%s:%d : réponse du serveur invalide : %s")
huHU("%s:%d: érvénytelen kiszolgálói válasz")
itIT("")
plPL("%s:%d: niepoprawna odpowiedź serwera: %s")
roRO("%s:%d: răspuns invalid de la server: %s")
ruRU("%s:%d: неправильный ответ сервера: %s")
srSP("")
trTR("%s:%d: Sunucudan gelen yanıt geçersiz")
zhCN("%s:%d: 无效服务器反应: %s")
zhTW("")

T_("%s:%d: maximum data length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka dat (%d B)")
deDE("%s:%d: Maximale Datenlänge überschritten (%d B)")
esES("%s:%d: longitud de datos máxima excedida (%d B)")
fiFI("%s:%d: datan enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale des données (%d O)")
huHU("%s:%d: maximális adathossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalny rozmiar danych (%d B)")
roRO("%s:%d: dimeniunea maximă a datelor a fost depășită (%d B)")
ruRU("%s:%d: превышен максимальный размер данных "
     "(%d B)")
srSP("")
trTR("%s:%d: maksimum veri boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大数据长度(%d B)")
zhTW("")

T_("%s:%d: maximum header length exceeded (%d B)")
csCZ("%s:%d: byla překročena maximální délka hlaviček (%d B)")
deDE("%s:%d: Maximale Headerlänge überschritten (%d B)")
esES("%s:%d: longitud de encabezado máxima excedida (%d B)")
fiFI("%s:%d: headerin enimmäispituus ylitetty (%d B)")
frFR("%s:%d : dépassement de la longueur maximale de l'en-tête (%d O)")
huHU("%s:%d: maximális fejléchossz túllépése (%d B)")
itIT("")
plPL("%s:%d: przekroczono dopuszczalną długość nagłówka (%d B)")
roRO("%s:%d: dimeniunea maximă a antetului a fost depășită (%d B)")
ruRU("%s:%d: превышен максимальный размер заголовка "
     "(%d B)")
srSP("")
trTR("%s:%d:Maksimum üstbilgi boyutu aşıldı (%d B)")
zhCN("%s:%d: 超出了最大头长度(%d B)")
zhTW("")

T_("%s:%d: timed out when receiving server response")
csCZ("%s:%d: vypršel časový limit při načítání odpovědi")
deDE("%s:%d: Timeout beim Empfang der Serverantwort")
esES("%s:%d: tiempo de espera agotado esperando respuesta del servidor")
fiFI("%s:%d: palvelinvastineen vastaanotto aikakatkaistu")
frFR("%s%d : temps dépassé à la réception de la réponse du serveur")
huHU("%s:%d: időtúllépés a kiszolgáló válaszára várva")
itIT("")
plPL("%s:%d: przekroczono czas oczekiwania na odpowiedź serwera")
roRO("%s:%d: limită de timp depășită la primirea răspunsului de la server")
ruRU("%s:%d: таймаут при приёме ответа от сервера")
srSP("")
trTR("%s:%d: Sunucudan  yanıt beklenirken zaman aşımı meydana geldi")
zhCN("%s:%d: 接收服务器反应时超时")
zhTW("")

T_("Maximum content size exceeded: %d")
csCZ("Překročena maximální povolená délka datového obsahu: %d")
deDE("Maximaler Datenumfang überschritten: %d")
esES("Tamaño de contenido máximo excedido: %d")
fiFI("Sisällön enimmäiskoko ylitetty: %d")
frFR("")
huHU("A maximális tartalomhossz túllépve: %d")
itIT("")
plPL("Przekroczono dopuszczalny rozmiar zawartości: %d")
roRO("Dimeniunea maximă a conținutului depășită: %d")
ruRU("Превышен максимальный размер содержимого: "
     "%d")
srSP("")
trTR("Maksimum içerik boyutu aşıldı: %d")
zhCN("最大内容长度超出:%d")
zhTW("")

T_("Partial input: %d out of %d")
csCZ("Přijata neúplná data: %d z %d")
deDE("Unvollständiger Empfang: %d von %d")
esES("Entrada parcial: %d de %d")
fiFI("Osittainen syöte: %d / %d")
frFR("Saisie partielle : %d de %d")
huHU("Részleges beolvasás: %d a %d-ból")
itIT("")
plPL("Dane częściowe: %d z %d")
roRO("Intrări parțiale: %d din %d")
ruRU("Частичный ввод: %d из %d")
srSP("")
trTR("Kısmi girdi: %d/%d")
zhCN("部分输入: %d out of %d")
zhTW("")


// smtp.cpp

T_("Communication Failure: Timeout.")
csCZ("Porucha komunikace: vypršel časový limit.")
deDE("Kommunikationsfehler: Timeout")
esES("Fallo de comunicación: Tiempo de espera agotado.")
fiFI("Viestintävirhe: Aikakatkaisu.")
frFR("")
huHU("Kommunikációs hiba: Időtúllépés")
itIT("")
plPL("")
roRO("Eroare în comunicare: Limită de timp depășită.")
ruRU("Ошибка связи. Таймаут.")
srSP("")
trTR("Bağlantı başarısız: Zaman aşımı.")
zhCN("")
zhTW("")

T_("Error writing data to socket: communication port closed.")
csCZ("Chyba při zápisu dat do socketu: komunikační kanál byl uzavřen.")
deDE("Socketfehler beim Schreiben der Daten: Port wurde geschlossen.")
esES("Error escribiendo datos de socket: puerto de comunicación cerrado.")
fiFI("Virhe socketiin kirjoitettaessa: kommunikointiportti suljettu.")
frFR("")
huHU("Hiba az adatok socket-re írásakor: kommunikációs port zárva.")
itIT("")
plPL("")
roRO("Eroare la scriere în soclu: portul de comunicare este închis.")
ruRU("Ошибка посылки данных в сокет: порт связи "
     "закрыт")
srSP("")
trTR("Sokete yazma hatası: bağlantı kesildi.")
zhCN("")
zhTW("")

T_("Error writing data to socket, error code: ")
csCZ("Chyba při zápisu dat do socketu, kód chyby: ")
deDE("Socketfehler beim Schreiben der Daten, Fehlercode: ")
esES("Error escribiendo datos a socket, código de error: ")
fiFI("Virhe socketiin kirjoitettaessa, virhe koodi: ")
frFR("")
huHU("Hiba az adatok socket-re írásakor, hibakód: ")
itIT("")
plPL("")
roRO("Eroare la scriere în soclu, cod:")
ruRU("Ошибка посылки данных в сокет: код оибки: ")
srSP("")
trTR("Sokete yazma hatası meydana geldi. Hata kodu: ")
zhCN("")
zhTW("")

T_("Error reading data from socket: communication port closed.")
csCZ("")
deDE("")
esES("")
fiFI("")
frFR("")
huHU("")
itIT("")
plPL("")
roRO("")
ruRU("Ошибка чтения данных из сокета: порт связи "
     "закрыт")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Error reading socket, error code: %s")
csCZ("")
deDE("")
esES("")
fiFI("")
frFR("")
huHU("")
itIT("")
plPL("")
roRO("")
ruRU("Ошибка чтения данных из сокета, код ошибки: "
     "%s")
srSP("")
trTR("")
zhCN("")
zhTW("")

T_("Host not set.")
csCZ("Hostitel není zadán.")
deDE("Host nicht eingerichtet")
esES("Host no especificado.")
fiFI("Isäntää ei ole asetettu.")
frFR("")
huHU("A távoli gép nincs megadva.")
itIT("")
plPL("")
roRO("Host-ul nu este ales.")
ruRU("Сервер не определен")
srSP("")
trTR("Host hazır değil.")
zhCN("")
zhTW("")

T_("Recipient not set.")
csCZ("Není zadán příjemce.")
deDE("Empfänger nicht eingerichtet")
esES("Recipiente no especificado.")
fiFI("Vastaanottajaa ei ole asetettu.")
frFR("")
huHU("A fogadó gép nincs megadva.")
itIT("")
plPL("")
roRO("Receptorul nu este ales")
ruRU("Получатель не определен")
srSP("")
trTR("Alıcı hazır değil.")
zhCN("")
zhTW("")


// sproc.cpp

T_("pipe() error; error code = %d")
csCZ("chyba pipe(); kód chyby = %d")
deDE("pipe()-Fehler; Fehlercode = %d")
esES("error en pipe(); codigo = %d")
fiFI("pipe() virhe; virhe koodi = %d")
frFR("erreur pipe(); code d'erreur = %d")
huHU("pipe() hiba; hibakód = %d")
itIT("")
plPL("błąd pipe(); kod błędu = %d")
roRO("eroare pipe(); cod = %d")
ruRU("ошибка pipe(); код ошибки = %d")
srSP("")
trTR("pipe() hatası; hata kodu = %d")
zhCN("pipe() error; error code = %d")
zhTW("")

T_("fork() error; error code = %d")
csCZ("chyba fork(); kód chyby = %d")
deDE("fork()-Fehler; Fehlercode = %d")
esES("error en fork(); codigo = %d")
fiFI("fork() virhe; virhe koodi = %d")
frFR("erreur fork(); code d'erreur = %d")
huHU("fork() hiba; hibakód = %d")
itIT("")
plPL("błąd fork(); kod błędu = %d")
roRO("eroare fork(): cod = %d")
ruRU("ошибка fork(); код ошибки = %d")
srSP("")
trTR("fork() hatası; hata kodu = %d")
zhCN("fork() error; error code = %d")
zhTW("")

T_("Opening host '%s' / port %d failed, error = %s")
csCZ("Připojování k hostiteli '%s' / port %d selhalo, chyba = %s")
deDE("Zugriff auf den Host '%s' / port %d fehlgeschlagen, Fehler = %s")
esES("Abriendo host '%s' / falló puerto %d, error = %s")
fiFI("Kytkentä isäntään '%s' / portti %d epäonnistui, virhe = %s")
frFR("Erreur d'ouverture de '%s' / port %d, erreur = %s")
huHU("A '%s' gép / %d port megnyitása sikertelen, hiba = %s")
itIT("")
plPL("Łączenie z hostem '%s' / port %d nie powiodło się, błąd = %s")
roRO("Se deschide host-ul '%s' / eșuare pe portul %d, eroare = %s")
ruRU("Подсоединение к хосту '%s' / порту %d не удачно, "
     "ошибка = %s")
srSP("")
trTR("'%s' hostuna '%d' portundan bağlanma girişi başarısız oldu. Hata "
     "= %s")
zhCN("Opening host '%s' / port %d failed, error = %s")
zhTW("")

T_("Error running process: %s\nCommand: %s")
csCZ("Chyba při spouštění procesu: %s\nPříkaz: %s")
deDE("Fehler beim Ausführen des Prozesses: %s\nBefehl: %s")
esES("Error ejecutando proceso: %s\nComando: %s")
fiFI("Virhe prosessin suorittamisessa: %s\nCommand: %s")
frFR("Erreur d'exécution du programme : %s\nCommande : %s")
huHU("Hiba a %s folyamat\n%s parancs futtatásánál")
itIT("")
plPL("Błąd uruchamiania procesu: %s\nKomenda: %s")
roRO("Eroare execuție proces: %s\nComanda: %s")
ruRU("Ошибка при запуске процесса: %s\nКоманда: "
     "%s")
srSP("")
trTR("'%s' işleminin çalıştırılması sırasında hata oluştu\nKomut: "
     "%s")
zhCN("运行进城错误:%s\n命令: %s")
zhTW("")

T_("Communication error; process = %s")
csCZ("Chyba spojení; proces = %s")
deDE("Kommunikationsfehler; Prozess = %s")
esES("Error de comunicación; proceso = %s")
fiFI("Kommunikointi virhe; prosessi = %s")
frFR("Erreur de communication ; processus = %s")
huHU("Kommunikációs hiba; folyamat = %s")
itIT("")
plPL("Błąd komunikacji; proces = %s")
roRO("Erare de comunicare, procesul = %s")
ruRU("Ошибка коммуникации; процесс = %s")
srSP("")
trTR("İletişim hatası; işlem = %s")
zhCN("通信错误; 进城 = %s")
zhTW("")

T_("Missing command line (host = %s).")
csCZ("Chybí příkazová řádka (hostitel = %s).")
deDE("Fehlende Befehlszeile (Host = %s)")
esES("Línea de comandos ausente (host=%s).")
fiFI("Puuttuva komentorivi (isäntä = %s).")
frFR("Ligne de commande manquante (hôte = %s).")
huHU("Hiányzó parancssor (gép = %s)")
itIT("")
plPL("Brak linii poleceń (host = %s).")
roRO("Linie de comandă negasită (host = %s)")
ruRU("Не указана командная строка (хост = %s)")
srSP("")
trTR("Eksik komut satırı (Host = %s).")
zhCN("缺少命令行(主机 = %s).")
zhTW("")


// Obsolete

T_("Error reading data from socket: commuication port closed.")
csCZ("Chyba při čtení dat ze socketu: komunikační kanál byl uzavřen.")
deDE("Socketfehler beim Lesen der Daten: Port wurde geschlossen.")
esES("Error leyendo datos de socket: puerto de comunicación cerrado.")
fiFI("Virhe socketista luettaessa: kommunikointiportti suljettu.")
frFR("")
huHU("Hiba az adatok socket-ről olvasásakor:  kommunikációs port zárva.")
itIT("")
plPL("")
roRO("Eroare la citire din soclu: portul de comunicare este închis.")
ruRU("Ошибка чтения данных из сокета: порт связи "
     "закрыт")
srSP("")
trTR("Soket okuma hatası: bağlantı kesildi.")
zhCN("")
zhTW("")

T_("Cannot open socket %s:%d: %s")
csCZ("Nelze otevřít socket %s:%d: %s")
deDE("Socket %s:%d: %s kann nicht geöffnet werden.")
esES("No puedo abrir socket %s:%d: %s")
fiFI("Socketia ei voi avata %s:%d: %s")
frFR("")
huHU("Sikertelen socket-megnyitás %s:%d: %s")
itIT("")
plPL("")
roRO("Nu se poate deschide soclul %s:%d: %s")
ruRU("Не могу открыть сокет %s:%d: %s")
srSP("")
trTR("Hata: Soket açılamadı. %s:%d: %s")
zhCN("")
zhTW("")
