#define WEBKEY(x) x

K_BACK       = WEBKEY(100) + K_DELTA,
K_BACKSPACE  = WEBKEY(101) + K_DELTA,

//handled extra in fbKEYtoK
K_TAB        = 9, //SDLK_TAB,

K_SPACE      = 32, //SDLK_SPACE,

K_RETURN     = 13, //SDLK_RETURN,
K_ENTER      = K_RETURN,

K_SHIFT_KEY  = WEBKEY(0) + K_DELTA,
K_CTRL_KEY   = WEBKEY(1) + K_DELTA,
K_ALT_KEY    = WEBKEY(2) + K_DELTA,
K_CAPSLOCK   = WEBKEY(3) + K_DELTA,
K_ESCAPE     = WEBKEY(4) + K_DELTA,
K_PRIOR      = WEBKEY(5) + K_DELTA,
K_PAGEUP     = WEBKEY(6) + K_DELTA,
K_NEXT       = WEBKEY(7) + K_DELTA,
K_PAGEDOWN   = WEBKEY(8) + K_DELTA,
K_END        = WEBKEY(9) + K_DELTA,
K_HOME       = WEBKEY(10) + K_DELTA,
K_LEFT       = WEBKEY(11) + K_DELTA,
K_UP         = WEBKEY(12) + K_DELTA,
K_RIGHT      = WEBKEY(13) + K_DELTA,
K_DOWN       = WEBKEY(14) + K_DELTA,
K_INSERT     = WEBKEY(15) + K_DELTA,
K_DELETE     = WEBKEY(16) + K_DELTA,

K_NUMPAD0    = WEBKEY(17) + K_DELTA,
K_NUMPAD1    = WEBKEY(18) + K_DELTA,
K_NUMPAD2    = WEBKEY(19) + K_DELTA,
K_NUMPAD3    = WEBKEY(20) + K_DELTA,
K_NUMPAD4    = WEBKEY(21) + K_DELTA,
K_NUMPAD5    = WEBKEY(22) + K_DELTA,
K_NUMPAD6    = WEBKEY(23) + K_DELTA,
K_NUMPAD7    = WEBKEY(24) + K_DELTA,
K_NUMPAD8    = WEBKEY(25) + K_DELTA,
K_NUMPAD9    = WEBKEY(26) + K_DELTA,
K_MULTIPLY   = WEBKEY(27) + K_DELTA,
K_ADD        = WEBKEY(28) + K_DELTA,
K_SEPARATOR  = WEBKEY(29) + K_DELTA,
K_SUBTRACT   = WEBKEY(30) + K_DELTA,
K_DECIMAL    = WEBKEY(31) + K_DELTA,
K_DIVIDE     = WEBKEY(32) + K_DELTA,
K_SCROLL     = WEBKEY(33) + K_DELTA,

K_F1         = WEBKEY(34) + K_DELTA,
K_F2         = WEBKEY(35) + K_DELTA,
K_F3         = WEBKEY(36) + K_DELTA,
K_F4         = WEBKEY(37) + K_DELTA,
K_F5         = WEBKEY(38) + K_DELTA,
K_F6         = WEBKEY(39) + K_DELTA,
K_F7         = WEBKEY(40) + K_DELTA,
K_F8         = WEBKEY(41) + K_DELTA,
K_F9         = WEBKEY(42) + K_DELTA,
K_F10        = WEBKEY(43) + K_DELTA,
K_F11        = WEBKEY(44) + K_DELTA,
K_F12        = WEBKEY(45) + K_DELTA,

K_A          = WEBKEY(46) + K_DELTA,
K_B          = WEBKEY(47) + K_DELTA,
K_C          = WEBKEY(48) + K_DELTA,
K_D          = WEBKEY(49) + K_DELTA,
K_E          = WEBKEY(50) + K_DELTA,
K_F          = WEBKEY(51) + K_DELTA,
K_G          = WEBKEY(52) + K_DELTA,
K_H          = WEBKEY(53) + K_DELTA,
K_I          = WEBKEY(54) + K_DELTA,
K_J          = WEBKEY(55) + K_DELTA,
K_K          = WEBKEY(56) + K_DELTA,
K_L          = WEBKEY(57) + K_DELTA,
K_M          = WEBKEY(58) + K_DELTA,
K_N          = WEBKEY(59) + K_DELTA,
K_O          = WEBKEY(60) + K_DELTA,
K_P          = WEBKEY(61) + K_DELTA,
K_Q          = WEBKEY(62) + K_DELTA,
K_R          = WEBKEY(63) + K_DELTA,
K_S          = WEBKEY(64) + K_DELTA,
K_T          = WEBKEY(65) + K_DELTA,
K_U          = WEBKEY(66) + K_DELTA,
K_V          = WEBKEY(67) + K_DELTA,
K_W          = WEBKEY(68) + K_DELTA,
K_X          = WEBKEY(69) + K_DELTA,
K_Y          = WEBKEY(70) + K_DELTA,
K_Z          = WEBKEY(71) + K_DELTA,
K_0          = WEBKEY(72) + K_DELTA,
K_1          = WEBKEY(73) + K_DELTA,
K_2          = WEBKEY(74) + K_DELTA,
K_3          = WEBKEY(75) + K_DELTA,
K_4          = WEBKEY(76) + K_DELTA,
K_5          = WEBKEY(77) + K_DELTA,
K_6          = WEBKEY(78) + K_DELTA,
K_7          = WEBKEY(79) + K_DELTA,
K_8          = WEBKEY(80) + K_DELTA,
K_9          = WEBKEY(81) + K_DELTA,

K_CTRL_LBRACKET  = K_CTRL|219|K_DELTA,
K_CTRL_RBRACKET  = K_CTRL|221|K_DELTA,
K_CTRL_MINUS     = K_CTRL|0xbd|K_DELTA,
K_CTRL_GRAVE     = K_CTRL|0xc0|K_DELTA,
K_CTRL_SLASH     = K_CTRL|0xbf|K_DELTA,
K_CTRL_BACKSLASH = K_CTRL|0xdc|K_DELTA,
K_CTRL_COMMA     = K_CTRL|0xbc|K_DELTA,
K_CTRL_PERIOD    = K_CTRL|0xbe|K_DELTA,
K_CTRL_SEMICOLON = K_CTRL|0xbe|K_DELTA,
K_CTRL_EQUAL     = K_CTRL|0xbb|K_DELTA,
K_CTRL_APOSTROPHE= K_CTRL|0xde|K_DELTA,

K_BREAK      = WEBKEY(82) + K_DELTA, // Is it really?
