TABLE_(CUSTOMERS)
   INT_     (ID) PRIMARY_KEY AUTO_INCREMENT
   STRING_  (NAME, 100)
   STRING_  (ADDRESS, 100)
   STRING_  (CSZ, 70)
   STRING_	(PHONE1,20)
   STRING_	(PHONE2,20)
   STRING_	(UNIT_INFO,400)
   STRING_	(NOTES,400)
   BOOL_	(CURRENT)
   BOOL_	(SERVICE)
END_TABLE

TABLE_(JOBS)
	INT_	(JOBID) PRIMARY_KEY
	INT_	(CUSTOMER_ID)
	STRING_	(DONEDATE, 25)
	STRING_	(DESCRIPTION, 200)
	STRING_	(COST, 25)
END_TABLE
