#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// Oci7.cpp

T_("Error loading OCI7 Oracle database client library.")
csCZ("Nelze nalézt dynamickou knihovnu OCI7 pro spojení s Oracle")
deDE("Fehler beim Laden der OCI7 Client Bibliothek.")
esES("Error cargando la librer�a OCI7 del cliente de base de datos Oracle")
fiFI("Virhe ladattaessa OCI7 Oracle tietokanta-asiakas kirjastoa.")
frFR("Erreur de chargement de la librairie OC17 Oracle database client")
huHU("Hiba az OCI7 Oracle database client library betöltése közben.")
nlNL("")
roRO("Eroare la încărcare bibliotecii client bază de date OCI7")
ruRU("Ошибка загрузки клиентской библиотеки "
     "базы данных OCI7 Oracle")
skSK("Nemožno nájsť dynamickú knižnicu OCI7 pre spojenie s Oracle")
trTR("Hata: OCI7 Oracle veritabanı istemci kütüphanesi (Oracle database client "
     "library) yüklenemedi.")
zhTW("載入OCI7 Oracle資料庫用戶端函式庫時發生錯誤.")

T_("Connecting to server")
csCZ("Navazuji spojení")
deDE("Verbindungsaufbau mit Server")
esES("Conectando al servidor")
fiFI("Yhdistää palvelimeen")
frFR("Connection au serveur")
huHU("Kapcsolódás a szerverhez")
nlNL("")
roRO("Se onectează la server")
ruRU("Подключение к серверу")
skSK("Nadväzovanie spojenia")
trTR("Sunucuya bağlanıyor")
zhTW("連接到伺服器")

T_("Connecting to database server")
csCZ("Spojuji s databází")
deDE("Verbindsaufbau mit Datenbank Server")
esES("Conectando al servidor de la base de datos")
fiFI("Yhdistää tietokantapalvelimeen")
frFR("connection au serveur de database")
huHU("Kapcsolódás az adatbázis-szerverhez")
nlNL("")
roRO("Se conectează la server bază de date")
ruRU("Подключение к SQL серверу")
skSK("Pripájanie k databáze")
trTR("Veritabanı sunucusuna bağlanıyor")
zhTW("連接到資料庫伺服器")


// Oci8.cpp

T_("Error running OCI8 Oracle connection dynamic library.")
csCZ("Nelze spustit dynamickou knihovnu OCI8 pro připojení k databázi Oracle.")
deDE("Fehler bei der Ausführung der dynamischen OCI8 Oracle Verbindungsbibliothek.")
esES("Error ejecutando la conexi�n a la librer�a din�mica OCI8 de Oracle")
fiFI("Virhe käytettäessä dynaamista OCI8 Oracle yhteyskirjastoa.")
frFR("Erreur d'exécution de la librairie dynamique OC18 Oracle connection")
huHU("Hiba az OCI8 Oracle connection dynamic library futtatása közben.")
nlNL("")
roRO("Eroare la rularea bibliotecii dinamice de conectare la OCI8")
ruRU("Ошибка запуска динамической библиотеки "
     "подключения OCI8 Oracle")
skSK("Nemožno spustiť dynamickú knižnicu OCI8 pre pripojenie k databáze "
     "Oracle.")
trTR("Hata: OCI8 Oracle connection dynamic library'sinin calıştırılması "
     "sırasında bir hata meydana geldi.")
zhTW("執行OCI8 Oracle連接動態函式庫時發生錯誤.")

T_("Unknown error.")
csCZ("Neznámá chyba.")
deDE("Unbekannter Fehler.")
esES("Error desconocido.")
fiFI("Tuntematon virhe.")
frFR("Erreur inconnue")
huHU("Ismeretlen hiba.")
nlNL("")
roRO("Eroare necunoscută.")
ruRU("Неизвестная ошибка")
skSK("Neznáma chyba.")
trTR("Bilinmeyen hata.")
zhTW("未知的錯誤.")

T_("(unknown error)")
csCZ("(neznámá chyba)")
deDE("(Unbekannter Fehler)")
esES("(error desconocido)")
fiFI("(tuntematon virhe)")
frFR("(Erreur inconnue)")
huHU("(ismeretlen hiba)")
nlNL("")
roRO("(eroare necunoscută)")
ruRU("(неизвестная ошибка)")
skSK("(neznáma chyba)")
trTR("(bilinmeyen hata)")
zhTW("(未知的錯誤)")

T_("<not supplied>")
csCZ("<není zadáno>")
deDE("<nicht geliefert>")
esES("<no suministrado>")
fiFI("<ei ole annettu>")
frFR("<non fournis>")
huHU("<nincs megadva>")
nlNL("")
roRO("<nu a fost specificat>")
ruRU("<не поддерживается>")
skSK("<nie je zadané>")
trTR("<sağlanmamış>")
zhTW("<沒有支援>")

T_("Error initializing connection")
csCZ("Chyba při navazování spojení")
deDE("Fehler beim Verbindungsaufbau")
esES("Error iniciando la conexi�n")
fiFI("Virhe yhteyden alustamisessa")
frFR("Erreur d'initialisation de la connection")
huHU("Hiba a kapcsolat inicializálása közben")
nlNL("")
roRO("Eroare la inițializarea conexiunii")
ruRU("Ошибка запуска соединения")
skSK("Chyba pri nadväzovaní spojenia")
trTR("Bağlantı hatası")
zhTW("初始化連線錯誤")

T_("OCI8 connection")
csCZ("Spojení OCI8")
deDE("OCI8 Verbindung")
esES("Conexi�n OCI8")
fiFI("OCI8 yhteys")
frFR("connection OCI8")
huHU("OCI8 kapcsolat")
nlNL("")
roRO("Conexiune OCI8")
ruRU("OCI8 соединение")
skSK("Spojenie OCI8")
trTR("OCI8 bağlantısı")
zhTW("連接 OCI8")

T_("Closing reference cursor")
csCZ("Zavírám referenční kurzor")
deDE("")
esES("Cerrando el cursor de referencia")
fiFI("Suljetaan referenssikursoria")
frFR("Fermeture référence curseur")
huHU("Referencia-kurzor lezárása")
nlNL("")
roRO("Se închide cursorul de referință")
ruRU("Закрыть курсор связи")
skSK("Uzatváram referenčný kurzor")
trTR("Closing reference cursor")
zhTW("Closing reference cursor")

T_("Error initializing OCI8 library (%s)")
csCZ("Chyba při inicializaci OCI8")
deDE("Fehler beim Initialisieren der OCI8 Bibliothek (%s)")
esES("Error iniciando la librer�a OCI8 (%s)")
fiFI("Virhe alustettaessa OCI8 kirjastoa (%s)")
frFR("Erreur d'initialisation de la librairie OCI8 ( %s )")
huHU("Hiba az OCI8 library inicializálása közben (%s)")
nlNL("")
roRO("Eroare la inițializarea bibliotecii OCI8 (%s)")
ruRU("Ошибка инициализации библиотеки OCI8 (%s)")
skSK("Chyba pri inicializácii OCI8")
trTR("")
zhTW("初始化OCI8函式庫 (%s)錯誤")

T_("Connecting to Oracle database.")
csCZ("Připojování k databázi Oracle")
deDE("Verbindungsaufbau mit Oracle Datenbank.")
esES("Conectando a la base de datos Oracle.")
fiFI("Muodostaa yhteyttä Oracle tietokantaan")
frFR("Connection à Oracle")
huHU("Kapcsolódás Oracle adatbázishoz.")
nlNL("")
roRO("Conectare la baza de date Oracle")
ruRU("Подключение к базе данных Oracle")
skSK("Pripájanie k databáze Oracle")
trTR("Oracle veritabanına bağlanılıyor...")
zhTW("連接到Oracle資料庫.")

T_("Error loading OCI8 Oracle connection dynamic library.")
csCZ("Nelze nalézt dynamickou knihovnu OCI8 pro spojení s Oracle")
deDE("Fehler beim Laden der dynamischen OCI8 Oracle Verbindungsbibliothek.")
esES("Error cargando la conexi�n a la librer�a din�mica OCI8 de Oracle")
fiFI("Virhe ladattaessa dynaamista OCI8 Oracle yhteyskirjastoa.")
frFR("Erreur de chargement de la librairie dynamique OCI8 Oracle connection")
huHU("Hiba az OCI8 Oracle connection dynamic library betöltésekor.")
nlNL("")
roRO("Eroare la încărcare bibliotecii client bază de date OCI8")
ruRU("Ошибка загрузки динамической библиотеки "
     "связи OCI8 Oracle")
skSK("Nemožno nájsť dynamickú knižnicu OCI8 pre spojenie s Oracle")
trTR("")
zhTW("載入OCI8 Oracle連接動態函式庫錯誤.")

T_("Connecting to server '%s'")
csCZ("Připojování k serveru '%s'")
deDE("Verbindungsaufbau mit Server '%s'")
esES("Conectando al servidor '%s'")
fiFI("Muodostaa yhteyttä palvelimeen '%s'")
frFR("Connection au serveur '%s'")
huHU("Kapcsolódás a következő szerverhez: '%s'")
nlNL("")
roRO("Conectare la server '%s'")
ruRU("Подключение к серверу %s")
skSK("Pripájanie k serveru '%s'")
trTR("%s sunucusuna bağlanılıyor.")
zhTW("連接到伺服器'%s'")


// Obsolete

T_("Error initializing OCI8 library.")
csCZ("Chyba při inicializaci knihovny OCI8")
deDE("Fehler bei der Initialisierung der OCI8 Bibliothek.")
esES("Error iniciando la librer�a OCI8.")
fiFI("Virhe alustettaessa OCI8 kirjastoa")
frFR("Erreur d'initialisation de la librairie OCI8")
huHU("Hiba az OCI8 library inicializálásakor.")
nlNL("")
roRO("Eroare la inițializarea bibliotecii OCI8")
ruRU("Ошибка инициализации библиотеки OCI8")
skSK("Chyba pri inicializácii knižnice OCI8")
trTR("OCI8 kütüphanesinin başlatılması sırasında bir hata meytdana geldi.")
zhTW("初始化OCI8函式庫錯誤.")
