#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// Oci7.cpp

T_("Error loading OCI7 Oracle database client library.")
csCZ("Nelze nalézt dynamickou knihovnu OCI7 pro spojení s Oracle")
deDE("Fehler beim Laden der OCI7 Client Bibliothek.")
esES("Error cargando la librería OCI7 del cliente de base de datos Oracle")
fiFI("Virhe ladattaessa OCI7 Oracle tietokanta-asiakas kirjastoa.")
huHU("Hiba az OCI7 Oracle database client library betöltése közben.")
roRO("Eroare la încărcare bibliotecii client bază de date OCI7")
ruRU("Ошибка загрузки клиентской библиотеки "
     "базы данных OCI7 Oracle")
trTR("Hata: OCI7 Oracle veritabanı istemci kütüphanesi (Oracle database client "
     "library) yüklenemedi.")
zhTW("載入OCI7 Oracle資料庫用戶端函式庫時發生錯誤.")

T_("Connecting to server")
csCZ("Navazuji spojení")
deDE("Verbindungsaufbau mit Server")
esES("Conectando al servidor")
fiFI("Yhdistää palvelimeen")
huHU("Kapcsolódás a szerverhez")
roRO("Se onectează la server")
ruRU("Подключение к серверу")
trTR("Sunucuya bağlanıyor")
zhTW("連接到伺服器")

T_("Connecting to database server")
csCZ("Spojuji s databází")
deDE("Verbindsaufbau mit Datenbank Server")
esES("Conectando al servidor de la base de datos")
fiFI("Yhdistää tietokantapalvelimeen")
huHU("Kapcsolódás az adatbázis-szerverhez")
roRO("Se conectează la server bază de date")
ruRU("Подключение к SQL серверу")
trTR("Veritabanı sunucusuna bağlanıyor")
zhTW("連接到資料庫伺服器")


// Oci8.cpp

T_("Error running OCI8 Oracle connection dynamic library.")
csCZ("Nelze spustit dynamickou knihovnu OCI8 pro připojení k databázi Oracle.")
deDE("Fehler bei der Ausführung der dynamischen OCI8 Oracle Verbindungsbibliothek.")
esES("Error ejecutando la conexión a la librería dinámica OCI8 de Oracle")
fiFI("Virhe käytettäessä dynaamista OCI8 Oracle yhteyskirjastoa.")
huHU("Hiba az OCI8 Oracle connection dynamic library futtatása közben.")
roRO("Eroare la rularea bibliotecii dinamice de conectare la OCI8")
ruRU("Ошибка запуска динамической библиотеки "
     "подключения OCI8 Oracle")
trTR("Hata: OCI8 Oracle connection dynamic library'sinin calıştırılması "
     "sırasında bir hata meydana geldi.")
zhTW("執行OCI8 Oracle連接動態函式庫時發生錯誤.")

T_("Unknown error.")
csCZ("Neznámá chyba.")
deDE("Unbekannter Fehler.")
esES("Error desconocido.")
fiFI("Tuntematon virhe.")
huHU("Ismeretlen hiba.")
roRO("Eroare necunoscută.")
ruRU("Неизвестная ошибка")
trTR("Bilinmeyen hata.")
zhTW("未知的錯誤.")

T_("(unknown error)")
csCZ("(neznámá chyba)")
deDE("(Unbekannter Fehler)")
esES("(error desconocido)")
fiFI("(tuntematon virhe)")
huHU("(ismeretlen hiba)")
roRO("(eroare necunoscută)")
ruRU("(неизвестная ошибка)")
trTR("(bilinmeyen hata)")
zhTW("(未知的錯誤)")

T_("<not supplied>")
csCZ("<není zadáno>")
deDE("<nicht geliefert>")
esES("<no suministrado>")
fiFI("<ei ole annettu>")
huHU("<nincs megadva>")
roRO("<nu a fost specificat>")
ruRU("<не поддерживается>")
trTR("<sağlanmamış>")
zhTW("<沒有支援>")

T_("Error initializing connection")
csCZ("Chyba při navazování spojení")
deDE("Fehler beim Verbindungsaufbau")
esES("Error iniciando la conexión")
fiFI("Virhe yhteyden alustamisessa")
huHU("Hiba a kapcsolat inicializálása közben")
roRO("Eroare la inițializarea conexiunii")
ruRU("Ошибка запуска соединения")
trTR("Bağlantı hatası")
zhTW("初始化連線錯誤")

T_("OCI8 connection")
csCZ("Spojení OCI8")
deDE("OCI8 Verbindung")
esES("Conexión OCI8")
fiFI("OCI8 yhteys")
huHU("OCI8 kapcsolat")
roRO("Conexiune OCI8")
ruRU("OCI8 соединение")
trTR("OCI8 bağlantısı")
zhTW("連接 OCI8")

T_("Closing reference cursor")
csCZ("Zavírám referenční kurzor")
deDE("")
esES("Cerrando el cursor de referencia")
fiFI("Suljetaan referenssikursoria")
huHU("Referencia-kurzor lezárása")
roRO("Se închide cursorul de referință")
ruRU("Закрыть курсор связи")
trTR("Closing reference cursor")
zhTW("Closing reference cursor")

T_("Error initializing OCI8 library (%s)")
csCZ("Chyba při inicializaci OCI8")
deDE("Fehler beim Initialisieren der OCI8 Bibliothek (%s)")
esES("Error iniciando la librería OCI8 (%s)")
fiFI("Virhe alustettaessa OCI8 kirjastoa (%s)")
huHU("Hiba az OCI8 library inicializálása közben (%s)")
roRO("Eroare la inițializarea bibliotecii OCI8 (%s)")
ruRU("Ошибка инициализации библиотеки OCI8 (%s)")
trTR("")
zhTW("初始化OCI8函式庫 (%s)錯誤")

T_("Connecting to Oracle database.")
csCZ("Připojování k databázi Oracle")
deDE("Verbindungsaufbau mit Oracle Datenbank.")
esES("Conectando a la base de datos Oracle.")
fiFI("Muodostaa yhteyttä Oracle tietokantaan")
huHU("Kapcsolódás Oracle adatbázishoz.")
roRO("Conectare la baza de date Oracle")
ruRU("Подключение к базе данных Oracle")
trTR("Oracle veritabanına bağlanılıyor...")
zhTW("連接到Oracle資料庫.")

T_("Error loading OCI8 Oracle connection dynamic library.")
csCZ("Nelze nalézt dynamickou knihovnu OCI8 pro spojení s Oracle")
deDE("Fehler beim Laden der dynamischen OCI8 Oracle Verbindungsbibliothek.")
esES("Error cargando la conexión a la librería dinámica OCI8 de Oracle")
fiFI("Virhe ladattaessa dynaamista OCI8 Oracle yhteyskirjastoa.")
huHU("Hiba az OCI8 Oracle connection dynamic library betöltésekor.")
roRO("Eroare la încărcare bibliotecii client bază de date OCI8")
ruRU("Ошибка загрузки динамической библиотеки "
     "связи OCI8 Oracle")
trTR("")
zhTW("載入OCI8 Oracle連接動態函式庫錯誤.")

T_("Connecting to server '%s'")
csCZ("Připojování k serveru '%s'")
deDE("Verbindungsaufbau mit Server '%s'")
esES("Conectando al servidor '%s'")
fiFI("Muodostaa yhteyttä palvelimeen '%s'")
huHU("Kapcsolódás a következő szerverhez: '%s'")
roRO("Conectare la server '%s'")
ruRU("Подключение к серверу %s")
trTR("%s sunucusuna bağlanılıyor.")
zhTW("連接到伺服器'%s'")


// Obsolete

T_("Error initializing OCI8 library.")
csCZ("Chyba při inicializaci knihovny OCI8")
deDE("Fehler bei der Initialisierung der OCI8 Bibliothek.")
esES("Error iniciando la librería OCI8.")
fiFI("Virhe alustettaessa OCI8 kirjastoa")
huHU("Hiba az OCI8 library inicializálásakor.")
roRO("Eroare la inițializarea bibliotecii OCI8")
ruRU("Ошибка инициализации библиотеки OCI8")
trTR("OCI8 kütüphanesinin başlatılması sırasında bir hata meytdana geldi.")
zhTW("初始化OCI8函式庫錯誤.")
