HELP_TOPIC_BEGIN("DlgPathStyleMap", LNG_ENGLISH, "Styly èar")
	HELP_TOPIC_TEXT(
	"[ [A@0+84 Dialog slouží k výbìru stylu èáry nebo editaci stylù \r\n"
	"èar. V dialogu se zobrazují všechny styly èar, které jsou právì \r\n"
	"v systému k dispozici. Každý styl èáry je oznaèen textovým názvem, \r\n"
	"který se používá jako odkaz na styl èáry. Kromì názvu se pøi \r\n"
	"vykreslování èáry zadává ještì šíøka èáry a implicitní barva \r\n"
	"(nìkteré segmenty èar mohou být vykresleny touto implicitní barvou, \r\n"
	"jiné pevnì zadanou barvou).]]\r\n"
	"&\r\n"
	"[A+84 ]\r\n"
	"&\r\n"
	"[= \r\n"
	"@@GIF:3570*2970\r\n"
	"ÀÇÉÆ¸·áèÊ–»€€ÏãÏÏ\377\377\377\377¿¿¿\377ŸŸŸ¯¯¯ß³ßß\377¿˜€€€€€€€€€€€€€€¬€¨€€€è–\r\n"
	"Ü€„\377ðÈÉ«½½¸ëÍ»\377àÒ¨ŽäéžèªÝ®ìëšÁ±Ì´ôíßø®ïüï\377À ðÈ¬®šÈ¤òÉìÂºŸÅÁì€¨îÚ¯Ø¬öËíŽú¿à°øÌ®\r\n"
	"¯›Ïè´úÍîÏ»ßð¸Ùª“ïÛïø¼þÏïû\377€ÖôÔü€‚‡ˆ‰Š‹\377ŒŽ‘’\377“”•–—˜™\377š›œžŸ ï¡¢£”Õ„¦\377¤©ª«¬­®\r\n"
	"Ÿ¯°±²­ÔÔï’µ†·€¶Œý¦Ó¨³ÁÂÃ¿ÄÅÆÇÈ”³\377»Ì¹ŒË¸ÎßÏ¸…‹¾õÒù©ƒ‚ÛÉÞßŸàáâã‘´Ù÷ÝŠæØèéËßëŠ×Õ‰¶ˆ\r\n"
	"\377ìóöøäû¿üýþ\377›–©Œ˜¸ÐŠ½÷ÚÉð¡¼—¨Þ•˜‚‹Ìˆ¸ñÆâÄ‹–¯êÜßÈ±£Ç \377òÃŠœÉ²¤Éé“¨ÓªÜÉ²‡¥Ë—°ãÂÜ\r\n"
	"‹†€ Á«”‹ÚõÁØíŠ€œ¸‚à©ñÆÎš¹ùæÄª¯‘†Ì§Ð£Ê½ÊµªÕ«ØœçÒ©© ÊÁ€«¹ ˜Ëö¦¬Ø°‚–ü´“¤öì¡Ê‡\r\n"
	"ðÝê£©Ö»þòñæÍÊ·¯çß¿€ƒ‹†¹ãÐë×ÃÃÝ•­ëêèÓÁê³Ó®ÅœÔÐ¯ÑÇÇ­ê–Û‘•³ç¢›‘æœ¾Ìº´éÓ¨ÓÛ›Ôéå¦Ï‰\r\n"
	"ƒîÌ–°“Ë¯Ú¶¯ßÚÆæ£ ·ïƒµ€ùè½Ã¸ñâÅìý§\377üøò×ßÐ£ËŸÎ½ßºõëØ³ëß\377Î½»÷ïàÃù‹ŸÏ¾¼ùÞ©ÍŒ÷õ‰ÀÀ\r\n"
	"”³îôš£çý˜û²âô»‹ÑüïÎÜ¹\377ãÃ¼©— \377€ý™æ÷Þˆ¦¨à¹‚Œ¶èàƒÆâÇšØŠ ­…€ÀÅ–Ÿ©ÃÄù”™îœº©—ß•ÌÈß\r\n"
	"€\377¦Çƒôª©þ‡à„°Æ¨ËãŒ´Öè£„ô“Þˆá‡†ÈÙ–‹ó¦à¦Ù¯øÒÞ‰«ˆ–¨ÜŠÌŽ¨áàò¶˜øã”ØÔÖéå•Ø–á—ÞÍ–Ž²£\r\n"
	"Òû¼ØóÈïïÍ±Ç¤ˆÆ’ »æšì¶©æŒÐî’€çœôÖöéçøæ©çýžüöéçŸ€œ†ªè „–êÏè¡ˆîù…—ŽÞ¶ÙÅ¡î¾Ôª€›ÂíÉƒ\r\n"
	"û›—¦ªé¦œ¾öêé§ †ª×ê¨ˆêÈœ½¦ÂŠªŽ“ÒØº¢€¤Æªë÷¬´Öêë­¸¦þÚ˜³õîúþê¯ˆñêè«¹¹–ëì±È¦÷«ì²øþô«\r\n"
	"Ï\377Îªúç´­­Æúª Øæï«í¶Üöëíó·Ýš‰î¸ä½–ëî¹è¦›\377‡¸ê¶ëî»ëðÆ«ïìÎþëï½øæ«¯¿¹õîëï¿€”‡¬ð™ý‚ä\r\n"
	"óðÁˆ§¬ðÂƒ‡äØð€ÇÆ¬ñÄ”×ìñ¹Å˜ç¬ñÆœ®÷ìñÇ ‡¬ëòÈ¤—ìòÉž¨§¬òÊ¬ËÛœÞ —ù”ÀµÀ´×ìóÍ\377ì„±³Ã±ÃŒ\r\n"
	"£óÏÀ‡­ô˜Øƒø ÅËÂÉ¦¼ôÒÌ·ó‰ÑàœÍ³¶Ê¬»íõÕØÏ‹±õ—ÒßØ³¯ºÙ‡­öØàîíÅ×¶ýí™Ùì·íöžæÈÛ±óÚÈßë\r\n"
	"»óÛøç­÷™Ðñƒ±ÝÓóï¼÷à„—¾Î¨×Ì¬ôàÞ®›îøãï›Ýï±ÏŒÓùåý˜ßÝ÷\377ß‹¬ûÍõÝÛ´¬ïúè¤—îºÅø¹¦þúê¬·\r\n"
	"ïîúÆ©ßÑ÷¬–èËü¹ØÜßÌùÏ±×¡ëûî·÷ÞÅì¿¦îì¹à¹ƒÉÏû—¿«Ï³»ð» Îµñé»ß¾öòÎÛ¬ÆüóÙ‡Œ½ññ×ÞõèÝ×\r\n"
	"¼ýùÏû¾ëàÇ·Ž½úÞœ³¿ÀßÓÂÏ½íÈ“¿¿À×çï\377¯ôŸ«§ÛÃä÷µîé«Á€ÂëŸÎ±ˆ…†æÁ€ŽÅÌ—ôÀð¿˜ŠÙïèïóÚ„\r\n"
	"‚ý§¹‚®Œ¶›”ÛÍç…æ™ø ö–Ìßòˆ›†±¿ù®Ý…¯œÛÌà¸Ü´…Ò¬…²¤Ê¡çæÈÀœÆÉÐï´Œß—¬è×¼ªƒúÐÛÚŽÝÈÁÝ\r\n"
	"÷ñƒµôàÀÓ–èÄ¦º†Äü¡•çÈÂ¢¡\377Âìâƒ…ÝŠ•¨Â â“±ŠÐœš…µ†Æ—±ŒÖŠÌœˆ«˜ÂûÆÍð‹ë‹£îñ’¸´ºÂ‘‰\r\n"
	"ÔèÔ£”Ù¸Ç®¿Êððäâæ“»È…¢†¯þý–ã£Ð¨¨´Å¿¦±ƒŒÔ˜¥ßèÉ¸–×Ñ‡‹ÌŸ—£¾ÖÁ¤‰ñäÑää¥\377¸Å¦«­ñß›„åŽ\r\n"
	"ð‘©·Åî°Ž“òº£©øÁ–‡âÒ\377êú¥â°íØÂ¼¢Ð©”ûœã°ñ¥êÌ±ÑÌêºœ˜ž¯ÕˆÊåÊÎ°“ÖŒ×´ÏôÖÊ»¥³šÙ¸¤æ†Ã©Íâ\r\n"
	"îÒ×“¤¹×ßÕÌõ¦ë›÷êæ€ÇéÎ¾öµ³žæ‚§Ž—ŽéÍôª“§ŸÁÄ¦Àóé´Îé¢“‰\377œßè¹î©Ðïé•“öò¼¢¯› šÐúÒô\377Ü\r\n"
	"Ä­âÁ§úÑý…Š´£ÝÊèê£«ÇÍ†‚”Ñ –½©·ÄÊ–¾’ºÏªÝ©éÇãŠ­–ö‡Î¥‘Ì¨Í¤±€Ý±ô§ú³è©ÁŠÊÍé•¾Ô§Àåƒ•\r\n"
	"ÜüºÓ¤âá©„Ã¥Á¡¹¾í¤ºõ©éüéÒÕáÐˆ¦Êµé¨›íêÖß –“¯Âô¬ò¨ðëÔ›éÌˆöÂÒ¬èÝƒëÌ®êÕ¸¶á®ëóÝ‚£ÛŠ¿£\r\n"
	"—‚Ó®ñ˜Ý™\377ŠØ²šôøÆÄ§ÑóÊØãÂ²á«ä±¢ÖË´±Äöí°ÙØëÍûÊ›ØÃÒö±Õà¬ŒæåøÙÐÚÖ¬£½‚æ©²ÇÕÓú¶´è\r\n"
	"ÁÐÉä¥‹×Ø´öÁ¶æ¡í×œ•›Ö”Ú–Œ÷¬É­îÏúÛ´¯„·ËÃÕëØÛ—ÛÕÆ–×Ý¸ž\377œìóóìŠÎ›²–§ÍÚýíô¿ ±ê¼ê÷»ÌË˜÷\r\n"
	"ó±°Ú°¶ö›ž•ï™Ææ†óö®×äí…ï¤”¨Þ²Ô÷¶Œîµ¯Æâ›ò²þÚÌ®‰ÝÁ§ÛËÊÚ³Þ¢·¼¦‹ƒÊ” ü²†§¸°žÇä˜ƒ·¶á’\r\n"
	"ŽÕøÀ¹ë°ˆä»–Û€Ã”¹¹®­°‡½ ²Ïî¦ÌÄ‹¦ñã‰¹šá‰«Ø”ã¨Ö°‚Ç¼Ýã‡×˜Âæ°Õ®ù±›âÄÒûø€«»±ÒÜâŒ—Ùô\r\n"
	"«ýñƒûëä•Ç‡ŽÉÏ¾²‘ðƒØ†çñ¼ùþ„§Œ›œâÈ¨»ùÊÝ†³‡ŒïÚâ—ûù™Ëçžó’Á¦ßä’µ¹»Õö°Æ±ŒÐ­«û¹Áæ²šñ\r\n"
	"²¬åµ\377Ù´ÉŽÄ³˜Í¼è·Çë™ÐþŽó\377ã¢ïŒÜ¹”Ó³Ù•±£ëÙüç¾\377ÙÒŠÆôžÕäÄëïÚÓª«ô¨©ãœæ¡¯šÔÐ—Ý­€ÁŒÞÉ\r\n"
	"Í£º†—žõ¦’å½éÊÇº‹Æñ©õÝèÜ‹Ÿš×§¶ô£®áÌ†«óóÛžþµ­ÍÝ”ë¨\377Ú¾ïöØöìÓ›ÆÉÓïšØÏ–ö³\377£ûâÚß›ÃÜ\r\n"
	"ðªâÕýáÞÌ¦›ÛÑ–ôºã­ýéí›Ôý¸Î®Ñí¼çî˜Ùï¶÷…Œý½ïðïëªãæë¹éÌ¶Ñðò­«µµÐøÂÎî¹ó§¸Õ´Ôø£™\r\n"
	"ìÎÜ‰‡›ŽÆêž°ß¿ëñÛÔ–ØºÇëÀí•»ð‡ç™ãŒßøÇ“îñ›ÁŽ×µËµ÷¬ÝÓŽØ„Ø¼²òÆ¹Í‡úêóœÓ»Šå½\377²Éë\377¬ó\r\n"
	"æ—¢ç¹¯ðÎ™ÏÑ…¤\377œ€„Á¿¶ÄÙŽÞÏÜœâ³¹¶•®žô˜—œÒ½¾äÒÇî²óŒÓýº¬©¦»Öµõ÷âÖéã× ÈÑ¨žÝÇóµ…›\r\n"
	"ï‡ûÒ‰½÷ç\377òÝî›ÅûÛä£¾öÔ×¼ð•\377†üõÁŽñÍ±£ÞðÙ\377¼µì”¿ãÆŸÜÏï’¿¸ï³¿ÚŽÊ‹ÝòÄ—ð”ÆÏúÒ›«þô¹¸­ê×\r\n"
	"ßÏúÖ»þ‡žƒ—úÛ¹Ïûô\377µÕ—¯½îù¹õû™ïþ÷ÛÛê½ÁÏü›àÇüøÅÏþÊ „¿ôßª\377±ùëà¾è÷ýê›Áú‚¯´õ·Ï†ì£\r\n"
	"Ö³÷Ü\377™¼¿ßÏÐ‹\377üäü ¿²·ýºö×»\377ý¦ÛžüÝçÏ\377úƒ¬ãý¸·¿ã‰ß÷ß\377Âãß÷Å§²ûý—÷±çö«Ú·\377À·€Ëå÷\377È÷øµ§\r\n"
	"™€Æ×€ù×ðõÊ‡´Ç€ÍÜ÷öþ§„Ø¦ð–ýáçÉ™ø’Â¸”Å¤ô–ùèâ„ä®Ü‚ä÷÷ý­ú§‚÷Â‚âÆà‚ØÄý˜ÅéµãƒÎƒ\r\n"
	"Ó§ƒß¢Ëºé„Åïôä€„¤ÃÁ¤ºÇÈÃ‚¸èÐÀˆ°Â»È„ä‚‡‘ƒ”¸¯›ôÅˆóôÈÕ„ÊÚé¸ÂÞ¨È÷¢ï‚û’…âØƒŒ’ˆ€˜‡¯í\r\n"
	"„ôË‰´Æâøå†¢ÖÊÍè„é›—´¤‡®û”†ˆ‚ç’£‡¤•ÈóØÉ­éÅ‡×ô‡ÀÊƒˆõø¿ü˜×ˆ˜®±”‡Ÿ­Ô…’ˆÀæ¶¨ƒðÂ†úò\r\n"
	"Ç‰‹è¯¾ˆ‚¯‡‰í’‰Ë˜ØíÆ˜\377ÃËô„ä¥Ø„âäù€·“‰©ˆ†ÊÔ¸ø ˆþ¢¥¸ûš¨ñŸè…Ï¸‰ŠóáæÏÓ‹Ú·‹•Ú×‹±Ø‰©—\r\n"
	"Ý‹Š·‹å÷…÷Å§Œ†ÇŒë×Ç‚¿‡Õ×Ýˆ¿øˆœçõÛ¥Ó§™³ÇôÇŒŸç·ŒÎÈ\377ÂØòýØèŽé¨‹í¿¸ŒëÈ‹à¨–ùâøÜÞ¸û\r\n"
	"ï®¸ï˜ñ÷ØŒûøóøòø÷Èà„·Ö¿‡ŒÕ÷ôêß÷ù¸€Ý‡€áøÀ÷ü—ŽØ—¸öÃ¸’‰õ”™é–¹Œ’‰“Å¥Ö£Çö\r\n"
	"ÛÉŽéŽæ—’ð¸’‚·Õž•é‡ê¸ò¬Â‰®Éò°é¹‘²‰¢õòæé½Ù’™žõ’òø‘€™”õ³†ŽùÚ¶–¢Äéµ†¹\377’Ö°Û‡\r\n"
	"Ï©¡•ÛÎù¸õ¨é”ö¸¨½ÈÕ•ôè•·Òé’ÚÙ”»Ù‹•ïÓ×¥÷•ý¸™©ð\377–—•°•—¯‰°Öý¸ïÜ¦ßÚ—ãß“óÞîÝÖï¿¨—ù™\r\n"
	"äÖ‚åï†Ö—ÙÛÖïŠ™ï‹‡™˜Œùæâ°µùçãô–ïÛÙí•ÉþÊÍöíƒ¹îîÄ²âô¤è¢ùãÙ£Éè¥Éë§Í‰íû¥¾íÉð¸™‡‰ì\r\n"
	"Ýšù™–©î³Ÿù™õ†˜È¶èÈì–›ðÖ›ÙÀÉåÁ¹åÃœ¹â™é““Ùñ–Ðùî²É™ß†é›Í¹ìÞö†ÇÉÏ™ðãÒä\377Ú¹‹®ãñä¨û„\r\n"
	"¤Ùíì†í·É÷›íÆïå‰›ÝÁÖØ™ÁÜ§ùžð©ºÞÙÛ—¼õ—éµžø\377‰ë¶é\377œ¿ä¹žÏÙŸ€×æžñ¹ „ŠÍžÌ÷†˜‚îÎ„Ÿ½Ù›º\r\n")
	HELP_TOPIC_TEXT(
	"ÛéŸ€ÊŸû™Ë›™ üÔ î˜š¡Ê¦™ƒö§žÊ–¡Òùý¡ùæ ú–ž·œ³›‚ª¡ªëº¢§ªòô¹ØêêÈ™ìéä•Š¡ê¢«—é™æé£¥º\r\n"
	"¶íÈÙ¼ÅéâòÁŠãÃú›Âîù¤Ä‰áâ–í”Þ—“Ûùš®³ªŸ×™¢“–Š˜ùùž·Ê¡¢ˆ‰ðÌêø±©ùßßš£´Òú™áÚ¥ãŠý›åš„Ì•\r\n"
	"¬Îê–Ô¨˜Û©”ðº‘‹‰Íç©’¡Ù¼ã¹”Êé–ò“ÚñÚš™Ù¨ÖÐ§áù‹¦Ë¹§\377š´÷ù¢åæŸ‹šåŒ€àô¿ú€¡“úõìê—±\r\n"
	"“ù¦—ù©å‡í–‘é©¾‡œþœÙ\377§®É©ê Éõ º§ž¾Ê¨ÉÙ¦Ëùå§Ò¹õ¸çª¢¢éØé×«ôÓú”þª¨³™äÄêéÔì‰ æ“øèÅ—²\r\n"
	"ôêÛÈÊ–°ÚÙ«¿©€ÆºŽóŽêðº‰ª´Þ—¬¶Å¡‡ˆÛ¨–ª—º­ÞŸè¦ëðúä¦Ú®æêúª÷Ÿ®êº®ìº„­­é§è—¯ãöà¨“©¯öŠ\r\n"
	"û“šÚ­÷º¯·Ìš¯ÏÊ¯€—Û¤þª®‹Ï°ôÚ¡…ë¯¦‡»­‰›¯‹Š›‚‹þ›ÁŠ‘ûþ“ë‹ •«þ—ûŒ¬ëÚ±ž‹±ò÷ù±¢»²Úª \r\n"
	"ïÕ‡­°Õ²¡úø«­É•€ŠÏ¯õ¹©ïé•æ®›¨°‹£·ê«ÝÚ³ŒŠÙ®¯˜«ÖÊ³·ÉÚ³·û¨²ò›©Â›´¡êé³Õˆ´³‹\377Ôµ¬«µÑÚ†\r\n"
	"ýž”µìô®‡Òêµ·´…¼ûÅŠÃËÌØÛ¯‘ÜºÅÄèÆÏõô·‚˜ŒÞšà¯§ºËÙØ‚´ÌË‹„«³«ÔøÅ¶Ô„÷û¬ÂÔµ£ØÈ‹äËÚëÏá\r\n"
	"ï‹°‹®ŠÃï…•è·Áƒ² \377˜ÈÜ¤‰ûšÈ¬±ª·õ‹îÅ‡¤ˆðûµŒÔëˆ›ÅßÙ•ŽÍë¬ã«øÉþû¹—‹´ýü³µê‚¹€åÛ´ÛäŸô‘\r\n"
	"ñ «»É¬„¸úö«Å”»·šç‹…¬äÆ¡äß…™Û¯°›º·§ú´ý¤º¨›Å· ‰¯·Àû¼ðê¼´«¼ï¹„¼Ùº¸Û–Ú¸³ª½øÚ¿´Ôú¯Ð‹ø\r\n"
	"ãŒûÙªë‹Ø¥ûÛáËÙãûÉŒ§Ë½©ë½ø¦‹ýç‹«îþ»»ðË¾¥•¿¾ç˜\377€ö«û¾óË¾ë»¶÷ËÛ¯±«¯¨º›–€ü«Ü›ù®ÎÛÀ¬º»\r\n"
	"¤ˆ¬À¸û´ô½ë\377«Š‹™ºßÀÞËÀ’ÚÁ¥–úÁ‘ÌÀ““Ì¨œì•žìÝ´ œ»ßºÂ¾†¼«¦ú¼š³Ü²ùŠ­Šªé°˜¼·¨üÀìª¼¨®ÚªÍ\r\n"
	"šÚ¼¯ÜÌ™\377Ãúˆ”ø»¿ ÀÕˆÄìÄ»×…Ä—Åª››ù¿½Ë••º´¼Ò¬”äÅ«¾‚œÂ¶éÙ³üéÃÀ¼•ßéÄ¦ØìÂÚ¬­ã’”¿§µ¬ñÛ\r\n"
	"ùŒ¶¼ºàµ¬¡ßÛÜðüÅ­Ÿœµ\377«½°ŒÍÁ¦œÁåŒ¾àÊÜØÅüÀÛ›«´«œÀ¿«ûºåÛ½‚œÇ¶üÚÃäìÅþ—¼Èü¨¹¹‹éÉºÌÈ¬Ç\r\n"
	"\377ÝÛÆ‰Ü¾ïÞ³² ¬“·Ÿ\377ÆåÈÉ÷Œ\377¥¡œÊðÇšÍ”¬Á–œò ¯ªÊ²üþçÐ¯Â›¼Àý¬õ½±¼Ë¼ÜÃºåËŠŒÈú«›Ä½ÜÌ«“Õ\r\n"
	"õÀüÈÙüÊ“¾ÌÌÆüÌ£“ÎðÉì¼ö¬Ãý¶Ê¥ÐœÍîØ¥òÝúªƒ‹ûËÌìÆÎ¬Í£äìæ®çÅ´“üÁüœÎÒÉß©èì¡åœÏ¸ÛÆ…îÜÍ¼\r\n"
	"÷üÍÂì•õŒÑÆ±õô˜ªÆœõ¬¶œÔÖ¹§ö¹ü­ªŠ«ÐŽÜÍ¬öôÂœÉÍ§«Óž¬·àìÆßŒÁ¬\377ŒÒêìÈíÔ¬Ð’·Ç¹ÑüÛ Ý¨ãÌ\r\n"
	"ÍÐ•˜Ñö•ÈæøÜÌŽ¼È·ŒÏËìÑ™œÝÇ¯«ÉÁœÓ·íšÓº½ÓµÛ®¼ýÓÀýŠúý›ƒ™›þ¬ÏÜÔüúÔÈúý¯Ê½\377Ôò“ÚÔÎ­±¥­\r\n"
	"Á¶ÑýÐÝÕôÆ½Õˆ‹ÕÊÂ÷ÕÜíýÞýÍÕÖ­ÕŒ«Ö•À—ÖæüèßÖÄ·ÖìýÜûîýÖº—×àòÍûôÝ×™Ê÷×øýøú½¯×…××þ½ô\r\n"
	"å€Ø´·Ø„ÕÝñ†ýØ’—óØŠíðŒÝØßÛõØýÜ’¶½Ù¿ÕÙ–þÛ˜ÙŸµÙûœíØžýÙ€¦•Ú¢×¤Ý™ÚãõÚ¨ýÕ÷ª½ÚÉÕÚ®\r\n"
	"•½Ó°Û±µÓÛ´ýÒ¶ýÛÎ•ÛºÍÑ¼»ÝÛŠõÛÀÚÐÂ½ÜõÔÜûÆ½ÎÈÜáç´ÜÌíÍÎý»ÜÃ”ÝÒí¿íÔÝÝóóÝØý¾Ú½ÝÝÓ\r\n"
	"×ÝÞí¼àÞÝÀ³Þä¹æþýÞ—“Þêýþ¸ìÝÞ†óÞ©ðÍ¸ò½ßûÞÓ\377ßö·øûßï³ßüÝÎ¶þýßä“à ‚®¶„ÞàÙÂóàˆþµŠ¾\r\n"
	"­àÎÓàŽÎ´¤žáÃ³á”Ðž´–þá¿“áášþ³œÞá†µóá ¾°¢Ò¾âÓâ¦þü¯¨žâû²âò¬ž¯®þâ÷‚’ã²¾¯´Þ«ãñòã¸þ®\r\n"
	"¾º¾ãíÒã¾±ž®Àžäç²ÁäÄÞ®Æþä—ã’äÊþ­ÌŸÞäÝòäÐî¬ü½ÕÓ¾»¼ÒþåØ’åÚÑ¾üä±Ý¾‰ÞßÎ±áŽ¹¤ÜÞæýðæè\r\n"
	"Ù¾‡ê¾æùÐÁæîþ‡ðžç„ò°çôŽ‡öÚþçîçúÞŠýöÓ¬ýþ¹œ´¹®·ºÎƒè…î¸ÅÓºàÉÕ‰î¶·ëÓÑÖþèìò“é”­º”Þ\r\n"
	"î¶–ÎÆ•éñ•®½°ý\377È÷žþéü¦Ì¢â¾êã£¹úÖè“ŽêØ“·÷—Éêåíê¯¾Žê½Ëé˜Î×ëµÞØ²Žæ¹ºŽÍ¶®Îí—üëš“ìû¼\r\n"
	"ßìÄÞƒÆþË¿¹žì®´ì·ŽýêÎîÊ\377Î—èÓÎ´ƒÎçë×ž¹è”ÔÞ·þíàžîâ¾•îºåÛÞ¾ýýòîÝ“îêýî¼ìÞîÀó×îðž¹ò¾ï\r\n"
	"å—ÓïîÌçêÀî¿À½ø®íáÀï½ ¦“‹þ‚†ÏÄÓ÷ï—žð‡ßñð˜ …Ü³é·ï’ðêÃâŒ¡¿¯\377ŽÐ¾À¯”Ÿô‹¯ñŸê’ñ‡ó¯\r\n"
	"¹ÇŸ¿ñð¢ßò²ƒòñÒò¼¾þñú¢ò†ÛÁò\377Ð‰®¿Áã°Ÿ‡í›Ò…Ü”ñ´ŸãëÖàóþÞñ©ž•óïÐÆì¬àÆ¾¯ó†¬«ô•æÞô ß¦\r\n"
	"ó¥‡î óÃóáó–õËÃˆŠ¥ìüó¸îôí†€¤¬¨‡ÖŸÐ½é°Ñ„Èˆ¤ó°ôžÏáà™Ï†â¯¦ïÐåöÑ¯Ó®“ö¢÷¯†Þßãï’ŸôÓ¯ÓãÀ\r\n"
	"µ÷Ø¯Î˜‹È Îïò–ß÷µøÉÉÑË\377Ÿö…˜öŠË°´ìïòî¯øµ¡¨Ã¼ŸÏ\377éöÚ¹ÚßõÏ•\377ò˜ß®‚¾Ïò£ó¥ÏÆ®§ï¯û¯ã\r\n"
	"øý¯¯­ñ©§\377õ«¿®³Ÿ¿óµÏ÷ú °ô„¿ø¡¿û°ªßÌŒÁ°‹ Íü¯®ïØº²üÏïï˜£ðÎ”Ï¸ÐŸýû³×ýÔŸ·Ö\377ýžï“ýÚß¶ô\r\n"
	"¶àüàŸþâ¿Óþä‹òüþŸèŸþêÏº‘€€€»]\r\n"
	"&\r\n"
	"[A+84 ]\r\n"
	"&\r\n"
	"[ [A@0+84 Tabulka v horní èásti dialogu slouží k výbìru stylu \r\n"
	"èáry. V obdélníkovém poli jsou uspoøádány náhledy všech dostupných \r\n"
	"stylù èar. Dvojitým kliknutím na náhled èáry vyberete styl èáry \r\n"
	"pro další použití v místì, odkud byl dialog vyvolán (odpovídá \r\n"
	"funkci tlaèítka ]\r\n"
	"@@GIF:343*99\r\n"
	"€ÇÉÆ¸·á®È€€™€€ÏãÏÏßßß¬€€€€€®€€€¼‚Âœ©Ë¬þ±€œ´Ú‹ï¯‹¹û¿ýâÈ¯…äé™äÀ‚´­ª©ãàÖð\r\n"
	"öŒ¡ôÎß²È›ÚÙÐ¿›¯ç¸Ì‚ž‚¦ó‰ýÊ§Ô õŠÍê·×‚€»[A@0+84 ). Pravým tlaèítkem mùžete zobrazit \r\n"
	"lokální nabídku funkcí pro práci se styly èar`:]]\r\n"
	"&\r\n"
	"[A+84 ]\r\n")
HELP_TOPIC_END()
