#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// GridCtrl.cpp

T_("Close")
deDE("Schließen")
esES("Cerra")
fiFI("Sulje")
huHU("Bezár")
plPL("Zamknij")
ruRU("Закрыть")

T_("Search")
deDE("Suchen")
esES("")
fiFI("")
huHU("Keresés")
plPL("")
ruRU("Поиск")

T_("Append")
deDE("Anfügen")
esES("")
fiFI("Lisää loppuun")
huHU("Hozzáfűzés")
plPL("Dodaj")
ruRU("Добавить")

T_("Insert ")
deDE("Einfügen")
esES("")
fiFI("Lisää väliin ")
huHU("Beszúrás")
plPL("Wstaw")
ruRU("Вставить")

T_("Duplicate")
deDE("Duplizieren")
esES("")
fiFI("Kahdenna")
huHU("Duplikálás")
plPL("Zduplikuj")
ruRU("Дублировать")

T_("Delete ")
deDE("Löschen")
esES("")
fiFI("Poista")
huHU("Törlés")
plPL("Usuń")
ruRU("Удалить")

T_("Edit")
deDE("Bearbeiten")
esES("")
fiFI("Muokkaa")
huHU("Szerkesztés")
plPL("Edytuj")
ruRU("Редактировать")

T_("Accept")
deDE("Bestätigen")
esES("")
fiFI("Hyväksy")
huHU("Elfogadás")
plPL("Zatwierdź")
ruRU("Подтвердить")

T_("Cancel")
deDE("Abruch")
esES("Cancelar")
fiFI("Peruuta")
huHU("Mégsem")
plPL("Anuluj")
ruRU("Отмена")

T_("Move up")
deDE("Nach oben")
esES("")
fiFI("Siirrä ylös")
huHU("Mozgatás fel")
plPL("Przesuń do góry")
ruRU("Вверх")

T_("Move down")
deDE("Nach unten")
esES("")
fiFI("Siirrä alas")
huHU("Mozgatás le")
plPL("Przesuń w dół")
ruRU("Вниз")

T_("First %s")
deDE("Erster %s")
esES("")
fiFI("Ensimmäinen %s")
huHU("Első %s")
plPL("Pierwszy %s")
ruRU("Первые %s")

T_("Previous %s")
deDE("Vorheriger %s")
esES("")
fiFI("Edellinen %s")
huHU("Előző %s")
plPL("Poprzedni %s")
ruRU("Предыдущие $s")

T_("Next %s")
deDE("Nächster %s")
esES("")
fiFI("Seuraava %s")
huHU("Következő %s")
plPL("Następny %s")
ruRU("Следующие %s")

T_("Last %s")
deDE("Letzter %s")
esES("")
fiFI("Viimeinen %s")
huHU("Utolsó %s")
plPL("Ostatni %s")
ruRU("Последние %s")

T_("Immediate search")
deDE("Sofort suchen")
esES("")
fiFI("Välitön haku")
huHU("Azonnali keresés")
plPL("Wyszukiwanie natychmiastowe")
ruRU("Непосредственный поиск")

T_("Hide rows")
deDE("Reihen ausblenden")
esES("")
fiFI("Piilota rivit")
huHU("Sorok rejtése")
plPL("Ukrywaj niepasujące wiersze")
ruRU("Спрятать строки")

T_("Highlight found cells")
deDE("Markiere gefundene Zellen")
esES("")
fiFI("Korosta löydetyt solut")
huHU("Talált cellák kiemelése")
plPL("Podświetlaj znalezione komórki")
ruRU("Подсветить найденные ячейки")

T_("Case sensitive")
deDE("Gross-/Kleinschreibung beachten")
esES("")
fiFI("Huomioi isot/pienet kirjaimet")
huHU("Kis-/nagybetű érzékeny")
plPL("Rozróżniaj małe i duże litery")
ruRU("Учитывать регистр")

T_("row")
deDE("Reihe")
esES("fila")
fiFI("rivi")
huHU("sor")
plPL("wiersz")
ruRU("ряды")

T_("Insert a new %s into the table.")
deDE("Neuen %s in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla.")
fiFI("Lisää uusi %s taulukkoon.")
huHU("Új %s beszúrása a táblázatba")
plPL("Wstawia nowy %s do tabeli.")
ruRU("Вставить новый %s в таблицу.")

T_("Insert before")
deDE("Davor einfügen")
esES("")
fiFI("Lisää ennen")
huHU("Beszúrás elé")
plPL("Wstaw przed")
ruRU("Вставить до")

T_("Insert a new %s into the table before current")
deDE("Neuen %s in die Tabelle vor aktuellen einfügen")
esES("Insertar un nuevo %s en la tabla antes del actual")
fiFI("Lisää uusi %s taulukkoon ennen nykyistä")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
ruRU("Вставить новый %s в таблицу перед существующим")

T_("Insert after")
deDE("Danach einfügen")
esES("")
fiFI("Lisää jälkeen")
huHU("Beszúrás utána")
plPL("Wstaw za")
ruRU("Вставить после")

T_("Insert a new %s into the table after current")
deDE("Neuen %s in die Tabelle nach aktuellen einfügen")
esES("Insertar un nuevo %s en la tabla después de la actual")
fiFI("Lisää uusi %s taulukkoon nykyisen jälkeen")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
plPL("Wstawia nowy %s do tabeli po aktualnym")
ruRU("Вставить новый %s в таблицу после существующего")

T_("Append a new %s at the end of the table.")
deDE("Neue %s am Ende der Tabelle hinzufügen")
esES("Añadir un nuevo %s en el final de la tabla.")
fiFI("Lisää uusi %s taulukon loppuun.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
plPL("Dodaje nowy %s na końcu tabeli.")
ruRU("Добавить новый %s в конце таблицы.")

T_("Duplicate current table %s.")
deDE("Neuen %s in die Tabelle am Ende einfügen")
esES("Duplicar la tabla actual %s.")
fiFI("Kahdenna tämänhetkinen taulukko %s.")
huHU("Az aktuális táblázat megkettőzése")
plPL("Utwórz duplikat aktualnej tabeli %s.")
ruRU("Дублировать текущий %s таблицы.")

T_("Edit active %s.")
deDE("Aktuellen %s bearbeiten")
esES("Editar activa %s")
fiFI("Muokkaa aktiivista %s.")
huHU("Az aktuális %s szerkesztése")
plPL("Edytuje aktualny %s.")
ruRU("Редактировать активный %s.")

T_("Delete active %s.")
deDE("Aktuellen %s löschen")
esES("Borrar activa %s.")
fiFI("Poista aktiivinen %s.")
huHU("Az aktív %s törlése")
plPL("Usuń aktualny %s.")
ruRU("Удалить активный %s.")

T_("Select all")
deDE("Alle auswählen")
esES("Seleccionar todo")
fiFI("Valitse kaikki")
huHU("Minden kiválasztása")
plPL("Zaznacz wszystkie")
ruRU("Выделить всё")

T_("Select all table rows")
deDE("Alle Reihen auswählen")
esES("Seleccionar todas las filas de la tabla")
fiFI("Valitse kaikki taulukon rivit")
huHU("Az összes sor kijelölése")
plPL("Zaznacz wszystkie wiersze tabeli")
ruRU("Выделить все ряды таблицы")

T_("Columns")
deDE("Spalten")
esES("")
fiFI("Sarakkeet")
huHU("Oszlopok")
plPL("Kolumny")
ruRU("Колонки")

T_("Copy")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
huHU("Másolás")
plPL("Kopiuj")
ruRU("Копировать")

T_("Cut")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
huHU("Kivágás")
plPL("Wytnij")
ruRU("Вырезать")

T_("Paste")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
huHU("Beillesztés")
plPL("Wklej")
ruRU("Вставить")

T_("Paste as")
deDE("Einfügen als")
esES("")
fiFI("Liitä nimellä")
huHU("Beillesztés másként")
plPL("Wklej jako")
ruRU("Вставить как")

T_("appended")
deDE("anhängen")
esES("")
fiFI("lisätty loppuun")
huHU("hozzáfűzve")
plPL("dodane")
ruRU("добавлено")

T_("inserted")
deDE("einfügen")
esES("")
fiFI("lisätty väliin")
huHU("beszúrva")
plPL("wstawione")
ruRU("вставлено")

T_("Moving selection (%d %s) before row %d")
deDE("Verschieben der Auswahl (%d %s) vor Reihe %d")
esES("")
fiFI("Siirtää valintaa (%d %s) ennen riviä %d")
huHU("Kijelölés mozgatása (%d %s) a %d. sor elé")
plPL("Przenoszenie selekcji (%d %s) przed %d wiersz")
ruRU("Переместить отмеченное (%d %s) до строки "
     "%d")

T_("rows")
deDE("Reihen")
esES("")
fiFI("rivit")
huHU("sorok")
plPL("wierszy")
ruRU("строк")

T_("Moving row %d before row %d")
deDE("Verschieben der Reihe %d vor Reihe %d")
esES("")
fiFI("Siirtää riviä %d ennen riviä %d")
huHU("%d. sor mozgatása %d. sor elé")
plPL("Przenoszenie wiersza %d przed wiersz %d")
ruRU("Переместить строку %d до строки %d")

T_("Moving %d %s before row %d")
deDE("Verschieben %d %s vor Reihe %d")
esES("")
fiFI("Siirtää %d %s ennen riviä %d")
huHU("%d %s mozgatása a %d. sor elé")
plPL("Przenoszenie %d %s przed wiersz %d")
ruRU("Переместить %d %s до строки %d")

T_("cell")
deDE("Zelle")
esES("")
fiFI("solu")
huHU("cella")
plPL("komórki")
ruRU("ячейка")

T_("cells")
deDE("Zellen")
esES("")
fiFI("solut")
huHU("cellák")
plPL("komórek")
ruRU("ячейки")


// Obsolete

T_("Do you really want to delete selected %s ?")
deDE("Möchten sie wirklich die ausgewählte %s löschen?")
esES("")
fiFI("Haluatko varmasti poistaa valitun %s ?")
huHU("Biztosan töröljük a kijelölt %s ?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")

T_("Swap %s with previous thus moving it up.")
deDE("Vertauschen der %s mit dem Vorgänger zum Aufwärtsbewegen.")
esES("Intercambiar %s con el anterior y así moverlo arriba.")
fiFI("Vaihda %s yläpuolella sijaitsevan kanssa.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
plPL("Zamień %s z poprzednim przesuwając go do góry.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")

T_("Swap %s with next thus moving it down.")
deDE("Vertauschen der %s mit dem Nachfolger zum Abwärtsbewegen")
esES("Intercambiar %s con el siguiente y así moverlo abajo")
fiFI("Vaihda %s alapuolella sijaitsevan kanssa.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
plPL("Zamień %s z następnym przesuwając go w dół.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")

T_("Find")
deDE("Suchen")
esES("")
fiFI("Etsi")
huHU("Keresés")
plPL("Znajdź")
ruRU("Найти")

T_("Find options")
deDE("Suche Optionen")
esES("")
fiFI("Haku optiot")
huHU("Keresés beállításai")
plPL("Opcje szukania")
ruRU("Опции поиска")
