#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// GridCtrl.cpp

T_("Close")
deDE("Schließen")
esES("Cerra")
fiFI("Sulje")
frFR("Fermer")
huHU("Bezár")
nlNL("Sluiten")
plPL("Zamknij")
ruRU("Закрыть")
skSK("Zatvoriť")
zhTW("關閉")

T_("Search")
deDE("Suchen")
esES("Buscar")
fiFI("")
frFR("Chercher")
huHU("Keresés")
nlNL("Zoeken")
plPL("")
ruRU("Поиск")
skSK("Nájsť")
zhTW("搜尋")

T_("Append")
deDE("Anfügen")
esES("A�adir")
fiFI("Lisää loppuun")
frFR("Ajouter")
huHU("Hozzáfűzés")
nlNL("Plaatsen")
plPL("Dodaj")
ruRU("Добавить")
skSK("Pridať")
zhTW("增加")

T_("Insert ")
deDE("Einfügen")
esES("Insertar")
fiFI("Lisää väliin ")
frFR("Insérer")
huHU("Beszúrás")
nlNL("Invoegen")
plPL("Wstaw")
ruRU("Вставить")
skSK("Vložiť")
zhTW("插入 ")

T_("Duplicate")
deDE("Duplizieren")
esES("Duplicar")
fiFI("Kahdenna")
frFR("Dupliquer")
huHU("Duplikálás")
nlNL("Dupliceren")
plPL("Zduplikuj")
ruRU("Дублировать")
skSK("Duplikovať")
zhTW("複製")

T_("Delete ")
deDE("Löschen")
esES("Borrar")
fiFI("Poista")
frFR("Effacer")
huHU("Törlés")
nlNL("Verwijderen ")
plPL("Usuń")
ruRU("Удалить")
skSK("Odstrániť")
zhTW("刪除 ")

T_("Edit")
deDE("Bearbeiten")
esES("Editar")
fiFI("Muokkaa")
frFR("Modifier")
huHU("Szerkesztés")
nlNL("Bewerken")
plPL("Edytuj")
ruRU("Редактировать")
skSK("Upraviť")
zhTW("編輯")

T_("Accept")
deDE("Bestätigen")
esES("Aceptar")
fiFI("Hyväksy")
frFR("Accepter")
huHU("Elfogadás")
nlNL("Accepteren")
plPL("Zatwierdź")
ruRU("Подтвердить")
skSK("Akceptovať")
zhTW("接受")

T_("Cancel")
deDE("Abbrechen")
esES("Cancelar")
fiFI("Peruuta")
frFR("Annuler")
huHU("Mégsem")
nlNL("Afbreken")
plPL("Anuluj")
ruRU("Отмена")
skSK("Storno")
zhTW("取消")

T_("Move up")
deDE("Nach oben")
esES("Mover arriba")
fiFI("Siirrä ylös")
frFR("Déplacer vers le haut")
huHU("Mozgatás fel")
nlNL("Omhoog verplaatsen")
plPL("Przesuń do góry")
ruRU("Вверх")
skSK("Posunúť hore")
zhTW("往上移")

T_("Move down")
deDE("Nach unten")
esES("Mover abajo")
fiFI("Siirrä alas")
frFR("Déplacer vers le bas")
huHU("Mozgatás le")
nlNL("Omlaag verplaatsen")
plPL("Przesuń w dół")
ruRU("Вниз")
skSK("Posunúť dole")
zhTW("往下移")

T_("First %s")
deDE("Erster %s")
esES("Primer %s")
fiFI("Ensimmäinen %s")
frFR("Premier %s")
huHU("Első %s")
nlNL("Eerste %s")
plPL("Pierwszy %s")
ruRU("Первые %s")
skSK("Prvý %s")
zhTW("第一個 %s")

T_("Previous %s")
deDE("Vorheriger %s")
esES("Previo %s")
fiFI("Edellinen %s")
frFR("Précédent %s")
huHU("Előző %s")
nlNL("Voorgaande %s")
plPL("Poprzedni %s")
ruRU("Предыдущие $s")
skSK("Predošlý %s")
zhTW("前一個 %s")

T_("Next %s")
deDE("Nächster %s")
esES("Siguiente %s")
fiFI("Seuraava %s")
frFR("Suivant %s")
huHU("Következő %s")
nlNL("Volgende %s")
plPL("Następny %s")
ruRU("Следующие %s")
skSK("Ďalší %s")
zhTW("下一個 %s")

T_("Last %s")
deDE("Letzter %s")
esES("�ltimo %s")
fiFI("Viimeinen %s")
frFR("Dernier %s")
huHU("Utolsó %s")
nlNL("Laatste %s")
plPL("Ostatni %s")
ruRU("Последние %s")
skSK("Posledný")
zhTW("最後一個 %s")

T_("Immediate search")
deDE("Sofort suchen")
esES("Buscar siguiente")
fiFI("Välitön haku")
frFR("Rechere immédiate")
huHU("Azonnali keresés")
nlNL("Onmiddelijk zoeken")
plPL("Wyszukiwanie natychmiastowe")
ruRU("Непосредственный поиск")
skSK("Rýchle vyhľadávanie")
zhTW("立即搜尋")

T_("Hide rows")
deDE("Reihen ausblenden")
esES("Ocultar filas")
fiFI("Piilota rivit")
frFR("Cacher colonnes")
huHU("Sorok rejtése")
nlNL("Verberg rijen")
plPL("Ukrywaj niepasujące wiersze")
ruRU("Спрятать строки")
skSK("Skryť riadky")
zhTW("隱藏列")

T_("Highlight found cells")
deDE("Markiere gefundene Zellen")
esES("Marcar celdas encontradas")
fiFI("Korosta löydetyt solut")
frFR("Surligner cellules trouvées")
huHU("Talált cellák kiemelése")
nlNL("Markeer gevonden cellen")
plPL("Podświetlaj znalezione komórki")
ruRU("Подсветить найденные ячейки")
skSK("Zvýrazniť nájdené bunky")
zhTW("反白所選取的單格")

T_("Case sensitive")
deDE("Gross-/Kleinschreibung beachten")
esES("Distingue may�sculas de min�sculas")
fiFI("Huomioi isot/pienet kirjaimet")
frFR("Sensible a la casse")
huHU("Kis-/nagybetű érzékeny")
nlNL("Hoofdletter gevoelig")
plPL("Rozróżniaj małe i duże litery")
ruRU("Учитывать регистр")
skSK("Rozoznávať malé a veľké písmená")
zhTW("區分大小寫")

T_("row")
deDE("Zeile")
esES("fila")
fiFI("rivi")
frFR("ligne")
huHU("sor")
nlNL("rijen")
plPL("wiersz")
ruRU("ряды")
skSK("riadok")
zhTW("列")

T_("Insert a new %s into the table.")
deDE("Neue %s in die Tabelle einfügen")
esES("Instertar un nuevo %s en la tabla.")
fiFI("Lisää uusi %s taulukkoon.")
frFR("Insère une nouvelle %d dans la table.")
huHU("Új %s beszúrása a táblázatba")
nlNL("Voeg een nieuwe %s in de tabel.")
plPL("Wstawia nowy %s do tabeli.")
ruRU("Вставить новый %s в таблицу.")
skSK("Vložiť nový %s do tabuľky.")
zhTW("插入新的 %s 到表格")

T_("Insert before")
deDE("Davor einfügen")
esES("Insertar antes")
fiFI("Lisää ennen")
frFR("Insérer avant")
huHU("Beszúrás elé")
nlNL("Invoegen voor")
plPL("Wstaw przed")
ruRU("Вставить до")
skSK("Vložiť pred")
zhTW("前插")

T_("Insert a new %s into the table before current")
deDE("Neue %s vor der aktuellen in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla antes del actual")
fiFI("Lisää uusi %s taulukkoon ennen nykyistä")
frFR("Insérer une nouvelle %d dans la table avant l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
nlNL("Voeg een nieuwe %s in de voorgaande tabel")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
ruRU("Вставить новый %s в таблицу перед существующим")
skSK("Vložiť nový %s pred aktuálny")
zhTW("在表格中目前項前插入新的 %s")

T_("Insert after")
deDE("Danach einfügen")
esES("Insertar despu�s")
fiFI("Lisää jälkeen")
frFR("Insérer après")
huHU("Beszúrás utána")
nlNL("Invoegen na")
plPL("Wstaw za")
ruRU("Вставить после")
skSK("Vložiť za")
zhTW("後插")

T_("Insert a new %s into the table after current")
deDE("Neue %s hinter der aktuellen in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla despu�s de la actual")
fiFI("Lisää uusi %s taulukkoon nykyisen jälkeen")
frFR("Insérer une nouvelle %d dans la table après l'actuelle")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
nlNL("Voeg een nieuwe %s in de volgende tabel")
plPL("Wstawia nowy %s do tabeli po aktualnym")
ruRU("Вставить новый %s в таблицу после существующего")
skSK("Vložiť %s za aktuálny")
zhTW("在表格中目前項後插入新的 %s")

T_("Append a new %s at the end of the table.")
deDE("Neue %s am Ende der Tabelle hinzufügen")
esES("A�adir un nuevo %s en el final de la tabla.")
fiFI("Lisää uusi %s taulukon loppuun.")
frFR("Ajouter une nouvelle %s à la fin de la table.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
nlNL("Plaats een nieuwe %s op het einde van de tabel.")
plPL("Dodaje nowy %s na końcu tabeli.")
ruRU("Добавить новый %s в конце таблицы.")
skSK("Pridať nový %s na koniec tabuľky")
zhTW("在表格末尾插入新的 %s")

T_("Duplicate current table %s.")
deDE("Aktuelle %s der Tabelle duplizieren")
esES("Duplicar %s de la tabla actual")
fiFI("Kahdenna tämänhetkinen taulukko %s.")
frFR("Dupliquer la table %s sélectionnée.")
huHU("Az aktuális táblázat megkettőzése")
nlNL("Dupliceer huidige tabel %s.")
plPL("Utwórz duplikat aktualnej tabeli %s.")
ruRU("Дублировать текущий %s таблицы.")
skSK("Duplikovať aktuálny %s.")
zhTW("複製目前表格 %s.")

T_("Edit active %s.")
deDE("Aktive %s bearbeiten")
esES("Editar 5s activo")
fiFI("Muokkaa aktiivista %s.")
frFR("Editer %s actif.")
huHU("Az aktuális %s szerkesztése")
nlNL("Bewerk actieve %s.")
plPL("Edytowanie aktualnego %s.")
ruRU("Редактировать активный %s.")
skSK("Upraviť aktuálny %s.")
zhTW("編輯活動 %s")

T_("Delete active %s.")
deDE("Aktive %s löschen")
esES("Borrar %s activo.")
fiFI("Poista aktiivinen %s.")
frFR("Supprimer %s actif.")
huHU("Az aktív %s törlése")
nlNL("Verwijder actieve %s.")
plPL("Usuwa aktualny %s.")
ruRU("Удалить активный %s.")
skSK("Odstrániť aktuálny %s.")
zhTW("刪除活動 %s")

T_("Select all")
deDE("Alles auswählen")
esES("Seleccionar todo")
fiFI("Valitse kaikki")
frFR("Tout sélectionner")
huHU("Minden kiválasztása")
nlNL("Selecteer alles")
plPL("Zaznacz wszystko")
ruRU("Выделить всё")
skSK("Vybrať všetko")
zhTW("全選")

T_("Select all table rows")
deDE("Alle Zeilen der Tabelle auswählen")
esES("Seleccionar todas las filas de la tabla")
fiFI("Valitse kaikki taulukon rivit")
frFR("Sélectionner toutes les lignes")
huHU("Az összes sor kijelölése")
nlNL("Selecteer alle tabel rijen")
plPL("Zaznacz wszystkie wiersze tabeli")
ruRU("Выделить все ряды таблицы")
skSK("Vybrať všetky riadky v tabuľke")
zhTW("全選表格列")

T_("Columns")
deDE("Spalten")
esES("Columnas")
fiFI("Sarakkeet")
frFR("Colonnes")
huHU("Oszlopok")
nlNL("Kolommen")
plPL("Kolumny")
ruRU("Колонки")
skSK("Stĺpce")
zhTW("行")

T_("Copy")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
frFR("Copier")
huHU("Másolás")
nlNL("Kopieëren")
plPL("Kopiuj")
ruRU("Копировать")
skSK("Kopírovať")
zhTW("複製")

T_("Cut")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
frFR("Couper")
huHU("Kivágás")
nlNL("Knippen")
plPL("Wytnij")
ruRU("Вырезать")
skSK("Vystrihnúť")
zhTW("剪下")

T_("Paste")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
frFR("Coller")
huHU("Beillesztés")
nlNL("Plakken")
plPL("Wklej")
ruRU("Вставить")
skSK("Prilepiť")
zhTW("貼上")

T_("Paste as")
deDE("Einfügen als")
esES("Pegar como")
fiFI("Liitä nimellä")
frFR("Coller comme...")
huHU("Beillesztés másként")
nlNL("Plakken als")
plPL("Wklej jako")
ruRU("Вставить как")
skSK("Prilepiť ako")
zhTW("選擇性貼上")

T_("appended")
deDE("anhängen")
esES("a�adido")
fiFI("lisätty loppuun")
frFR("ajouté")
huHU("hozzáfűzve")
nlNL("geplaatst")
plPL("dodane")
ruRU("добавлено")
skSK("pridaný")
zhTW("已新增")

T_("inserted")
deDE("einfügen")
esES("insertado")
fiFI("lisätty väliin")
frFR("inséré")
huHU("beszúrva")
nlNL("toegevoegd")
plPL("wstawione")
ruRU("вставлено")
skSK("vložený")
zhTW("已插入")

T_("Moving selection (%d %s) before row %d")
deDE("Verschieben der Auswahl (%d %s) vor Reihe %d")
esES("Moviendo selecci�n (%d %s) antes de fila %d")
fiFI("Siirtää valintaa (%d %s) ennen riviä %d")
frFR("Déplacement de la sélection (%d %s) avant la ligne %d")
huHU("Kijelölés mozgatása (%d %s) a %d. sor elé")
nlNL("Selectie verplaatst (%d %s) voor rij %d")
plPL("Przenoszenie selekcji (%d %s) przed %d wiersz")
ruRU("Переместить отмеченное (%d %s) до строки "
     "%d")
skSK("Presunúť označené (%d %s) pred riadok %d")
zhTW("移動所選取的(%d %s)到 列%d之前")

T_("rows")
deDE("Reihen")
esES("filas")
fiFI("rivit")
frFR("lignes")
huHU("sorok")
nlNL("rijen")
plPL("wierszy")
ruRU("строк")
skSK("riadky")
zhTW("列")

T_("Moving row %d before row %d")
deDE("Verschieben der Reihe %d vor Reihe %d")
esES("Moviendo fila %d antes de fila %d")
fiFI("Siirtää riviä %d ennen riviä %d")
frFR("Déplacement de la ligne %d avant la ligne %d")
huHU("%d. sor mozgatása %d. sor elé")
nlNL("Rij %d verplaatst voor rij %d")
plPL("Przenoszenie wiersza %d przed wiersz %d")
ruRU("Переместить строку %d до строки %d")
skSK("Presunúť riadok %d pred riadok %d")
zhTW("移動 列%d到 列%d之前")

T_("Moving %d %s before row %d")
deDE("Verschieben %d %s vor Reihe %d")
esES("Moviendo %d %s antes de fila %d")
fiFI("Siirtää %d %s ennen riviä %d")
frFR("Déplacement %d %s avant la ligne %d")
huHU("%d %s mozgatása a %d. sor elé")
nlNL("%d %s wordt verplaats voor rij %d")
plPL("Przenoszenie %d %s przed wiersz %d")
ruRU("Переместить %d %s до строки %d")
skSK("Presunúť %d %s pred riadok %d")
zhTW("移動 %d %s到 列%d之前")

T_("cell")
deDE("Zelle")
esES("celda")
fiFI("solu")
frFR("cellule")
huHU("cella")
nlNL("cel")
plPL("komórki")
ruRU("ячейка")
skSK("bunka")
zhTW("單格")

T_("cells")
deDE("Zellen")
esES("celdas")
fiFI("solut")
frFR("cellules")
huHU("cellák")
nlNL("cellen")
plPL("komórek")
ruRU("ячейки")
skSK("bunky")
zhTW("單格")

T_("Do you really want to delete selected %s ?")
deDE("Möchten sie wirklich die ausgewählte %s löschen?")
esES("� Realmente quieres borrar las %s seleccionadas ?")
fiFI("Haluatko varmasti poistaa valitun %s ?")
frFR("Voulez vous vraiment effacer la sélection %s ?")
huHU("Biztosan töröljük a kijelölt %s ?")
nlNL("Weet je zeker dat je de geselecteerde %s wilt verwijderen?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")
skSK("Zmazať aktuálny %s ?")
zhTW("真的要刪除所選取的 %s 嗎？")


// Obsolete

T_("Swap %s with previous thus moving it up.")
deDE("%s mit der vorigen vertauschen und so nach oben verschieben")
esES("Intercambiar %s con el anterior y as� moverlo arriba.")
fiFI("Vaihda %s yläpuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le précédent.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
nlNL("Wissel %s om met de voorgaande.")
plPL("Zamienia %s z poprzednim przesuwając go do góry.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
skSK("Vymeniť aktuálny %s s predošlým a tak ho posunúť hore.")
zhTW("將%s與前面換位上移之")

T_("Swap %s with next thus moving it down.")
deDE("%s mit der nächsten vertauschen und so nach unten verschieben")
esES("Intercambiar %s con el siguiente y as� moverlo abajo")
fiFI("Vaihda %s alapuolella sijaitsevan kanssa.")
frFR("Intervertir %s avec le suivant.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
nlNL("Wissel %s om met de volgende.")
plPL("Zamienia %s z następnym przesuwając go w dół.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
skSK("Vymeniť aktuálny %s s ďalším a tak ho posunúť dole.")
zhTW("將%s與後面換位下移之")

T_("Find")
deDE("Suchen")
esES("Encontrar")
fiFI("Etsi")
frFR("Rechercher")
huHU("Keresés")
nlNL("Zoeken")
plPL("Znajdź")
ruRU("Найти")
skSK("Vyhľadať")
zhTW("尋找")

T_("Find options")
deDE("Suche Optionen")
esES("Encontrar opciones")
fiFI("Haku optiot")
frFR("Option de recherche")
huHU("Keresés beállításai")
nlNL("Zoek opties")
plPL("Opcje szukania")
ruRU("Опции поиска")
skSK("Vlastnosti vyhľadávania")
zhTW("尋找選項")
