#ifdef _MSC_VER
#pragma setlocale("C")
#endif
// GridCtrl.cpp

T_("Close")
deDE("Schließen")
esES("Cerra")
fiFI("Sulje")
huHU("Bezár")
plPL("Zamknij")
ruRU("Закрыть")
zhTW("關閉")

T_("Search")
deDE("Suchen")
esES("")
fiFI("")
huHU("Keresés")
plPL("")
ruRU("Поиск")
zhTW("")

T_("Append")
deDE("Anfügen")
esES("")
fiFI("Lisää loppuun")
huHU("Hozzáfűzés")
plPL("Dodaj")
ruRU("Добавить")
zhTW("")

T_("Insert ")
deDE("Einfügen")
esES("")
fiFI("Lisää väliin ")
huHU("Beszúrás")
plPL("Wstaw")
ruRU("Вставить")
zhTW("")

T_("Duplicate")
deDE("Duplizieren")
esES("")
fiFI("Kahdenna")
huHU("Duplikálás")
plPL("Zduplikuj")
ruRU("Дублировать")
zhTW("")

T_("Delete ")
deDE("Löschen")
esES("")
fiFI("Poista")
huHU("Törlés")
plPL("Usuń")
ruRU("Удалить")
zhTW("")

T_("Edit")
deDE("Bearbeiten")
esES("")
fiFI("Muokkaa")
huHU("Szerkesztés")
plPL("Edytuj")
ruRU("Редактировать")
zhTW("")

T_("Accept")
deDE("Bestätigen")
esES("")
fiFI("Hyväksy")
huHU("Elfogadás")
plPL("Zatwierdź")
ruRU("Подтвердить")
zhTW("")

T_("Cancel")
deDE("Abruch")
esES("Cancelar")
fiFI("Peruuta")
huHU("Mégsem")
plPL("Anuluj")
ruRU("Отмена")
zhTW("取消")

T_("Move up")
deDE("Nach oben")
esES("")
fiFI("Siirrä ylös")
huHU("Mozgatás fel")
plPL("Przesuń do góry")
ruRU("Вверх")
zhTW("")

T_("Move down")
deDE("Nach unten")
esES("")
fiFI("Siirrä alas")
huHU("Mozgatás le")
plPL("Przesuń w dół")
ruRU("Вниз")
zhTW("")

T_("First %s")
deDE("Erster %s")
esES("")
fiFI("Ensimmäinen %s")
huHU("Első %s")
plPL("Pierwszy %s")
ruRU("Первые %s")
zhTW("")

T_("Previous %s")
deDE("Vorheriger %s")
esES("")
fiFI("Edellinen %s")
huHU("Előző %s")
plPL("Poprzedni %s")
ruRU("Предыдущие $s")
zhTW("")

T_("Next %s")
deDE("Nächster %s")
esES("")
fiFI("Seuraava %s")
huHU("Következő %s")
plPL("Następny %s")
ruRU("Следующие %s")
zhTW("")

T_("Last %s")
deDE("Letzter %s")
esES("")
fiFI("Viimeinen %s")
huHU("Utolsó %s")
plPL("Ostatni %s")
ruRU("Последние %s")
zhTW("")

T_("Immediate search")
deDE("Sofort suchen")
esES("")
fiFI("Välitön haku")
huHU("Azonnali keresés")
plPL("Wyszukiwanie natychmiastowe")
ruRU("Непосредственный поиск")
zhTW("")

T_("Hide rows")
deDE("Reihen ausblenden")
esES("")
fiFI("Piilota rivit")
huHU("Sorok rejtése")
plPL("Ukrywaj niepasujące wiersze")
ruRU("Спрятать строки")
zhTW("")

T_("Highlight found cells")
deDE("Markiere gefundene Zellen")
esES("")
fiFI("Korosta löydetyt solut")
huHU("Talált cellák kiemelése")
plPL("Podświetlaj znalezione komórki")
ruRU("Подсветить найденные ячейки")
zhTW("")

T_("Case sensitive")
deDE("Gross-/Kleinschreibung beachten")
esES("")
fiFI("Huomioi isot/pienet kirjaimet")
huHU("Kis-/nagybetű érzékeny")
plPL("Rozróżniaj małe i duże litery")
ruRU("Учитывать регистр")
zhTW("")

T_("row")
deDE("Reihe")
esES("fila")
fiFI("rivi")
huHU("sor")
plPL("wiersz")
ruRU("ряды")
zhTW("列")

T_("Insert a new %s into the table.")
deDE("Neuen %s in die Tabelle einfügen")
esES("Insertar un nuevo %s en la tabla.")
fiFI("Lisää uusi %s taulukkoon.")
huHU("Új %s beszúrása a táblázatba")
plPL("Wstawia nowy %s do tabeli.")
ruRU("Вставить новый %s в таблицу.")
zhTW("插入新的 %s 到表格")

T_("Insert before")
deDE("Davor einfügen")
esES("")
fiFI("Lisää ennen")
huHU("Beszúrás elé")
plPL("Wstaw przed")
ruRU("Вставить до")
zhTW("")

T_("Insert a new %s into the table before current")
deDE("Neuen %s in die Tabelle vor aktuellen einfügen")
esES("Insertar un nuevo %s en la tabla antes del actual")
fiFI("Lisää uusi %s taulukkoon ennen nykyistä")
huHU("Új %s beszúrása a táblázatba az aktuális elé")
plPL("Wstawia nowy %s do tabeli przed aktualnym")
ruRU("Вставить новый %s в таблицу перед существующим")
zhTW("在表格中目前項前插入新的 %s")

T_("Insert after")
deDE("Danach einfügen")
esES("")
fiFI("Lisää jälkeen")
huHU("Beszúrás utána")
plPL("Wstaw za")
ruRU("Вставить после")
zhTW("")

T_("Insert a new %s into the table after current")
deDE("Neuen %s in die Tabelle nach aktuellen einfügen")
esES("Insertar un nuevo %s en la tabla después de la actual")
fiFI("Lisää uusi %s taulukkoon nykyisen jälkeen")
huHU("Új %s beszúrása a táblázatba az aktuális mögé")
plPL("Wstawia nowy %s do tabeli po aktualnym")
ruRU("Вставить новый %s в таблицу после существующего")
zhTW("在表格中目前項後插入新的 %s")

T_("Append a new %s at the end of the table.")
deDE("Neue %s am Ende der Tabelle hinzufügen")
esES("Añadir un nuevo %s en el final de la tabla.")
fiFI("Lisää uusi %s taulukon loppuun.")
huHU("Új %s hozzáfűzése a táblázat végéhez")
plPL("Dodaje nowy %s na końcu tabeli.")
ruRU("Добавить новый %s в конце таблицы.")
zhTW("在表格末尾插入新的 %s")

T_("Duplicate current table %s.")
deDE("Neuen %s in die Tabelle am Ende einfügen")
esES("Duplicar la tabla actual %s.")
fiFI("Kahdenna tämänhetkinen taulukko %s.")
huHU("Az aktuális táblázat megkettőzése")
plPL("Utwórz duplikat aktualnej tabeli %s.")
ruRU("Дублировать текущий %s таблицы.")
zhTW("複製目前表格 %s.")

T_("Edit active %s.")
deDE("Aktuellen %s bearbeiten")
esES("Editar activa %s")
fiFI("Muokkaa aktiivista %s.")
huHU("Az aktuális %s szerkesztése")
plPL("Edytuje aktualny %s.")
ruRU("Редактировать активный %s.")
zhTW("編輯活動 %s")

T_("Delete active %s.")
deDE("Aktuellen %s löschen")
esES("Borrar activa %s.")
fiFI("Poista aktiivinen %s.")
huHU("Az aktív %s törlése")
plPL("Usuń aktualny %s.")
ruRU("Удалить активный %s.")
zhTW("刪除活動 %s")

T_("Select all")
deDE("Alle auswählen")
esES("Seleccionar todo")
fiFI("Valitse kaikki")
huHU("Minden kiválasztása")
plPL("Zaznacz wszystkie")
ruRU("Выделить всё")
zhTW("全選")

T_("Select all table rows")
deDE("Alle Reihen auswählen")
esES("Seleccionar todas las filas de la tabla")
fiFI("Valitse kaikki taulukon rivit")
huHU("Az összes sor kijelölése")
plPL("Zaznacz wszystkie wiersze tabeli")
ruRU("Выделить все ряды таблицы")
zhTW("全選表格列")

T_("Columns")
deDE("Spalten")
esES("")
fiFI("Sarakkeet")
huHU("Oszlopok")
plPL("Kolumny")
ruRU("Колонки")
zhTW("")

T_("Copy")
deDE("Kopieren")
esES("Copiar")
fiFI("Kopioi")
huHU("Másolás")
plPL("Kopiuj")
ruRU("Копировать")
zhTW("複製")

T_("Cut")
deDE("Ausschneiden")
esES("Cortar")
fiFI("Leikkaa")
huHU("Kivágás")
plPL("Wytnij")
ruRU("Вырезать")
zhTW("剪下")

T_("Paste")
deDE("Einfügen")
esES("Pegar")
fiFI("Liitä")
huHU("Beillesztés")
plPL("Wklej")
ruRU("Вставить")
zhTW("貼上")

T_("Paste as")
deDE("Einfügen als")
esES("")
fiFI("Liitä nimellä")
huHU("Beillesztés másként")
plPL("Wklej jako")
ruRU("Вставить как")
zhTW("")

T_("appended")
deDE("anhängen")
esES("")
fiFI("lisätty loppuun")
huHU("hozzáfűzve")
plPL("dodane")
ruRU("добавлено")
zhTW("")

T_("inserted")
deDE("einfügen")
esES("")
fiFI("lisätty väliin")
huHU("beszúrva")
plPL("wstawione")
ruRU("вставлено")
zhTW("")

T_("Moving selection (%d %s) before row %d")
deDE("Verschieben der Auswahl (%d %s) vor Reihe %d")
esES("")
fiFI("Siirtää valintaa (%d %s) ennen riviä %d")
huHU("Kijelölés mozgatása (%d %s) a %d. sor elé")
plPL("Przenoszenie selekcji (%d %s) przed %d wiersz")
ruRU("Переместить отмеченное (%d %s) до строки "
     "%d")
zhTW("")

T_("rows")
deDE("Reihen")
esES("")
fiFI("rivit")
huHU("sorok")
plPL("wierszy")
ruRU("строк")
zhTW("")

T_("Moving row %d before row %d")
deDE("Verschieben der Reihe %d vor Reihe %d")
esES("")
fiFI("Siirtää riviä %d ennen riviä %d")
huHU("%d. sor mozgatása %d. sor elé")
plPL("Przenoszenie wiersza %d przed wiersz %d")
ruRU("Переместить строку %d до строки %d")
zhTW("")

T_("Moving %d %s before row %d")
deDE("Verschieben %d %s vor Reihe %d")
esES("")
fiFI("Siirtää %d %s ennen riviä %d")
huHU("%d %s mozgatása a %d. sor elé")
plPL("Przenoszenie %d %s przed wiersz %d")
ruRU("Переместить %d %s до строки %d")
zhTW("")

T_("cell")
deDE("Zelle")
esES("")
fiFI("solu")
huHU("cella")
plPL("komórki")
ruRU("ячейка")
zhTW("")

T_("cells")
deDE("Zellen")
esES("")
fiFI("solut")
huHU("cellák")
plPL("komórek")
ruRU("ячейки")
zhTW("")

T_("Do you really want to delete selected %s ?")
deDE("Möchten sie wirklich die ausgewählte %s löschen?")
esES("")
fiFI("Haluatko varmasti poistaa valitun %s ?")
huHU("Biztosan töröljük a kijelölt %s ?")
plPL("Czy na pewno chcesz usunąć zaznaczone %s ?")
ruRU("Вы действительно хотите удалить выделенный "
     "%s?")
zhTW("")


// Obsolete

T_("Swap %s with previous thus moving it up.")
deDE("Vertauschen der %s mit dem Vorgänger zum Aufwärtsbewegen.")
esES("Intercambiar %s con el anterior y así moverlo arriba.")
fiFI("Vaihda %s yläpuolella sijaitsevan kanssa.")
huHU("%s felcserélése az előzővel - felfelé mozgatás")
plPL("Zamień %s z poprzednim przesuwając go do góry.")
ruRU("Поменять местами %s с предыдущим, подвинув "
     "вверх.")
zhTW("將%s與前面換位上移之")

T_("Swap %s with next thus moving it down.")
deDE("Vertauschen der %s mit dem Nachfolger zum Abwärtsbewegen")
esES("Intercambiar %s con el siguiente y así moverlo abajo")
fiFI("Vaihda %s alapuolella sijaitsevan kanssa.")
huHU("%s felcserélése a következővel - lefelé mozgatás")
plPL("Zamień %s z następnym przesuwając go w dół.")
ruRU("Поменять местами %s со следующим, подвинув "
     "вниз.")
zhTW("將%s與後面換位下移之")

T_("Find")
deDE("Suchen")
esES("Encontrar")
fiFI("Etsi")
huHU("Keresés")
plPL("Znajdź")
ruRU("Найти")
zhTW("")

T_("Find options")
deDE("Suche Optionen")
esES("")
fiFI("Haku optiot")
huHU("Keresés beállításai")
plPL("Opcje szukania")
ruRU("Опции поиска")
zhTW("")
