//////////////////////////////////////////////////////////////////////
// id.h: some common SQL identifiers.

#pragma BLITZ_APPROVE

SQLID(DUAL)
SQLID(ROWID)
#ifndef flagMSSQL
SQLID(ROWNUM)
#endif
SQLID(USERNAME)
SQLID(ALL_USERS)
SQLID(TABLE_NAME)
SQLID(USER_TABLES)
SQLID(VIEW_NAME)
SQLID(USER_VIEWS)
SQLID(SEQUENCE_NAME)
SQLID(USER_SEQUENCES)
SQLID(SESSION_ROLES)
SQLID(TABLE_SCHEMA)
SQLID(GRANTEE)
SQLID(GRANTOR)
SQLID(GRANTED_ROLE)
SQLID(PRIVILEGE)
SQLID(ALL_TAB_PRIVS)
SQLID(SYNONYM_NAME)
SQLID(ALL_SYNONYMS)
SQLID(USER)
SQLID(USER_ROLE_PRIVS)
SQLID(DBA_ROLE_PRIVS)
SQLID(ALL_TAB_COLUMNS)
SQLID(DATA_TYPE)
SQLID(COLUMN_ID)
